(function (global) {
    "use strict";
    const arExtra = {
    "validation": {
        "passwordLowercase": "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل.",
        "passwordDigit": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل.",
        "passwordSymbol": "يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل.",
        "passwordLength": "يجب أن تكون كلمة المرور بين 8 و30 حرفاً.",
        "noHtml": "يجب ألا يتضمن {{label}} HTML.",
        "position": {
            "headerSave": "لا يمكن حفظ هذه الوضعية:\n\n",
            "headerPlay": "لا يمكن اللعب من هذه الوضعية:\n\n",
            "headerUse": "لا يمكن استخدام هذه الوضعية:\n\n",
            "headerSaveBookmark": "لا يمكن حفظ هذه العلامة:\n\n",
            "headerAddBookmark": "لا يمكن إضافة هذه العلامة:\n\n",
            "boardUnreadable": "تعذّر قراءة الرقعة. حاول مرة أخرى بعد اكتمال التحميل.",
            "whiteKingNone": "يجب أن يكون هناك ملك أبيض واحد بالضبط على الرقعة. لم يُعثر على أي ملك.",
            "whiteKingCount": "يجب أن يكون هناك ملك أبيض واحد بالضبط على الرقعة. وُجد {{count}} ملك/ملوك بيض.",
            "blackKingNone": "يجب أن يكون هناك ملك أسود واحد بالضبط على الرقعة. لم يُعثر على أي ملك.",
            "blackKingCount": "يجب أن يكون هناك ملك أسود واحد بالضبط على الرقعة. وُجد {{count}} ملك/ملوك سود.",
            "kingsAdjacent": "لا يمكن أن يكون الملكان في خانات متجاورة (بما في ذلك القطر).",
            "sideInCheck": "دور {{mover}}، لكن ملك {{king}} في كش بالفعل. لا يمكن أن يكون الطرف الذي عليه الدور يُعطي كشاً — غيّر الدور أو انقل القطع.",
            "drawInsufficientKings": "هذه الوضعية تعادل لنقص المواد (ملك مقابل ملك). أضف قطعاً ليبقى كش مات ممكناً.",
            "drawInsufficientMinor": "هذه الوضعية تعادل لنقص المواد (ملك وفيل أو حصان مقابل ملك وحيد). أضف قطعاً ليبقى كش مات ممكناً.",
            "drawBishopsSameColor": "هذه الوضعية تعادل لنقص المواد (فيل مقابل فيل على لون الخانة نفسه). أضف قطعاً ليبقى كش مات ممكناً.",
            "tooManyQueens": "لدى {{color}} {{count}} وزير/وزراء؛ الحد الأقصى 9 لكل لون.",
            "tooManyRooks": "لدى {{color}} {{count}} قلعة/قلاع؛ الحد الأقصى 10 لكل لون.",
            "tooManyBishops": "لدى {{color}} {{count}} فيل/فيلة؛ الحد الأقصى 10 لكل لون.",
            "tooManyKnights": "لدى {{color}} {{count}} حصان/خيول؛ الحد الأقصى 10 لكل لون.",
            "tooManyPawns": "لدى {{color}} {{count}} بيدق/بيادق؛ الحد الأقصى 8 لكل لون."
        }
    },
    "auth": {
        "wrongCredentials": "اسم المستخدم أو كلمة المرور غير صحيحة",
        "userAdded": "تمت إضافة المستخدم بنجاح",
        "couldNotSaveBookmark": "تعذّر حفظ العلامة",
        "invalidUserId": "معرّف مستخدم غير صالح",
        "generationJobRunning": "مهمة توليد أخرى قيد التشغيل بالفعل…",
        "listingPgnFiles": "جارٍ سرد ملفات PGN…"
    },
    "classic": {
        "loadGame": "تحميل لعبة",
        "load": "تحميل",
        "enterGameState": "الصق حالة اللعبة هنا...",
        "rematch": "إعادة المباراة",
        "drawOffer": "عرض تعادل",
        "lastMove": "آخر نقلة",
        "bookmarks": "العلامات",
        "bookmarkAlertTitle": "علامة للوضعية",
        "promotion": "ترقية!",
        "check": "كش",
        "checkmateWins": "كش مات! {{winner}} يفوز!",
        "drawReason": "تعادل! {{reason}}",
        "opponentDisconnected": "انقطع اتصال الخصم",
        "opponentResignedWins": "استسلم الخصم، {{winner}} يفوز",
        "somethingWentWrong": "حدث خطأ ما",
        "playerRejoined": "أعاد {{name}} الانضمام",
        "aPlayerRejoined": "أعاد أحد اللاعبين الانضمام",
        "opponentRejoined": "أعاد الخصم الانضمام",
        "rematchOfferAccepted": "قُبل عرض إعادة المباراة",
        "rematchOfferDeclined": "رُفض عرض إعادة المباراة",
        "sideOffersDraw": "{{side}} يعرض تعادلاً",
        "drawOfferDeclined": "رُفض عرض التعادل",
        "watcherWatching": "{{name}} يشاهد اللعبة",
        "drawOfferSent": "أُرسل عرض التعادل",
        "rematchOfferSent": "أُرسل عرض إعادة المباراة",
        "newGameStarted": "بدأت لعبة جديدة",
        "gameOver": "انتهت اللعبة",
        "gameCancelled": "أُلغيت اللعبة",
        "youResignedWins": "استسلمت، {{winner}} يفوز",
        "movesCopied": "نُسخت النقلات إلى الحافظة!",
        "failedCopyMoves": "فشل نسخ النقلات",
        "failedLoadBrainConfig": "فشل تحميل إعداد المحرك.",
        "failedSaveBrainConfig": "فشل حفظ إعداد المحرك.",
        "offerDrawConfirm": "هل تعرض تعادلاً؟",
        "drawOfferAccept": "أرسل الخصم عرض تعادل، هل تقبل؟",
        "rematchOfferAccept": "عرض الخصم إعادة مباراة، هل توافق؟",
        "confirmExitGame": "هل أنت متأكد أنك تريد الخروج من اللعبة؟",
        "mobileResign": "استسلام",
        "mobileRematch": "إعادة المباراة",
        "mobileDraw": "تعادل",
        "mobileFlip": "قلب",
        "mobileLastMove": "آخر نقلة",
        "mobileMovesList": "قائمة النقلات",
        "researchToolbox": "صندوق الأدوات",
        "researchBrainConfig": "إعداد المحرك",
        "researchSave": "حفظ",
        "researchDiscard": "تجاهل",
        "researchEditMode": "وضع التحرير",
        "researchRun": "تشغيل",
        "researchProperty": "الخاصية",
        "researchValue": "القيمة",
        "playerOnline": "متصل",
        "playerDisconnectedStatus": "منقطع",
        "playerOffline": "غير متصل",
        "humanVsComputer": "إنسان مقابل حاسوب",
        "newGameTwoPlayers": "لعبة جديدة — لاعبان",
        "settings": "الإعدادات",
        "help": "مساعدة",
        "drawOffersNotVsEngine": "عروض التعادل غير متاحة عند اللعب ضد المحرك.",
        "failedStartFromBookmark": "فشل بدء اللعبة من العلامة.",
        "resignConfirm": "استسلام؟",
        "areYouSure": "هل أنت متأكد؟",
        "gameOverOpponentFailedReconnectWinsClassic": "انتهت اللعبة — فشل الخصم في إعادة الاتصال. {{winner}} يفوز.",
        "reconnectTimeoutNoMoves": "انتهت مهلة إعادة الاتصال دون أي نقلة.",
        "waitingOpponentRejoin": "في انتظار إعادة انضمام الخصم",
        "timeoutOneSec": "المهلة: ثانية واحدة",
        "timeoutSecs": "المهلة: {{count}} ث",
        "whitePieceAlt": "قطعة بيضاء",
        "blackPieceAlt": "قطعة سوداء",
        "eraserTitle": "ممحاة",
        "eraserAria": "ممحاة — إزالة قطعة من الخانة",
        "selectTitle": "تحديد",
        "selectAria": "تحديد — اسحب القطع لنقلها",
        "resetAria": "إعادة تعيين — مسح جميع القطع",
        "defaultPositionAria": "الوضعية الافتراضية — إعداد وضعية البداية القياسية",
        "loading": "جارٍ التحميل...",
        "engineLabel": "المحرك"
    },
    "site": {
        "home": "الرئيسية",
        "search": "بحث",
        "friends": "الأصدقاء",
        "groups": "المجموعات",
        "debug": "تصحيح",
        "account": "الحساب",
        "preferences": "التفضيلات",
        "administrate": "الإدارة",
        "logOut": "تسجيل الخروج",
        "logIn": "تسجيل الدخول",
        "admin": "المشرف",
        "homeAria": "الرئيسية",
        "confirm": "تأكيد",
        "cancel": "إلغاء",
        "notice": "تنبيه",
        "ok": "موافق",
        "username": "اسم المستخدم:",
        "password": "كلمة المرور:",
        "login": "تسجيل الدخول",
        "register": {
            "rookie": "مبتدئ",
            "skilled": "ماهر",
            "elite": "نخبة",
            "grandMaster": "أستاذ كبير"
        },
        "email": "البريد الإلكتروني:",
        "welcome": {
            "greeting": "مرحباً بعودتك",
            "tagline": "دورك في انتظارك",
            "playNow": "العب الآن!",
            "activeGames": "الألعاب النشطة",
            "live": "مباشر",
            "showAll": "عرض الكل",
            "viewAllActive": "عرض جميع الألعاب النشطة",
            "mostRecent": "الأحدث أولاً",
            "noGamesNow": "لا توجد ألعاب حالياً",
            "myGames": "ألعابي",
            "viewAllGames": "عرض جميع الألعاب",
            "recentCompleted": "أحدث ألعابك المكتملة",
            "noCompleted": "لا توجد ألعاب مكتملة بعد",
            "activeGamesAria": "الألعاب النشطة",
            "inviteOnlineFriend": "ادعُ صديقاً عبر الإنترنت للعب",
            "friendsPageTitle": "صفحة الأصدقاء",
            "manageFriends": "إدارة",
            "colFriend": "الصديق",
            "colStatus": "الحالة",
            "findPlayers": "البحث عن لاعبين",
            "waitingForResponse": "في انتظار الرد",
            "inviteSentSuffix": "(أُرسلت الدعوة)",
            "sortByRowNumber": "ترتيب حسب رقم الصف",
            "sortBy": "ترتيب حسب {{key}}"
        },
        "gameList": {
            "date": "التاريخ",
            "time": "الوقت",
            "result": "النتيجة",
            "reason": "السبب",
            "type": "النوع",
            "status": "الحالة",
            "event": "الحدث",
            "site": "الموقع",
            "round": "الجولة"
        },
        "loginPage": {
            "title": "تسجيل الدخول"
        },
        "error": {
            "title": "حدث خطأ ما",
            "body": "حدث خطأ.",
            "back": "العودة إلى الرئيسية"
        },
        "log": {
            "title": "سجل الخادم",
            "clear": "مسح العرض",
            "latest": "الأحدث",
            "waiting": "في انتظار مخرجات سجل الخادم…"
        },
        "activeGames": {
            "moves": "النقلات",
            "turn": "الدور",
            "status": "الحالة",
            "inProgress": "جارية",
            "onHold": "معلّقة",
            "vs": " مقابل ",
            "minutesAgo": "منذ {{count}} دقائق",
            "oneMinuteAgo": "منذ دقيقة واحدة",
            "justStarted": "بدأت للتو",
            "notStarted": "لم تبدأ",
            "startedTooltip": "بدأت: {{when}}",
            "playersVs": "{{white}} مقابل {{black}}"
        },
        "friendsPage": {
            "title": "الأصدقاء",
            "tagline": "اعثر على شركاء شطرنج جدد",
            "myFriends": "أصدقائي",
            "noFriendsYet": "لا أصدقاء بعد",
            "findPlayers": "البحث عن لاعبين",
            "searchByUsername": "البحث باسم المستخدم",
            "searchPlaceholder": "اكتب للبحث…",
            "enterCharToSearch": "أدخل حرفاً واحداً على الأقل للبحث",
            "noMatchingUsers": "لا مستخدمين مطابقين",
            "playing": "يلعب",
            "pendingFriendshipOffer": "عرض صداقة معلّق",
            "joining": "ينضم",
            "rejoin": "إعادة الانضمام",
            "friendRequest": "طلب صداقة",
            "wantsToBeFriends": "(يريد الصداقة)",
            "pendingOfferSuffix": "(عرض صداقة معلّق)",
            "waitingFriendRespond": "في انتظار رد صديقك",
            "cancelBeforeRemove": "ألغِ دعوة اللعبة قبل إزالة هذا الصديق",
            "friendsTag": "أصدقاء",
            "offerReceivedTag": "وُرد عرض — راجع أصدقائك",
            "addFriend": "إضافة صديق",
            "withdraw": "سحب",
            "requestFailed": "فشل الطلب",
            "removeFriendConfirm": "هل تزيل هذا الصديق من قائمتك؟",
            "removeFriendTitle": "إزالة صديق",
            "withdrawOfferConfirm": "هل تسحب عرض الصداقة هذا؟",
            "withdrawOfferTitle": "سحب العرض",
            "couldNotAccept": "تعذّر القبول",
            "couldNotDecline": "تعذّر الرفض",
            "couldNotRemove": "تعذّر الإزالة",
            "couldNotCancelInvite": "تعذّر إلغاء الدعوة",
            "couldNotWithdraw": "تعذّر السحب",
            "couldNotSendInvite": "تعذّر إرسال الدعوة",
            "couldNotSendGameInvite": "تعذّر إرسال دعوة اللعبة",
            "gameInvite": "دعوة لعبة",
            "gameInvitationsAria": "دعوات الألعاب",
            "gameInvitationAria": "دعوة لعبة",
            "chessInviteTitle": "دعوة شطرنج",
            "wantsToPlayAsBlack": "{{name}} يريد اللعب. تلعب كلون أسود.",
            "aFriend": "صديق",
            "youPlayAsWhite": "تلعب كلون أبيض",
            "youPlayAsBlack": "تلعب كلون أسود",
            "establishingGame": "جارٍ إعداد اللعبة…",
            "yourOpponent": "خصمك",
            "declinedYourInvite": "رفض {{name}} دعوة لعبتك.",
            "cancelInvite": "إلغاء الدعوة",
            "accept": "قبول",
            "decline": "رفض",
            "invite": "دعوة",
            "remove": "إزالة",
            "offerSent": "أُرسل العرض",
            "pending": "معلّق",
            "online": "متصل",
            "offline": "غير متصل"
        },
        "adminPage": {
            "title": "الإدارة",
            "users": "المستخدمون",
            "generate": "توليد",
            "games": "الألعاب",
            "engines": "المحركات",
            "states": "الحالات",
            "addUser": "إضافة مستخدم",
            "sectionsAria": "أقسام الإدارة",
            "openingBookLabel": "كتاب الافتتاحيات:",
            "gameLines": "خطوط اللعب",
            "noGamesInDb": "لا ألعاب في قاعدة البيانات بعد.",
            "gamesPaginationAria": "ترقيم صفحات الألعاب",
            "colNum": "#",
            "colUsername": "اسم المستخدم",
            "colType": "النوع",
            "colEmail": "البريد الإلكتروني",
            "colPassword": "كلمة المرور",
            "colLevel": "المستوى",
            "colElo": "Elo",
            "colJoined": "تاريخ الانضمام",
            "colLastLogin": "آخر تسجيل دخول",
            "colActiveGames": "الألعاب النشطة",
            "colFriends": "الأصدقاء",
            "colBookmarks": "العلامات",
            "colId": "المعرّف",
            "colStatus": "الحالة",
            "colName": "الاسم",
            "colAvailable": "متاح",
            "colNotes": "ملاحظات",
            "colNote": "ملاحظة",
            "colAction": "إجراء",
            "emptyUsers": "لا مستخدمين بعد.",
            "emptyData": "لا بيانات بعد.",
            "emptyStates": "استخدم توليد لفتح صفحة كتاب الافتتاحيات وتوليد الحالات.",
            "clickToEdit": "انقر للتحرير",
            "updateFailed": "فشل التحديث",
            "couldNotSave": "تعذّر الحفظ",
            "setPassword": "تعيين كلمة المرور",
            "setPasswordTitle": "انقر لتعيين كلمة مرور جديدة (4–30 حرفاً)",
            "passwordLengthInvalid": "يجب أن تكون كلمة المرور بين 4 و30 حرفاً.",
            "invalidPassword": "كلمة مرور غير صالحة",
            "saved": "حُفظ",
            "newPasswordPlaceholder": "كلمة مرور جديدة",
            "clickChangeUserType": "انقر لتغيير نوع المستخدم",
            "userTypeAria": "نوع المستخدم",
            "changeUserTypeTitle": "تغيير نوع المستخدم",
            "grantAdminConfirm": "هل تمنح هذا المستخدم صلاحيات المشرف؟ سيتمكن من الوصول إلى أدوات الإدارة وإدارة الحسابات.",
            "demoteAdminConfirm": "هل تغيّر هذا المستخدم من مشرف إلى {{type}}؟ سيفقد الوصول إلى منطقة الإدارة.",
            "changeUserTypeConfirm": "هل تغيّر هذا المستخدم إلى {{type}}؟",
            "clickChangeLevel": "انقر لتغيير المستوى",
            "playerLevelAria": "مستوى اللاعب",
            "sortByRowNumber": "ترتيب حسب رقم الصف",
            "sortBy": "ترتيب حسب {{key}}",
            "delete": "حذف",
            "first": "الأول",
            "last": "الأخير",
            "previous": "السابق",
            "next": "التالي",
            "previous5Pages": "5 صفحات سابقة",
            "next5Pages": "5 صفحات تالية",
            "previous10Pages": "10 صفحات سابقة",
            "next10Pages": "10 صفحات تالية",
            "userTypeAdmin": "مشرف",
            "userTypePartner": "شريك",
            "userTypeMember": "عضو",
            "generateTitle": "كتاب الافتتاحيات وتوليد الحالات",
            "backToAdmin": "← العودة إلى الإدارة",
            "generateIntro": "يعيد تشغيل جميع ملفات PGN ضمن مجلد مدير الألعاب في الخادم إما إلى مجموعة State في Mongo أو كتاب الافتتاحيات القائم على الأسطر (data/opening-book-lines.txt). اختر هدفاً، ثم اضغط بدء التوليد — لا يبدأ شيء حتى تفعل ذلك.",
            "target": "الهدف",
            "targetMongo": "MongoDB — إضافة صفوف إلى مجموعة State",
            "targetBook": "ملف الأسطر — كتابة كتاب الافتتاحيات (opening-book-lines.txt)",
            "startGeneration": "بدء التوليد",
            "stop": "إيقاف",
            "idle": "خامل.",
            "starting": "جارٍ البدء…",
            "running": "قيد التشغيل ({{mode}})…",
            "readingFiles": "جارٍ قراءة {{count}} ملف/ملفات…",
            "replayingGames": "جارٍ إعادة تشغيل {{count}} لعبة/ألعاب…",
            "writingOpeningBook": "جارٍ كتابة كتاب الافتتاحيات…",
            "readingPgn": "قراءة PGN {{index}} / {{total}} ({{games}} لعبة/ألعاب)",
            "replayGameProgress": "إعادة تشغيل اللعبة {{current}} / {{total}} (اكتملت بنجاح: {{completed}})",
            "stopped": "توقف.",
            "bookUnchanged": "لم يُعدّل كتاب الافتتاحيات الحالي.",
            "bookLinesInFile": "{{count}} خط/خطوط لعب في {{file}}.",
            "cancelledBeforeRead": "أُلغي قبل قراءة ملفات PGN.",
            "cancelledAfterRead": "أُلغي بعد القراءة؛ تُركت إعادة التشغيل (لم يُكتب شيء).",
            "mongoGamesSaved": "حُفظت صفوف حالة جديدة لـ {{count}} لعبة/ألعاب.",
            "doneBook": "تم. {{count}} خط/خطوط لعب → {{file}}",
            "doneBookFileOnly": "تم. {{file}}",
            "doneMongo": "تم. حُدّثت مجموعة State في MongoDB{{detail}}.",
            "doneMongoDetail": " ({{count}} لعبة/ألعاب أُعيد تشغيلها بنجاح)",
            "errorPrefix": "خطأ: {{message}}",
            "unknownError": "غير معروف",
            "connectionClosed": "أُغلق الاتصال (راجع سجلات الخادم أو حاول مرة أخرى).",
            "openingBookDefault": "كتاب الافتتاحيات"
        },
        "playNow": {
            "title": "لعبة جديدة",
            "startTitle": "بدء لعبة جديدة",
            "playingColor": "لون اللعب",
            "timeMin": "الوقت (د)",
            "difficulty": "الصعوبة (1–5)",
            "mousePreference": "تفضيل الماوس",
            "drag": "سحب",
            "doubleClick": "نقرة مزدوجة",
            "showAvailableMoves": "إظهار النقلات المتاحة",
            "private": "خاص",
            "playComputer": "العب ضد الحاسوب",
            "browseAll": "تصفح الكل",
            "yourHistory": "سجلّك",
            "fullList": "القائمة الكاملة",
            "gameLibrary": "مكتبة الألعاب",
            "openLibrarySearch": "فتح بحث المكتبة",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "الألعاب النشطة",
            "tagline": "جميع الألعاب الجارية",
            "liveGames": "ألعاب مباشرة",
            "game": "لعبة",
            "started": "بدأت"
        },
        "list": {
            "title": "جميع الألعاب",
            "action": "إجراء"
        },
        "searchPage": {
            "title": "بحث:",
            "button": "بحث",
            "resultsFound": "وُجد {{count}} نتيجة:",
            "first": "الأول",
            "last": "الأخير",
            "previous": "السابق",
            "next": "التالي",
            "previous5Pages": "5 صفحات سابقة",
            "next5Pages": "5 صفحات تالية",
            "previous10Pages": "10 صفحات سابقة",
            "next10Pages": "10 صفحات تالية"
        },
        "game": {
            "moves": "النقلات",
            "white": "أبيض",
            "black": "أسود",
            "resign": "استسلام",
            "draw": "تعادل",
            "undo": "تراجع",
            "flip": "قلب",
            "practice": "تدريب"
        },
        "mobileWelcome": {
            "title": "الرئيسية — شطرنج",
            "play": "لعب",
            "library": "المكتبة",
            "friends": "الأصدقاء"
        },
        "mobileGame": {
            "title": "لعبة",
            "moves": "النقلات",
            "resign": "استسلام"
        }
    },
    "desktop": {
        "error": {
            "title": "حدث خطأ ما",
            "body": "حدث خطأ.",
            "back": "العودة إلى الرئيسية"
        },
        "chrome": {
            "preferences": "التفضيلات",
            "display": "العرض",
            "gameplay": "أسلوب اللعب",
            "pieceSet": "مجموعة القطع",
            "boardTheme": "سمة الرقعة",
            "themeBlue": "أزرق",
            "themeDark": "داكن",
            "customizeTheme": "تخصيص السمة…",
            "builtInThemesAria": "سمات مدمجة",
            "savedCustomThemesAria": "سمات مخصّصة محفوظة",
            "pieceSetsAria": "مجموعات القطع",
            "homeAria": "الرئيسية — شمرلنغ للشطرنج"
        },
        "prefs": {
            "language": "اللغة",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "تحكم الماوس",
            "thinkingTime": "وقت التفكير",
            "thinkingTimeAria": "وقت التفكير بالثواني",
            "immediateResign": "استسلام فوري",
            "secondsOption": "{{count}} ث",
            "enterFullScreen": "دخول ملء الشاشة",
            "exitFullScreen": "الخروج من ملء الشاشة",
            "fullScreenUnavailable": "ملء الشاشة غير متاح في هذا المتصفح."
        },
        "gameRun": {
            "yourColor": "لونك",
            "engine": "المحرك",
            "thinkTime": "وقت التفكير (ثوانٍ)",
            "thinkTimeAria": "وقت تفكير المحرك بالثواني",
            "play": "لعب",
            "nextMove": "النقلة التالية",
            "computer": "الحاسوب",
            "computerColorHint": "اللون الذي يلعب به الحاسوب — تلعب الطرف الآخر"
        },
        "brainConfig": {
            "title": "إعداد المحرك",
            "save": "حفظ",
            "reset": "إعادة تعيين",
            "saved": "حُفظ الإعداد",
            "failedSave": "فشل حفظ الإعداد",
            "brainLabel": "Brain",
            "loading": "جارٍ التحميل…",
            "failedLoad": "فشل تحميل إعداد المحرك.",
            "discardSwitchConfirm": "هل تتجاهل التغييرات غير المحفوظة وتبدّل إصدار Brain؟",
            "discard": "تجاهل",
            "pieceScores": "قيم القطع",
            "specialEvaluations": "تقييمات خاصة",
            "gamePhase": "مرحلة اللعبة",
            "pawnFilesOpeningMid": "أعمدة البيدق (افتتاح / وسط)",
            "pawnFilesEndGame": "أعمدة البيدق (نهاية)"
        },
        "customTheme": {
            "title": "سمة مخصّصة",
            "name": "اسم السمة",
            "save": "حفظ",
            "delete": "حذف",
            "saved": "حُفظ",
            "searchProperties": "البحث في الخصائص",
            "filterPlaceholder": "تصفية حسب اسم الخاصية…",
            "namePlaceholder": "سمتي",
            "resetPreset": "إعادة تعيين إلى الإعداد الحالي",
            "couldNotSave": "تعذّر حفظ السمة. حاول مرة أخرى.",
            "untitled": "بلا عنوان",
            "defaultName": "سمة مخصّصة"
        },
        "positionSetup": {
            "clearBoard": "مسح الرقعة",
            "startingPosition": "وضعية البداية",
            "flipBoard": "قلب الرقعة",
            "eraser": "ممحاة",
            "selectAndMove": "تحديد ونقل",
            "defaultStartingPosition": "وضعية البداية الافتراضية",
            "savePosition": "حفظ الوضعية",
            "saveAsNewPosition": "حفظ كوضعية جديدة",
            "validatePosition": "التحقق من الوضعية",
            "positionFlags": "علامات الوضعية",
            "turn": "الدور",
            "flagCheck": "كش",
            "flagCheckmate": "كش مات",
            "flagDraw": "تعادل",
            "flagWhiteKingMoved": "تحرّك الملك الأبيض",
            "flagBlackKingMoved": "تحرّك الملك الأسود",
            "flagWhiteKingsideRookMoved": "تحرّكت قلعة الجناح الأبيض",
            "flagWhiteQueensideRookMoved": "تحرّكت قلعة الوزير الأبيض",
            "flagBlackKingsideRookMoved": "تحرّكت قلعة الجناح الأسود",
            "flagBlackQueensideRookMoved": "تحرّكت قلعة الوزير الأسود"
        }
    },
    "mobile": {
        "drawOfferTitle": "عرض تعادل",
        "drawOfferMessage": "أرسل الخصم عرض تعادل. هل تقبل؟",
        "rematchTitle": "إعادة المباراة",
        "rematchMessage": "أرسل الخصم عرض إعادة مباراة. هل تقبل؟",
        "gameId": "معرّف اللعبة: {{id}}",
        "drawOfferAgree": "عرض الخصم تعادلاً، هل توافق؟",
        "rematchOfferAgree": "عرض الخصم إعادة مباراة، هل توافق؟",
        "newGameWatchFromHome": "بدأت لعبة جديدة — انتقل إلى الرئيسية للمشاهدة."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = arExtra;
    } else {
        global.ShmerlingStringsArExtra = arExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
