/**
 * Arabic string catalog — mirrors src/strings/en.js structure with Arabic values.
 */
(function (global) {
    "use strict";

    const ar = {
        common: {
            white: "أبيض",
            black: "أسود",
            draw: "تعادل",
            winner: "الفائز",
            engine: "المحرك",
            ok: "موافق",
            cancel: "إلغاء",
            confirm: "تأكيد",
            yes: "نعم",
            no: "لا",
            notice: "تنبيه",
            input: "إدخال",
            start: "بدء",
            collapse: "طي",
            expand: "توسيع",
            delete: "حذف",
            rename: "إعادة تسمية",
            save: "حفظ",
            aPlayer: "لاعب",
            pleaseEnterValue: "يرجى إدخال قيمة.",
        },
        play: {
            appTitle: "شمرلنغ للشطرنج",
            shell: {
                gameActions: "إجراءات اللعبة",
                playersAndClocks: "اللاعبون والساعات",
                whitePlayerClock: "ساعة اللاعب الأبيض",
                blackPlayerClock: "ساعة اللاعب الأسود",
                startFromLoadedPosition: "بدء اللعبة من الوضعية المحمّلة",
                moves: "النقلات",
                expandMovesPanel: "توسيع لوحة النقلات",
                expandMoves: "توسيع النقلات",
                collapseMovesPanel: "طي لوحة النقلات",
                reviewNavigation: "تنقل المراجعة",
                positionSetup: "إعداد الوضعية",
                pieces: "القطع",
                collapsePiecesPanel: "طي لوحة القطع",
                brainConfiguration: "إعداد المحرك",
                configuration: "الإعداد",
                collapseConfigurationPanel: "طي لوحة الإعداد",
                games: "الألعاب",
                expandGamesPanel: "توسيع لوحة الألعاب",
                expandGames: "توسيع الألعاب",
                collapseGamesPanel: "طي لوحة الألعاب",
                savedListFilter: "تصفية القائمة المحفوظة",
                positions: "الوضعيات",
                gameStatus: "حالة اللعبة",
                capturedPieces: "القطع المأسورة",
            },
            sessionMode: {
                play: "وضع اللعب",
                positionSetup: "إعداد الوضعية",
                configuration: "وضع الإعداد",
                playback: "وضع التشغيل",
                review: "وضع المراجعة",
                watch: "وضع المشاهدة",
                practice: "وضع التدريب",
            },
            status: {
                chooseNewGameOrSetup:
                    "اختر لعبة جديدة أو إعداد الوضعية من الشريط الجانبي",
                chooseNewGame: "اختر لعبة جديدة من الشريط الجانبي",
                setMoveColorEngineThinkTime:
                    "حدّد النقلة واللون والمحرك ووقت التفكير في الشريط العلوي، ثم اضغط لعب",
                gameOver: "انتهت اللعبة",
                gameInProgress: "اللعبة جارية",
                boardLoading: "الرقعة ما زالت تُحمّل…",
                boardNotReady: "الرقعة غير جاهزة بعد. يرجى الانتظار والمحاولة مرة أخرى.",
                leaveOnlineBeforeConfiguration:
                    "غادر اللعبة عبر الإنترنت قبل فتح الإعداد",
                configurationNotInPractice:
                    "الإعداد غير متاح في وضع التدريب",
                configurationModeEdit:
                    "وضع الإعداد — عدّل القيم واحفظ",
                selectSavedOrSetup:
                    "اختر لعبة محفوظة أو أعد وضعية على الرقعة أولاً",
                gameAlreadyInProgress: "هناك لعبة جارية بالفعل",
                yourMove: "دورك",
                engineToMove: "دور المحرك…",
                leaveOnlineBeforePositionSetup:
                    "غادر اللعبة عبر الإنترنت قبل فتح إعداد الوضعية",
                positionSetupNotInPractice:
                    "إعداد الوضعية غير متاح في وضع التدريب",
                positionSetupPlacePieces:
                    "إعداد الوضعية — ضع القطع على الرقعة",
                drawWithReason: "تعادل — {{reason}}",
                checkmateWins: "كش مات — {{winner}} يفوز",
                check: "كش",
                waitBeforeEvaluate:
                    "انتظر انتهاء النقلة الحالية قبل التقييم",
                evaluationUnavailable:
                    "التقييم غير متاح. أعد تشغيل تطبيق شمرلنغ للشطرنج.",
                evaluatingPosition: "جارٍ تقييم الوضعية…",
                evaluationFailed: "فشل التقييم",
                evaluationLine: "التقييم (دور {{side}}): {{score}}",
                checkmate: "كش مات",
                drawZero: "تعادل (0)",
                totalLabel: "المجموع: {{value}}",
                openFolderDesktopOnly:
                    "فتح المجلد متاح فقط في تطبيق سطح المكتب",
                couldNotOpenGamesLogFolder: "تعذّر فتح مجلد سجل الألعاب",
                positionValid: "الوضعية صالحة",
                playingFromCustomPosition: "اللعب من وضعية مخصّصة",
                nothingToSave: "لا يوجد ما يُحفظ",
                positionSaved: "تم حفظ الوضعية",
                couldNotSavePosition: "تعذّر حفظ الوضعية",
                savedPositionNotFound: "الوضعية المحفوظة غير موجودة",
                positionUpdated: "تم تحديث الوضعية",
                couldNotUpdatePosition: "تعذّر تحديث الوضعية",
                nameCannotBeEmpty: "لا يمكن أن يكون الاسم فارغاً",
                gameRenamed: "تمت إعادة تسمية اللعبة",
                couldNotRenameGame: "تعذّر إعادة تسمية اللعبة",
                deletedCount: "تم حذف {{count}} عنصر/عناصر",
                couldNotDeleteSelected: "تعذّر حذف العناصر المحددة",
                couldNotLoadSavedGame: "تعذّر تحميل اللعبة المحفوظة",
                editingPositionSaveBookmark:
                    "تحرير الوضعية — احفظ لتحديث هذه العلامة",
                couldNotOpenPositionForEditing:
                    "تعذّر فتح الوضعية للتحرير",
                gameSaved: "تم حفظ اللعبة",
                couldNotSaveGame: "تعذّر حفظ اللعبة",
                engineMoveNotApplied: "تعذّر تطبيق نقلة المحرك",
                engineCouldNotFindMove: "لم يجد المحرك نقلة",
                engineError: "خطأ في المحرك",
                engineThinking: "المحرك يفكّر…",
                sessionError: "خطأ في الجلسة",
                timesUpLost: "انتهى الوقت! {{loser}} خسر",
                drawOfferTitle: "عرض تعادل",
                drawOfferMessage: "أرسل الخصم عرض تعادل. هل تقبل؟",
                rematchTitle: "إعادة المباراة",
                playerDisconnectedWaiting:
                    "انقطع اتصال {{who}} — في انتظار إعادة الانضمام ({{countdown}})",
                opponentDisconnectedCountdown:
                    "انقطع اتصال الخصم — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "أُلغيت اللعبة — انتهت مهلة إعادة الاتصال دون أي نقلة.",
                playerFailedToReconnectWins:
                    "فشل {{loser}} في إعادة الاتصال — {{winner}} يفوز",
                gameOverOpponentFailedReconnect:
                    "انتهت اللعبة — فشل الخصم في إعادة الاتصال.",
                couldNotStartRematch: "تعذّر بدء إعادة المباراة",
                rematchStarted: "بدأت إعادة المباراة",
                gameCancelled: "أُلغيت اللعبة",
                gameCancelledWithDetail: "أُلغيت اللعبة — {{detail}}",
                resignFailed: "فشل الاستسلام",
                gameResumedYourMove: "استُؤنفت اللعبة — دورك",
                practiceNotAvailable: "وضع التدريب غير متاح",
                couldNotJoinOnPlay: "تعذّر الانضمام إلى هذه اللعبة على /play",
                practiceDebugNotAvailable:
                    "التدريب / التصحيح غير متاح لهذا الحساب",
                reviewRequiresWebApi: "المراجعة تتطلب واجهة الويب",
                couldNotLoadReviewGame: "تعذّر تحميل لعبة المراجعة",
                notReviewGameLink: "هذا الرابط ليس لعبة مراجعة",
                onlineRequiresWebApi: "اللعب عبر الإنترنت يتطلب واجهة الويب",
                couldNotLoadOnlineGame: "تعذّر تحميل اللعبة عبر الإنترنت",
                notOnlineGameOnPlay: "هذا الرابط ليس لعبة عبر الإنترنت على /play",
                watchingLiveGame: "مشاهدة لعبة مباشرة",
                waitingForOpponentToJoin: "في انتظار انضمام الخصم…",
                waitingForOpponent: "في انتظار الخصم…",
                onlineGameConnected: "لعبة عبر الإنترنت — متصل",
                gameDeleted: "تم حذف اللعبة",
                itemsDeleted: "تم حذف {{count}} عنصر/عناصر",
                choosePromotionPiece: "اختر قطعة الترقية",
                invalidPromotionPiece: "قطعة ترقية غير صالحة",
                drawOfferNotAvailable: "عرض التعادل غير متاح الآن",
            },
            drawReasons: {
                stalemate: "جمود",
                fiftyMoves: "50 نقلة",
                insufficientMaterial: "نقص المواد",
                threefoldRepetition: "تكرار ثلاثي",
                drawOfferAccepted: "قُبل عرض تعادل لاعب {{by}}",
            },
            actions: {
                newGame: "لعبة جديدة",
                resign: "استسلام",
                draw: "تعادل",
                undo: "تراجع",
                redo: "إعادة",
                lastMove: "آخر نقلة",
                positionSetup: "إعداد الوضعية",
                config: "إعداد",
                flip: "قلب",
                save: "حفظ",
                exit: "خروج",
                loadToStart: "تحميل للبدء",
                editPosition: "تحرير الوضعية",
            },
            savedGames: {
                defaultName: "لعبة محفوظة",
                nameAriaLabel: "اسم اللعبة المحفوظة",
                showDetails: "عرض التفاصيل",
                detailsAriaLabel: "تفاصيل اللعبة المحفوظة",
                editPosition: "تحرير الوضعية",
                deleteSavedGame: "حذف اللعبة المحفوظة",
                renameSavedGame: "إعادة تسمية اللعبة المحفوظة",
                noSavedPositions: "لا توجد وضعيات محفوظة بعد.",
                noSavedGames: "لا توجد ألعاب محفوظة بعد.",
                nextMoveDash: "النقلة التالية: —",
                nextMove: "النقلة التالية: {{side}}",
                player: "اللاعب",
                savedAt: "حُفظت: {{when}}",
                gameId: "معرّف اللعبة: {{id}}",
                playersVs: "{{white}} مقابل {{black}}",
            },
            reviewNav: {
                start: "البداية",
                back: "رجوع",
                play: "تشغيل",
                pause: "إيقاف مؤقت",
                forward: "تقدّم",
                end: "النهاية",
            },
            newGameDialog: {
                title: "لعبة جديدة ضد الذكاء الاصطناعي",
                yourColor: "لونك",
                engine: "المحرك",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "الوقت لكل طرف (دقائق)",
                allowUndo: "السماح بالتراجع",
            },
            prompts: {
                positionName: "اسم الوضعية",
                savePositionAs: "حفظ الوضعية باسم",
            },
            dialogs: {
                resignTitle: "هل تستسلم من هذه اللعبة؟",
                resignBody: "ستخسر اللعبة.",
                leaveTitle: "مغادرة اللعبة؟",
                leaveBody: "ستُستسلم من لعبتك.",
                areYouSure: "هل أنت متأكد؟",
                discardUnsavedBrainConfig:
                    "هل تتجاهل تغييرات إعداد المحرك غير المحفوظة؟",
                accept: "قبول",
                decline: "رفض",
                saveAs: "حفظ باسم",
                savePosition: "حفظ الوضعية",
                invalidPosition: "وضعية غير صالحة",
                rematchChooseColor: "اختر لونك لإعادة المباراة:",
                rematchOfferAgree: "عرض الخصم إعادة مباراة. هل توافق؟",
                rematchColorPreference:
                    "يريد الخصم اللعب كلون {{offerer}}. ستلعب كلون {{you}}. هل توافق؟",
            },
        },
        session: {
            engineThinking: "المحرك يفكّر…",
            engineCouldNotFindMove: "لم يجد المحرك نقلة",
            engineError: "خطأ في المحرك",
            positionSetupPlacePieces: "إعداد الوضعية — ضع القطع على الرقعة",
            configurationModeEdit: "وضع الإعداد — عدّل القيم واحفظ",
            practiceBothSides: "تدريب — الطرفان",
            opponentDisconnected: "انقطع اتصال الخصم",
            opponentRejoined: "أعاد الخصم الانضمام",
            playerRejoined: "أعاد {{name}} الانضمام",
            drawOfferSent: "أُرسل عرض التعادل",
            drawOfferDeclined: "رُفض عرض التعادل",
            rematchOfferSent: "أُرسل عرض إعادة المباراة",
            rematchOfferDeclined: "رُفض عرض إعادة المباراة",
            drawAgreed: "اتُفق على التعادل",
            rematchAcceptedNoGameId: "قُبلت إعادة المباراة لكن لا يوجد معرّف لعبة جديد",
            rematchOfferAccepted: "قُبل عرض إعادة المباراة",
            gameOver: "انتهت اللعبة",
            somethingWentWrong: "حدث خطأ ما",
            opponentResigned: "استسلم الخصم",
            opponentLeftGame: "غادر الخصم اللعبة",
            opponentFailedToReconnect: "فشل الخصم في إعادة الاتصال",
            gameCancelled: "أُلغيت اللعبة",
            gameCancelledWithDetail: "أُلغيت اللعبة — {{detail}}",
            waitingForOpponent: "في انتظار الخصم…",
            couldNotResolveWebSocketUrl: "تعذّر تحديد عنوان WebSocket",
            opponentJoined: "انضم {{name}}",
            opponentDefault: "الخصم",
            connectionError: "خطأ في الاتصال",
            playerDisconnectedWaitingRejoin:
                "انقطع اتصال {{name}} — في انتظار إعادة الانضمام",
            playerFailedToReconnectWins:
                "فشل {{loser}} في إعادة الاتصال — {{winner}} يفوز",
            watcherWaitingForReconnect: "في انتظار إعادة اتصال أحد اللاعبين…",
        },
        site: {
            confirm: "تأكيد",
            cancel: "إلغاء",
            notice: "تنبيه",
            ok: "موافق",
            home: "الرئيسية",
            search: "بحث",
            friends: "الأصدقاء",
            groups: "المجموعات",
            debug: "تصحيح",
            account: "الحساب",
            preferences: "التفضيلات",
            administrate: "الإدارة",
            logOut: "تسجيل الخروج",
            logIn: "تسجيل الدخول",
            admin: "المشرف",
            homeAria: "الرئيسية",
        },
        validation: {
            validEmail: "يرجى إدخال بريد إلكتروني صالح",
            passwordsMustMatch: "يرجى التأكد من تطابق حقول كلمة المرور.",
            chooseUsername: "يرجى اختيار اسم مستخدم",
            usernameNotAvailable: "اسم المستخدم هذا غير متاح",
            passwordNoWhitespace: "يجب ألا تحتوي كلمة المرور على مسافات.",
            passwordUppercase: "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = ar;
    } else {
        global.ShmerlingStringsAr = ar;
    }
})(typeof window !== "undefined" ? window : globalThis);
