/**
 * Bengali supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const bnExtra = {
        validation: {
            passwordLowercase: "পাসওয়ার্ডে অন্তত একটি ছোট হাতের অক্ষর থাকতে হবে।",
            passwordDigit: "পাসওয়ার্ডে কমপক্ষে একটি সংখ্যা থাকতে হবে।",
            passwordSymbol: "পাসওয়ার্ডে অন্তত একটি বিশেষ চিহ্ন থাকতে হবে।",
            passwordLength: "পাসওয়ার্ড 8-30 অক্ষর দীর্ঘ হতে হবে।",
            noHtml: "{{label}} HTML অন্তর্ভুক্ত করা উচিত নয়৷",
            position: {
                headerSave: "এই অবস্থান সংরক্ষণ করতে পারবেন না:",
                headerPlay: "এই অবস্থান থেকে খেলতে পারবেন না:",
                headerUse: "এই অবস্থান ব্যবহার করতে পারবেন না:",
                headerSaveBookmark: "এই বুকমার্ক সংরক্ষণ করা যাবে না:",
                headerAddBookmark: "এই বুকমার্ক যোগ করা যাবে না:",
                boardUnreadable: "বোর্ড পড়তে পারিনি। বোর্ড লোড হওয়ার পরে আবার চেষ্টা করুন।",
                whiteKingNone: "বোর্ডে ঠিক একজন সাদা রাজা থাকতে হবে। কোনোটাই পাওয়া যায়নি।",
                whiteKingCount: "বোর্ডে ঠিক একজন সাদা রাজা থাকতে হবে। {{count}} সাদা রাজা পাওয়া গেছে।",
                blackKingNone: "বোর্ডে অবশ্যই একজন কালো রাজা থাকতে হবে। কোনোটাই পাওয়া যায়নি।",
                blackKingCount: "বোর্ডে অবশ্যই একজন কালো রাজা থাকতে হবে। {{count}} কালো রাজা পাওয়া গেছে।",
                kingsAdjacent: "দুই রাজা সন্নিহিত স্কোয়ারে থাকতে পারে না (তির্যক সহ)।",
                sideInCheck: "{{mover}} সরাতে হবে, কিন্তু {{king}} এর রাজা ইতিমধ্যেই চেক করছেন৷ সরানোর পাশ চেক দিতে পারে না - পালা পরিবর্তন বা টুকরা সরান.",
                drawInsufficientKings: "এই অবস্থানটি অপর্যাপ্ত উপাদান (রাজা বনাম রাজা) দ্বারা একটি ড্র। টুকরা যোগ করুন যাতে চেকমেট সম্ভব থাকে।",
                drawInsufficientMinor: "এই অবস্থানটি অপর্যাপ্ত উপাদান (রাজা এবং বিশপ বা নাইট বনাম একাকী রাজা) দ্বারা একটি ড্র। টুকরা যোগ করুন যাতে চেকমেট সম্ভব থাকে।",
                drawBishopsSameColor: "এই অবস্থানটি অপর্যাপ্ত উপাদান দ্বারা একটি ড্র (একই বর্গাকার রঙে বিশপ বনাম বিশপ)। টুকরা যোগ করুন যাতে চেকমেট সম্ভব থাকে।",
                tooManyQueens: "{{color}} এর {{count}} রাণী আছে; সর্বোচ্চ 9 প্রতি রঙ.",
                tooManyRooks: "{{color}} এর {{count}} রুক আছে; সর্বোচ্চ 10 প্রতি রঙ.",
                tooManyBishops: "{{color}} এর {{count}} বিশপ আছে; সর্বোচ্চ 10 প্রতি রঙ.",
                tooManyKnights: "{{color}} এর {{count}} নাইট আছে; সর্বোচ্চ 10 প্রতি রঙ.",
                tooManyPawns: "{{color}} এর {{count}} প্যান আছে; সর্বোচ্চ 8 রঙ প্রতি."
            }
        },
        auth: {
            whoAreYou: "তুমি কে?",
            enterPassword: "পাসওয়ার্ড দয়া করে",
            sorry: "দুঃখিত",
            continue: "চালিয়ে যান",
            usernameField: "ব্যবহারকারীর নাম",
            passwordField: "পাসওয়ার্ড",
            wrongCredentials: "ভুল ব্যবহারকারীর নাম বা পাসওয়ার্ড",
            userAdded: "ব্যবহারকারী সফলভাবে যোগ করা হয়েছে",
            couldNotSaveBookmark: "বুকমার্ক সংরক্ষণ করা যায়নি",
            invalidUserId: "অবৈধ ব্যবহারকারী আইডি",
            generationJobRunning: "আরেকটি প্রজন্মের কাজ ইতিমধ্যেই চলছে...",
            listingPgnFiles: "PGN ফাইল তালিকাভুক্ত করা হচ্ছে..."
        },
        classic: {
            loadGame: "লোড গেম",
            load: "লোড",
            enterGameState: "খেলার অবস্থা এখানে আটকে দিন...",
            rematch: "রিম্যাচ",
            drawOffer: "ড্র অফার",
            lastMove: "লাস্ট মুভ",
            bookmarks: "বুকমার্ক",
            bookmarkAlertTitle: "বুকমার্ক অবস্থান",
            promotion: "পদোন্নতি !",
            check: "চেক করুন",
            checkmateWins: "চেকমেট ! {{winner}} জয়!",
            drawReason: "ড্র — {{reason}}",
            opponentDisconnected: "প্রতিপক্ষ সংযোগ বিচ্ছিন্ন করেছে",
            opponentResignedWins: "প্রতিপক্ষ পদত্যাগ করেছে, {{winner}} জিতেছে",
            somethingWentWrong: "কিছু ভুল হয়েছে",
            playerRejoined: "{{name}} আবার যোগদান করেছে৷",
            aPlayerRejoined: "একজন খেলোয়াড় আবার যোগ দিয়েছেন",
            opponentRejoined: "প্রতিপক্ষ আবার যোগ দিল",
            rematchOfferAccepted: "পুনরায় ম্যাচ অফার গৃহীত",
            rematchOfferDeclined: "রিম্যাচ অফার প্রত্যাখ্যান",
            sideOffersDraw: "{{side}} অফার ড্র",
            drawOfferDeclined: "ড্র অফার প্রত্যাখ্যান করা হয়েছে",
            watcherWatching: "{{name}} খেলা দেখছে",
            drawOfferSent: "ড্র অফার পাঠানো হয়েছে",
            rematchOfferSent: "রিম্যাচ অফার পাঠানো হয়েছে",
            newGameStarted: "নতুন খেলা শুরু হয়েছে",
            gameOver: "খেলা শেষ",
            gameCancelled: "খেলা বাতিল",
            youResignedWins: "আপনি পদত্যাগ করেছেন, {{winner}} জিতেছেন",
            movesCopied: "ক্লিপবোর্ডে কপি করা হয়েছে!",
            failedCopyMoves: "পদক্ষেপগুলি অনুলিপি করতে ব্যর্থ হয়েছে৷",
            failedLoadBrainConfig: "ব্রেন কনফিগারেশন লোড করতে ব্যর্থ হয়েছে৷",
            failedSaveBrainConfig: "মস্তিষ্কের কনফিগারেশন সংরক্ষণ করতে ব্যর্থ হয়েছে৷",
            offerDrawConfirm: "একটি ড্র প্রস্তাব?",
            drawOfferAccept: "প্রতিপক্ষ ড্রয়ের প্রস্তাব পাঠিয়েছে, মেনে নেবেন?",
            rematchOfferAccept: "Opponenet একটি রিম্যাচ প্রস্তাব, রাজি?",
            rematchOfferAcceptWithTime: "প্রতিপক্ষ একটি রিম্যাচের প্রস্তাব দিয়েছে (প্রতি পাশে {{minutes}} মিনিট)। রাজি?",
            rematchTimePrompt: "রিম্যাচের জন্য প্রতি পক্ষের মিনিট:",
            connectionLost: "সংযোগ হারিয়েছে — চালগুলি সার্ভারে পৌঁছাচ্ছে না",
            confirmExitGame: "আপনি কি নিশ্চিত আপনি গেম থেকে প্রস্থান করতে চান?",
            mobileResign: "পদত্যাগ করুন",
            mobileRematch: "রিম্যাচ",
            mobileDraw: "ড্র",
            mobileFlip: "ফ্লিপ",
            mobileLastMove: "শেষ চাল",
            mobileMovesList: "সরানো তালিকা",
            researchToolbox: "টুলবক্স",
            researchBrainConfig: "ব্রেন কনফিগারেশন",
            researchSave: "সংরক্ষণ করুন",
            researchDiscard: "বাতিল করুন",
            researchEditMode: "সম্পাদনা মোড",
            researchRun: "চালান",
            researchProperty: "সম্পত্তি",
            researchValue: "মান",
            playerOnline: "অনলাইন",
            playerDisconnectedStatus: "সংযোগ বিচ্ছিন্ন",
            playerOffline: "অফলাইন",
            humanVsComputer: "মানব বনাম কম্পিউটার",
            newGameTwoPlayers: "নতুন গেম 2 প্লেয়ার",
            settings: "সেটিংস",
            help: "সাহায্য",
            drawOffersNotVsEngine: "ইঞ্জিনের বিরুদ্ধে খেলার সময় ড্র অফার পাওয়া যায় না।",
            failedStartFromBookmark: "বুকমার্ক থেকে গেম শুরু করতে ব্যর্থ হয়েছে৷",
            resignConfirm: "পদত্যাগ করবেন?",
            areYouSure: "আপনি কি নিশ্চিত?",
            gameOverOpponentFailedReconnectWinsClassic: "খেলা শেষ - প্রতিপক্ষ পুনরায় সংযোগ করতে ব্যর্থ হয়েছে৷ {{winner}} জয়।",
            reconnectTimeoutNoMoves: "পুনঃসংযোগ টাইম আউট কোনো চাল খেলা ছাড়া.",
            waitingOpponentRejoin: "প্রতিপক্ষের পুনরায় যোগদানের জন্য অপেক্ষা করা হচ্ছে",
            timeoutOneSec: "সময়সীমা: 1 সেকেন্ড",
            timeoutSecs: "সময়সীমা: {{count}} সেকেন্ড",
            whitePieceAlt: "সাদা টুকরা",
            blackPieceAlt: "কালো টুকরা",
            eraserTitle: "ইরেজার",
            eraserAria: "ইরেজার - বর্গক্ষেত্র থেকে টুকরা সরান",
            selectTitle: "নির্বাচন করুন",
            selectAria: "নির্বাচন করুন - টুকরোগুলি সরাতে টেনে আনুন",
            resetAria: "রিসেট করুন - সমস্ত টুকরা সাফ করুন",
            defaultPositionAria: "ডিফল্ট অবস্থান - স্ট্যান্ডার্ড প্রারম্ভিক অবস্থান সেট আপ করুন",
            loading: "লোড হচ্ছে...",
            engineLabel: "ইঞ্জিন"
        },
        site: {
            home: "বাড়ি",
            search: "অনুসন্ধান করুন",
            friends: "বন্ধুরা",
            groups: "গোষ্ঠী",
            debug: "ডিবাগ",
            account: "হিসাব",
            preferences: "পছন্দসমূহ",
            administrate: "প্রশাসন",
            logOut: "লগ আউট করুন",
            logIn: "লগ ইন করুন",
            admin: "অ্যাডমিন",
            homeAria: "বাড়ি",
            confirm: "নিশ্চিত করুন",
            cancel: "বাতিল করুন",
            notice: "লক্ষ্য করুন",
            ok: "OK",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "ফুটার",
                privacy: "গোপনীয়তা নীতি",
                terms: "ব্যবহারের শর্তাবলী",
                contact: "যোগাযোগ",
                copyright: "© {{year}} শমারলিং দাবা। সর্বস্বত্ব সংরক্ষিত",
                lastUpdated: "সর্বশেষ আপডেট করা হয়েছে: {{date}}",
                privacyTitle: "গোপনীয়তা নীতি",
                privacyLead: "শমারলিং দাবা কীভাবে অ্যাকাউন্ট এবং গেমপ্লে তথ্য পরিচালনা করে।",
                privacyBody: "আমরা পরিষেবা পরিচালনা করতে, গেম এবং পছন্দগুলি রাখতে এবং পণ্যের উন্নতি করতে আপনার অ্যাকাউন্টের বিবরণ ব্যবহার করি। আমরা ব্যক্তিগত তথ্য বিক্রি করি না। সম্পূর্ণ নীতি পাঠ এখানে প্রকাশিত হবে.",
                termsTitle: "ব্যবহারের শর্তাবলী",
                termsLead: "শমারলিং দাবা ব্যবহারের নিয়ম।",
                termsBody: "Shmerling দাবা ব্যবহার করে আপনি ন্যায্যভাবে খেলতে, অন্য খেলোয়াড়দের সম্মান করতে এবং শুধুমাত্র ব্যক্তিগত দাবা খেলার জন্য পরিষেবা ব্যবহার করতে সম্মত হন। সম্পূর্ণ শর্তাবলী এখানে প্রকাশিত হবে.",
                contactTitle: "যোগাযোগ",
                contactLead: "Shmerling দাবা দলের সাথে যোগাযোগ করুন.",
                contactBody: "সমর্থন এবং গোপনীয়তা প্রশ্নের জন্য যোগাযোগের বিশদ বিবরণ এখানে প্রকাশিত হবে।",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "ব্যবহারকারীর নাম:",
            password: "পাসওয়ার্ড:",
            login: "লগইন করুন",
            register: {
                submit: "নিবন্ধন করুন",
                confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন:",
                playerLevel: "প্লেয়ার লেভেল:",
                rookie: "রুকি",
                skilled: "দক্ষ",
                elite: "অভিজাত",
                grandMaster: "গ্র্যান্ড মাস্টার"
            },
            email: "ইমেইল:",
            welcome: {
                greeting: "ফিরে স্বাগতম",
                tagline: "আপনার পদক্ষেপ অপেক্ষা করছে",
                playNow: "এখন খেলুন!",
                activeGames: "সক্রিয় গেম",
                live: "লাইভ",
                showAll: "সব দেখান",
                viewAllActive: "সমস্ত সক্রিয় গেম দেখুন",
                mostRecent: "সবচেয়ে সাম্প্রতিক প্রথম",
                noGamesNow: "এই মুহূর্তে কোনো খেলা নেই",
                myGames: "আমার শেষ খেলা",
                viewAllGames: "সমস্ত গেম দেখুন",
                recentCompleted: "আপনার সাম্প্রতিক সমাপ্ত গেম",
                noCompleted: "এখনও কোন সম্পূর্ণ খেলা",
                activeGamesAria: "সক্রিয় গেম",
                inviteOnlineFriend: "খেলার জন্য একজন অনলাইন বন্ধুকে আমন্ত্রণ জানান",
                friendsPageTitle: "বন্ধুদের পেজ",
                manageFriends: "পরিচালনা করুন",
                colFriend: "বন্ধু",
                colStatus: "স্ট্যাটাস",
                findPlayers: "খেলোয়াড় খুঁজুন",
                waitingForResponse: "প্রতিক্রিয়ার অপেক্ষায়",
                inviteSentSuffix: "(আমন্ত্রণ পাঠানো হয়েছে)",
                sortByRowNumber: "সারি সংখ্যা অনুসারে সাজান",
                sortBy: "{{key}} অনুসারে সাজান"
            },
            gameList: {
                date: "তারিখ",
                time: "সময়",
                result: "ফলাফল",
                reason: "কারণ",
                type: "টাইপ",
                status: "স্ট্যাটাস",
                event: "ঘটনা",
                site: "সাইট",
                round: "গোলাকার"
            },
            loginPage: {
                title: "লগইন করুন"
            },
            error: {
                title: "কিছু ভুল হয়েছে",
                body: "একটি ত্রুটি ঘটেছে.",
                back: "মূলে ফিরে যান"
            },
            log: {
                title: "সার্ভার লগ",
                clear: "পরিষ্কার দৃশ্য",
                latest: "সর্বশেষ",
                waiting: "সার্ভার লগ আউটপুটের জন্য অপেক্ষা করা হচ্ছে..."
            },
            activeGames: {
                moves: "নড়াচড়া করে",
                turn: "পালা",
                status: "স্ট্যাটাস",
                inProgress: "চলছে",
                onHold: "হোল্ডে",
                vs: "বনাম",
                minutesAgo: "{{count}} মিনিট আগে",
                oneMinuteAgo: "1 মিনিট আগে",
                justStarted: "সবে শুরু হয়েছে",
                notStarted: "শুরু হয়নি",
                startedTooltip: "শুরু হয়েছে: {{when}}",
                playersVs: "{{white}} বনাম {{black}}"
            },
            friendsPage: {
                title: "বন্ধুরা",
                tagline: "নতুন দাবা সঙ্গী খুঁজুন",
                myFriends: "আমার বন্ধুরা",
                noFriendsYet: "এখনো কোন বন্ধু নেই",
                findPlayers: "খেলোয়াড় খুঁজুন",
                searchByUsername: "ব্যবহারকারীর নাম দ্বারা অনুসন্ধান করুন",
                searchPlaceholder: "অনুসন্ধান করতে টাইপ করুন...",
                enterCharToSearch: "অনুসন্ধান করতে অন্তত একটি অক্ষর লিখুন",
                noMatchingUsers: "কোন মিল ব্যবহারকারী",
                playing: "বাজানো",
                pendingFriendshipOffer: "মুলতুবি বন্ধুত্ব প্রস্তাব",
                joining: "যোগদান করছেন",
                rejoin: "পুনরায় যোগদান করুন",
                friendRequest: "বন্ধুর অনুরোধ",
                wantsToBeFriends: "(বন্ধু হতে চায়)",
                pendingOfferSuffix: "(বন্ধুত্ব অফার মুলতুবি)",
                waitingFriendRespond: "আপনার বন্ধুর প্রতিক্রিয়ার জন্য অপেক্ষা করছি",
                cancelBeforeRemove: "এই বন্ধুকে সরিয়ে দেওয়ার আগে গেমের আমন্ত্রণ বাতিল করুন",
                friendsTag: "বন্ধুরা",
                offerReceivedTag: "অফার প্রাপ্ত হয়েছে — আপনার বন্ধুদের দেখুন",
                addFriend: "বন্ধু যোগ করুন",
                withdraw: "প্রত্যাহার করুন",
                requestFailed: "অনুরোধ ব্যর্থ হয়েছে",
                removeFriendConfirm: "এই বন্ধুটিকে আপনার তালিকা থেকে সরিয়ে দেবেন?",
                removeFriendTitle: "বন্ধুকে সরিয়ে দাও",
                withdrawOfferConfirm: "এই বন্ধুত্ব প্রস্তাব প্রত্যাহার?",
                withdrawOfferTitle: "অফার প্রত্যাহার করুন",
                couldNotAccept: "মেনে নিতে পারেনি",
                couldNotDecline: "অস্বীকার করতে পারেনি",
                couldNotRemove: "সরাতে পারেনি",
                couldNotCancelInvite: "আমন্ত্রণ বাতিল করা যায়নি",
                couldNotWithdraw: "প্রত্যাহার করা যায়নি",
                couldNotSendInvite: "আমন্ত্রণ পাঠানো যায়নি",
                couldNotSendGameInvite: "খেলার আমন্ত্রণ পাঠানো যায়নি",
                gameInvite: "খেলার আমন্ত্রণ",
                gameInvitationsAria: "খেলার আমন্ত্রণ",
                gameInvitationAria: "খেলার আমন্ত্রণ",
                chessInviteTitle: "দাবা আমন্ত্রণ",
                wantsToPlayAsBlack: "{{name}} খেলতে চায়। তুমি কালো হয়ে খেলো।",
                wantsToPlayYouWhite: "{{name}} খেলতে চায়। তুমি সাদা হয়ে খেলো।",
                aFriend: "একজন বন্ধু",
                youPlayAsWhite: "তুমি সাদা হয়ে খেলো",
                youPlayAsBlack: "তুমি কালো হয়ে খেলো",
                establishingGame: "খেলা স্থাপন করা হচ্ছে...",
                yourOpponent: "আপনার প্রতিপক্ষ",
                declinedYourInvite: "{{name}} আপনার খেলার আমন্ত্রণ প্রত্যাখ্যান করেছে৷",
                cancelInvite: "আমন্ত্রণ বাতিল করুন",
                accept: "গ্রহণ করুন",
                decline: "প্রত্যাখ্যান",
                invite: "আমন্ত্রণ জানান",
                inviteSettingsTitle: "আমন্ত্রণ সেটিংস",
                inviteSettingsFor: "{{name}} আমন্ত্রণ জানান",
                inviteTimeMinutes: "প্রতি পাশে সময় (মিনিট)",
                inviteYourColor: "তোমার রং",
                inviteColorWhite: "সাদা",
                inviteColorBlack: "কালো",
                inviteColorRandom: "এলোমেলো",
                inviteFriendly: "বন্ধুত্বপূর্ণ খেলা",
                inviteFriendlyHint: "পরে ELO-তে গণনা করতে টিক চিহ্ন সরিয়ে দিন (রেট করা প্লে)।",
                invitePrivate: "ব্যক্তিগত খেলা",
                invitePrivateHint: "পাবলিক অ্যাক্টিভ-গেমস লবি থেকে এই গেমটি লুকান৷",
                inviteSaveDefaults: "ডিফল্ট সংরক্ষণ করুন",
                inviteOfferTime: "{{minutes}} মিনিট",
                inviteOfferFriendly: "বন্ধুত্বপূর্ণ",
                inviteOfferRated: "রেট",
                inviteOfferPrivate: "ব্যক্তিগত",
                remove: "সরান",
                offerSent: "অফার পাঠানো হয়েছে",
                pending: "মুলতুবি",
                online: "অনলাইন",
                offline: "অফলাইন"
            },
            adminPage: {
                title: "প্রশাসন",
                tagline: "ব্যবহারকারী, গেম, ইঞ্জিন, খোলার বই এবং বট ডুয়েল",
                panelTitle: "অ্যাডমিন কনসোল",
                users: "ব্যবহারকারীদের",
                generate: "তৈরি করুন",
                games: "গেমস",
                engines: "ইঞ্জিন",
                states: "রাজ্যগুলি",
                openingBook: "খোলা বই",
                bots: "বট",
                addUser: "ব্যবহারকারী যোগ করুন",
                sectionsAria: "অ্যাডমিন বিভাগ",
                openingBookLabel: "খোলা বই:",
                openingBookStatusTitle: "বর্তমান খোলার বই",
                openingBookFile: "ফাইল",
                openingBookExists: "স্ট্যাটাস",
                openingBookExistsYes: "বর্তমান",
                openingBookExistsNo: "অনুপস্থিত",
                openingBookLines: "খেলা লাইন",
                openingBookSize: "আকার",
                openingBookModified: "সর্বশেষ সংশোধন করা হয়েছে",
                openingBookPgnSources: "পিজিএন সূত্র",
                openingBookPgnCount: "{{count}} PGN ফাইল(গুলি) থেকে পুনর্নির্মাণের জন্য উপলব্ধ",
                openingBookIntro: "সার্ভারের PGN ফোল্ডারগুলি থেকে লাইন-ভিত্তিক খোলার বই (data/opening-book-lines.txt) পুনর্নির্মাণ করুন। নীচের খোলার বই তৈরি করুন ব্যবহার করুন - আপনি এটি টিপে না হওয়া পর্যন্ত কিছুই চলবে না।",
                generateOpeningBook: "খোলার বই তৈরি করুন",
                botsIntro: "একটি পাবলিক ইঞ্জিন-বনাম-ইঞ্জিন গেম শুরু করুন। সদস্যরা এটিকে অ্যাক্টিভ গেমস অন হোম থেকে দর্শক হিসেবে খুলতে পারেন।",
                botsWhiteEngine: "সাদা ইঞ্জিন",
                botsBlackEngine: "কালো ইঞ্জিন",
                botsWhiteDifficulty: "অসুবিধা (1-6)",
                botsBlackDifficulty: "অসুবিধা (1-6)",
                botsSkillLevel: "দক্ষতা (0-20)",
                botsTimeMinutes: "ঘড়ি (মিনিট)",
                botsStart: "দ্বন্দ্ব শুরু করুন",
                botsStarting: "দ্বন্দ্ব শুরু হচ্ছে...",
                botsStarted: "দ্বন্দ্ব শুরু হয়েছে: {{white}} বনাম {{black}}।",
                botsWatchLink: "এই খেলা দেখুন",
                botsListedNote: "অন্যান্য ব্যবহারকারীদের জন্য হোম → সক্রিয় গেম তালিকাভুক্ত।",
                botsStartFailed: "দ্বৈরথ শুরু করা যায়নি।",
                botsStopped: "থামার অনুরোধ করা হলো।",
                botsStopFailed: "দ্বন্দ্ব থামাতে পারেনি।",
                gameLines: "খেলা লাইন",
                noGamesInDb: "ডাটাবেসে এখনো কোনো গেম নেই।",
                gamesPaginationAria: "গেম পৃষ্ঠা সংখ্যা",
                colNum: "#",
                colUsername: "ব্যবহারকারীর নাম",
                colType: "টাইপ",
                colEmail: "ইমেইল",
                colPassword: "পাসওয়ার্ড",
                colLevel: "স্তর",
                colElo: "এলো",
                colJoined: "যোগদান করেছেন",
                colLastLogin: "শেষ লগইন",
                colActiveGames: "সক্রিয় গেম",
                colFriends: "বন্ধুরা",
                colBookmarks: "বুকমার্ক",
                colId: "আইডি",
                colStatus: "স্ট্যাটাস",
                colName: "নাম",
                colAvailable: "পাওয়া যায়",
                colEnabled: "সক্রিয়",
                colBackend: "ব্যাকএন্ড",
                colCommand: "আদেশ",
                colNotes: "নোট",
                colNote: "দ্রষ্টব্য",
                colAction: "অ্যাকশন",
                emptyUsers: "এখনো কোনো ব্যবহারকারী নেই।",
                emptyData: "এখনো কোনো তথ্য নেই।",
                emptyEngines: "রেজিস্ট্রিতে কোন প্লে ইঞ্জিন নেই।",
                emptyStates: "ওপেনিং-বুক এবং স্টেট জেনারেশন পেজ খুলতে জেনারেট ব্যবহার করুন।",
                engineAvailableYes: "পাওয়া যায়",
                engineAvailableNo: "অনুপলব্ধ",
                engineEnable: "সক্ষম করুন",
                engineDisable: "নিষ্ক্রিয় করুন",
                enginesLoadFailed: "ইঞ্জিন লোড করা যায়নি",
                enginesSaveFailed: "ইঞ্জিন আপডেট করা যায়নি",
                clickToEdit: "সম্পাদনা করতে ক্লিক করুন",
                updateFailed: "আপডেট ব্যর্থ হয়েছে",
                couldNotSave: "বাঁচাতে পারেনি",
                setPassword: "পাসওয়ার্ড সেট করুন",
                setPasswordTitle: "একটি নতুন পাসওয়ার্ড সেট করতে ক্লিক করুন (4-30 অক্ষর)",
                passwordLengthInvalid: "পাসওয়ার্ড 4 থেকে 30 অক্ষরের মধ্যে হতে হবে।",
                invalidPassword: "অবৈধ পাসওয়ার্ড",
                saved: "সংরক্ষিত",
                newPasswordPlaceholder: "নতুন পাসওয়ার্ড",
                clickChangeUserType: "ব্যবহারকারীর ধরন পরিবর্তন করতে ক্লিক করুন",
                userTypeAria: "ব্যবহারকারীর ধরন",
                changeUserTypeTitle: "ব্যবহারকারীর ধরন পরিবর্তন করুন",
                grantAdminConfirm: "এই ব্যবহারকারীকে প্রশাসক বিশেষাধিকার প্রদান করবেন? তারা অ্যাডমিন টুল অ্যাক্সেস করতে এবং অ্যাকাউন্ট পরিচালনা করতে সক্ষম হবে।",
                demoteAdminConfirm: "এই ব্যবহারকারীকে অ্যাডমিন থেকে {{type}} এ পরিবর্তন করবেন? তারা অ্যাডমিন এলাকায় অ্যাক্সেস হারাবে।",
                changeUserTypeConfirm: "এই ব্যবহারকারীকে {{type}} এ পরিবর্তন করবেন?",
                clickChangeLevel: "স্তর পরিবর্তন করতে ক্লিক করুন",
                playerLevelAria: "প্লেয়ার লেভেল",
                sortByRowNumber: "সারি সংখ্যা অনুসারে সাজান",
                sortBy: "{{key}} অনুসারে সাজান",
                delete: "মুছুন",
                first: "প্রথম",
                last: "শেষ",
                previous: "আগের",
                next: "পরবর্তী",
                previous5Pages: "আগের ৫ পৃষ্ঠা",
                next5Pages: "পরবর্তী 5 পৃষ্ঠা",
                previous10Pages: "আগের 10 পৃষ্ঠা",
                next10Pages: "পরবর্তী 10 পৃষ্ঠা",
                userTypeAdmin: "অ্যাডমিন",
                userTypePartner: "অংশীদার",
                userTypeMember: "সদস্য",
                generateTitle: "খোলা বই এবং রাষ্ট্র প্রজন্ম",
                backToAdmin: "← অ্যাডমিনে ফিরে যান",
                generateIntro: "সার্ভারের গেম ম্যানেজার ফোল্ডারের অধীনে থাকা সমস্ত PGN ফাইল স্টেট মঙ্গো সংগ্রহে বা লাইন-ভিত্তিক খোলার বইতে (data/opening-book-lines.txt) রিপ্লে করে। একটি লক্ষ্য চয়ন করুন, তারপরে স্টার্ট জেনারেশন টিপুন - আপনি না করা পর্যন্ত কিছুই চলবে না।",
                target: "টার্গেট",
                targetMongo: "MongoDB — রাজ্য সংগ্রহে সারি যুক্ত করুন",
                targetBook: "লাইন ফাইল — খোলার বই লিখুন (opening-book-lines.txt)",
                startGeneration: "প্রজন্ম শুরু করুন",
                stop: "থামো",
                idle: "নিষ্ক্রিয়।",
                starting: "শুরু হচ্ছে...",
                running: "চলছে ({{mode}})…",
                readingFiles: "{{count}} ফাইল(গুলি) পড়া হচ্ছে…",
                replayingGames: "{{count}} গেম রিপ্লে করা হচ্ছে...",
                writingOpeningBook: "উদ্বোধনী বই লেখা হচ্ছে...",
                readingPgn: "PGN পড়া {{index}} / {{total}} ({{games}} গেম)",
                replayGameProgress: "রিপ্লে গেম {{current}} / {{total}} (সমাপ্ত ঠিক আছে: {{completed}})",
                stopped: "থেমে গেল।",
                bookUnchanged: "বিদ্যমান খোলার বই পরিবর্তন করা হয়নি.",
                bookLinesInFile: "{{count}} গেম লাইন(গুলি) {{file}} এ।",
                cancelledBeforeRead: "PGN পড়ার আগে বাতিল করা হয়েছে।",
                cancelledAfterRead: "পড়ার পরে বাতিল; রিপ্লে বাদ দেওয়া হয়েছিল (কিছু লেখা হয়নি)।",
                mongoGamesSaved: "{{count}} গেম(গুলি)তে নতুন স্টেট সারি সেভ করা হয়েছে।",
                doneBook: "সম্পন্ন {{count}} গেম লাইন → {{file}}",
                doneBookFileOnly: "সম্পন্ন {{file}}",
                doneMongo: "সম্পন্ন MongoDB রাজ্য সংগ্রহ আপডেট করা হয়েছে{{detail}}।",
                doneMongoDetail: "({{count}} গেমগুলি আবার প্লে হয়েছে ঠিক আছে)",
                errorPrefix: "ত্রুটি: {{message}}",
                unknownError: "অজানা",
                connectionClosed: "সংযোগ বন্ধ (সার্ভার লগ চেক করুন বা আবার চেষ্টা করুন)।",
                openingBookDefault: "খোলার বই"
            },
            playNow: {
                title: "নতুন খেলা",
                startTitle: "একটি নতুন গেম শুরু করুন",
                playingColor: "রঙ খেলা",
                timeMin: "সময় (মিনিট)",
                difficulty: "অসুবিধা (1-5)",
                mousePreference: "মাউস পছন্দ",
                drag: "টেনে আনুন",
                doubleClick: "ডাবল ক্লিক করুন",
                showAvailableMoves: "উপলব্ধ চাল দেখান",
                private: "ব্যক্তিগত",
                privateHint: "অন্যান্য সদস্যদের সক্রিয় গেম তালিকায় ব্যক্তিগত গেমগুলি দেখানো হয় না৷",
                playComputer: "কম্পিউটার খেলুন",
                browseAll: "সব ব্রাউজ করুন",
                yourHistory: "তোমার ইতিহাস",
                fullList: "সম্পূর্ণ তালিকা",
                gameLibrary: "গেম লাইব্রেরি",
                openLibrarySearch: "লাইব্রেরি অনুসন্ধান খুলুন",
                brain3: "মস্তিষ্ক 3",
                brain2: "মস্তিষ্ক 2"
            },
            activeGamesList: {
                title: "সক্রিয় গেম",
                tagline: "সব খেলা চলছে",
                liveGames: "লাইভ গেম",
                game: "খেলা",
                started: "শুরু হয়েছে"
            },
            list: {
                title: "সব গেম",
                tagline: "আপনার সম্পূর্ণ গেম",
                allGames: "গেমস শেষ",
                gamesCount: "{{count}} গেম",
                action: "অ্যাকশন"
            },
            searchPage: {
                title: "অনুসন্ধান:",
                tagline: "আর্কাইভে বিখ্যাত গেম খুঁজুন",
                results: "ফলাফল",
                resultsCount: "{{count}} ফলাফল",
                noResults: "আপনার অনুসন্ধানের সাথে কোনো গেম মেলে না",
                button: "অনুসন্ধান করুন",
                resultsFound: "{{count}} ফলাফল পাওয়া গেছে:",
                first: "প্রথম",
                last: "শেষ",
                previous: "আগের",
                next: "পরবর্তী",
                previous5Pages: "আগের ৫ পৃষ্ঠা",
                next5Pages: "পরবর্তী 5 পৃষ্ঠা",
                previous10Pages: "আগের 10 পৃষ্ঠা",
                next10Pages: "পরবর্তী 10 পৃষ্ঠা"
            },
            game: {
                moves: "নড়াচড়া করে",
                white: "সাদা",
                black: "কালো",
                resign: "পদত্যাগ করুন",
                draw: "ড্র",
                undo: "পূর্বাবস্থায় ফেরান",
                flip: "ফ্লিপ",
                practice: "অনুশীলন করুন"
            },
            mobileWelcome: {
                title: "বাড়ি — দাবা",
                play: "খেলা",
                library: "লাইব্রেরি",
                friends: "বন্ধুরা"
            },
            mobileGame: {
                title: "খেলা",
                moves: "নড়াচড়া করে",
                resign: "পদত্যাগ করুন"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "কিছু ভুল হয়েছে",
                body: "একটি ত্রুটি ঘটেছে.",
                back: "মূলে ফিরে যান"
            },
            chrome: {
                preferences: "পছন্দসমূহ",
                closePreferences: "পছন্দগুলি বন্ধ করুন",
                display: "প্রদর্শন",
                gameplay: "গেমপ্লে",
                pieceSet: "টুকরা সেট",
                boardTheme: "থিম",
                theme: "থিম",
                themeBlue: "নীল",
                themeDark: "অন্ধকার",
                customizeTheme: "থিম পরিচালনা করুন...",
                builtInThemesAria: "অন্তর্নির্মিত থিম",
                savedCustomThemesAria: "সংরক্ষিত কাস্টম থিম",
                pieceSetsAria: "টুকরা সেট",
                homeAria: "Shmerling দাবা বাড়িতে"
            },
            prefs: {
                language: "ভাষা",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "মাউস নিয়ন্ত্রণ",
                mouseDrag: "টেনে আনুন",
                mouseClick: "ক্লিক করুন",
                thinkingTime: "ইঞ্জিন চিন্তার সময়",
                thinkingTimeAria: "সেকেন্ডে ইঞ্জিন চিন্তার সময়",
                immediateResign: "অবিলম্বে পদত্যাগ করুন",
                secondsOption: "{{count}}",
                selectedTheme: "নির্বাচিত: {{name}}",
                selectedPieceSet: "নির্বাচিত: {{name}}",
                enterFullScreen: "পূর্ণ পর্দায় প্রবেশ করুন",
                exitFullScreen: "পূর্ণ স্ক্রীন থেকে প্রস্থান করুন",
                fullScreenUnavailable: "এই ব্রাউজারে ফুল স্ক্রিন পাওয়া যায় না।"
            },
            gameRun: {
                yourColor: "তোমার রং",
                engine: "ইঞ্জিন",
                thinkTime: "চিন্তা করার সময় (সেকেন্ড)",
                thinkTimeAria: "সেকেন্ডে ইঞ্জিন চিন্তার সময়",
                play: "খেলা",
                nextMove: "পরবর্তী পদক্ষেপ",
                computer: "কম্পিউটার",
                computerColorHint: "কম্পিউটার কোন রঙ খেলে - আপনি অন্য দিকে খেলুন"
            },
            brainConfig: {
                title: "মস্তিষ্কের কনফিগারেশন",
                save: "সংরক্ষণ করুন",
                reset: "রিসেট করুন",
                saved: "কনফিগারেশন সংরক্ষিত",
                failedSave: "কনফিগারেশন সংরক্ষণ করতে ব্যর্থ হয়েছে",
                brainLabel: "মস্তিষ্ক",
                loading: "লোড হচ্ছে...",
                failedLoad: "ব্রেন কনফিগারেশন লোড করতে ব্যর্থ হয়েছে৷",
                discardSwitchConfirm: "অসংরক্ষিত পরিবর্তনগুলি বাতিল করবেন এবং মস্তিষ্কের সংস্করণ পরিবর্তন করবেন?",
                discard: "বাতিল করুন",
                pieceScores: "পিস স্কোর",
                specialEvaluations: "বিশেষ মূল্যায়ন",
                gamePhase: "খেলার পর্ব",
                pawnFilesOpeningMid: "প্যান ফাইল (খোলা / মাঝামাঝি)",
                pawnFilesEndGame: "প্যান ফাইল (শেষ খেলা)"
            },
            customTheme: {
                title: "থিম",
                name: "থিমের নাম",
                save: "সংরক্ষণ করুন",
                delete: "মুছুন",
                saved: "থিম",
                searchProperties: "বৈশিষ্ট্য অনুসন্ধান করুন",
                filterPlaceholder: "সম্পত্তির নাম অনুসারে ফিল্টার করুন...",
                namePlaceholder: "আমার থিম",
                resetPreset: "পরিবর্তনগুলি রিসেট করুন",
                couldNotSave: "থিম সংরক্ষণ করা যায়নি. আবার চেষ্টা করুন",
                untitled: "শিরোনামহীন",
                defaultName: "নতুন থিম"
            },
            positionSetup: {
                clearBoard: "ক্লিয়ার বোর্ড",
                startingPosition: "শুরুর অবস্থান",
                flipBoard: "ফ্লিপ বোর্ড",
                eraser: "ইরেজার",
                selectAndMove: "নির্বাচন করুন এবং সরান",
                defaultStartingPosition: "ডিফল্ট শুরু অবস্থান",
                savePosition: "অবস্থান সংরক্ষণ করুন",
                saveAsNewPosition: "নতুন অবস্থান হিসাবে সংরক্ষণ করুন",
                validatePosition: "অবস্থান যাচাই করুন",
                positionFlags: "অবস্থান পতাকা",
                turn: "পালা",
                flagCheck: "চেক করুন",
                flagCheckmate: "চেকমেট",
                flagDraw: "ড্র",
                flagWhiteKingMoved: "সাদা রাজা সরে গেল",
                flagBlackKingMoved: "কালো রাজা সরে গেল",
                flagWhiteKingsideRookMoved: "সাদা কিংসাইড রুক সরানো",
                flagWhiteQueensideRookMoved: "সাদা কুইনসাইড রুক সরানো",
                flagBlackKingsideRookMoved: "কালো কিংসাইড রুক সরানো",
                flagBlackQueensideRookMoved: "কালো কুইনসাইড রুক সরানো"
            }
        },
        errorPage: {
            code: "ত্রুটি {{code}}",
            notFoundTitle: "পৃষ্ঠা পাওয়া যায়নি",
            notFoundMessage: "আপনি যে পৃষ্ঠাটি খুঁজছেন সেটি বিদ্যমান নেই।",
            genericTitle: "কিছু ভুল হয়েছে",
            genericMessage: "একটি অপ্রত্যাশিত ত্রুটি ঘটেছে৷ আবার চেষ্টা করুন.",
            backHome: "হোমে ফিরে যান"
        },
        mobile: {
            drawOfferTitle: "ড্র অফার",
            drawOfferMessage: "প্রতিপক্ষ ড্র প্রস্তাব পাঠিয়েছে। মেনে নেবেন?",
            rematchTitle: "রিম্যাচ",
            rematchMessage: "প্রতিপক্ষ আবার ম্যাচের অফার পাঠিয়েছে। মেনে নেবেন?",
            gameId: "গেম আইডি: {{id}}",
            drawOfferAgree: "প্রতিপক্ষ একটি ড্র প্রস্তাব, রাজি?",
            rematchOfferAgree: "প্রতিপক্ষ একটি রিম্যাচ প্রস্তাব, রাজি?",
            newGameWatchFromHome: "নতুন গেম শুরু হয়েছে — দেখতে বাড়িতে যান৷"
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = bnExtra;
    } else {
        global.ShmerlingStringsBnExtra = bnExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
