/**
 * Bengali string catalog — mirrors src/strings/en.js structure.
 */
(function (global) {
    "use strict";

    const bn = {
        common: {
            white: "সাদা",
            black: "কালো",
            draw: "ড্র",
            winner: "বিজয়ী",
            engine: "ইঞ্জিন",
            ok: "OK",
            cancel: "বাতিল করুন",
            confirm: "নিশ্চিত করুন",
            yes: "হ্যাঁ",
            no: "না",
            notice: "বিজ্ঞপ্তি",
            input: "ইনপুট",
            start: "শুরু করুন",
            collapse: "সংকুচিত করুন",
            expand: "প্রসারিত করুন",
            delete: "মুছুন",
            rename: "নাম পরিবর্তন করুন",
            save: "সংরক্ষণ করুন",
            aPlayer: "একজন খেলোয়াড়",
            pleaseEnterValue: "অনুগ্রহ করে একটি মান লিখুন।"
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "গেম অ্যাকশন",
                playersAndClocks: "খেলোয়াড় এবং ঘড়ি",
                whitePlayerClock: "সাদা প্লেয়ার ঘড়ি",
                blackPlayerClock: "কালো প্লেয়ার ঘড়ি",
                startFromLoadedPosition: "লোড অবস্থান থেকে খেলা শুরু করুন",
                moves: "চাল",
                expandMovesPanel: "চাল প্যানেল প্রসারিত করুন",
                expandMoves: "চাল দেখান",
                collapseMovesPanel: "চাল প্যানেল সংকুচিত করুন",
                reviewNavigation: "নেভিগেশন পর্যালোচনা করুন",
                positionSetup: "অবস্থান সেটআপ",
                pieces: "টুকরা",
                collapsePiecesPanel: "টুকরা প্যানেল সঙ্কুচিত করুন",
                brainConfiguration: "মস্তিষ্কের কনফিগারেশন",
                configuration: "কনফিগারেশন",
                collapseConfigurationPanel: "কনফিগারেশন প্যানেল সঙ্কুচিত করুন",
                games: "গেমস",
                expandGamesPanel: "গেম প্যানেল প্রসারিত করুন",
                expandGames: "গেমস প্রসারিত করুন",
                expandGamesLocked: "একটি খেলা চলাকালীন গেম প্যানেল অনুপলব্ধ৷",
                collapseGamesPanel: "গেম প্যানেল আড়াল করুন",
                chat: "চ্যাট",
                expandChatPanel: "চ্যাট প্যানেল প্রসারিত করুন",
                collapseChatPanel: "চ্যাট প্যানেল সঙ্কুচিত করুন",
                chatPlaceholder: "একটি বার্তা টাইপ করুন...",
                chatWatcherReadonly: "দর্শকরা শুধুমাত্র আড্ডা পড়তে পারেন",
                sendChat: "পাঠান",
                savedListFilter: "সংরক্ষিত তালিকা ফিল্টার",
                positions: "পদ",
                gameStatus: "খেলা অবস্থা",
                capturedPieces: "বন্দী টুকরা"
            },
            sessionMode: {
                play: "প্লে মোড",
                positionSetup: "অবস্থান সেটআপ",
                configuration: "কনফিগারেশন মোড",
                playback: "প্লেব্যাক মোড",
                review: "পর্যালোচনা মোড",
                watch: "ওয়াচ মোড",
                practice: "অনুশীলন মোড"
            },
            status: {
                chooseNewGameOrSetup: "সাইডবার থেকে নতুন গেম বা পজিশন সেটআপ বেছে নিন",
                chooseNewGame: "সাইডবার থেকে নতুন গেম বেছে নিন",
                setMoveColorEngineThinkTime: "হেডারে সরানো, রঙ, ইঞ্জিন এবং চিন্তা করার সময় সেট করুন, তারপর প্লে টিপুন",
                gameOver: "খেলা শেষ",
                gameInProgress: "খেলা চলছে",
                boardLoading: "বোর্ড এখনও লোড হচ্ছে...",
                boardNotReady: "বোর্ড এখনো প্রস্তুত নয়। অনুগ্রহ করে অপেক্ষা করুন এবং আবার চেষ্টা করুন।",
                leaveOnlineBeforeConfiguration: "কনফিগারেশন খোলার আগে অনলাইন গেমটি ছেড়ে দিন",
                configurationNotInPractice: "অনুশীলন মোডে কনফিগারেশন উপলব্ধ নয়",
                configurationModeEdit: "কনফিগারেশন মোড - মান সম্পাদনা করুন এবং সংরক্ষণ করুন",
                selectSavedOrSetup: "একটি সংরক্ষিত গেম নির্বাচন করুন বা প্রথমে বোর্ডে একটি অবস্থান সেট আপ করুন৷",
                gameAlreadyInProgress: "একটি খেলা ইতিমধ্যেই চলছে",
                yourMove: "তোমার চাল",
                engineToMove: "সরানোর জন্য ইঞ্জিন...",
                leaveOnlineBeforePositionSetup: "পজিশন সেটআপ খোলার আগে অনলাইন গেমটি ছেড়ে দিন",
                positionSetupNotInPractice: "অনুশীলন মোডে অবস্থান সেটআপ উপলব্ধ নয়",
                positionSetupPlacePieces: "অবস্থান সেটআপ - বোর্ডে টুকরা রাখুন",
                drawWithReason: "ড্র — {{reason}}",
                checkmateWins: "চেকমেট — {{winner}} জয়",
                check: "কিস্তি",
                waitBeforeEvaluate: "মূল্যায়ন করার আগে বর্তমান পদক্ষেপটি শেষ হওয়ার জন্য অপেক্ষা করুন",
                evaluationUnavailable: "মূল্যায়ন পাওয়া যায় না. Shmerling Chess অ্যাপটি পুনরায় চালু করুন।",
                evaluatingPosition: "অবস্থান মূল্যায়ন করা হচ্ছে...",
                evaluationFailed: "মূল্যায়ন ব্যর্থ হয়েছে",
                evaluationLine: "মূল্যায়ন (সরানোর জন্য {{side}}): {{score}}",
                checkmate: "কিশ",
                drawZero: "ড্র (0)",
                totalLabel: "মোট: {{value}}",
                openFolderDesktopOnly: "খোলা ফোল্ডার শুধুমাত্র ডেস্কটপ অ্যাপে উপলব্ধ",
                couldNotOpenGamesLogFolder: "গেম লগ ফোল্ডার খুলতে পারেনি",
                positionValid: "অবস্থান বৈধ",
                playingFromCustomPosition: "কাস্টম অবস্থান থেকে খেলা",
                nothingToSave: "সংরক্ষণ করার কিছুই নেই",
                positionSaved: "অবস্থান সংরক্ষিত",
                couldNotSavePosition: "অবস্থান সংরক্ষণ করা যায়নি",
                savedPositionNotFound: "সংরক্ষিত অবস্থান পাওয়া যায়নি",
                positionUpdated: "অবস্থান আপডেট করা হয়েছে",
                couldNotUpdatePosition: "অবস্থান আপডেট করা যায়নি",
                nameCannotBeEmpty: "নাম খালি রাখা যাবে না",
                gameRenamed: "খেলার নাম পরিবর্তন করা হয়েছে",
                couldNotRenameGame: "গেমের নাম পরিবর্তন করা যায়নি",
                deletedCount: "মুছে ফেলা হয়েছে {{count}} আইটেম(গুলি)",
                couldNotDeleteSelected: "নির্বাচিত আইটেম মুছে ফেলা যায়নি",
                couldNotLoadSavedGame: "সংরক্ষিত খেলা লোড করা যায়নি",
                editingPositionSaveBookmark: "অবস্থান সম্পাদনা — এই বুকমার্ক আপডেট করতে সংরক্ষণ করুন",
                couldNotOpenPositionForEditing: "সম্পাদনার জন্য অবস্থান খুলতে পারেনি",
                gameSaved: "খেলা সংরক্ষিত",
                couldNotSaveGame: "খেলা সংরক্ষণ করা যায়নি",
                engineMoveNotApplied: "ইঞ্জিন সরানো প্রয়োগ করা যাবে না",
                engineCouldNotFindMove: "ইঞ্জিন একটি সরানো খুঁজে পাওয়া যায়নি",
                engineError: "ইঞ্জিন ত্রুটি",
                engineThinking: "ইঞ্জিন চিন্তা…",
                sessionError: "সেশন ত্রুটি",
                timesUpLost: "{{loser}} সময়মতো হারিয়ে গেছে",
                drawOfferTitle: "ড্র অফার",
                drawOfferMessage: "প্রতিপক্ষ ড্র প্রস্তাব পাঠিয়েছে। মেনে নেবেন?",
                rematchTitle: "রিম্যাচ",
                playerDisconnectedWaiting: "{{who}} সংযোগ বিচ্ছিন্ন — পুনরায় যোগদানের জন্য অপেক্ষা করা হচ্ছে ({{countdown}})",
                opponentDisconnectedCountdown: "প্রতিপক্ষের সংযোগ বিচ্ছিন্ন — {{countdown}}",
                gameCancelledReconnectTimeout: "খেলা বাতিল হয়েছে — কোনো চাল না খেলেই পুনরায় সংযোগের সময় শেষ হয়ে গেছে।",
                playerFailedToReconnectWins: "{{loser}} পুনরায় সংযোগ করতে ব্যর্থ হয়েছে — {{winner}} জিতেছে৷",
                gameOverOpponentFailedReconnect: "খেলা শেষ - প্রতিপক্ষ পুনরায় সংযোগ করতে ব্যর্থ হয়েছে৷",
                couldNotStartRematch: "পুনরায় ম্যাচ শুরু করা যায়নি",
                rematchStarted: "রিম্যাচ শুরু হয়েছে",
                gameCancelled: "খেলা বাতিল",
                gameCancelledWithDetail: "খেলা বাতিল হয়েছে — {{detail}}",
                gameCancelledOpponentLeftBeforeFirstMove: "খেলা বাতিল — প্রতিপক্ষ প্রথম পদক্ষেপের আগেই চলে গেছে।",
                resignFailed: "পদত্যাগ ব্যর্থ হয়েছে",
                gameResumedYourMove: "খেলা আবার শুরু হয়েছে - আপনার পদক্ষেপ",
                practiceNotAvailable: "অনুশীলন মোড উপলব্ধ নেই",
                couldNotJoinOnPlay: "/প্লেতে এই গেমটিতে যোগ দিতে পারেনি৷",
                practiceDebugNotAvailable: "এই অ্যাকাউন্টের জন্য অনুশীলন/ডিবাগ উপলব্ধ নেই",
                reviewRequiresWebApi: "পর্যালোচনার জন্য ওয়েব API প্রয়োজন",
                couldNotLoadReviewGame: "পর্যালোচনা গেম লোড করা যায়নি",
                notReviewGameLink: "এই লিঙ্ক একটি পর্যালোচনা খেলা নয়",
                onlineRequiresWebApi: "অনলাইন খেলার জন্য ওয়েব API প্রয়োজন",
                couldNotLoadOnlineGame: "অনলাইন গেম লোড করা যায়নি",
                notOnlineGameOnPlay: "এই লিঙ্কটি /প্লেতে একটি অনলাইন গেম নয়",
                watchingLiveGame: "লাইভ খেলা দেখছেন",
                waitingForOpponentToJoin: "প্রতিপক্ষের যোগদানের জন্য অপেক্ষা করা হচ্ছে...",
                waitingForOpponent: "প্রতিপক্ষের জন্য অপেক্ষা করা হচ্ছে...",
                onlineGameConnected: "অনলাইন গেম — সংযুক্ত",
                gameDeleted: "খেলা মুছে ফেলা হয়েছে",
                itemsDeleted: "{{count}} আইটেম মুছে ফেলা হয়েছে",
                choosePromotionPiece: "প্রচার টুকরা চয়ন করুন",
                invalidPromotionPiece: "অবৈধ প্রচার টুকরা",
                drawOfferNotAvailable: "ড্র অফার এখন উপলব্ধ নয়"
            },
            drawReasons: {
                stalemate: "অচলাবস্থা",
                fiftyMoves: "50 চাল",
                insufficientMaterial: "অপর্যাপ্ত উপাদান",
                threefoldRepetition: "তিনগুণ পুনরাবৃত্তি",
                drawOfferAccepted: "{{by}} প্লেয়ারের ড্র অফার গৃহীত হয়েছে"
            },
            actions: {
                newGame: "নতুন খেলা",
                resign: "হার মেনে নিন",
                draw: "ড্র",
                undo: "পূর্বাবস্থায় ফেরান",
                redo: "আবার করুন",
                lastMove: "শেষ চাল",
                positionSetup: "অবস্থান সেটআপ",
                config: "কনফিগার",
                flip: "ফ্লিপ",
                save: "সংরক্ষণ করুন",
                exit: "প্রস্থান করুন",
                backToLobby: "লবিতে ফিরে যান",
                loadToStart: "শুরু করতে লোড করুন",
                editPosition: "অবস্থান সম্পাদনা করুন",
                loadGame: "খেলা লোড করুন",
                loadPosition: "অবস্থান লোড করুন"
            },
            savedGames: {
                defaultName: "সংরক্ষিত খেলা",
                nameAriaLabel: "সংরক্ষিত খেলার নাম",
                showDetails: "বিস্তারিত দেখান",
                detailsAriaLabel: "সংরক্ষিত খেলা বিবরণ",
                editPosition: "অবস্থান সম্পাদনা করুন",
                deleteSavedGame: "সংরক্ষিত গেম মুছুন",
                renameSavedGame: "সংরক্ষিত গেমের নাম পরিবর্তন করুন",
                noSavedPositions: "এখনও কোনো সংরক্ষিত অবস্থান.",
                noSavedGames: "এখনও কোন সংরক্ষিত গেম.",
                nextMoveDash: "পরবর্তী পদক্ষেপ: -",
                nextMove: "পরবর্তী পদক্ষেপ: {{side}}",
                player: "প্লেয়ার",
                savedAt: "সংরক্ষিত: {{when}}",
                gameId: "গেম আইডি: {{id}}",
                playersVs: "{{white}} বনাম {{black}}",
                defaultPositionName: "সংরক্ষিত অবস্থান",
                itemsSelected: "{{count}}টি আইটেম নির্বাচিত"
            },
            reviewNav: {
                start: "শুরু করুন",
                back: "ব্যাক",
                play: "খেলা",
                pause: "বিরতি",
                forward: "ফরোয়ার্ড",
                end: "শেষ"
            },
            newGameDialog: {
                title: "নতুন গেম বনাম এআই",
                yourColor: "তোমার রং",
                engine: "ইঞ্জিন",
                brain43: "মস্তিষ্ক 4.3",
                brain42: "মস্তিষ্ক 4.2",
                brain41: "মস্তিষ্ক 4.1",
                brain4: "মস্তিষ্ক 4.0",
                stockfish: "Stockfish",
                timePerSideMinutes: "প্রতি পাশে সময় (মিনিট)",
                allowUndo: "পূর্বাবস্থায় ফেরার অনুমতি দিন",
                private: "ব্যক্তিগত",
                privateHint: "অন্যান্য সদস্যদের সক্রিয় গেম তালিকায় ব্যক্তিগত গেমগুলি দেখানো হয় না৷"
            },
            prompts: {
                positionName: "পদের নাম",
                savePositionAs: "হিসাবে অবস্থান সংরক্ষণ করুন"
            },
            dialogs: {
                resignTitle: "এই খেলা পদত্যাগ?",
                resignBody: "আপনি খেলা হারাতে হবে.",
                leaveTitle: "খেলা ছেড়ে দিন?",
                leaveBody: "আপনার খেলা পদত্যাগ করা হবে.",
                areYouSure: "আপনি কি নিশ্চিত?",
                discardUnsavedBrainConfig: "অসংরক্ষিত মস্তিষ্কের কনফিগারেশন পরিবর্তন বাতিল করবেন?",
                accept: "গ্রহণ করুন",
                decline: "প্রত্যাখ্যান",
                saveAs: "হিসাবে সংরক্ষণ করুন",
                savePosition: "অবস্থান সংরক্ষণ করুন",
                invalidPosition: "অবৈধ অবস্থান",
                rematchChooseColor: "পুনরায় ম্যাচের জন্য আপনার রঙ চয়ন করুন:",
                rematchOfferAgree: "প্রতিপক্ষ আবার ম্যাচের প্রস্তাব দিয়েছে। রাজি?",
                rematchOfferAgreeWithTime: "প্রতিপক্ষ একটি রিম্যাচের প্রস্তাব দিয়েছে (প্রতি পাশে {{minutes}} মিনিট)। রাজি?",
                rematchColorPreference: "প্রতিপক্ষ {{offerer}} হিসেবে খেলতে চায়। আপনি {{you}} হিসাবে খেলবেন। রাজি?",
                rematchColorPreferenceWithTime: "প্রতিপক্ষ {{offerer}} ({{minutes}} মিনিট প্রতি পাশ) হিসাবে খেলতে চায়। আপনি {{you}} হিসাবে খেলবেন। রাজি?"
            }
        },
        session: {
            engineThinking: "ইঞ্জিন চিন্তা…",
            engineCouldNotFindMove: "ইঞ্জিন একটি সরানো খুঁজে পাওয়া যায়নি",
            engineError: "ইঞ্জিন ত্রুটি",
            positionSetupPlacePieces: "অবস্থান সেটআপ - বোর্ডে টুকরা রাখুন",
            configurationModeEdit: "কনফিগারেশন মোড - মান সম্পাদনা করুন এবং সংরক্ষণ করুন",
            practiceBothSides: "অনুশীলন - উভয় পক্ষের",
            opponentDisconnected: "প্রতিপক্ষ সংযোগ বিচ্ছিন্ন",
            opponentRejoined: "প্রতিপক্ষ আবার যোগ দিয়েছে",
            playerRejoined: "{{name}} আবার যোগদান করেছে৷",
            drawOfferSent: "ড্র অফার পাঠানো হয়েছে",
            drawOfferDeclined: "ড্র অফার প্রত্যাখ্যান করা হয়েছে",
            rematchOfferSent: "রিম্যাচ অফার পাঠানো হয়েছে",
            rematchOfferDeclined: "রিম্যাচ অফার প্রত্যাখ্যান",
            rematchUnavailable: "প্রতিপক্ষ আর রিম্যাচের জন্য উপলব্ধ নেই",
            drawAgreed: "ড্র রাজি",
            rematchAcceptedNoGameId: "রিম্যাচ গৃহীত কিন্তু কোনো নতুন গেম আইডি নেই",
            rematchOfferAccepted: "পুনরায় ম্যাচ অফার গৃহীত",
            gameOver: "খেলা শেষ",
            somethingWentWrong: "কিছু ভুল হয়েছে",
            opponentResigned: "প্রতিপক্ষ পদত্যাগ করেছেন",
            opponentLeftGame: "খেলা ছেড়ে দেয় প্রতিপক্ষ",
            opponentFailedToReconnect: "প্রতিপক্ষ পুনরায় সংযোগ করতে ব্যর্থ হয়েছে৷",
            gameCancelled: "খেলা বাতিল",
            gameCancelledWithDetail: "খেলা বাতিল হয়েছে — {{detail}}",
            gameCancelledOpponentLeftBeforeFirstMove: "খেলা বাতিল — প্রতিপক্ষ প্রথম পদক্ষেপের আগেই চলে গেছে।",
            gameCancelledReconnectTimeout: "খেলা বাতিল হয়েছে — কোনো চাল না খেলেই পুনরায় সংযোগের সময় শেষ হয়ে গেছে।",
            waitingForOpponent: "প্রতিপক্ষের জন্য অপেক্ষা করা হচ্ছে...",
            couldNotResolveWebSocketUrl: "WebSocket URL সমাধান করা যায়নি",
            opponentJoined: "{{name}} যোগদান করেছে৷",
            opponentDefault: "প্রতিপক্ষ",
            connectionError: "সংযোগ ত্রুটি",
            connectionLost: "সংযোগ হারিয়েছে — চালগুলি সার্ভারে পৌঁছাচ্ছে না",
            reconnecting: "পুনরায় সংযোগ করা হচ্ছে...",
            connectionRestored: "সংযোগ পুনরুদ্ধার করা হয়েছে৷",
            flagReported: "পতাকা - সার্ভারের সাথে নিশ্চিত করা হচ্ছে...",
            playerDisconnectedWaitingRejoin: "{{name}} সংযোগ বিচ্ছিন্ন — পুনরায় যোগদানের জন্য অপেক্ষা করা হচ্ছে৷",
            playerFailedToReconnectWins: "{{loser}} পুনরায় সংযোগ করতে ব্যর্থ হয়েছে — {{winner}} জিতেছে৷",
            watcherWaitingForReconnect: "একজন খেলোয়াড়ের পুনরায় সংযোগের জন্য অপেক্ষা করা হচ্ছে..."
        },
        site: {
            confirm: "নিশ্চিত করুন",
            cancel: "বাতিল করুন",
            notice: "লক্ষ্য করুন",
            ok: "OK",
            home: "বাড়ি",
            search: "অনুসন্ধান করুন",
            friends: "বন্ধুরা",
            groups: "গোষ্ঠী",
            debug: "ডিবাগ",
            account: "হিসাব",
            preferences: "পছন্দসমূহ",
            administrate: "প্রশাসন",
            logOut: "লগ আউট করুন",
            logIn: "লগ ইন করুন",
            admin: "অ্যাডমিন",
            homeAria: "বাড়ি"
        },
        validation: {
            validEmail: "একটি বৈধ ইমেল পূরণ করুন",
            passwordsMustMatch: "অনুগ্রহ করে নিশ্চিত করুন যে পাসওয়ার্ড ক্ষেত্রগুলি অভিন্ন।",
            chooseUsername: "একটি ব্যবহারকারীর নাম চয়ন করুন",
            usernameNotAvailable: "এই ব্যবহারকারীর নাম উপলব্ধ নেই",
            passwordNoWhitespace: "পাসওয়ার্ডে অবশ্যই হোয়াইটস্পেস থাকবে না।",
            passwordUppercase: "পাসওয়ার্ডে কমপক্ষে একটি বড় হাতের অক্ষর থাকতে হবে।"
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = bn;
    } else {
        global.ShmerlingStringsBn = bn;
    }
})(typeof window !== "undefined" ? window : globalThis);
