/**
 * German supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const deExtra = {
        validation: {
            passwordLowercase: "Das Passwort muss mindestens einen Kleinbuchstaben enthalten.",
            passwordDigit: "Das Passwort muss mindestens eine Ziffer enthalten.",
            passwordSymbol: "Das Passwort muss mindestens ein Sonderzeichen enthalten.",
            passwordLength: "Das Passwort muss 8–30 Zeichen lang sein.",
            noHtml: "{{label}} darf kein HTML enthalten.",
            position: {
                headerSave: "Diese Stellung kann nicht gespeichert werden:\n\n",
                headerPlay: "Von dieser Stellung aus kann nicht gespielt werden:\n\n",
                headerUse: "Diese Stellung kann nicht verwendet werden:\n\n",
                headerSaveBookmark: "Dieses Lesezeichen kann nicht gespeichert werden:\n\n",
                headerAddBookmark: "Dieses Lesezeichen kann nicht hinzugefügt werden:\n\n",
                boardUnreadable: "Brett konnte nicht gelesen werden. Versuchen Sie es erneut, nachdem das Brett geladen wurde.",
                whiteKingNone: "Es muss genau ein weißer König auf dem Brett stehen. Keiner wurde gefunden.",
                whiteKingCount: "Es muss genau ein weißer König auf dem Brett stehen. {{count}} weiße Könige gefunden.",
                blackKingNone: "Es muss genau ein schwarzer König auf dem Brett stehen. Keiner wurde gefunden.",
                blackKingCount: "Es muss genau ein schwarzer König auf dem Brett stehen. {{count}} schwarze Könige gefunden.",
                kingsAdjacent: "Die beiden Könige dürfen nicht auf benachbarten Feldern stehen (einschließlich diagonal).",
                sideInCheck: "{{mover}} ist am Zug, aber der König von {{king}} steht bereits im Schach. Die ziehende Seite darf kein Schach geben — ändern Sie den Zug oder verschieben Sie Figuren.",
                drawInsufficientKings: "Diese Stellung ist remis wegen unzureichenden Materials (König gegen König). Fügen Sie Figuren hinzu, damit Schachmatt möglich bleibt.",
                drawInsufficientMinor: "Diese Stellung ist remis wegen unzureichenden Materials (König und Läufer oder Springer gegen alleinigen König). Fügen Sie Figuren hinzu, damit Schachmatt möglich bleibt.",
                drawBishopsSameColor: "Diese Stellung ist remis wegen unzureichenden Materials (Läufer gegen Läufer auf gleicher Feldfarbe). Fügen Sie Figuren hinzu, damit Schachmatt möglich bleibt.",
                tooManyQueens: "{{color}} hat {{count}} Damen; das Maximum beträgt 9 pro Farbe.",
                tooManyRooks: "{{color}} hat {{count}} Türme; das Maximum beträgt 10 pro Farbe.",
                tooManyBishops: "{{color}} hat {{count}} Läufer; das Maximum beträgt 10 pro Farbe.",
                tooManyKnights: "{{color}} hat {{count}} Springer; das Maximum beträgt 10 pro Farbe.",
                tooManyPawns: "{{color}} hat {{count}} Bauern; das Maximum beträgt 8 pro Farbe."
            }
        },
        auth: {
            whoAreYou: "Wer bist du?",
            enterPassword: "Gib dein Passwort ein",
            sorry: "Tut uns leid",
            continue: "Weiter",
            usernameField: "Benutzername",
            passwordField: "Passwort",
            wrongCredentials: "Falscher Benutzername oder falsches Passwort",
            userAdded: "Benutzer erfolgreich hinzugefügt",
            couldNotSaveBookmark: "Lesezeichen konnte nicht gespeichert werden",
            invalidUserId: "Ungültige Benutzer-ID",
            generationJobRunning: "Ein anderer Generierungsauftrag läuft bereits…",
            listingPgnFiles: "PGN-Dateien werden aufgelistet…"
        },
        classic: {
            loadGame: "Partie laden",
            load: "Laden",
            enterGameState: "Spielstand hier einfügen…",
            rematch: "Revanche",
            drawOffer: "Remis anbieten",
            lastMove: "Letzter Zug",
            bookmarks: "Lesezeichen",
            bookmarkAlertTitle: "Stellung als Lesezeichen",
            promotion: "Umwandlung!",
            check: "Schach",
            checkmateWins: "Schachmatt! {{winner}} gewinnt!",
            drawReason: "Remis! {{reason}}",
            opponentDisconnected: "Der Gegner wurde getrennt",
            opponentResignedWins: "Der Gegner hat aufgegeben, {{winner}} gewinnt",
            somethingWentWrong: "Etwas ist schiefgelaufen",
            playerRejoined: "{{name}} wieder verbunden",
            aPlayerRejoined: "Ein Spieler ist wieder verbunden",
            opponentRejoined: "Der Gegner ist wieder verbunden",
            rematchOfferAccepted: "Revanche-Angebot angenommen",
            rematchOfferDeclined: "Revanche-Angebot abgelehnt",
            sideOffersDraw: "{{side}} bietet Remis an",
            drawOfferDeclined: "Remis-Angebot abgelehnt",
            watcherWatching: "{{name}} verfolgt die Partie",
            drawOfferSent: "Remis-Angebot gesendet",
            rematchOfferSent: "Revanche-Angebot gesendet",
            newGameStarted: "Neue Partie gestartet",
            gameOver: "Partie beendet",
            gameCancelled: "Partie abgebrochen",
            youResignedWins: "Sie haben aufgegeben, {{winner}} gewinnt",
            movesCopied: "Züge in die Zwischenablage kopiert!",
            failedCopyMoves: "Züge konnten nicht kopiert werden",
            failedLoadBrainConfig: "Brain-Konfiguration konnte nicht geladen werden.",
            failedSaveBrainConfig: "Brain-Konfiguration konnte nicht gespeichert werden.",
            offerDrawConfirm: "Remis anbieten?",
            drawOfferAccept: "Der Gegner hat Remis angeboten, annehmen?",
            rematchOfferAccept: "Der Gegner hat eine Revanche angeboten, zustimmen?",
            rematchOfferAcceptWithTime: "Der Gegner bot einen Rückkampf an ({{minutes}} Minuten pro Seite). Zustimmen?",
            rematchTimePrompt: "Minuten pro Seite für das Rückspiel:",
            connectionLost: "Verbindung verloren – Bewegungen erreichen den Server nicht",
            confirmExitGame: "Möchten Sie die Partie wirklich verlassen?",
            mobileResign: "Aufgeben",
            mobileRematch: "Revanche",
            mobileDraw: "Remis",
            mobileFlip: "Drehen",
            mobileLastMove: "Letzter Zug",
            mobileMovesList: "Zugliste",
            researchToolbox: "Werkzeugkasten",
            researchBrainConfig: "Brain-Konfig.",
            researchSave: "Speichern",
            researchDiscard: "Verwerfen",
            researchEditMode: "Bearbeitungsmodus",
            researchRun: "Ausführen",
            researchProperty: "Eigenschaft",
            researchValue: "Wert",
            playerOnline: "Online",
            playerDisconnectedStatus: "Getrennt",
            playerOffline: "Offline",
            humanVsComputer: "Mensch gegen Computer",
            newGameTwoPlayers: "Neue Partie — 2 Spieler",
            settings: "Einstellungen",
            help: "Hilfe",
            drawOffersNotVsEngine: "Remis-Angebote sind beim Spiel gegen die Engine nicht verfügbar.",
            failedStartFromBookmark: "Partie konnte nicht vom Lesezeichen aus gestartet werden.",
            resignConfirm: "Aufgeben?",
            areYouSure: "Sind Sie sicher?",
            gameOverOpponentFailedReconnectWinsClassic: "Partie beendet — Gegner konnte nicht wieder verbinden. {{winner}} gewinnt.",
            reconnectTimeoutNoMoves: "Wiederverbindung abgelaufen, ohne dass Züge gespielt wurden.",
            waitingOpponentRejoin: "Warte auf Wiederbeitritt des Gegners",
            timeoutOneSec: "Zeitlimit: 1 Sek.",
            timeoutSecs: "Zeitlimit: {{count}} Sek.",
            whitePieceAlt: "Weiße Figur",
            blackPieceAlt: "Schwarze Figur",
            eraserTitle: "Radierer",
            eraserAria: "Radierer – Figur vom Feld entfernen",
            selectTitle: "Auswählen",
            selectAria: "Auswählen – Figuren zum Verschieben ziehen",
            resetAria: "Zurücksetzen – alle Figuren entfernen",
            defaultPositionAria: "Standardstellung – Ausgangsstellung einrichten",
            loading: "Wird geladen…",
            engineLabel: "Engine"
        },
        site: {
            home: "Start",
            search: "Suche",
            friends: "Freunde",
            groups: "Gruppen",
            debug: "Debug",
            account: "Konto",
            preferences: "Einstellungen",
            administrate: "Verwaltung",
            logOut: "Abmelden",
            logIn: "Anmelden",
            admin: "Admin",
            homeAria: "Start",
            confirm: "Bestätigen",
            cancel: "Abbrechen",
            notice: "Hinweis",
            ok: "OK",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "Fußzeile",
                privacy: "Datenschutzrichtlinie",
                terms: "Nutzungsbedingungen",
                contact: "Kontakt",
                copyright: "© {{year}} Shmerling Chess. Alle Rechte vorbehalten.",
                lastUpdated: "Zuletzt aktualisiert: {{date}}",
                privacyTitle: "Datenschutzrichtlinie",
                privacyLead: "Wie Shmerling Chess Konto- und Spieldaten verarbeitet.",
                privacyBody: "Wir verwenden Ihre Kontodaten, um den Dienst zu betreiben, Partien und Einstellungen zu speichern und das Produkt zu verbessern. Wir verkaufen keine personenbezogenen Daten. Der vollständige Richtlinientext wird hier veröffentlicht.",
                termsTitle: "Nutzungsbedingungen",
                termsLead: "Die Regeln für die Nutzung von Shmerling Chess.",
                termsBody: "Mit der Nutzung von Shmerling Chess verpflichten Sie sich, fair zu spielen, andere Spieler zu respektieren und den Dienst nur für persönliches Schachspiel zu verwenden. Die vollständigen Bedingungen werden hier veröffentlicht.",
                contactTitle: "Kontakt",
                contactLead: "Kontakt zum Shmerling-Chess-Team.",
                contactBody: "Kontaktdaten für Support und Datenschutzfragen werden hier veröffentlicht.",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "Benutzername:",
            password: "Passwort:",
            login: "Anmelden",
            register: {
                submit: "Registrieren",
                confirmPassword: "Passwort bestätigen:",
                playerLevel: "Spielerstufe:",
                rookie: "Anfänger",
                skilled: "Geübt",
                elite: "Elite",
                grandMaster: "Großmeister"
            },
            email: "E-Mail:",
            welcome: {
                greeting: "Willkommen zurück",
                tagline: "Ihr Zug wartet",
                playNow: "Jetzt spielen!",
                activeGames: "Aktive Partien",
                live: "Live",
                showAll: "Alle anzeigen",
                viewAllActive: "Alle aktiven Partien anzeigen",
                mostRecent: "Neueste zuerst",
                noGamesNow: "Derzeit keine Partien",
                myGames: "Meine Partien",
                viewAllGames: "Alle Partien anzeigen",
                recentCompleted: "Ihre kürzlich beendeten Partien",
                noCompleted: "Noch keine beendeten Partien",
                activeGamesAria: "Aktive Partien",
                inviteOnlineFriend: "Einen Online-Freund zum Spielen einladen",
                friendsPageTitle: "Freundeseite",
                manageFriends: "Verwalten",
                colFriend: "Freund",
                colStatus: "Status",
                findPlayers: "Spieler finden",
                waitingForResponse: "Warte auf Antwort",
                inviteSentSuffix: "(Einladung gesendet)",
                sortByRowNumber: "Nach Zeilennummer sortieren",
                sortBy: "Sortieren nach {{key}}"
            },
            gameList: {
                date: "Datum",
                time: "Zeit",
                result: "Ergebnis",
                reason: "Grund",
                type: "Typ",
                status: "Status",
                event: "Turnier",
                site: "Ort",
                round: "Runde"
            },
            loginPage: {
                title: "Anmelden"
            },
            error: {
                title: "Etwas ist schiefgelaufen",
                body: "Ein Fehler ist aufgetreten.",
                back: "Zurück zur Startseite"
            },
            log: {
                title: "Serverprotokoll",
                clear: "Ansicht leeren",
                latest: "Neueste",
                waiting: "Warte auf Serverprotokoll-Ausgabe…"
            },
            activeGames: {
                moves: "Züge",
                turn: "Am Zug",
                status: "Status",
                inProgress: "Läuft",
                onHold: "Pausiert",
                vs: " vs ",
                minutesAgo: "vor {{count}} Minuten",
                oneMinuteAgo: "vor 1 Minute",
                justStarted: "Gerade gestartet",
                notStarted: "Noch nicht gestartet",
                startedTooltip: "Gestartet: {{when}}",
                playersVs: "{{white}} vs. {{black}}"
            },
            friendsPage: {
                title: "Freunde",
                tagline: "Neue Schachpartner finden",
                myFriends: "Meine Freunde",
                noFriendsYet: "Noch keine Freunde",
                findPlayers: "Spieler finden",
                searchByUsername: "Nach Benutzername suchen",
                searchPlaceholder: "Zum Suchen tippen…",
                enterCharToSearch: "Geben Sie mindestens ein Zeichen ein, um zu suchen",
                noMatchingUsers: "Keine passenden Benutzer",
                playing: "Spielt",
                pendingFriendshipOffer: "Ausstehendes Freundschaftsangebot",
                joining: "Tritt bei",
                rejoin: "Wieder beitreten",
                friendRequest: "Freundschaftsanfrage",
                wantsToBeFriends: "(möchte befreundet sein)",
                pendingOfferSuffix: "(ausstehendes Freundschaftsangebot)",
                waitingFriendRespond: "Warte auf Antwort Ihres Freundes",
                cancelBeforeRemove: "Brechen Sie die Partie-Einladung ab, bevor Sie diesen Freund entfernen",
                friendsTag: "Freunde",
                offerReceivedTag: "Angebot erhalten — siehe Ihre Freunde",
                addFriend: "Freund hinzufügen",
                withdraw: "Zurückziehen",
                requestFailed: "Anfrage fehlgeschlagen",
                removeFriendConfirm: "Diesen Freund aus Ihrer Liste entfernen?",
                removeFriendTitle: "Freund entfernen",
                withdrawOfferConfirm: "Dieses Freundschaftsangebot zurückziehen?",
                withdrawOfferTitle: "Angebot zurückziehen",
                couldNotAccept: "Konnte nicht annehmen",
                couldNotDecline: "Konnte nicht ablehnen",
                couldNotRemove: "Konnte nicht entfernen",
                couldNotCancelInvite: "Einladung konnte nicht abgebrochen werden",
                couldNotWithdraw: "Konnte nicht zurückziehen",
                couldNotSendInvite: "Einladung konnte nicht gesendet werden",
                couldNotSendGameInvite: "Partie-Einladung konnte nicht gesendet werden",
                gameInvite: "Partie-Einladung",
                gameInvitationsAria: "Partie-Einladungen",
                gameInvitationAria: "Partie-Einladung",
                chessInviteTitle: "Schach-Einladung",
                wantsToPlayAsBlack: "{{name}} möchte spielen. Sie spielen Schwarz.",
                wantsToPlayYouWhite: "{{name}} möchte spielen. Du spielst als Weiß.",
                aFriend: "Ein Freund",
                youPlayAsWhite: "Sie spielen Weiß",
                youPlayAsBlack: "Sie spielen Schwarz",
                establishingGame: "Partie wird eingerichtet…",
                yourOpponent: "Ihr Gegner",
                declinedYourInvite: "{{name}} hat Ihre Partie-Einladung abgelehnt.",
                cancelInvite: "Einladung abbrechen",
                accept: "Annehmen",
                decline: "Ablehnen",
                invite: "Einladen",
                inviteSettingsTitle: "Einladungseinstellungen",
                inviteSettingsFor: "{{name}} einladen",
                inviteTimeMinutes: "Zeit pro Seite (Minuten)",
                inviteYourColor: "Deine Farbe",
                inviteColorWhite: "Weiß",
                inviteColorBlack: "Schwarz",
                inviteColorRandom: "Zufällig",
                inviteFriendly: "Freundschaftsspiel",
                inviteFriendlyHint: "Deaktivieren Sie die Markierung, um später für ELO zu zählen (gewertetes Spiel).",
                invitePrivate: "Privates Spiel",
                invitePrivateHint: "Verstecken Sie dieses Spiel vor der öffentlichen Lobby für aktive Spiele.",
                inviteSaveDefaults: "Standardeinstellungen speichern",
                inviteOfferTime: "{{minutes}} min",
                inviteOfferFriendly: "Freundlich",
                inviteOfferRated: "Bewertet",
                inviteOfferPrivate: "Privat",
                remove: "Entfernen",
                offerSent: "Angebot gesendet",
                pending: "Ausstehend",
                online: "Online",
                offline: "Offline"
            },
            adminPage: {
                title: "Verwaltung",
                tagline: "Benutzer, Spiele, Engines, Eröffnungsbuch und Bot-Duelle",
                panelTitle: "Admin-Konsole",
                users: "Benutzer",
                generate: "Generieren",
                games: "Partien",
                engines: "Engines",
                states: "Stellungen",
                openingBook: "Eröffnungsbuch",
                bots: "Bots",
                addUser: "Benutzer hinzufügen",
                sectionsAria: "Admin-Bereiche",
                openingBookLabel: "Eröffnungsbuch:",
                openingBookStatusTitle: "Aktuelles Eröffnungsbuch",
                openingBookFile: "Datei",
                openingBookExists: "Status",
                openingBookExistsYes: "Gegenwärtig",
                openingBookExistsNo: "Fehlen",
                openingBookLines: "Spiellinien",
                openingBookSize: "Größe",
                openingBookModified: "Zuletzt geändert",
                openingBookPgnSources: "PGN-Quellen",
                openingBookPgnCount: "{{count}} PGN-Datei(en) zum Neuaufbau verfügbar",
                openingBookIntro: "Erstellen Sie das zeilenbasierte Eröffnungsbuch (data/opening-book-lines.txt) aus den PGN-Ordnern des Servers neu. Verwenden Sie unten „Eröffnungsbuch generieren“ – nichts wird ausgeführt, bis Sie darauf drücken.",
                generateOpeningBook: "Eröffnungsbuch erstellen",
                botsIntro: "Starten Sie ein öffentliches Engine-gegen-Engine-Spiel. Mitglieder können es von Active Games on Home aus als Beobachter öffnen.",
                botsWhiteEngine: "Weißer Motor",
                botsBlackEngine: "Schwarzer Motor",
                botsWhiteDifficulty: "Schwierigkeit (1–6)",
                botsBlackDifficulty: "Schwierigkeit (1–6)",
                botsSkillLevel: "Fähigkeit (0–20)",
                botsTimeMinutes: "Uhr (Minuten)",
                botsStart: "Duell beginnen",
                botsStarting: "Startduell…",
                botsStarted: "Duell begonnen: {{white}} gegen {{black}}.",
                botsWatchLink: "Sehen Sie sich dieses Spiel an",
                botsListedNote: "Gelistet unter Startseite → Aktive Spiele für andere Benutzer.",
                botsStartFailed: "Das Duell konnte nicht gestartet werden.",
                botsStopped: "Stopp angefordert.",
                botsStopFailed: "Konnte das Duell nicht stoppen.",
                gameLines: "Partievarianten",
                noGamesInDb: "Noch keine Partien in der Datenbank.",
                gamesPaginationAria: "Partien-Seitennummerierung",
                colNum: "#",
                colUsername: "Benutzername",
                colType: "Typ",
                colEmail: "E-Mail",
                colPassword: "Passwort",
                colLevel: "Stufe",
                colElo: "Elo",
                colJoined: "Beigetreten",
                colLastLogin: "Letzte Anmeldung",
                colActiveGames: "Aktive Partien",
                colFriends: "Freunde",
                colBookmarks: "Lesezeichen",
                colId: "Id",
                colStatus: "Status",
                colName: "Name",
                colAvailable: "Verfügbar",
                colEnabled: "Ermöglicht",
                colBackend: "Backend",
                colCommand: "Befehl",
                colNotes: "Notizen",
                colNote: "Notiz",
                colAction: "Aktion",
                emptyUsers: "Noch keine Benutzer.",
                emptyData: "Noch keine Daten.",
                emptyEngines: "Keine Play-Engines in der Registrierung.",
                emptyStates: "Verwenden Sie „Generieren“, um die Seite für Eröffnungsbuch- und Stellungsgenerierung zu öffnen.",
                engineAvailableYes: "Verfügbar",
                engineAvailableNo: "Nicht verfügbar",
                engineEnable: "Aktivieren",
                engineDisable: "Deaktivieren",
                enginesLoadFailed: "Motoren konnten nicht geladen werden",
                enginesSaveFailed: "Engine konnte nicht aktualisiert werden",
                clickToEdit: "Zum Bearbeiten klicken",
                updateFailed: "Aktualisierung fehlgeschlagen",
                couldNotSave: "Konnte nicht speichern",
                setPassword: "Passwort setzen",
                setPasswordTitle: "Klicken, um ein neues Passwort zu setzen (4–30 Zeichen)",
                passwordLengthInvalid: "Das Passwort muss zwischen 4 und 30 Zeichen lang sein.",
                invalidPassword: "Ungültiges Passwort",
                saved: "Gespeichert",
                newPasswordPlaceholder: "Neues Passwort",
                clickChangeUserType: "Klicken, um Benutzertyp zu ändern",
                userTypeAria: "Benutzertyp",
                changeUserTypeTitle: "Benutzertyp ändern",
                grantAdminConfirm: "Diesem Benutzer Admin-Rechte gewähren? Er kann dann Admin-Tools nutzen und Konten verwalten.",
                demoteAdminConfirm: "Diesen Benutzer von Admin auf {{type}} ändern? Er verliert den Zugang zum Admin-Bereich.",
                changeUserTypeConfirm: "Diesen Benutzer auf {{type}} ändern?",
                clickChangeLevel: "Klicken, um Stufe zu ändern",
                playerLevelAria: "Spielerstufe",
                sortByRowNumber: "Nach Zeilennummer sortieren",
                sortBy: "Sortieren nach {{key}}",
                delete: "Löschen",
                first: "Erste",
                last: "Letzte",
                previous: "Zurück",
                next: "Weiter",
                previous5Pages: "5 Seiten zurück",
                next5Pages: "5 Seiten weiter",
                previous10Pages: "10 Seiten zurück",
                next10Pages: "10 Seiten weiter",
                userTypeAdmin: "Admin",
                userTypePartner: "Partner",
                userTypeMember: "Mitglied",
                generateTitle: "Eröffnungsbuch- und Stellungsgenerierung",
                backToAdmin: "← Zurück zur Verwaltung",
                generateIntro: "Spielt alle PGN-Dateien im Partien-Manager-Ordner des Servers entweder in die State-MongoDB-Sammlung oder in das zeilenbasierte Eröffnungsbuch (data/opening-book-lines.txt) ein. Wählen Sie ein Ziel und drücken Sie dann „Generierung starten“ — es läuft nichts, bis Sie das tun.",
                target: "Ziel",
                targetMongo: "MongoDB — Zeilen zur State-Sammlung hinzufügen",
                targetBook: "Zeilendatei — Eröffnungsbuch schreiben (opening-book-lines.txt)",
                startGeneration: "Generierung starten",
                stop: "Stoppen",
                idle: "Leerlauf.",
                starting: "Wird gestartet…",
                running: "Läuft ({{mode}})…",
                readingFiles: "{{count}} Datei(en) werden gelesen…",
                replayingGames: "{{count}} Partien werden nachgespielt…",
                writingOpeningBook: "Eröffnungsbuch wird geschrieben…",
                readingPgn: "PGN {{index}} / {{total}} wird gelesen ({{games}} Partien)",
                replayGameProgress: "Partie {{current}} / {{total}} wird nachgespielt (erfolgreich: {{completed}})",
                stopped: "Gestoppt.",
                bookUnchanged: "Vorhandenes Eröffnungsbuch wurde nicht geändert.",
                bookLinesInFile: "{{count}} Partievariante(n) in {{file}}.",
                cancelledBeforeRead: "Vor dem Lesen der PGNs abgebrochen.",
                cancelledAfterRead: "Nach dem Lesen abgebrochen; Nachspielen übersprungen (nichts geschrieben).",
                mongoGamesSaved: "Für {{count}} Partie(n) wurden neue Stellungszeilen gespeichert.",
                doneBook: "Fertig. {{count}} Partievarianten → {{file}}",
                doneBookFileOnly: "Fertig. {{file}}",
                doneMongo: "Fertig. MongoDB-State-Sammlung aktualisiert{{detail}}.",
                doneMongoDetail: " ({{count}} Partien erfolgreich nachgespielt)",
                errorPrefix: "Fehler: {{message}}",
                unknownError: "Unbekannt",
                connectionClosed: "Verbindung geschlossen (Serverprotokoll prüfen oder erneut versuchen).",
                openingBookDefault: "Eröffnungsbuch"
            },
            playNow: {
                title: "Neue Partie",
                startTitle: "Neue Partie starten",
                playingColor: "Spielfarbe",
                timeMin: "Zeit (Min.)",
                difficulty: "Schwierigkeit (1–5)",
                mousePreference: "Maussteuerung",
                drag: "Ziehen",
                doubleClick: "Doppelklick",
                showAvailableMoves: "Mögliche Züge anzeigen",
                private: "Privat",
                privateHint: "Private Partien werden nicht in den Aktive-Partien-Listen anderer Mitglieder angezeigt.",
                playComputer: "Gegen Computer spielen",
                browseAll: "Alle durchsuchen",
                yourHistory: "Ihr Verlauf",
                fullList: "Vollständige Liste",
                gameLibrary: "Partienbibliothek",
                openLibrarySearch: "Bibliothekssuche öffnen",
                brain3: "Brain 3",
                brain2: "Brain 2"
            },
            activeGamesList: {
                title: "Aktive Partien",
                tagline: "Alle laufenden Partien",
                liveGames: "Live-Partien",
                game: "Partie",
                started: "Gestartet"
            },
            list: {
                title: "Alle Partien",
                tagline: "Deine abgeschlossenen Spiele",
                allGames: "Abgeschlossene Spiele",
                gamesCount: "{{count}} Spiele",
                action: "Aktion"
            },
            searchPage: {
                title: "Suche:",
                tagline: "Partien im PGN-Archiv finden",
                results: "Ergebnisse",
                resultsCount: "{{count}} Ergebnisse",
                noResults: "Keine Partien passen zur Suche",
                button: "Suchen",
                resultsFound: "{{count}} Ergebnisse gefunden:",
                first: "Erste",
                last: "Letzte",
                previous: "Zurück",
                next: "Weiter",
                previous5Pages: "5 Seiten zurück",
                next5Pages: "5 Seiten weiter",
                previous10Pages: "10 Seiten zurück",
                next10Pages: "10 Seiten weiter"
            },
            game: {
                moves: "Züge",
                white: "Weiß",
                black: "Schwarz",
                resign: "Aufgeben",
                draw: "Remis",
                undo: "Rückgängig",
                flip: "Drehen",
                practice: "Training"
            },
            mobileWelcome: {
                title: "Start — Schach",
                play: "Spielen",
                library: "Bibliothek",
                friends: "Freunde"
            },
            mobileGame: {
                title: "Partie",
                moves: "Züge",
                resign: "Aufgeben"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "Etwas ist schiefgelaufen",
                body: "Ein Fehler ist aufgetreten.",
                back: "Zurück zur Startseite"
            },
            chrome: {
                preferences: "Einstellungen",
                closePreferences: "Einstellungen schließen",
                display: "Anzeige",
                gameplay: "Spielverhalten",
                pieceSet: "Figurensatz",
                boardTheme: "Brett-Design",
                theme: "Thema",
                themeBlue: "Blau",
                themeDark: "Dunkel",
                customizeTheme: "Design anpassen…",
                builtInThemesAria: "Integrierte Designs",
                savedCustomThemesAria: "Gespeicherte benutzerdefinierte Designs",
                pieceSetsAria: "Figurensätze",
                homeAria: "Shmerling Chess Start"
            },
            prefs: {
                language: "Sprache",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "Maussteuerung",
                mouseDrag: "Ziehen",
                mouseClick: "Klicken",
                thinkingTime: "Bedenkzeit",
                thinkingTimeAria: "Bedenkzeit in Sekunden",
                immediateResign: "Sofort aufgeben",
                secondsOption: "{{count}} s",
                selectedTheme: "Ausgewählt: {{name}}",
                selectedPieceSet: "Ausgewählt: {{name}}",
                enterFullScreen: "Vollbild aktivieren",
                exitFullScreen: "Vollbild beenden",
                fullScreenUnavailable: "Vollbild ist in diesem Browser nicht verfügbar."
            },
            gameRun: {
                yourColor: "Ihre Farbe",
                engine: "Engine",
                thinkTime: "Bedenkzeit (Sekunden)",
                thinkTimeAria: "Engine-Bedenkzeit in Sekunden",
                play: "Spielen",
                nextMove: "Nächster Zug",
                computer: "Computer",
                computerColorHint: "Welche Farbe der Computer spielt — Sie spielen die andere Seite"
            },
            brainConfig: {
                title: "Brain-Konfiguration",
                save: "Speichern",
                reset: "Zurücksetzen",
                saved: "Konfiguration gespeichert",
                failedSave: "Konfiguration konnte nicht gespeichert werden",
                brainLabel: "Brain",
                loading: "Wird geladen…",
                failedLoad: "Brain-Konfiguration konnte nicht geladen werden.",
                discardSwitchConfirm: "Nicht gespeicherte Änderungen verwerfen und Brain-Version wechseln?",
                discard: "Verwerfen",
                pieceScores: "Figurenwerte",
                specialEvaluations: "Spezialbewertungen",
                gamePhase: "Spielphase",
                pawnFilesOpeningMid: "Bauernlinien (Eröffnung / Mittelspiel)",
                pawnFilesEndGame: "Bauernlinien (Endspiel)"
            },
            customTheme: {
                title: "Benutzerdefiniertes Design",
                name: "Designname",
                save: "Speichern",
                delete: "Löschen",
                saved: "Gespeichert",
                searchProperties: "Eigenschaften suchen",
                filterPlaceholder: "Nach Eigenschaftsname filtern…",
                namePlaceholder: "Mein Design",
                resetPreset: "Auf aktuelle Voreinstellung zurücksetzen",
                couldNotSave: "Design konnte nicht gespeichert werden. Erneut versuchen.",
                untitled: "Ohne Titel",
                defaultName: "Benutzerdefiniertes Design"
            },
            positionSetup: {
                clearBoard: "Brett leeren",
                startingPosition: "Ausgangsstellung",
                flipBoard: "Brett drehen",
                eraser: "Radierer",
                selectAndMove: "Auswählen und verschieben",
                defaultStartingPosition: "Standard-Ausgangsstellung",
                savePosition: "Stellung speichern",
                saveAsNewPosition: "Als neue Stellung speichern",
                validatePosition: "Stellung prüfen",
                positionFlags: "Stellungsflags",
                turn: "Am Zug",
                flagCheck: "Schach",
                flagCheckmate: "Schachmatt",
                flagDraw: "Remis",
                flagWhiteKingMoved: "Weißer König gezogen",
                flagBlackKingMoved: "Schwarzer König gezogen",
                flagWhiteKingsideRookMoved: "Weißer Königsflügel-Turm gezogen",
                flagWhiteQueensideRookMoved: "Weißer Damenflügel-Turm gezogen",
                flagBlackKingsideRookMoved: "Schwarzer Königsflügel-Turm gezogen",
                flagBlackQueensideRookMoved: "Schwarzer Damenflügel-Turm gezogen"
            }
        },
        errorPage: {
            code: "Fehler {{code}}",
            notFoundTitle: "Seite nicht gefunden",
            notFoundMessage: "Die gesuchte Seite existiert nicht.",
            genericTitle: "Etwas ist schiefgelaufen",
            genericMessage: "Ein unerwarteter Fehler ist aufgetreten. Bitte erneut versuchen.",
            backHome: "Zurück zur Startseite"
        },
        mobile: {
            drawOfferTitle: "Remis-Angebot",
            drawOfferMessage: "Der Gegner hat Remis angeboten. Annehmen?",
            rematchTitle: "Revanche",
            rematchMessage: "Der Gegner hat eine Revanche angeboten. Annehmen?",
            gameId: "Partie-ID: {{id}}",
            drawOfferAgree: "Der Gegner hat Remis angeboten, zustimmen?",
            rematchOfferAgree: "Der Gegner hat eine Revanche angeboten, zustimmen?",
            newGameWatchFromHome: "Neue Partie gestartet — gehen Sie zur Startseite, um zuzuschauen."
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = deExtra;
    } else {
        global.ShmerlingStringsDeExtra = deExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
