(function (global) {
    "use strict";
    const enExtra = {
    "validation": {
        "passwordLowercase": "Password must have at least one Lowercase Character.",
        "passwordDigit": "Password must contain at least one Digit.",
        "passwordSymbol": "Password must contain at least one Special Symbol.",
        "passwordLength": "Password must be 8-30 Characters Long.",
        "noHtml": "{{label}} must not include HTML.",
        "position": {
            "headerSave": "Cannot save this position:\n\n",
            "headerPlay": "Cannot play from this position:\n\n",
            "headerUse": "Cannot use this position:\n\n",
            "headerSaveBookmark": "Cannot save this bookmark:\n\n",
            "headerAddBookmark": "Cannot add this bookmark:\n\n",
            "boardUnreadable": "Could not read the board. Try again after the board has loaded.",
            "whiteKingNone": "There must be exactly one white king on the board. None was found.",
            "whiteKingCount": "There must be exactly one white king on the board. Found {{count}} white kings.",
            "blackKingNone": "There must be exactly one black king on the board. None was found.",
            "blackKingCount": "There must be exactly one black king on the board. Found {{count}} black kings.",
            "kingsAdjacent": "The two kings cannot be on adjacent squares (including diagonally).",
            "sideInCheck": "{{mover}} is to move, but {{king}}'s king is already in check. The side to move cannot be giving check — change turn or move pieces.",
            "drawInsufficientKings": "This position is a draw by insufficient material (king versus king). Add pieces so checkmate remains possible.",
            "drawInsufficientMinor": "This position is a draw by insufficient material (king and bishop or knight versus lone king). Add pieces so checkmate remains possible.",
            "drawBishopsSameColor": "This position is a draw by insufficient material (bishop versus bishop on the same square color). Add pieces so checkmate remains possible.",
            "tooManyQueens": "{{color}} has {{count}} queens; the maximum is 9 per color.",
            "tooManyRooks": "{{color}} has {{count}} rooks; the maximum is 10 per color.",
            "tooManyBishops": "{{color}} has {{count}} bishops; the maximum is 10 per color.",
            "tooManyKnights": "{{color}} has {{count}} knights; the maximum is 10 per color.",
            "tooManyPawns": "{{color}} has {{count}} pawns; the maximum is 8 per color."
        }
    },
    "auth": {
        "whoAreYou": "Who are you?",
        "enterPassword": "Password please",
        "sorry": "Sorry",
        "continue": "Continue",
        "usernameField": "Username",
        "passwordField": "Password",
        "wrongCredentials": "Wrong username or password",
        "userAdded": "User added Successfully",
        "couldNotSaveBookmark": "Could not save bookmark",
        "invalidUserId": "Invalid user id",
        "generationJobRunning": "Another generation job is already running…",
        "listingPgnFiles": "Listing PGN files…"
    },
    "classic": {
        "loadGame": "Load Game",
        "load": "Load",
        "enterGameState": "Paste game state here...",
        "rematch": "Rematch",
        "drawOffer": "Draw Offer",
        "lastMove": "Last Move",
        "bookmarks": "Bookmarks",
        "bookmarkAlertTitle": "Bookmark position",
        "promotion": "Promotion!",
        "check": "Check",
        "checkmateWins": "Checkmate! {{winner}} wins!",
        "drawReason": "Draw! {{reason}}",
        "opponentDisconnected": "The opponent disconnected",
        "opponentResignedWins": "The opponent resigned, {{winner}} wins",
        "somethingWentWrong": "Something went wrong",
        "playerRejoined": "{{name}} rejoined",
        "aPlayerRejoined": "A player rejoined",
        "opponentRejoined": "The opponent rejoined",
        "rematchOfferAccepted": "Rematch offer accepted",
        "rematchOfferDeclined": "Rematch offer declined",
        "sideOffersDraw": "{{side}} offers draw",
        "drawOfferDeclined": "Draw offer declined",
        "watcherWatching": "{{name}} is watching the game",
        "drawOfferSent": "Draw offer sent",
        "rematchOfferSent": "Rematch offer sent",
        "newGameStarted": "New Game Started",
        "gameOver": "Game Over",
        "gameCancelled": "Game cancelled",
        "youResignedWins": "You resigned, {{winner}} wins",
        "movesCopied": "Moves copied to clipboard!",
        "failedCopyMoves": "Failed to copy moves",
        "failedLoadBrainConfig": "Failed to load brain config.",
        "failedSaveBrainConfig": "Failed to save brain config.",
        "offerDrawConfirm": "Offer a Draw?",
        "drawOfferAccept": "Opponent sent a draw offer, accept?",
        "rematchOfferAccept": "Opponenet offer a rematch, agree?",
        "rematchOfferAcceptWithTime":
            "Opponent offered a rematch ({{minutes}} min per side). Agree?",
        "rematchTimePrompt": "Minutes per side for the rematch:",
        "connectionLost": "Connection lost — moves are not reaching the server",
        "confirmExitGame": "Are you sure you want to exit the game?",
        "mobileResign": "Resign",
        "mobileRematch": "Rematch",
        "mobileDraw": "Draw",
        "mobileFlip": "Flip",
        "mobileLastMove": "Last move",
        "mobileMovesList": "Moves list",
        "researchToolbox": "Toolbox",
        "researchBrainConfig": "Brain Config",
        "researchSave": "Save",
        "researchDiscard": "Discard",
        "researchEditMode": "edit mode",
        "researchRun": "Run",
        "researchProperty": "Property",
        "researchValue": "Value",
        "playerOnline": "Online",
        "playerDisconnectedStatus": "Disconnected",
        "playerOffline": "Offline",
        "humanVsComputer": "Human Vs. Computer",
        "newGameTwoPlayers": "New Game 2 Players",
        "settings": "Settings",
        "help": "Help",
        "drawOffersNotVsEngine": "Draw offers are not available when playing against the engine.",
        "failedStartFromBookmark": "Failed to start game from bookmark.",
        "resignConfirm": "Resign?",
        "areYouSure": "Are you sure?",
        "gameOverOpponentFailedReconnectWinsClassic": "Game over — opponent failed to reconnect. {{winner}} wins.",
        "reconnectTimeoutNoMoves": "Reconnect timed out with no moves played.",
        "waitingOpponentRejoin": "Waiting for opponent to rejoin",
        "timeoutOneSec": "Timeout: 1 sec",
        "timeoutSecs": "Timeout: {{count}} sec",
        "whitePieceAlt": "White piece",
        "blackPieceAlt": "Black piece",
        "eraserTitle": "Eraser",
        "eraserAria": "Eraser – remove piece from square",
        "selectTitle": "Select",
        "selectAria": "Select – drag pieces to move them",
        "resetAria": "Reset – clear all pieces",
        "defaultPositionAria": "Default position – set up standard starting position",
        "loading": "Loading...",
        "engineLabel": "Engine"
    },
    "site": {
        "home": "Home",
        "search": "Search",
        "friends": "Friends",
        "groups": "Groups",
        "debug": "Debug",
        "account": "Account",
        "preferences": "Preferences",
        "administrate": "Administrate",
        "logOut": "Log out",
        "logIn": "Log in",
        "admin": "Admin",
        "homeAria": "Home",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "notice": "Notice",
        "ok": "OK",
        "accountPage": {
            "title": "Account",
            "lead": "View your profile details",
            "detailsHeading": "Your details",
            "username": "Username",
            "email": "Email",
            "userType": "Account type",
            "level": "Level",
            "elo": "Elo",
            "joined": "Joined",
            "lastLogin": "Last login",
            "friendsCount": "Friends",
            "bookmarksCount": "Bookmarks",
            "passwordHeading": "Change password",
            "passwordBody": "Enter your current password, then choose a new password (4–30 characters).",
            "currentPassword": "Current password",
            "newPassword": "New password",
            "confirmPassword": "Confirm new password",
            "passwordButton": "Update password",
            "passwordMismatch": "New password and confirmation do not match.",
            "passwordUpdated": "Password updated.",
            "passwordFailed": "Could not update the password. Check your current password and try again.",
            "exportHeading": "Download my data",
            "exportBody": "Download a JSON file with your profile (excluding password), preferences, friends, invites, bookmarks, and games associated with this account.",
            "exportButton": "Download JSON",
            "deleteHeading": "Delete account",
            "deleteBody": "Permanently delete this account. Bookmarks and friend links are removed. Shared online games keep history with your name replaced by “Deleted User”. Sole-owned games are deleted. This cannot be undone.",
            "deleteConfirmLabel": "Type your username to confirm",
            "deleteConfirmHelp": "Enter {{username}} exactly, then confirm.",
            "deleteButton": "Delete my account",
            "deleteConfirmDialog": "Delete this account permanently? This cannot be undone.",
            "deleteMismatch": "Username does not match.",
            "deleteFailed": "Could not delete the account. Try again or contact support.",
        },
        "footer": {
            "logoAlt": "Shmerling Chess",
            "navAria": "Footer",
            "privacy": "Privacy Policy",
            "terms": "Terms of Use",
            "contact": "Contact",
            "accessibility": "Accessibility",
            "copyright": "© {{year}} Shmerling Chess. All rights reserved.",
            "lastUpdated": "Last updated: {{date}}",
            "privacyTitle": "Privacy Policy",
            "privacyLead": "This policy explains how Shmerling Chess collects, uses, stores, and shares personal data when you use the web service and related desktop software.",
            "privacyBody": "See the sections below for controller identity, purposes, legal bases, retention, rights, and international transfers.",
            "termsTitle": "Terms of Use",
            "termsLead": "These terms govern your use of Shmerling Chess. By creating an account or using the service, you agree to them.",
            "termsBody": "See the sections below for account rules, fair play, acceptable use, and liability.",
            "contactTitle": "Contact",
            "contactLead": "How to reach the Shmerling Chess controller for support and privacy requests.",
            "contactBody": "Use the contact details below for support and data-protection requests.",
            "accessibilityTitle": "Accessibility statement",
            "accessibilityLead": "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549).",
        },
        "privacy": {
            "controllerHeading": "Who is the controller",
            "controllerBody": "The data controller for Shmerling Chess is Ariel Shmerling, operating the Shmerling Chess service. For privacy requests, use the email address shown on the Contact page.",
            "dataHeading": "What we collect",
            "dataBody": "Account data: username, email address, hashed password, account type/level, and timestamps such as joined date and last login. Gameplay data: games you play or watch (moves, clocks, results, privacy flags), friends and invites, bookmarks/saved positions, and Play preferences (themes, docks, mouse mode, and similar UI settings). Technical data: session cookies needed to keep you signed in, and routine server logs (for example approximate timing and error diagnostics) used to operate and secure the service.",
            "purposesHeading": "Why we use your data",
            "purposesBody": "We process personal data to create and authenticate accounts, provide single-player and online chess, save and review games, sync preferences, enable friends and messaging related to play, send operational notices (such as admin privilege alerts when configured), prevent abuse and secure the service, and improve reliability and features.",
            "basesHeading": "Legal bases",
            "basesBody": "Where GDPR (or similar laws) apply, we rely on: performance of a contract (providing the chess service you request); legitimate interests (securing the service, preventing abuse, basic product improvement) balanced against your rights; and consent where required for optional communications or non-essential processing. You may withdraw consent for optional processing without affecting the lawfulness of processing before withdrawal.",
            "retentionHeading": "How long we keep data",
            "retentionBody": "Account and game records are kept while your account remains active and as needed to provide history, review, and fair-play records. Session cookies last for the configured session lifetime (typically up to about one day of inactivity for the signed-in session cookie). Server logs are retained only as long as reasonably needed for security and operations. You may request deletion of your account data as described under Your rights; some residual backups or legal holds may persist for a limited period.",
            "sharingHeading": "Who we share data with",
            "sharingBody": "We do not sell personal information. We use service providers that process data on our behalf, such as database hosting (for example MongoDB Atlas), application hosting, and email delivery (SMTP) when notification features are enabled. Other players may see your username and public game information when you play online or appear on public lists; private games remain restricted according to product rules.",
            "transfersHeading": "International transfers",
            "transfersBody": "Infrastructure may be located in more than one country (for example database or hosting regions). When personal data is transferred internationally, we rely on appropriate safeguards available from our providers (such as standard contractual clauses or equivalent mechanisms) and process only what is needed to run the service.",
            "rightsHeading": "Your rights",
            "rightsBody": "Depending on your location, you may have the right to access, rectify, erase, restrict, or port your personal data, to object to certain processing, and to lodge a complaint with a supervisory authority. Signed-in users can open Account from the site menu to view profile details, download a JSON copy of their data, or permanently delete their account. You may also contact us using the Contact page. We may need to verify your identity before fulfilling a request.",
            "securityHeading": "Security",
            "securityBody": "Passwords are stored hashed. We use HTTPS in production deployments, session cookies marked HttpOnly, and application controls such as CSRF protections and content security policies. No method of transmission or storage is perfectly secure; please choose a strong unique password.",
            "cookiesHeading": "Cookies and local storage",
            "cookiesBody": "We use an essential session cookie to keep you signed in. The Play client may also store preferences and similar settings in browser local storage on your device. These are used to operate the service and remember your choices—not for third-party advertising.",
            "childrenHeading": "Children",
            "childrenBody": "Shmerling Chess is not directed at children under 16 (or the digital consent age in your country). If you believe a child has provided personal data, contact us so we can delete it.",
            "changesHeading": "Changes to this policy",
            "changesBody": "We may update this Privacy Policy from time to time. The “Last updated” date on this page will change when we do. Continued use of the service after an update means you acknowledge the revised policy.",
        },
        "terms": {
            "acceptanceHeading": "Agreement",
            "acceptanceBody": "By registering for or using Shmerling Chess (the website, APIs used by the site, and the desktop app that connects to it), you agree to these Terms of Use and our Privacy Policy. If you do not agree, do not use the service.",
            "accountHeading": "Accounts",
            "accountBody": "You must provide accurate registration information and keep your credentials confidential. You are responsible for activity under your account. We may suspend or close accounts that are abusive, compromised, or create risk for other users or the service.",
            "fairPlayHeading": "Fair play",
            "fairPlayBody": "Play honestly. Do not cheat, harass other players, exploit bugs for unfair advantage, or attempt to disrupt matches. Engine assistance in online human vs human play is prohibited unless a mode explicitly allows it.",
            "acceptableUseHeading": "Acceptable use",
            "acceptableUseBody": "Do not attempt unauthorized access, probe or overload the service, scrape in a way that harms availability, upload malware, or use the service for anything unlawful. Do not reverse engineer the service except where applicable law allows.",
            "contentHeading": "Games and content",
            "contentBody": "You retain rights in content you submit to the extent the law provides. You grant us a license to host, display, and process that content as needed to operate Shmerling Chess (including showing games to opponents, spectators where allowed, and history/review features). Public PGN libraries and opening-book materials we ship are for use within the product.",
            "availabilityHeading": "Availability and changes",
            "availabilityBody": "We provide the service on an “as available” basis. Features may change, and we may modify or discontinue parts of the service with or without notice when reasonably needed for maintenance, security, or product evolution.",
            "disclaimerHeading": "Disclaimers",
            "disclaimerBody": "Shmerling Chess is provided “as is” without warranties of any kind to the fullest extent permitted by law, including merchantability, fitness for a particular purpose, and non-infringement. Engine evaluations and opening-book suggestions are informational and may be imperfect.",
            "liabilityHeading": "Limitation of liability",
            "liabilityBody": "To the fullest extent permitted by law, the controller and operators of Shmerling Chess are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, ratings, or gameplay opportunities arising from your use of the service.",
            "terminationHeading": "Termination",
            "terminationBody": "You may stop using the service at any time. We may terminate or suspend access if you breach these terms or if we must do so for legal or security reasons. Provisions that by nature should survive (including disclaimers and liability limits) survive termination.",
            "lawHeading": "Governing law",
            "lawBody": "These terms are governed by the laws of the State of Israel, without regard to conflict-of-law rules, unless mandatory consumer protections in your country of residence require otherwise.",
            "contactHeading": "Contact",
            "contactBody": "Questions about these terms can be sent using the details on the Contact page.",
        },
        "contactPage": {
            "controllerHeading": "Controller",
            "controllerBody": "Ariel Shmerling, operating Shmerling Chess.",
            "emailHeading": "Email",
            "emailBody": "For support and privacy (GDPR and similar) requests, email:",
            "emailMissingBody": "Set SITE_CONTACT_EMAIL (or SMTP_FROM) on the server so a public contact address appears here. Until then, use the operator email configured for service notifications.",
            "whatToIncludeHeading": "What to include",
            "whatToIncludeBody": "Please include your username (if any), the page or feature involved, and whether your message is about support, accessibility, or a privacy rights request. We aim to respond within a reasonable time.",
            "securityHeading": "Security reports",
            "securityBody": "If you believe you found a security vulnerability, email the same address with a responsible description. Do not include passwords or session cookies in your report.",
        },
        "accessibility": {
            "skipToMain": "Skip to main content",
            "themeToggle": "Toggle color theme",
            "chatInput": "Chat message",
            "sendChat": "Send chat message",
            "boardRegion": "Chessboard",
            "pieceAlt": "{{color}} {{piece}}",
            "squareLabel": "{{square}}{{piece}}",
            "emptySquare": "empty",
            "statementCommitmentHeading": "Our commitment",
            "statementCommitmentBody": "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
            "statementScopeHeading": "What this covers",
            "statementScopeBody": "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
            "statementLimitsHeading": "Known limitations",
            "statementLimitsBody": "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
            "statementContactHeading": "Feedback and requests",
            "statementContactBody": "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
            "statementStandardsHeading": "Standards reference",
            "statementStandardsBody": "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services.",
        },
        "username": "Username:",
        "password": "Password:",
        "login": "Login",
        "register": {
            "submit": "Register",
            "confirmPassword": "Confirm password:",
            "playerLevel": "Player level:",
            "rookie": "Rookie",
            "skilled": "Skilled",
            "elite": "Elite",
            "grandMaster": "Grand Master"
        },
        "email": "Email:",
        "welcome": {
            "greeting": "Welcome Back",
            "tagline": "Your move awaits",
            "playNow": "Play Now!",
            "activeGames": "Active Games",
            "live": "Live",
            "showAll": "Show All",
            "viewAllActive": "View all active games",
            "mostRecent": "Most recent first",
            "noGamesNow": "No games at the moment",
            "myGames": "My Last Games",
            "viewAllGames": "View All Games",
            "recentCompleted": "Your recent completed games",
            "noCompleted": "No completed games yet",
            "activeGamesAria": "Active games",
            "inviteOnlineFriend": "Invite an online friend to play",
            "friendsPageTitle": "Friends page",
            "manageFriends": "Manage",
            "colFriend": "Friend",
            "colStatus": "Status",
            "findPlayers": "Find players",
            "waitingForResponse": "Waiting for response",
            "inviteSentSuffix": "(invite sent)",
            "sortByRowNumber": "Sort by row number",
            "sortBy": "Sort by {{key}}"
        },
        "gameList": {
            "date": "Date",
            "time": "Time",
            "result": "Result",
            "reason": "Reason",
            "type": "Type",
            "status": "Status",
            "event": "Event",
            "site": "Site",
            "round": "Round"
        },
        "loginPage": {
            "title": "Login"
        },
        "error": {
            "title": "Something went wrong",
            "body": "An error occurred.",
            "back": "Back to main"
        },
        "log": {
            "title": "Server log",
            "clear": "Clear view",
            "latest": "Latest",
            "waiting": "Waiting for server log output…"
        },
        "activeGames": {
            "moves": "Moves",
            "turn": "Turn",
            "status": "Status",
            "inProgress": "In progress",
            "onHold": "On hold",
            "vs": " vs ",
            "minutesAgo": "{{count}} minutes ago",
            "oneMinuteAgo": "1 minute ago",
            "justStarted": "Just started",
            "notStarted": "Not started",
            "startedTooltip": "Started: {{when}}",
            "playersVs": "{{white}} Vs. {{black}}"
        },
        "friendsPage": {
            "title": "Friends",
            "tagline": "Find new chess mates",
            "myFriends": "My friends",
            "noFriendsYet": "No friends yet",
            "findPlayers": "Find players",
            "searchByUsername": "Search by username",
            "searchPlaceholder": "Type to search…",
            "enterCharToSearch": "Enter at least one character to search",
            "noMatchingUsers": "No matching users",
            "playing": "Playing",
            "pendingFriendshipOffer": "Pending friendship offer",
            "joining": "Joining",
            "rejoin": "Rejoin",
            "friendRequest": "Friend request",
            "wantsToBeFriends": "(wants to be friends)",
            "pendingOfferSuffix": "(pending friendship offer)",
            "waitingFriendRespond": "Waiting for your friend to respond",
            "cancelBeforeRemove": "Cancel the game invite before removing this friend",
            "friendsTag": "Friends",
            "offerReceivedTag": "Offer received — see Your friends",
            "addFriend": "Add friend",
            "withdraw": "Withdraw",
            "requestFailed": "Request failed",
            "removeFriendConfirm": "Remove this friend from your list?",
            "removeFriendTitle": "Remove friend",
            "withdrawOfferConfirm": "Withdraw this friendship offer?",
            "withdrawOfferTitle": "Withdraw offer",
            "couldNotAccept": "Could not accept",
            "couldNotDecline": "Could not decline",
            "couldNotRemove": "Could not remove",
            "couldNotCancelInvite": "Could not cancel invite",
            "couldNotWithdraw": "Could not withdraw",
            "couldNotSendInvite": "Could not send invite",
            "couldNotSendGameInvite": "Could not send game invite",
            "gameInvite": "Game invite",
            "gameInvitationsAria": "Game invitations",
            "gameInvitationAria": "Game invitation",
            "chessInviteTitle": "Chess invite",
            "wantsToPlayAsBlack": "{{name}} wants to play. You play as Black.",
            "wantsToPlayYouWhite": "{{name}} wants to play. You play as White.",
            "aFriend": "A friend",
            "youPlayAsWhite": "You play as White",
            "youPlayAsBlack": "You play as Black",
            "establishingGame": "Establishing game…",
            "yourOpponent": "Your opponent",
            "declinedYourInvite": "{{name}} declined your game invite.",
            "cancelInvite": "Cancel invite",
            "accept": "Accept",
            "decline": "Decline",
            "invite": "Invite",
            "inviteSettingsTitle": "Invite settings",
            "inviteSettingsFor": "Invite {{name}}",
            "inviteTimeMinutes": "Time per side (minutes)",
            "inviteYourColor": "Your color",
            "inviteColorWhite": "White",
            "inviteColorBlack": "Black",
            "inviteColorRandom": "Random",
            "inviteFriendly": "Friendly game",
            "inviteFriendlyHint": "Uncheck to count toward ELO later (rated play).",
            "invitePrivate": "Private game",
            "invitePrivateHint": "Hide this game from the public active-games lobby.",
            "inviteSaveDefaults": "Save defaults",
            "inviteOfferTime": "{{minutes}} min",
            "inviteOfferFriendly": "Friendly",
            "inviteOfferRated": "Rated",
            "inviteOfferPrivate": "Private",
            "remove": "Remove",
            "offerSent": "Offer sent",
            "pending": "Pending",
            "online": "Online",
            "offline": "Offline"
        },
        "adminPage": {
            "title": "Administration",
            "tagline": "Users, games, engines, opening book, and bot duels",
            "panelTitle": "Admin console",
            "users": "Users",
            "generate": "Generate",
            "games": "Games",
            "engines": "Engines",
            "states": "States",
            "openingBook": "Opening book",
            "bots": "Bots",
            "addUser": "Add user",
            "sectionsAria": "Admin sections",
            "openingBookLabel": "Opening book:",
            "openingBookStatusTitle": "Current opening book",
            "openingBookFile": "File",
            "openingBookExists": "Status",
            "openingBookExistsYes": "Present",
            "openingBookExistsNo": "Missing",
            "openingBookLines": "Game lines",
            "openingBookSize": "Size",
            "openingBookModified": "Last modified",
            "openingBookPgnSources": "PGN sources",
            "openingBookPgnCount": "{{count}} PGN file(s) available to rebuild from",
            "openingBookIntro": "Rebuild the line-based opening book (data/opening-book-lines.txt) from the server’s PGN folders. Use Generate opening book below—nothing runs until you press it.",
            "generateOpeningBook": "Generate opening book",
            "botsIntro": "Start a public engine-vs-engine game. Members can open it from Active Games on Home as watchers.",
            "botsWhiteEngine": "White engine",
            "botsBlackEngine": "Black engine",
            "botsWhiteDifficulty": "Difficulty (1–6)",
            "botsBlackDifficulty": "Difficulty (1–6)",
            "botsSkillLevel": "Skill (0–20)",
            "botsTimeMinutes": "Clock (minutes)",
            "botsStart": "Start duel",
            "botsStarting": "Starting duel…",
            "botsStarted": "Duel started: {{white}} vs {{black}}.",
            "botsWatchLink": "Watch this game",
            "botsListedNote": "Listed on Home → Active Games for other users.",
            "botsStartFailed": "Could not start the duel.",
            "botsStopped": "Stop requested.",
            "botsStopFailed": "Could not stop the duel.",
            "gameLines": "game lines",
            "noGamesInDb": "No games in the database yet.",
            "gamesPaginationAria": "Games pagination",
            "colNum": "#",
            "colUsername": "Username",
            "colType": "Type",
            "colEmail": "Email",
            "colPassword": "Password",
            "colLevel": "Level",
            "colElo": "Elo",
            "colJoined": "Joined",
            "colLastLogin": "Last login",
            "colActiveGames": "Active games",
            "colFriends": "Friends",
            "colBookmarks": "Bookmarks",
            "colId": "Id",
            "colStatus": "Status",
            "colName": "Name",
            "colAvailable": "Available",
            "colEnabled": "Enabled",
            "colBackend": "Backend",
            "colCommand": "Command",
            "colNotes": "Notes",
            "colNote": "Note",
            "colAction": "Action",
            "emptyUsers": "No users yet.",
            "emptyData": "No data yet.",
            "emptyEngines": "No Play engines in the registry.",
            "emptyStates": "Use Generate to open the opening-book and state generation page.",
            "engineAvailableYes": "Available",
            "engineAvailableNo": "Unavailable",
            "engineEnable": "Enable",
            "engineDisable": "Disable",
            "enginesLoadFailed": "Could not load engines",
            "enginesSaveFailed": "Could not update engine",
            "clickToEdit": "Click to edit",
            "updateFailed": "Update failed",
            "couldNotSave": "Could not save",
            "setPassword": "Set password",
            "setPasswordTitle": "Click to set a new password (4–30 characters)",
            "passwordLengthInvalid": "Password must be between 4 and 30 characters.",
            "invalidPassword": "Invalid password",
            "saved": "Saved",
            "newPasswordPlaceholder": "New password",
            "clickChangeUserType": "Click to change user type",
            "userTypeAria": "User type",
            "changeUserTypeTitle": "Change user type",
            "grantAdminConfirm": "Grant admin privileges to this user? They will be able to access admin tools and manage accounts.",
            "demoteAdminConfirm": "Change this user from Admin to {{type}}? They will lose access to the admin area.",
            "changeUserTypeConfirm": "Change this user to {{type}}?",
            "clickChangeLevel": "Click to change level",
            "playerLevelAria": "Player level",
            "sortByRowNumber": "Sort by row number",
            "sortBy": "Sort by {{key}}",
            "delete": "Delete",
            "first": "First",
            "last": "Last",
            "previous": "Previous",
            "next": "Next",
            "previous5Pages": "Previous 5 pages",
            "next5Pages": "Next 5 pages",
            "previous10Pages": "Previous 10 pages",
            "next10Pages": "Next 10 pages",
            "userTypeAdmin": "Admin",
            "userTypePartner": "Partner",
            "userTypeMember": "Member",
            "generateTitle": "Opening book & state generation",
            "backToAdmin": "← Back to admin",
            "generateIntro": "Replays all PGN files under the server’s games manager folder into either the State Mongo collection or the line-based opening book (data/opening-book-lines.txt). Choose a target, then press Start generation—nothing runs until you do.",
            "target": "Target",
            "targetMongo": "MongoDB — append rows to the State collection",
            "targetBook": "Line file — write opening book (opening-book-lines.txt)",
            "startGeneration": "Start generation",
            "stop": "Stop",
            "idle": "Idle.",
            "starting": "Starting…",
            "running": "Running ({{mode}})…",
            "readingFiles": "Reading {{count}} file(s)…",
            "replayingGames": "Replaying {{count}} games…",
            "writingOpeningBook": "Writing opening book…",
            "readingPgn": "Reading PGN {{index}} / {{total}} ({{games}} games)",
            "replayGameProgress": "Replay game {{current}} / {{total}} (completed ok: {{completed}})",
            "stopped": "Stopped.",
            "bookUnchanged": "Existing opening book was not modified.",
            "bookLinesInFile": "{{count}} game line(s) in {{file}}.",
            "cancelledBeforeRead": "Cancelled before reading PGNs.",
            "cancelledAfterRead": "Cancelled after read; replay was skipped (nothing written).",
            "mongoGamesSaved": "{{count}} game(s) had new state rows saved.",
            "doneBook": "Done. {{count}} game lines → {{file}}",
            "doneBookFileOnly": "Done. {{file}}",
            "doneMongo": "Done. MongoDB State collection updated{{detail}}.",
            "doneMongoDetail": " ({{count}} games replayed ok)",
            "errorPrefix": "Error: {{message}}",
            "unknownError": "Unknown",
            "connectionClosed": "Connection closed (check server logs or try again).",
            "openingBookDefault": "opening book"
        },
        "playNow": {
            "title": "New game",
            "startTitle": "Start a new Game",
            "playingColor": "Playing color",
            "timeMin": "Time (min)",
            "difficulty": "Difficulty (1–5)",
            "mousePreference": "Mouse preference",
            "drag": "Drag",
            "doubleClick": "Double click",
            "showAvailableMoves": "Show available moves",
            "private": "Private",
            "privateHint": "Private games are not shown on other members' Active Games lists.",
            "playComputer": "Play computer",
            "browseAll": "Browse all",
            "yourHistory": "Your history",
            "fullList": "Full list",
            "gameLibrary": "Game library",
            "openLibrarySearch": "Open library search",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Active games",
            "tagline": "All games in progress",
            "liveGames": "Live games",
            "game": "Game",
            "started": "Started"
        },
        "list": {
            "title": "All Games",
            "tagline": "Your completed games",
            "allGames": "Completed games",
            "gamesCount": "{{count}} games",
            "action": "Action"
        },
        "searchPage": {
            "title": "Search:",
            "tagline": "Find famous games in the archive",
            "results": "Results",
            "resultsCount": "{{count}} results",
            "loading": "Loading games…",
            "loadingLibrary": "Opening the library…",
            "loadError": "Could not load search results. Try again.",
            "noResults": "No games match your search",
            "button": "Search",
            "resultsFound": "{{count}} Results found:",
            "first": "First",
            "last": "Last",
            "previous": "Previous",
            "next": "Next",
            "previous5Pages": "Previous 5 pages",
            "next5Pages": "Next 5 pages",
            "previous10Pages": "Previous 10 pages",
            "next10Pages": "Next 10 pages"
        },
        "game": {
            "moves": "Moves",
            "white": "White",
            "black": "Black",
            "resign": "Resign",
            "draw": "Draw",
            "undo": "Undo",
            "flip": "Flip",
            "practice": "Practice"
        },
        "mobileWelcome": {
            "title": "Home — Chess",
            "play": "Play",
            "library": "Library",
            "friends": "Friends"
        },
        "mobileGame": {
            "title": "Game",
            "moves": "Moves",
            "resign": "Resign"
        }
    },
    "desktop": {
        "error": {
            "title": "Something went wrong",
            "body": "An error occurred.",
            "back": "Back to main"
        },
        "chrome": {
            "preferences": "Preferences",
            "closePreferences": "Close preferences",
            "display": "Display",
            "gameplay": "Gameplay",
            "pieceSet": "Piece set",
            "boardTheme": "Theme",
            "theme": "Theme",
            "themeBlue": "Blue",
            "themeDark": "Dark",
            "customizeTheme": "Manage themes…",
            "builtInThemesAria": "Built-in themes",
            "savedCustomThemesAria": "Saved custom themes",
            "pieceSetsAria": "Piece sets",
            "homeAria": "Shmerling Chess home"
        },
        "prefs": {
            "language": "Language",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "languageBengali": "বাংলা",
            "languagePortuguese": "Português",
            "mouseControl": "Mouse control",
            "mouseDrag": "Drag",
            "mouseClick": "Click",
            "thinkingTime": "Engine thinking time",
            "thinkingTimeAria": "Engine thinking time in seconds",
            "immediateResign": "Immediate resign",
            "secondsOption": "{{count}}s",
            "selectedTheme": "Selected: {{name}}",
            "selectedPieceSet": "Selected: {{name}}",
            "enterFullScreen": "Enter full screen",
            "exitFullScreen": "Exit full screen",
            "fullScreenUnavailable": "Full screen is not available in this browser."
        },
        "gameRun": {
            "panelTitle": "Start game",
            "yourColor": "Your color",
            "engine": "Engine",
            "thinkTime": "Think time (seconds)",
            "thinkTimeAria": "Engine thinking time in seconds",
            "play": "Play",
            "nextMove": "Next move",
            "computer": "Computer",
            "computerColorHint": "Which color the computer plays — you play the other side"
        },
        "brainConfig": {
            "title": "Brain configuration",
            "save": "Save",
            "reset": "Reset",
            "saved": "Configuration saved",
            "failedSave": "Failed to save configuration",
            "brainLabel": "Brain",
            "loading": "Loading…",
            "failedLoad": "Failed to load brain config.",
            "discardSwitchConfirm": "Discard unsaved changes and switch brain version?",
            "discard": "Discard",
            "pieceScores": "Piece scores",
            "specialEvaluations": "Special evaluations",
            "gamePhase": "Game phase",
            "pawnFilesOpeningMid": "Pawn files (opening / mid)",
            "pawnFilesEndGame": "Pawn files (endgame)"
        },
        "customTheme": {
            "title": "Theme",
            "name": "Theme name",
            "save": "Save",
            "delete": "Delete",
            "saved": "Themes",
            "searchProperties": "Search properties",
            "filterPlaceholder": "Filter by property name…",
            "namePlaceholder": "My theme",
            "resetPreset": "Reset changes",
            "couldNotSave": "Could not save theme. Try again.",
            "untitled": "Untitled",
            "defaultName": "New theme",
            "resetToOriginal": "Reset to original",
            "resetPropertyAria": "Reset {{label}} to original"
        },
        "positionSetup": {
            "clearBoard": "Clear board",
            "startingPosition": "Starting position",
            "flipBoard": "Flip board",
            "eraser": "Eraser",
            "selectAndMove": "Select and move",
            "defaultStartingPosition": "Default starting position",
            "savePosition": "Save position",
            "saveAsNewPosition": "Save as new position",
            "validatePosition": "Validate position",
            "positionFlags": "Position flags",
            "turn": "Turn",
            "flagCheck": "Check",
            "flagCheckmate": "Checkmate",
            "flagDraw": "Draw",
            "flagWhiteKingMoved": "White king moved",
            "flagBlackKingMoved": "Black king moved",
            "flagWhiteKingsideRookMoved": "White kingside rook moved",
            "flagWhiteQueensideRookMoved": "White queenside rook moved",
            "flagBlackKingsideRookMoved": "Black kingside rook moved",
            "flagBlackQueensideRookMoved": "Black queenside rook moved"
        }
    },
    "errorPage": {
        "code": "Error {{code}}",
        "notFoundTitle": "Page not found",
        "notFoundMessage": "The page you are looking for does not exist.",
        "genericTitle": "Something went wrong",
        "genericMessage": "An unexpected error occurred. Please try again.",
        "backHome": "Back to home"
    },
    "mobile": {
        "drawOfferTitle": "Draw offer",
        "drawOfferMessage": "Opponent sent a draw offer. Accept?",
        "rematchTitle": "Rematch",
        "rematchMessage": "Opponent sent a rematch offer. Accept?",
        "gameId": "Game ID: {{id}}",
        "drawOfferAgree": "Opponent offered a draw, agree?",
        "rematchOfferAgree": "Opponent offered a rematch, agree?",
        "newGameWatchFromHome": "New game started — go to Home to watch."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = enExtra;
    } else {
        global.ShmerlingStringsEnExtra = enExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
