(function (global) {
    "use strict";
    const enExtra = {
    "validation": {
        "passwordLowercase": "Password must have at least one Lowercase Character.",
        "passwordDigit": "Password must contain at least one Digit.",
        "passwordSymbol": "Password must contain at least one Special Symbol.",
        "passwordLength": "Password must be 8-30 Characters Long.",
        "noHtml": "{{label}} must not include HTML.",
        "position": {
            "headerSave": "Cannot save this position:\n\n",
            "headerPlay": "Cannot play from this position:\n\n",
            "headerUse": "Cannot use this position:\n\n",
            "headerSaveBookmark": "Cannot save this bookmark:\n\n",
            "headerAddBookmark": "Cannot add this bookmark:\n\n",
            "boardUnreadable": "Could not read the board. Try again after the board has loaded.",
            "whiteKingNone": "There must be exactly one white king on the board. None was found.",
            "whiteKingCount": "There must be exactly one white king on the board. Found {{count}} white kings.",
            "blackKingNone": "There must be exactly one black king on the board. None was found.",
            "blackKingCount": "There must be exactly one black king on the board. Found {{count}} black kings.",
            "kingsAdjacent": "The two kings cannot be on adjacent squares (including diagonally).",
            "sideInCheck": "{{mover}} is to move, but {{king}}'s king is already in check. The side to move cannot be giving check — change turn or move pieces.",
            "drawInsufficientKings": "This position is a draw by insufficient material (king versus king). Add pieces so checkmate remains possible.",
            "drawInsufficientMinor": "This position is a draw by insufficient material (king and bishop or knight versus lone king). Add pieces so checkmate remains possible.",
            "drawBishopsSameColor": "This position is a draw by insufficient material (bishop versus bishop on the same square color). Add pieces so checkmate remains possible.",
            "tooManyQueens": "{{color}} has {{count}} queens; the maximum is 9 per color.",
            "tooManyRooks": "{{color}} has {{count}} rooks; the maximum is 10 per color.",
            "tooManyBishops": "{{color}} has {{count}} bishops; the maximum is 10 per color.",
            "tooManyKnights": "{{color}} has {{count}} knights; the maximum is 10 per color.",
            "tooManyPawns": "{{color}} has {{count}} pawns; the maximum is 8 per color."
        }
    },
    "auth": {
        "wrongCredentials": "Wrong username or password",
        "userAdded": "User added Successfully",
        "couldNotSaveBookmark": "Could not save bookmark",
        "invalidUserId": "Invalid user id",
        "generationJobRunning": "Another generation job is already running…",
        "listingPgnFiles": "Listing PGN files…"
    },
    "classic": {
        "loadGame": "Load Game",
        "load": "Load",
        "enterGameState": "Paste game state here...",
        "rematch": "Rematch",
        "drawOffer": "Draw Offer",
        "lastMove": "Last Move",
        "bookmarks": "Bookmarks",
        "bookmarkAlertTitle": "Bookmark position",
        "promotion": "Promotion!",
        "check": "Check",
        "checkmateWins": "Checkmate! {{winner}} wins!",
        "drawReason": "Draw! {{reason}}",
        "opponentDisconnected": "The opponent disconnected",
        "opponentResignedWins": "The opponent resigned, {{winner}} wins",
        "somethingWentWrong": "Something went wrong",
        "playerRejoined": "{{name}} rejoined",
        "aPlayerRejoined": "A player rejoined",
        "opponentRejoined": "The opponent rejoined",
        "rematchOfferAccepted": "Rematch offer accepted",
        "rematchOfferDeclined": "Rematch offer declined",
        "sideOffersDraw": "{{side}} offers draw",
        "drawOfferDeclined": "Draw offer declined",
        "watcherWatching": "{{name}} is watching the game",
        "drawOfferSent": "Draw offer sent",
        "rematchOfferSent": "Rematch offer sent",
        "newGameStarted": "New Game Started",
        "gameOver": "Game Over",
        "gameCancelled": "Game cancelled",
        "youResignedWins": "You resigned, {{winner}} wins",
        "movesCopied": "Moves copied to clipboard!",
        "failedCopyMoves": "Failed to copy moves",
        "failedLoadBrainConfig": "Failed to load brain config.",
        "failedSaveBrainConfig": "Failed to save brain config.",
        "offerDrawConfirm": "Offer a Draw?",
        "drawOfferAccept": "Opponent sent a draw offer, accept?",
        "rematchOfferAccept": "Opponenet offer a rematch, agree?",
        "confirmExitGame": "Are you sure you want to exit the game?",
        "mobileResign": "Resign",
        "mobileRematch": "Rematch",
        "mobileDraw": "Draw",
        "mobileFlip": "Flip",
        "mobileLastMove": "Last move",
        "mobileMovesList": "Moves list",
        "researchToolbox": "Toolbox",
        "researchBrainConfig": "Brain Config",
        "researchSave": "Save",
        "researchDiscard": "Discard",
        "researchEditMode": "edit mode",
        "researchRun": "Run",
        "researchProperty": "Property",
        "researchValue": "Value",
        "playerOnline": "Online",
        "playerDisconnectedStatus": "Disconnected",
        "playerOffline": "Offline",
        "humanVsComputer": "Human Vs. Computer",
        "newGameTwoPlayers": "New Game 2 Players",
        "settings": "Settings",
        "help": "Help",
        "drawOffersNotVsEngine": "Draw offers are not available when playing against the engine.",
        "failedStartFromBookmark": "Failed to start game from bookmark.",
        "resignConfirm": "Resign?",
        "areYouSure": "Are you sure?",
        "gameOverOpponentFailedReconnectWinsClassic": "Game over — opponent failed to reconnect. {{winner}} wins.",
        "reconnectTimeoutNoMoves": "Reconnect timed out with no moves played.",
        "waitingOpponentRejoin": "Waiting for opponent to rejoin",
        "timeoutOneSec": "Timeout: 1 sec",
        "timeoutSecs": "Timeout: {{count}} sec",
        "whitePieceAlt": "White piece",
        "blackPieceAlt": "Black piece",
        "eraserTitle": "Eraser",
        "eraserAria": "Eraser – remove piece from square",
        "selectTitle": "Select",
        "selectAria": "Select – drag pieces to move them",
        "resetAria": "Reset – clear all pieces",
        "defaultPositionAria": "Default position – set up standard starting position",
        "loading": "Loading...",
        "engineLabel": "Engine"
    },
    "site": {
        "home": "Home",
        "search": "Search",
        "friends": "Friends",
        "groups": "Groups",
        "debug": "Debug",
        "account": "Account",
        "preferences": "Preferences",
        "administrate": "Administrate",
        "logOut": "Log out",
        "logIn": "Log in",
        "admin": "Admin",
        "homeAria": "Home",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "notice": "Notice",
        "ok": "OK",
        "username": "Username:",
        "password": "Password:",
        "login": "Login",
        "register": {
            "rookie": "Rookie",
            "skilled": "Skilled",
            "elite": "Elite",
            "grandMaster": "Grand Master"
        },
        "email": "Email:",
        "welcome": {
            "greeting": "Welcome Back",
            "tagline": "Your move awaits",
            "playNow": "Play Now!",
            "activeGames": "Active Games",
            "live": "Live",
            "showAll": "Show All",
            "viewAllActive": "View all active games",
            "mostRecent": "Most recent first",
            "noGamesNow": "No games at the moment",
            "myGames": "My Games",
            "viewAllGames": "View All Games",
            "recentCompleted": "Your recent completed games",
            "noCompleted": "No completed games yet",
            "activeGamesAria": "Active games",
            "inviteOnlineFriend": "Invite an online friend to play",
            "friendsPageTitle": "Friends page",
            "manageFriends": "Manage",
            "colFriend": "Friend",
            "colStatus": "Status",
            "findPlayers": "Find players",
            "waitingForResponse": "Waiting for response",
            "inviteSentSuffix": "(invite sent)",
            "sortByRowNumber": "Sort by row number",
            "sortBy": "Sort by {{key}}"
        },
        "gameList": {
            "date": "Date",
            "time": "Time",
            "result": "Result",
            "reason": "Reason",
            "type": "Type",
            "status": "Status",
            "event": "Event",
            "site": "Site",
            "round": "Round"
        },
        "loginPage": {
            "title": "Login"
        },
        "error": {
            "title": "Something went wrong",
            "body": "An error occurred.",
            "back": "Back to main"
        },
        "log": {
            "title": "Server log",
            "clear": "Clear view",
            "latest": "Latest",
            "waiting": "Waiting for server log output…"
        },
        "activeGames": {
            "moves": "Moves",
            "turn": "Turn",
            "status": "Status",
            "inProgress": "In progress",
            "onHold": "On hold",
            "vs": " vs ",
            "minutesAgo": "{{count}} minutes ago",
            "oneMinuteAgo": "1 minute ago",
            "justStarted": "Just started",
            "notStarted": "Not started",
            "startedTooltip": "Started: {{when}}",
            "playersVs": "{{white}} Vs. {{black}}"
        },
        "friendsPage": {
            "title": "Friends",
            "tagline": "Find new chess mates",
            "myFriends": "My friends",
            "noFriendsYet": "No friends yet",
            "findPlayers": "Find players",
            "searchByUsername": "Search by username",
            "searchPlaceholder": "Type to search…",
            "enterCharToSearch": "Enter at least one character to search",
            "noMatchingUsers": "No matching users",
            "playing": "Playing",
            "pendingFriendshipOffer": "Pending friendship offer",
            "joining": "Joining",
            "rejoin": "Rejoin",
            "friendRequest": "Friend request",
            "wantsToBeFriends": "(wants to be friends)",
            "pendingOfferSuffix": "(pending friendship offer)",
            "waitingFriendRespond": "Waiting for your friend to respond",
            "cancelBeforeRemove": "Cancel the game invite before removing this friend",
            "friendsTag": "Friends",
            "offerReceivedTag": "Offer received — see Your friends",
            "addFriend": "Add friend",
            "withdraw": "Withdraw",
            "requestFailed": "Request failed",
            "removeFriendConfirm": "Remove this friend from your list?",
            "removeFriendTitle": "Remove friend",
            "withdrawOfferConfirm": "Withdraw this friendship offer?",
            "withdrawOfferTitle": "Withdraw offer",
            "couldNotAccept": "Could not accept",
            "couldNotDecline": "Could not decline",
            "couldNotRemove": "Could not remove",
            "couldNotCancelInvite": "Could not cancel invite",
            "couldNotWithdraw": "Could not withdraw",
            "couldNotSendInvite": "Could not send invite",
            "couldNotSendGameInvite": "Could not send game invite",
            "gameInvite": "Game invite",
            "gameInvitationsAria": "Game invitations",
            "gameInvitationAria": "Game invitation",
            "chessInviteTitle": "Chess invite",
            "wantsToPlayAsBlack": "{{name}} wants to play. You play as Black.",
            "aFriend": "A friend",
            "youPlayAsWhite": "You play as White",
            "youPlayAsBlack": "You play as Black",
            "establishingGame": "Establishing game…",
            "yourOpponent": "Your opponent",
            "declinedYourInvite": "{{name}} declined your game invite.",
            "cancelInvite": "Cancel invite",
            "accept": "Accept",
            "decline": "Decline",
            "invite": "Invite",
            "remove": "Remove",
            "offerSent": "Offer sent",
            "pending": "Pending",
            "online": "Online",
            "offline": "Offline"
        },
        "adminPage": {
            "title": "Administration",
            "users": "Users",
            "generate": "Generate",
            "games": "Games",
            "engines": "Engines",
            "states": "States",
            "addUser": "Add user",
            "sectionsAria": "Admin sections",
            "openingBookLabel": "Opening book:",
            "gameLines": "game lines",
            "noGamesInDb": "No games in the database yet.",
            "gamesPaginationAria": "Games pagination",
            "colNum": "#",
            "colUsername": "Username",
            "colType": "Type",
            "colEmail": "Email",
            "colPassword": "Password",
            "colLevel": "Level",
            "colElo": "Elo",
            "colJoined": "Joined",
            "colLastLogin": "Last login",
            "colActiveGames": "Active games",
            "colFriends": "Friends",
            "colBookmarks": "Bookmarks",
            "colId": "Id",
            "colStatus": "Status",
            "colName": "Name",
            "colAvailable": "Available",
            "colNotes": "Notes",
            "colNote": "Note",
            "colAction": "Action",
            "emptyUsers": "No users yet.",
            "emptyData": "No data yet.",
            "emptyStates": "Use Generate to open the opening-book and state generation page.",
            "clickToEdit": "Click to edit",
            "updateFailed": "Update failed",
            "couldNotSave": "Could not save",
            "setPassword": "Set password",
            "setPasswordTitle": "Click to set a new password (4–30 characters)",
            "passwordLengthInvalid": "Password must be between 4 and 30 characters.",
            "invalidPassword": "Invalid password",
            "saved": "Saved",
            "newPasswordPlaceholder": "New password",
            "clickChangeUserType": "Click to change user type",
            "userTypeAria": "User type",
            "changeUserTypeTitle": "Change user type",
            "grantAdminConfirm": "Grant admin privileges to this user? They will be able to access admin tools and manage accounts.",
            "demoteAdminConfirm": "Change this user from Admin to {{type}}? They will lose access to the admin area.",
            "changeUserTypeConfirm": "Change this user to {{type}}?",
            "clickChangeLevel": "Click to change level",
            "playerLevelAria": "Player level",
            "sortByRowNumber": "Sort by row number",
            "sortBy": "Sort by {{key}}",
            "delete": "Delete",
            "first": "First",
            "last": "Last",
            "previous": "Previous",
            "next": "Next",
            "previous5Pages": "Previous 5 pages",
            "next5Pages": "Next 5 pages",
            "previous10Pages": "Previous 10 pages",
            "next10Pages": "Next 10 pages",
            "userTypeAdmin": "Admin",
            "userTypePartner": "Partner",
            "userTypeMember": "Member",
            "generateTitle": "Opening book & state generation",
            "backToAdmin": "← Back to admin",
            "generateIntro": "Replays all PGN files under the server’s games manager folder into either the State Mongo collection or the line-based opening book (data/opening-book-lines.txt). Choose a target, then press Start generation—nothing runs until you do.",
            "target": "Target",
            "targetMongo": "MongoDB — append rows to the State collection",
            "targetBook": "Line file — write opening book (opening-book-lines.txt)",
            "startGeneration": "Start generation",
            "stop": "Stop",
            "idle": "Idle.",
            "starting": "Starting…",
            "running": "Running ({{mode}})…",
            "readingFiles": "Reading {{count}} file(s)…",
            "replayingGames": "Replaying {{count}} games…",
            "writingOpeningBook": "Writing opening book…",
            "readingPgn": "Reading PGN {{index}} / {{total}} ({{games}} games)",
            "replayGameProgress": "Replay game {{current}} / {{total}} (completed ok: {{completed}})",
            "stopped": "Stopped.",
            "bookUnchanged": "Existing opening book was not modified.",
            "bookLinesInFile": "{{count}} game line(s) in {{file}}.",
            "cancelledBeforeRead": "Cancelled before reading PGNs.",
            "cancelledAfterRead": "Cancelled after read; replay was skipped (nothing written).",
            "mongoGamesSaved": "{{count}} game(s) had new state rows saved.",
            "doneBook": "Done. {{count}} game lines → {{file}}",
            "doneBookFileOnly": "Done. {{file}}",
            "doneMongo": "Done. MongoDB State collection updated{{detail}}.",
            "doneMongoDetail": " ({{count}} games replayed ok)",
            "errorPrefix": "Error: {{message}}",
            "unknownError": "Unknown",
            "connectionClosed": "Connection closed (check server logs or try again).",
            "openingBookDefault": "opening book"
        },
        "playNow": {
            "title": "New game",
            "startTitle": "Start a new Game",
            "playingColor": "Playing color",
            "timeMin": "Time (min)",
            "difficulty": "Difficulty (1–5)",
            "mousePreference": "Mouse preference",
            "drag": "Drag",
            "doubleClick": "Double click",
            "showAvailableMoves": "Show available moves",
            "private": "Private",
            "playComputer": "Play computer",
            "browseAll": "Browse all",
            "yourHistory": "Your history",
            "fullList": "Full list",
            "gameLibrary": "Game library",
            "openLibrarySearch": "Open library search",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Active games",
            "tagline": "All games in progress",
            "liveGames": "Live games",
            "game": "Game",
            "started": "Started"
        },
        "list": {
            "title": "All Games",
            "action": "Action"
        },
        "searchPage": {
            "title": "Search:",
            "button": "Search",
            "resultsFound": "{{count}} Results found:",
            "first": "First",
            "last": "Last",
            "previous": "Previous",
            "next": "Next",
            "previous5Pages": "Previous 5 pages",
            "next5Pages": "Next 5 pages",
            "previous10Pages": "Previous 10 pages",
            "next10Pages": "Next 10 pages"
        },
        "game": {
            "moves": "Moves",
            "white": "White",
            "black": "Black",
            "resign": "Resign",
            "draw": "Draw",
            "undo": "Undo",
            "flip": "Flip",
            "practice": "Practice"
        },
        "mobileWelcome": {
            "title": "Home — Chess",
            "play": "Play",
            "library": "Library",
            "friends": "Friends"
        },
        "mobileGame": {
            "title": "Game",
            "moves": "Moves",
            "resign": "Resign"
        }
    },
    "desktop": {
        "error": {
            "title": "Something went wrong",
            "body": "An error occurred.",
            "back": "Back to main"
        },
        "chrome": {
            "preferences": "Preferences",
            "display": "Display",
            "gameplay": "Gameplay",
            "pieceSet": "Piece set",
            "boardTheme": "Board theme",
            "themeBlue": "Blue",
            "themeDark": "Dark",
            "customizeTheme": "Customize theme…",
            "builtInThemesAria": "Built-in themes",
            "savedCustomThemesAria": "Saved custom themes",
            "pieceSetsAria": "Piece sets",
            "homeAria": "Shmerling Chess home"
        },
        "prefs": {
            "language": "Language",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "mouseControl": "Mouse control",
            "thinkingTime": "Thinking time",
            "thinkingTimeAria": "Thinking time in seconds",
            "immediateResign": "Immediate resign",
            "secondsOption": "{{count}}s",
            "enterFullScreen": "Enter full screen",
            "exitFullScreen": "Exit full screen",
            "fullScreenUnavailable": "Full screen is not available in this browser."
        },
        "gameRun": {
            "yourColor": "Your color",
            "engine": "Engine",
            "thinkTime": "Think time (seconds)",
            "thinkTimeAria": "Engine thinking time in seconds",
            "play": "Play",
            "nextMove": "Next move",
            "computer": "Computer",
            "computerColorHint": "Which color the computer plays — you play the other side"
        },
        "brainConfig": {
            "title": "Brain configuration",
            "save": "Save",
            "reset": "Reset",
            "saved": "Configuration saved",
            "failedSave": "Failed to save configuration",
            "brainLabel": "Brain",
            "loading": "Loading…",
            "failedLoad": "Failed to load brain config.",
            "discardSwitchConfirm": "Discard unsaved changes and switch brain version?",
            "discard": "Discard",
            "pieceScores": "Piece scores",
            "specialEvaluations": "Special evaluations",
            "gamePhase": "Game phase",
            "pawnFilesOpeningMid": "Pawn files (opening / mid)",
            "pawnFilesEndGame": "Pawn files (endgame)"
        },
        "customTheme": {
            "title": "Custom theme",
            "name": "Theme name",
            "save": "Save",
            "delete": "Delete",
            "saved": "Saved",
            "searchProperties": "Search properties",
            "filterPlaceholder": "Filter by property name…",
            "namePlaceholder": "My theme",
            "resetPreset": "Reset to current preset",
            "couldNotSave": "Could not save theme. Try again.",
            "untitled": "Untitled",
            "defaultName": "Custom theme"
        },
        "positionSetup": {
            "clearBoard": "Clear board",
            "startingPosition": "Starting position",
            "flipBoard": "Flip board",
            "eraser": "Eraser",
            "selectAndMove": "Select and move",
            "defaultStartingPosition": "Default starting position",
            "savePosition": "Save position",
            "saveAsNewPosition": "Save as new position",
            "validatePosition": "Validate position",
            "positionFlags": "Position flags",
            "turn": "Turn",
            "flagCheck": "Check",
            "flagCheckmate": "Checkmate",
            "flagDraw": "Draw",
            "flagWhiteKingMoved": "White king moved",
            "flagBlackKingMoved": "Black king moved",
            "flagWhiteKingsideRookMoved": "White kingside rook moved",
            "flagWhiteQueensideRookMoved": "White queenside rook moved",
            "flagBlackKingsideRookMoved": "Black kingside rook moved",
            "flagBlackQueensideRookMoved": "Black queenside rook moved"
        }
    },
    "mobile": {
        "drawOfferTitle": "Draw offer",
        "drawOfferMessage": "Opponent sent a draw offer. Accept?",
        "rematchTitle": "Rematch",
        "rematchMessage": "Opponent sent a rematch offer. Accept?",
        "gameId": "Game ID: {{id}}",
        "drawOfferAgree": "Opponent offered a draw, agree?",
        "rematchOfferAgree": "Opponent offered a rematch, agree?",
        "newGameWatchFromHome": "New game started — go to Home to watch."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = enExtra;
    } else {
        global.ShmerlingStringsEnExtra = enExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
