/**
 * English string catalog — single source for user-facing copy (i18n prep).
 * Add locale files (e.g. es.js) and register them in index.js when translating.
 */
(function (global) {
    "use strict";

    const en = {
        common: {
            white: "White",
            black: "Black",
            draw: "Draw",
            winner: "Winner",
            engine: "Engine",
            ok: "OK",
            cancel: "Cancel",
            confirm: "Confirm",
            yes: "Yes",
            no: "No",
            notice: "Notice",
            input: "Input",
            start: "Start",
            collapse: "Collapse",
            expand: "Expand",
            delete: "Delete",
            rename: "Rename",
            save: "Save",
            aPlayer: "A player",
            pleaseEnterValue: "Please enter a value.",
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Game actions",
                playersAndClocks: "Players and clocks",
                whitePlayerClock: "White player clock",
                blackPlayerClock: "Black player clock",
                startFromLoadedPosition: "Start game from loaded position",
                moves: "Moves",
                expandMovesPanel: "Expand moves panel",
                expandMoves: "Expand moves",
                collapseMovesPanel: "Collapse moves panel",
                reviewNavigation: "Review navigation",
                positionSetup: "Position setup",
                pieces: "Pieces",
                collapsePiecesPanel: "Collapse pieces panel",
                brainConfiguration: "Brain configuration",
                configuration: "Configuration",
                collapseConfigurationPanel: "Collapse configuration panel",
                games: "Games",
                expandGamesPanel: "Expand games panel",
                expandGames: "Expand games",
                expandGamesLocked: "Games panel unavailable during a game",
                collapseGamesPanel: "Collapse games panel",
                chat: "Chat",
                expandChatPanel: "Expand chat panel",
                collapseChatPanel: "Collapse chat panel",
                chatPlaceholder: "Type a message…",
                chatWatcherReadonly: "Spectators can read chat only",
                sendChat: "Send",
                savedListFilter: "Saved list filter",
                positions: "Positions",
                gameStatus: "Game status",
                capturedPieces: "Captured pieces",
            },
            sessionMode: {
                play: "Play Mode",
                positionSetup: "Position Setup",
                configuration: "Configuration mode",
                playback: "Playback Mode",
                review: "Review Mode",
                watch: "Watch Mode",
                practice: "Practice Mode",
            },
            status: {
                chooseNewGameOrSetup:
                    "Choose New game or Position setup from the sidebar",
                chooseNewGame: "Choose New game from the sidebar",
                setMoveColorEngineThinkTime:
                    "Set move, color, engine, and think time in the header, then press Play",
                gameOver: "Game over",
                sideResigned: "Game over. {{name}} resigns.",
                reviewMode: "Review mode",
                reviewResultDraw: "Result: Draw (1/2-1/2)",
                reviewResultResigned:
                    "Result: {{loser}} resigned — {{winner}} wins ({{score}})",
                reviewResultTimeout:
                    "Result: {{loser}} lost on time — {{winner}} wins ({{score}})",
                reviewResultCheckmate:
                    "Result: Checkmate — {{winner}} wins ({{score}})",
                reviewResultWin: "Result: {{winner}} wins ({{score}})",
                reviewResultGeneric: "Result: {{result}}",
                positionSavedAsBookmark: "Position saved as new bookmark",
                promotionFailed: "Promotion failed",
                couldNotLoadGame: "Could not load game",
                gameStarted: "Game started",
                invalidMove: "Invalid move",
                moveNotApplied: "Move could not be applied",
                noPendingPromotion: "No pending promotion",
                promotionUnavailable: "Promotion is not available",
                squareTotal: "Square total: {{score}}",
                opponent: "Opponent",
                gameInProgress: "Game in progress",
                boardLoading: "Board is still loading…",
                boardNotReady: "Board is not ready yet. Please wait and try again.",
                booting: "Loading Play…",
                loadingPreferences: "Loading preferences…",
                loadingBoard: "Preparing the board…",
                startingGame: "Starting game…",
                connectingToServer: "Connecting to server…",
                leaveOnlineBeforeConfiguration:
                    "Leave the online game before opening Configuration",
                configurationNotInPractice:
                    "Configuration is not available in Practice mode",
                configurationModeEdit:
                    "Configuration mode — edit values and save",
                selectSavedOrSetup:
                    "Select a saved game or set up a position on the board first",
                gameAlreadyInProgress: "A game is already in progress",
                yourMove: "Your move",
                engineToMove: "Engine to move…",
                leaveOnlineBeforePositionSetup:
                    "Leave the online game before opening Position Setup",
                positionSetupNotInPractice:
                    "Position Setup is not available in Practice mode",
                positionSetupPlacePieces:
                    "Position setup — place pieces on the board",
                drawWithReason: "Draw — {{reason}}",
                checkmateWins: "Checkmate — {{winner}} wins",
                check: "Check",
                waitBeforeEvaluate:
                    "Wait for the current move to finish before evaluating",
                evaluationUnavailable:
                    "Evaluation is not available. Restart the Shmerling Chess app.",
                evaluatingPosition: "Evaluating position…",
                evaluationFailed: "Evaluation failed",
                evaluationLine: "Evaluation ({{side}} to move): {{score}}",
                checkmate: "Checkmate",
                drawZero: "Draw (0)",
                totalLabel: "Total: {{value}}",
                openFolderDesktopOnly:
                    "Open folder is only available in the desktop app",
                couldNotOpenGamesLogFolder: "Could not open games log folder",
                positionValid: "Position is valid",
                playingFromCustomPosition: "Playing from custom position",
                nothingToSave: "Nothing to save",
                positionSaved: "Position saved",
                couldNotSavePosition: "Could not save position",
                savedPositionNotFound: "Saved position not found",
                positionUpdated: "Position updated",
                couldNotUpdatePosition: "Could not update position",
                nameCannotBeEmpty: "Name cannot be empty",
                gameRenamed: "Game renamed",
                couldNotRenameGame: "Could not rename game",
                deletedCount: "Deleted {{count}} item(s)",
                couldNotDeleteSelected: "Could not delete selected items",
                couldNotLoadSavedGame: "Could not load saved game",
                editingPositionSaveBookmark:
                    "Editing position — Save to update this bookmark",
                couldNotOpenPositionForEditing:
                    "Could not open position for editing",
                gameSaved: "Game saved",
                couldNotSaveGame: "Could not save game",
                engineMoveNotApplied: "Engine move could not be applied",
                engineCouldNotFindMove: "Engine could not find a move",
                engineError: "Engine error",
                engineThinking: "Engine thinking…",
                sessionError: "Session error",
                timesUpLost: "{{loser}} lost on time",
                drawOfferTitle: "Draw offer",
                drawOfferMessage: "Opponent sent a draw offer. Accept?",
                rematchTitle: "Rematch",
                playerDisconnectedWaiting:
                    "{{who}} disconnected — waiting for rejoin ({{countdown}})",
                opponentDisconnectedCountdown:
                    "Opponent disconnected — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "Game cancelled — Reconnect timed out with no moves played.",
                playerFailedToReconnectWins:
                    "{{loser}} failed to reconnect — {{winner}} wins",
                gameOverOpponentFailedReconnect:
                    "Game over — opponent failed to reconnect.",
                couldNotStartRematch: "Could not start rematch",
                rematchStarted: "Rematch started",
                gameCancelled: "Game cancelled",
                gameCancelledWithDetail: "Game cancelled — {{detail}}",
                gameCancelledOpponentLeftBeforeFirstMove:
                    "Game cancelled — Opponent left before the first move.",
                resignFailed: "Resign failed",
                gameResumedYourMove: "Game resumed — your move",
                practiceNotAvailable: "Practice mode is not available",
                couldNotJoinOnPlay: "Could not join this game on /play",
                practiceDebugNotAvailable:
                    "Practice / Debug is not available for this account",
                reviewRequiresWebApi: "Review requires the web API",
                couldNotLoadReviewGame: "Could not load review game",
                notReviewGameLink: "This link is not a review game",
                onlineRequiresWebApi: "Online play requires the web API",
                couldNotLoadOnlineGame: "Could not load online game",
                notOnlineGameOnPlay: "This link is not an online game on /play",
                watchingLiveGame: "Watching live game",
                waitingForOpponentToJoin: "Waiting for opponent to join…",
                waitingForOpponent: "Waiting for opponent…",
                onlineGameConnected: "Online game — connected",
                gameDeleted: "Game deleted",
                itemsDeleted: "{{count}} items deleted",
                choosePromotionPiece: "Choose promotion piece",
                invalidPromotionPiece: "Invalid promotion piece",
                drawOfferNotAvailable: "Draw offer is not available now",
            },
            drawReasons: {
                stalemate: "Stalemate",
                fiftyMoves: "50 moves",
                insufficientMaterial: "Insufficient material",
                threefoldRepetition: "Threefold repetition",
                drawOfferAccepted: "{{by}} player's draw offer accepted",
            },
            actions: {
                newGame: "New game",
                resign: "Resign",
                draw: "Draw",
                undo: "Undo",
                redo: "Redo",
                lastMove: "Last move",
                positionSetup: "Position setup",
                config: "Config",
                flip: "Flip",
                save: "Save",
                exit: "Exit",
                backToLobby: "Back to Lobby",
                loadToStart: "Load to start",
                editPosition: "Edit position",
                loadGame: "Load game",
                loadPosition: "Load position",
            },
            savedGames: {
                defaultName: "Saved game",
                defaultPositionName: "Saved position",
                itemsSelected: "{{count}} items selected",
                nameAriaLabel: "Saved game name",
                showDetails: "Show details",
                detailsAriaLabel: "Saved game details",
                editPosition: "Edit position",
                deleteSavedGame: "Delete saved game",
                renameSavedGame: "Rename saved game",
                noSavedPositions: "No saved positions yet.",
                noSavedGames: "No saved games yet.",
                nextMoveDash: "Next move: —",
                nextMove: "Next move: {{side}}",
                player: "Player",
                savedAt: "Saved: {{when}}",
                gameId: "Game ID: {{id}}",
                playersVs: "{{white}} vs. {{black}}",
                manualSaveName: "Saved — {{white}} vs. {{black}}",
                positionSaveName: "Position — {{when}}",
                loadFromStartHint: "(double-click to load from start)",
                nameWithDate: "{{name}} — {{when}}",
                nameWithDateLoadHint: "{{name}} — {{when}} (double-click to load from start)",
                nameLoadHint: "{{name}} (double-click to load from start)",
            },
            reviewNav: {
                start: "Start",
                back: "Back",
                play: "Play",
                pause: "Pause",
                forward: "Forward",
                end: "End",
            },
            newGameDialog: {
                title: "New game vs AI",
                yourColor: "Your color",
                engine: "Engine",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                stockfish: "Stockfish",
                timePerSideMinutes: "Time per side (minutes)",
                allowUndo: "Allow undo",
                private: "Private",
                privateHint:
                    "Private games are not shown on other members' Active Games lists.",
            },
            prompts: {
                positionName: "Position name",
                savePositionAs: "Save position as",
            },
            dialogs: {
                resignTitle: "Resign this game?",
                resignBody: "You will lose the game.",
                leaveTitle: "Leave game?",
                leaveBody: "Your game will be resigned.",
                areYouSure: "Are you sure?",
                discardUnsavedBrainConfig:
                    "Discard unsaved brain configuration changes?",
                accept: "Accept",
                decline: "Decline",
                saveAs: "Save As",
                savePosition: "Save position",
                invalidPosition: "Invalid position",
                rematchChooseColor: "Choose your color for the rematch:",
                rematchOfferAgree: "Opponent offered a rematch. Agree?",
                rematchOfferAgreeWithTime:
                    "Opponent offered a rematch ({{minutes}} min per side). Agree?",
                rematchColorPreference:
                    "Opponent wants to play as {{offerer}}. You would play as {{you}}. Agree?",
                rematchColorPreferenceWithTime:
                    "Opponent wants to play as {{offerer}} ({{minutes}} min per side). You would play as {{you}}. Agree?",
            },
        },
        session: {
            engineThinking: "Engine thinking…",
            engineCouldNotFindMove: "Engine could not find a move",
            engineError: "Engine error",
            positionSetupPlacePieces: "Position setup — place pieces on the board",
            configurationModeEdit: "Configuration mode — edit values and save",
            practiceBothSides: "Practice — both sides",
            opponentDisconnected: "Opponent disconnected",
            opponentRejoined: "Opponent rejoined",
            playerRejoined: "{{name}} rejoined",
            drawOfferSent: "Draw offer sent",
            drawOfferDeclined: "Draw offer declined",
            rematchOfferSent: "Rematch offer sent",
            rematchOfferDeclined: "Rematch offer declined",
            rematchUnavailable: "Opponent is no longer available for a rematch",
            drawAgreed: "Draw agreed",
            rematchAcceptedNoGameId: "Rematch accepted but no new game id",
            rematchOfferAccepted: "Rematch offer accepted",
            gameOver: "Game over",
            somethingWentWrong: "Something went wrong",
            opponentResigned: "Opponent resigned",
            opponentLeftGame: "Opponent left the game",
            opponentFailedToReconnect: "Opponent failed to reconnect",
            gameCancelled: "Game cancelled",
            gameCancelledWithDetail: "Game cancelled — {{detail}}",
            gameCancelledOpponentLeftBeforeFirstMove:
                "Game cancelled — Opponent left before the first move.",
            gameCancelledReconnectTimeout:
                "Game cancelled — Reconnect timed out with no moves played.",
            waitingForOpponent: "Waiting for opponent…",
            couldNotResolveWebSocketUrl: "Could not resolve WebSocket URL",
            opponentJoined: "{{name}} joined",
            opponentDefault: "Opponent",
            connectionError: "Connection error",
            connectionLost: "Connection lost — moves are not reaching the server",
            reconnecting: "Reconnecting…",
            connectionRestored: "Connection restored",
            flagReported: "Flag — confirming with server…",
            playerDisconnectedWaitingRejoin:
                "{{name}} disconnected — waiting for rejoin",
            playerFailedToReconnectWins:
                "{{loser}} failed to reconnect — {{winner}} wins",
            watcherWaitingForReconnect: "Waiting for a player to reconnect…",
        },
        site: {
            confirm: "Confirm",
            cancel: "Cancel",
            notice: "Notice",
            ok: "OK",
            home: "Home",
            search: "Search",
            friends: "Friends",
            groups: "Groups",
            debug: "Debug",
            account: "Account",
            preferences: "Preferences",
            administrate: "Administrate",
            logOut: "Log out",
            logIn: "Log in",
            admin: "Admin",
            homeAria: "Home",
        },
        validation: {
            validEmail: "Please fill in a valid email",
            passwordsMustMatch: "Please ensure Password fields are identical.",
            chooseUsername: "Please choose a username",
            usernameNotAvailable: "This username is not available",
            passwordNoWhitespace: "Password must not contain Whitespaces.",
            passwordUppercase: "Password must have at least one Uppercase Character.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = en;
    } else {
        global.ShmerlingStringsEn = en;
    }
})(typeof window !== "undefined" ? window : globalThis);
