(function (global) {
    "use strict";
    const esExtra = {
    "validation": {
        "passwordLowercase": "La contraseña debe tener al menos una letra minúscula.",
        "passwordDigit": "La contraseña debe contener al menos un dígito.",
        "passwordSymbol": "La contraseña debe contener al menos un símbolo especial.",
        "passwordLength": "La contraseña debe tener entre 8 y 30 caracteres.",
        "noHtml": "{{label}} no debe incluir HTML.",
        "position": {
            "headerSave": "No se puede guardar esta posición:\n\n",
            "headerPlay": "No se puede jugar desde esta posición:\n\n",
            "headerUse": "No se puede usar esta posición:\n\n",
            "headerSaveBookmark": "No se puede guardar este marcador:\n\n",
            "headerAddBookmark": "No se puede añadir este marcador:\n\n",
            "boardUnreadable": "No se pudo leer el tablero. Inténtalo de nuevo cuando el tablero haya cargado.",
            "whiteKingNone": "Debe haber exactamente un rey blanco en el tablero. No se encontró ninguno.",
            "whiteKingCount": "Debe haber exactamente un rey blanco en el tablero. Se encontraron {{count}} reyes blancos.",
            "blackKingNone": "Debe haber exactamente un rey negro en el tablero. No se encontró ninguno.",
            "blackKingCount": "Debe haber exactamente un rey negro en el tablero. Se encontraron {{count}} reyes negros.",
            "kingsAdjacent": "Los dos reyes no pueden estar en casillas adyacentes (incluido en diagonal).",
            "sideInCheck": "Juegan {{mover}}, pero el rey de {{king}} ya está en jaque. El bando al movimiento no puede dar jaque — cambia el turno o mueve piezas.",
            "drawInsufficientKings": "Esta posición es tablas por material insuficiente (rey contra rey). Añade piezas para que el jaque mate siga siendo posible.",
            "drawInsufficientMinor": "Esta posición es tablas por material insuficiente (rey y alfil o caballo contra rey solo). Añade piezas para que el jaque mate siga siendo posible.",
            "drawBishopsSameColor": "Esta posición es tablas por material insuficiente (alfil contra alfil del mismo color de casilla). Añade piezas para que el jaque mate siga siendo posible.",
            "tooManyQueens": "{{color}} tiene {{count}} damas; el máximo es 9 por color.",
            "tooManyRooks": "{{color}} tiene {{count}} torres; el máximo es 10 por color.",
            "tooManyBishops": "{{color}} tiene {{count}} alfiles; el máximo es 10 por color.",
            "tooManyKnights": "{{color}} tiene {{count}} caballos; el máximo es 10 por color.",
            "tooManyPawns": "{{color}} tiene {{count}} peones; el máximo es 8 por color."
        }
    },
    "auth": {
        "whoAreYou": "¿Quién eres?",
        "enterPassword": "Introduce tu contraseña",
        "sorry": "Lo sentimos",
        "continue": "Continuar",
        "usernameField": "Nombre de usuario",
        "passwordField": "Contraseña",
        "wrongCredentials": "Nombre de usuario o contraseña incorrectos",
        "userAdded": "Usuario añadido correctamente",
        "couldNotSaveBookmark": "No se pudo guardar el marcador",
        "invalidUserId": "ID de usuario no válido",
        "generationJobRunning": "Ya hay otra tarea de generación en curso…",
        "listingPgnFiles": "Listando archivos PGN…"
    },
    "classic": {
        "loadGame": "Cargar partida",
        "load": "Cargar",
        "enterGameState": "Pega aquí el estado de la partida...",
        "rematch": "Revancha",
        "drawOffer": "Oferta de tablas",
        "lastMove": "Última jugada",
        "bookmarks": "Marcadores",
        "bookmarkAlertTitle": "Marcar posición",
        "promotion": "¡Promoción!",
        "check": "Jaque",
        "checkmateWins": "¡Jaque mate! ¡Ganan las {{winner}}!",
        "drawReason": "¡Tablas! {{reason}}",
        "opponentDisconnected": "El oponente se desconectó",
        "opponentResignedWins": "El oponente se rindió, ganan las {{winner}}",
        "somethingWentWrong": "Algo salió mal",
        "playerRejoined": "{{name}} se reconectó",
        "aPlayerRejoined": "Un jugador se reconectó",
        "opponentRejoined": "El oponente se reconectó",
        "rematchOfferAccepted": "Oferta de revancha aceptada",
        "rematchOfferDeclined": "Oferta de revancha rechazada",
        "sideOffersDraw": "{{side}} ofrece tablas",
        "drawOfferDeclined": "Oferta de tablas rechazada",
        "watcherWatching": "{{name}} está observando la partida",
        "drawOfferSent": "Oferta de tablas enviada",
        "rematchOfferSent": "Oferta de revancha enviada",
        "newGameStarted": "Nueva partida iniciada",
        "gameOver": "Partida terminada",
        "gameCancelled": "Partida cancelada",
        "youResignedWins": "Te rendiste, ganan las {{winner}}",
        "movesCopied": "¡Jugadas copiadas al portapapeles!",
        "failedCopyMoves": "Error al copiar las jugadas",
        "failedLoadBrainConfig": "Error al cargar la configuración del motor.",
        "failedSaveBrainConfig": "Error al guardar la configuración del motor.",
        "offerDrawConfirm": "¿Ofrecer tablas?",
        "drawOfferAccept": "El oponente envió una oferta de tablas, ¿aceptar?",
        "rematchOfferAccept": "El oponente ofreció una revancha, ¿aceptar?",
        "confirmExitGame": "¿Seguro que quieres salir de la partida?",
        "mobileResign": "Rendirse",
        "mobileRematch": "Revancha",
        "mobileDraw": "Tablas",
        "mobileFlip": "Girar",
        "mobileLastMove": "Última jugada",
        "mobileMovesList": "Lista de jugadas",
        "researchToolbox": "Caja de herramientas",
        "researchBrainConfig": "Config. del motor",
        "researchSave": "Guardar",
        "researchDiscard": "Descartar",
        "researchEditMode": "modo edición",
        "researchRun": "Ejecutar",
        "researchProperty": "Propiedad",
        "researchValue": "Valor",
        "playerOnline": "En línea",
        "playerDisconnectedStatus": "Desconectado",
        "playerOffline": "Desconectado",
        "humanVsComputer": "Humano vs. ordenador",
        "newGameTwoPlayers": "Nueva partida 2 jugadores",
        "settings": "Ajustes",
        "help": "Ayuda",
        "drawOffersNotVsEngine": "Las ofertas de tablas no están disponibles al jugar contra el motor.",
        "failedStartFromBookmark": "Error al iniciar la partida desde el marcador.",
        "resignConfirm": "¿Rendirse?",
        "areYouSure": "¿Estás seguro?",
        "gameOverOpponentFailedReconnectWinsClassic": "Partida terminada — el oponente no pudo reconectarse. Ganan las {{winner}}.",
        "reconnectTimeoutNoMoves": "Tiempo de reconexión agotado sin jugadas realizadas.",
        "waitingOpponentRejoin": "Esperando a que el oponente se reconecte",
        "timeoutOneSec": "Tiempo límite: 1 s",
        "timeoutSecs": "Tiempo límite: {{count}} s",
        "whitePieceAlt": "Pieza blanca",
        "blackPieceAlt": "Pieza negra",
        "eraserTitle": "Borrador",
        "eraserAria": "Borrador – quitar pieza de la casilla",
        "selectTitle": "Seleccionar",
        "selectAria": "Seleccionar – arrastra piezas para moverlas",
        "resetAria": "Restablecer – quitar todas las piezas",
        "defaultPositionAria": "Posición inicial – configurar la posición de inicio estándar",
        "loading": "Cargando...",
        "engineLabel": "Motor"
    },
    "site": {
        "home": "Inicio",
        "search": "Buscar",
        "friends": "Amigos",
        "groups": "Grupos",
        "debug": "Depuración",
        "account": "Cuenta",
        "preferences": "Preferencias",
        "administrate": "Administrar",
        "logOut": "Cerrar sesión",
        "logIn": "Iniciar sesión",
        "admin": "Admin",
        "homeAria": "Inicio",
        "confirm": "Confirmar",
        "cancel": "Cancelar",
        "notice": "Aviso",
        "ok": "Aceptar",
        "footer": {
            "logoAlt": "Shmerling Chess",
            "navAria": "Pie de página",
            "privacy": "Política de privacidad",
            "terms": "Términos de uso",
            "contact": "Contacto",
            "copyright": "© {{year}} Shmerling Chess. Todos los derechos reservados.",
            "lastUpdated": "Última actualización: {{date}}",
            "privacyTitle": "Política de privacidad",
            "privacyLead": "Cómo Shmerling Chess trata la información de cuenta y de juego.",
            "privacyBody": "Usamos los datos de tu cuenta para operar el servicio, guardar partidas y preferencias, y mejorar el producto. No vendemos información personal. El texto completo de la política se publicará aquí.",
            "termsTitle": "Términos de uso",
            "termsLead": "Las reglas para usar Shmerling Chess.",
            "termsBody": "Al usar Shmerling Chess aceptas jugar con fair play, respetar a otros jugadores y usar el servicio solo para ajedrez personal. Los términos completos se publicarán aquí.",
            "contactTitle": "Contacto",
            "contactLead": "Ponte en contacto con el equipo de Shmerling Chess.",
            "contactBody": "Los datos de contacto para soporte y privacidad se publicarán aquí."
        },
        "username": "Nombre de usuario:",
        "password": "Contraseña:",
        "login": "Iniciar sesión",
        "register": {
            "submit": "Registrarse",
            "confirmPassword": "Confirmar contraseña:",
            "playerLevel": "Nivel del jugador:",
            "rookie": "Principiante",
            "skilled": "Hábil",
            "elite": "Élite",
            "grandMaster": "Gran maestro"
        },
        "email": "Correo electrónico:",
        "welcome": {
            "greeting": "Bienvenido de nuevo",
            "tagline": "Tu jugada te espera",
            "playNow": "¡Jugar ahora!",
            "activeGames": "Partidas activas",
            "live": "En directo",
            "showAll": "Mostrar todo",
            "viewAllActive": "Ver todas las partidas activas",
            "mostRecent": "Más recientes primero",
            "noGamesNow": "No hay partidas en este momento",
            "myGames": "Mis partidas",
            "viewAllGames": "Ver todas las partidas",
            "recentCompleted": "Tus partidas recientes finalizadas",
            "noCompleted": "Aún no hay partidas finalizadas",
            "activeGamesAria": "Partidas activas",
            "inviteOnlineFriend": "Invita a un amigo en línea a jugar",
            "friendsPageTitle": "Página de amigos",
            "manageFriends": "Gestionar",
            "colFriend": "Amigo",
            "colStatus": "Estado",
            "findPlayers": "Buscar jugadores",
            "waitingForResponse": "Esperando respuesta",
            "inviteSentSuffix": "(invitación enviada)",
            "sortByRowNumber": "Ordenar por número de fila",
            "sortBy": "Ordenar por {{key}}"
        },
        "gameList": {
            "date": "Fecha",
            "time": "Hora",
            "result": "Resultado",
            "reason": "Motivo",
            "type": "Tipo",
            "status": "Estado",
            "event": "Evento",
            "site": "Sitio",
            "round": "Ronda"
        },
        "loginPage": {
            "title": "Iniciar sesión"
        },
        "error": {
            "title": "Algo salió mal",
            "body": "Se produjo un error.",
            "back": "Volver al inicio"
        },
        "log": {
            "title": "Registro del servidor",
            "clear": "Limpiar vista",
            "latest": "Más reciente",
            "waiting": "Esperando la salida del registro del servidor…"
        },
        "activeGames": {
            "moves": "Jugadas",
            "turn": "Turno",
            "status": "Estado",
            "inProgress": "En curso",
            "onHold": "En pausa",
            "vs": " vs ",
            "minutesAgo": "Hace {{count}} minutos",
            "oneMinuteAgo": "Hace 1 minuto",
            "justStarted": "Recién iniciada",
            "notStarted": "No iniciada",
            "startedTooltip": "Iniciada: {{when}}",
            "playersVs": "{{white}} vs. {{black}}"
        },
        "friendsPage": {
            "title": "Amigos",
            "tagline": "Encuentra nuevos compañeros de ajedrez",
            "myFriends": "Mis amigos",
            "noFriendsYet": "Aún no tienes amigos",
            "findPlayers": "Buscar jugadores",
            "searchByUsername": "Buscar por nombre de usuario",
            "searchPlaceholder": "Escribe para buscar…",
            "enterCharToSearch": "Introduce al menos un carácter para buscar",
            "noMatchingUsers": "No hay usuarios coincidentes",
            "playing": "Jugando",
            "pendingFriendshipOffer": "Solicitud de amistad pendiente",
            "joining": "Uniéndose",
            "rejoin": "Reconectarse",
            "friendRequest": "Solicitud de amistad",
            "wantsToBeFriends": "(quiere ser tu amigo)",
            "pendingOfferSuffix": "(solicitud de amistad pendiente)",
            "waitingFriendRespond": "Esperando la respuesta de tu amigo",
            "cancelBeforeRemove": "Cancela la invitación a partida antes de eliminar a este amigo",
            "friendsTag": "Amigos",
            "offerReceivedTag": "Oferta recibida — ver Tus amigos",
            "addFriend": "Añadir amigo",
            "withdraw": "Retirar",
            "requestFailed": "Error en la solicitud",
            "removeFriendConfirm": "¿Eliminar a este amigo de tu lista?",
            "removeFriendTitle": "Eliminar amigo",
            "withdrawOfferConfirm": "¿Retirar esta solicitud de amistad?",
            "withdrawOfferTitle": "Retirar solicitud",
            "couldNotAccept": "No se pudo aceptar",
            "couldNotDecline": "No se pudo rechazar",
            "couldNotRemove": "No se pudo eliminar",
            "couldNotCancelInvite": "No se pudo cancelar la invitación",
            "couldNotWithdraw": "No se pudo retirar",
            "couldNotSendInvite": "No se pudo enviar la invitación",
            "couldNotSendGameInvite": "No se pudo enviar la invitación a partida",
            "gameInvite": "Invitación a partida",
            "gameInvitationsAria": "Invitaciones a partida",
            "gameInvitationAria": "Invitación a partida",
            "chessInviteTitle": "Invitación de ajedrez",
            "wantsToPlayAsBlack": "{{name}} quiere jugar. Tú juegas con negras.",
            "aFriend": "Un amigo",
            "youPlayAsWhite": "Juegas con blancas",
            "youPlayAsBlack": "Juegas con negras",
            "establishingGame": "Estableciendo partida…",
            "yourOpponent": "Tu oponente",
            "declinedYourInvite": "{{name}} rechazó tu invitación a partida.",
            "cancelInvite": "Cancelar invitación",
            "accept": "Aceptar",
            "decline": "Rechazar",
            "invite": "Invitar",
            "remove": "Eliminar",
            "offerSent": "Oferta enviada",
            "pending": "Pendiente",
            "online": "En línea",
            "offline": "Desconectado"
        },
        "adminPage": {
            "title": "Administración",
            "users": "Usuarios",
            "generate": "Generar",
            "games": "Partidas",
            "engines": "Motores",
            "states": "Estados",
            "addUser": "Añadir usuario",
            "sectionsAria": "Secciones de administración",
            "openingBookLabel": "Libro de aperturas:",
            "gameLines": "líneas de partida",
            "noGamesInDb": "Aún no hay partidas en la base de datos.",
            "gamesPaginationAria": "Paginación de partidas",
            "colNum": "#",
            "colUsername": "Nombre de usuario",
            "colType": "Tipo",
            "colEmail": "Correo electrónico",
            "colPassword": "Contraseña",
            "colLevel": "Nivel",
            "colElo": "Elo",
            "colJoined": "Registro",
            "colLastLogin": "Último acceso",
            "colActiveGames": "Partidas activas",
            "colFriends": "Amigos",
            "colBookmarks": "Marcadores",
            "colId": "Id",
            "colStatus": "Estado",
            "colName": "Nombre",
            "colAvailable": "Disponible",
            "colNotes": "Notas",
            "colNote": "Nota",
            "colAction": "Acción",
            "emptyUsers": "Aún no hay usuarios.",
            "emptyData": "Aún no hay datos.",
            "emptyStates": "Usa Generar para abrir la página de generación del libro de aperturas y estados.",
            "clickToEdit": "Clic para editar",
            "updateFailed": "Error al actualizar",
            "couldNotSave": "No se pudo guardar",
            "setPassword": "Establecer contraseña",
            "setPasswordTitle": "Clic para establecer una nueva contraseña (4–30 caracteres)",
            "passwordLengthInvalid": "La contraseña debe tener entre 4 y 30 caracteres.",
            "invalidPassword": "Contraseña no válida",
            "saved": "Guardado",
            "newPasswordPlaceholder": "Nueva contraseña",
            "clickChangeUserType": "Clic para cambiar el tipo de usuario",
            "userTypeAria": "Tipo de usuario",
            "changeUserTypeTitle": "Cambiar tipo de usuario",
            "grantAdminConfirm": "¿Conceder privilegios de administrador a este usuario? Podrá acceder a las herramientas de administración y gestionar cuentas.",
            "demoteAdminConfirm": "¿Cambiar este usuario de Admin a {{type}}? Perderá el acceso al área de administración.",
            "changeUserTypeConfirm": "¿Cambiar este usuario a {{type}}?",
            "clickChangeLevel": "Clic para cambiar el nivel",
            "playerLevelAria": "Nivel del jugador",
            "sortByRowNumber": "Ordenar por número de fila",
            "sortBy": "Ordenar por {{key}}",
            "delete": "Eliminar",
            "first": "Primero",
            "last": "Último",
            "previous": "Anterior",
            "next": "Siguiente",
            "previous5Pages": "5 páginas anteriores",
            "next5Pages": "5 páginas siguientes",
            "previous10Pages": "10 páginas anteriores",
            "next10Pages": "10 páginas siguientes",
            "userTypeAdmin": "Admin",
            "userTypePartner": "Socio",
            "userTypeMember": "Miembro",
            "generateTitle": "Generación de libro de aperturas y estados",
            "backToAdmin": "← Volver a administración",
            "generateIntro": "Reproduce todos los archivos PGN de la carpeta del gestor de partidas del servidor en la colección State de MongoDB o en el libro de aperturas basado en líneas (data/opening-book-lines.txt). Elige un destino y pulsa Iniciar generación; no se ejecuta nada hasta que lo hagas.",
            "target": "Destino",
            "targetMongo": "MongoDB — añadir filas a la colección State",
            "targetBook": "Archivo de líneas — escribir libro de aperturas (opening-book-lines.txt)",
            "startGeneration": "Iniciar generación",
            "stop": "Detener",
            "idle": "Inactivo.",
            "starting": "Iniciando…",
            "running": "En ejecución ({{mode}})…",
            "readingFiles": "Leyendo {{count}} archivo(s)…",
            "replayingGames": "Reproduciendo {{count}} partida(s)…",
            "writingOpeningBook": "Escribiendo libro de aperturas…",
            "readingPgn": "Leyendo PGN {{index}} / {{total}} ({{games}} partidas)",
            "replayGameProgress": "Reproduciendo partida {{current}} / {{total}} (completadas ok: {{completed}})",
            "stopped": "Detenido.",
            "bookUnchanged": "El libro de aperturas existente no se modificó.",
            "bookLinesInFile": "{{count}} línea(s) de partida en {{file}}.",
            "cancelledBeforeRead": "Cancelado antes de leer los PGN.",
            "cancelledAfterRead": "Cancelado tras la lectura; se omitió la reproducción (no se escribió nada).",
            "mongoGamesSaved": "Se guardaron nuevas filas de estado en {{count}} partida(s).",
            "doneBook": "Listo. {{count}} líneas de partida → {{file}}",
            "doneBookFileOnly": "Listo. {{file}}",
            "doneMongo": "Listo. Colección State de MongoDB actualizada{{detail}}.",
            "doneMongoDetail": " ({{count}} partidas reproducidas correctamente)",
            "errorPrefix": "Error: {{message}}",
            "unknownError": "Desconocido",
            "connectionClosed": "Conexión cerrada (revisa los registros del servidor o inténtalo de nuevo).",
            "openingBookDefault": "libro de aperturas"
        },
        "playNow": {
            "title": "Nueva partida",
            "startTitle": "Iniciar una nueva partida",
            "playingColor": "Color de juego",
            "timeMin": "Tiempo (min)",
            "difficulty": "Dificultad (1–5)",
            "mousePreference": "Preferencia del ratón",
            "drag": "Arrastrar",
            "doubleClick": "Doble clic",
            "showAvailableMoves": "Mostrar jugadas disponibles",
            "private": "Privada",
            "privateHint": "Las partidas privadas no se muestran en las listas de partidas activas de otros miembros.",
            "playComputer": "Jugar contra el ordenador",
            "browseAll": "Ver todo",
            "yourHistory": "Tu historial",
            "fullList": "Lista completa",
            "gameLibrary": "Biblioteca de partidas",
            "openLibrarySearch": "Abrir búsqueda en la biblioteca",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Partidas activas",
            "tagline": "Todas las partidas en curso",
            "liveGames": "Partidas en directo",
            "game": "Partida",
            "started": "Iniciada"
        },
        "list": {
            "title": "Todas las partidas",
            "action": "Acción"
        },
        "searchPage": {
            "title": "Buscar:",
            "tagline": "Encuentra partidas en el archivo PGN",
            "results": "Resultados",
            "resultsCount": "{{count}} resultados",
            "noResults": "Ninguna partida coincide con tu búsqueda",
            "button": "Buscar",
            "resultsFound": "{{count}} resultados encontrados:",
            "first": "Primero",
            "last": "Último",
            "previous": "Anterior",
            "next": "Siguiente",
            "previous5Pages": "5 páginas anteriores",
            "next5Pages": "5 páginas siguientes",
            "previous10Pages": "10 páginas anteriores",
            "next10Pages": "10 páginas siguientes"
        },
        "game": {
            "moves": "Jugadas",
            "white": "Blancas",
            "black": "Negras",
            "resign": "Rendirse",
            "draw": "Tablas",
            "undo": "Deshacer",
            "flip": "Girar",
            "practice": "Práctica"
        },
        "mobileWelcome": {
            "title": "Inicio — Ajedrez",
            "play": "Jugar",
            "library": "Biblioteca",
            "friends": "Amigos"
        },
        "mobileGame": {
            "title": "Partida",
            "moves": "Jugadas",
            "resign": "Rendirse"
        }
    },
    "desktop": {
        "error": {
            "title": "Algo salió mal",
            "body": "Se produjo un error.",
            "back": "Volver al inicio"
        },
        "chrome": {
            "preferences": "Preferencias",
            "closePreferences": "Cerrar preferencias",
            "display": "Pantalla",
            "gameplay": "Jugabilidad",
            "pieceSet": "Set de piezas",
            "boardTheme": "Tema del tablero",
            "themeBlue": "Azul",
            "themeDark": "Oscuro",
            "customizeTheme": "Personalizar tema…",
            "builtInThemesAria": "Temas integrados",
            "savedCustomThemesAria": "Temas personalizados guardados",
            "pieceSetsAria": "Sets de piezas",
            "homeAria": "Inicio de Shmerling Chess"
        },
        "prefs": {
            "language": "Idioma",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "Control del ratón",
            "thinkingTime": "Tiempo de reflexión",
            "thinkingTimeAria": "Tiempo de reflexión en segundos",
            "immediateResign": "Rendición inmediata",
            "secondsOption": "{{count}} s",
            "enterFullScreen": "Pantalla completa",
            "exitFullScreen": "Salir de pantalla completa",
            "fullScreenUnavailable": "La pantalla completa no está disponible en este navegador."
        },
        "gameRun": {
            "yourColor": "Tu color",
            "engine": "Motor",
            "thinkTime": "Tiempo de reflexión (segundos)",
            "thinkTimeAria": "Tiempo de reflexión del motor en segundos",
            "play": "Jugar",
            "nextMove": "Siguiente jugada",
            "computer": "Ordenador",
            "computerColorHint": "Color que juega el ordenador — tú juegas el otro bando"
        },
        "brainConfig": {
            "title": "Configuración del motor",
            "save": "Guardar",
            "reset": "Restablecer",
            "saved": "Configuración guardada",
            "failedSave": "Error al guardar la configuración",
            "brainLabel": "Motor",
            "loading": "Cargando…",
            "failedLoad": "Error al cargar la configuración del motor.",
            "discardSwitchConfirm": "¿Descartar los cambios no guardados y cambiar la versión del motor?",
            "discard": "Descartar",
            "pieceScores": "Puntuación de piezas",
            "specialEvaluations": "Evaluaciones especiales",
            "gamePhase": "Fase de la partida",
            "pawnFilesOpeningMid": "Columnas de peones (apertura / medio juego)",
            "pawnFilesEndGame": "Columnas de peones (final)"
        },
        "customTheme": {
            "title": "Tema personalizado",
            "name": "Nombre del tema",
            "save": "Guardar",
            "delete": "Eliminar",
            "saved": "Guardado",
            "searchProperties": "Buscar propiedades",
            "filterPlaceholder": "Filtrar por nombre de propiedad…",
            "namePlaceholder": "Mi tema",
            "resetPreset": "Restablecer al preset actual",
            "couldNotSave": "No se pudo guardar el tema. Inténtalo de nuevo.",
            "untitled": "Sin título",
            "defaultName": "Tema personalizado"
        },
        "positionSetup": {
            "clearBoard": "Limpiar tablero",
            "startingPosition": "Posición inicial",
            "flipBoard": "Girar tablero",
            "eraser": "Borrador",
            "selectAndMove": "Seleccionar y mover",
            "defaultStartingPosition": "Posición inicial predeterminada",
            "savePosition": "Guardar posición",
            "saveAsNewPosition": "Guardar como nueva posición",
            "validatePosition": "Validar posición",
            "positionFlags": "Indicadores de posición",
            "turn": "Turno",
            "flagCheck": "Jaque",
            "flagCheckmate": "Jaque mate",
            "flagDraw": "Tablas",
            "flagWhiteKingMoved": "Rey blanco movido",
            "flagBlackKingMoved": "Rey negro movido",
            "flagWhiteKingsideRookMoved": "Torre de enroque corto blanca movida",
            "flagWhiteQueensideRookMoved": "Torre de enroque largo blanca movida",
            "flagBlackKingsideRookMoved": "Torre de enroque corto negra movida",
            "flagBlackQueensideRookMoved": "Torre de enroque largo negra movida"
        }
    },
    "errorPage": {
        "code": "Error {{code}}",
        "notFoundTitle": "Página no encontrada",
        "notFoundMessage": "La página que buscas no existe.",
        "genericTitle": "Algo salió mal",
        "genericMessage": "Ocurrió un error inesperado. Inténtalo de nuevo.",
        "backHome": "Volver al inicio"
    },
    "mobile": {
        "drawOfferTitle": "Oferta de tablas",
        "drawOfferMessage": "El oponente envió una oferta de tablas. ¿Aceptar?",
        "rematchTitle": "Revancha",
        "rematchMessage": "El oponente envió una oferta de revancha. ¿Aceptar?",
        "gameId": "ID de partida: {{id}}",
        "drawOfferAgree": "El oponente ofreció tablas, ¿aceptar?",
        "rematchOfferAgree": "El oponente ofreció una revancha, ¿aceptar?",
        "newGameWatchFromHome": "Nueva partida iniciada — ve a Inicio para observar."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = esExtra;
    } else {
        global.ShmerlingStringsEsExtra = esExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
