/**
 * Spanish string catalog — mirrors src/strings/en.js structure with Spanish values.
 */
(function (global) {
    "use strict";

    const es = {
        common: {
            white: "Blancas",
            black: "Negras",
            draw: "Tablas",
            winner: "Ganador",
            engine: "Motor",
            ok: "Aceptar",
            cancel: "Cancelar",
            confirm: "Confirmar",
            yes: "Sí",
            no: "No",
            notice: "Aviso",
            input: "Entrada",
            start: "Iniciar",
            collapse: "Contraer",
            expand: "Expandir",
            delete: "Eliminar",
            rename: "Renombrar",
            save: "Guardar",
            aPlayer: "Un jugador",
            pleaseEnterValue: "Introduce un valor.",
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Acciones de partida",
                playersAndClocks: "Jugadores y relojes",
                whitePlayerClock: "Reloj de las blancas",
                blackPlayerClock: "Reloj de las negras",
                startFromLoadedPosition: "Iniciar partida desde la posición cargada",
                moves: "Jugadas",
                expandMovesPanel: "Expandir panel de jugadas",
                expandMoves: "Expandir jugadas",
                collapseMovesPanel: "Contraer panel de jugadas",
                reviewNavigation: "Navegación de revisión",
                positionSetup: "Configuración de posición",
                pieces: "Piezas",
                collapsePiecesPanel: "Contraer panel de piezas",
                brainConfiguration: "Configuración del motor",
                configuration: "Configuración",
                collapseConfigurationPanel: "Contraer panel de configuración",
                games: "Partidas",
                expandGamesPanel: "Expandir panel de partidas",
                expandGames: "Expandir partidas",
                collapseGamesPanel: "Contraer panel de partidas",
                chat: "Chat",
                expandChatPanel: "Expandir el panel de chat",
                collapseChatPanel: "Contraer el panel de chat",
                chatPlaceholder: "Escribe un mensaje…",
                chatWatcherReadonly: "Los espectadores solo pueden leer el chat",
                sendChat: "Enviar",
                savedListFilter: "Filtro de lista guardada",
                positions: "Posiciones",
                gameStatus: "Estado de la partida",
                capturedPieces: "Piezas capturadas",
            },
            sessionMode: {
                play: "Modo de juego",
                positionSetup: "Configuración de posición",
                configuration: "Modo de configuración",
                playback: "Modo de reproducción",
                review: "Modo de revisión",
                watch: "Modo de observación",
                practice: "Modo de práctica",
            },
            status: {
                chooseNewGameOrSetup:
                    "Elige Nueva partida o Configuración de posición en la barra lateral",
                chooseNewGame: "Elige Nueva partida en la barra lateral",
                setMoveColorEngineThinkTime:
                    "Configura jugada, color, motor y tiempo de reflexión en la cabecera y pulsa Jugar",
                gameOver: "Partida terminada",
                gameInProgress: "Partida en curso",
                boardLoading: "El tablero aún se está cargando…",
                boardNotReady: "El tablero aún no está listo. Espera e inténtalo de nuevo.",
                leaveOnlineBeforeConfiguration:
                    "Abandona la partida en línea antes de abrir Configuración",
                configurationNotInPractice:
                    "La configuración no está disponible en el modo Práctica",
                configurationModeEdit:
                    "Modo de configuración — edita los valores y guarda",
                selectSavedOrSetup:
                    "Selecciona una partida guardada o configura una posición en el tablero primero",
                gameAlreadyInProgress: "Ya hay una partida en curso",
                yourMove: "Tu jugada",
                engineToMove: "Jugada del motor…",
                leaveOnlineBeforePositionSetup:
                    "Abandona la partida en línea antes de abrir Configuración de posición",
                positionSetupNotInPractice:
                    "La configuración de posición no está disponible en el modo Práctica",
                positionSetupPlacePieces:
                    "Configuración de posición — coloca piezas en el tablero",
                drawWithReason: "Tablas — {{reason}}",
                checkmateWins: "Jaque mate — ganan las {{winner}}",
                check: "Jaque",
                waitBeforeEvaluate:
                    "Espera a que termine la jugada actual antes de evaluar",
                evaluationUnavailable:
                    "La evaluación no está disponible. Reinicia la aplicación Shmerling Chess.",
                evaluatingPosition: "Evaluando posición…",
                evaluationFailed: "Error en la evaluación",
                evaluationLine: "Evaluación (juegan {{side}}): {{score}}",
                checkmate: "Jaque mate",
                drawZero: "Tablas (0)",
                totalLabel: "Total: {{value}}",
                openFolderDesktopOnly:
                    "Abrir carpeta solo está disponible en la aplicación de escritorio",
                couldNotOpenGamesLogFolder: "No se pudo abrir la carpeta del registro de partidas",
                positionValid: "La posición es válida",
                playingFromCustomPosition: "Jugando desde posición personalizada",
                nothingToSave: "Nada que guardar",
                positionSaved: "Posición guardada",
                couldNotSavePosition: "No se pudo guardar la posición",
                savedPositionNotFound: "Posición guardada no encontrada",
                positionUpdated: "Posición actualizada",
                couldNotUpdatePosition: "No se pudo actualizar la posición",
                nameCannotBeEmpty: "El nombre no puede estar vacío",
                gameRenamed: "Partida renombrada",
                couldNotRenameGame: "No se pudo renombrar la partida",
                deletedCount: "Se eliminaron {{count}} elemento(s)",
                couldNotDeleteSelected: "No se pudieron eliminar los elementos seleccionados",
                couldNotLoadSavedGame: "No se pudo cargar la partida guardada",
                editingPositionSaveBookmark:
                    "Editando posición — Guarda para actualizar este marcador",
                couldNotOpenPositionForEditing:
                    "No se pudo abrir la posición para editar",
                gameSaved: "Partida guardada",
                couldNotSaveGame: "No se pudo guardar la partida",
                engineMoveNotApplied: "No se pudo aplicar la jugada del motor",
                engineCouldNotFindMove: "El motor no encontró una jugada",
                engineError: "Error del motor",
                engineThinking: "El motor está pensando…",
                sessionError: "Error de sesión",
                timesUpLost: "¡Se acabó el tiempo! {{loser}} pierde",
                drawOfferTitle: "Oferta de tablas",
                drawOfferMessage: "El oponente envió una oferta de tablas. ¿Aceptar?",
                rematchTitle: "Revancha",
                playerDisconnectedWaiting:
                    "{{who}} se desconectó — esperando reconexión ({{countdown}})",
                opponentDisconnectedCountdown:
                    "Oponente desconectado — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "Partida cancelada — Tiempo de reconexión agotado sin jugadas realizadas.",
                playerFailedToReconnectWins:
                    "{{loser}} no pudo reconectarse — ganan las {{winner}}",
                gameOverOpponentFailedReconnect:
                    "Partida terminada — el oponente no pudo reconectarse.",
                couldNotStartRematch: "No se pudo iniciar la revancha",
                rematchStarted: "Revancha iniciada",
                gameCancelled: "Partida cancelada",
                gameCancelledWithDetail: "Partida cancelada — {{detail}}",
                resignFailed: "Error al rendirse",
                gameResumedYourMove: "Partida reanudada — tu jugada",
                practiceNotAvailable: "El modo Práctica no está disponible",
                couldNotJoinOnPlay: "No se pudo unir a esta partida en /play",
                practiceDebugNotAvailable:
                    "Práctica / Depuración no está disponible para esta cuenta",
                reviewRequiresWebApi: "La revisión requiere la API web",
                couldNotLoadReviewGame: "No se pudo cargar la partida de revisión",
                notReviewGameLink: "Este enlace no es una partida de revisión",
                onlineRequiresWebApi: "El juego en línea requiere la API web",
                couldNotLoadOnlineGame: "No se pudo cargar la partida en línea",
                notOnlineGameOnPlay: "Este enlace no es una partida en línea en /play",
                watchingLiveGame: "Observando partida en directo",
                waitingForOpponentToJoin: "Esperando a que se una el oponente…",
                waitingForOpponent: "Esperando al oponente…",
                onlineGameConnected: "Partida en línea — conectado",
                gameDeleted: "Partida eliminada",
                itemsDeleted: "{{count}} elementos eliminados",
                choosePromotionPiece: "Elige la pieza de promoción",
                invalidPromotionPiece: "Pieza de promoción no válida",
                drawOfferNotAvailable: "La oferta de tablas no está disponible ahora",
            },
            drawReasons: {
                stalemate: "Rey ahogado",
                fiftyMoves: "50 jugadas",
                insufficientMaterial: "Material insuficiente",
                threefoldRepetition: "Triple repetición",
                drawOfferAccepted: "Oferta de tablas de {{by}} aceptada",
            },
            actions: {
                newGame: "Nueva partida",
                resign: "Rendirse",
                draw: "Tablas",
                undo: "Deshacer",
                redo: "Rehacer",
                lastMove: "Última jugada",
                positionSetup: "Configuración de posición",
                config: "Config.",
                flip: "Girar",
                save: "Guardar",
                exit: "Salir",
                loadToStart: "Cargar para iniciar",
                editPosition: "Editar posición",
            },
            savedGames: {
                defaultName: "Partida guardada",
                nameAriaLabel: "Nombre de la partida guardada",
                showDetails: "Mostrar detalles",
                detailsAriaLabel: "Detalles de la partida guardada",
                editPosition: "Editar posición",
                deleteSavedGame: "Eliminar partida guardada",
                renameSavedGame: "Renombrar partida guardada",
                noSavedPositions: "Aún no hay posiciones guardadas.",
                noSavedGames: "Aún no hay partidas guardadas.",
                nextMoveDash: "Siguiente jugada: —",
                nextMove: "Siguiente jugada: {{side}}",
                player: "Jugador",
                savedAt: "Guardado: {{when}}",
                gameId: "ID de partida: {{id}}",
                playersVs: "{{white}} vs. {{black}}",
            },
            reviewNav: {
                start: "Inicio",
                back: "Atrás",
                play: "Reproducir",
                pause: "Pausa",
                forward: "Adelante",
                end: "Final",
            },
            newGameDialog: {
                title: "Nueva partida contra IA",
                yourColor: "Tu color",
                engine: "Motor",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "Tiempo por bando (minutos)",
                allowUndo: "Permitir deshacer",
                private: "Privada",
                privateHint:
                    "Las partidas privadas no se muestran en las listas de partidas activas de otros miembros.",
            },
            prompts: {
                positionName: "Nombre de la posición",
                savePositionAs: "Guardar posición como",
            },
            dialogs: {
                resignTitle: "¿Rendirse en esta partida?",
                resignBody: "Perderás la partida.",
                leaveTitle: "¿Abandonar la partida?",
                leaveBody: "Tu partida se dará por perdida.",
                areYouSure: "¿Estás seguro?",
                discardUnsavedBrainConfig:
                    "¿Descartar los cambios no guardados en la configuración del motor?",
                accept: "Aceptar",
                decline: "Rechazar",
                saveAs: "Guardar como",
                savePosition: "Guardar posición",
                invalidPosition: "Posición no válida",
                rematchChooseColor: "Elige tu color para la revancha:",
                rematchOfferAgree: "El oponente ofreció una revancha. ¿Aceptar?",
                rematchColorPreference:
                    "El oponente quiere jugar con {{offerer}}. Tú jugarías con {{you}}. ¿Aceptar?",
            },
        },
        session: {
            engineThinking: "El motor está pensando…",
            engineCouldNotFindMove: "El motor no encontró una jugada",
            engineError: "Error del motor",
            positionSetupPlacePieces: "Configuración de posición — coloca piezas en el tablero",
            configurationModeEdit: "Modo de configuración — edita los valores y guarda",
            practiceBothSides: "Práctica — ambos bandos",
            opponentDisconnected: "Oponente desconectado",
            opponentRejoined: "El oponente se reconectó",
            playerRejoined: "{{name}} se reconectó",
            drawOfferSent: "Oferta de tablas enviada",
            drawOfferDeclined: "Oferta de tablas rechazada",
            rematchOfferSent: "Oferta de revancha enviada",
            rematchOfferDeclined: "Oferta de revancha rechazada",
            drawAgreed: "Tablas acordadas",
            rematchAcceptedNoGameId: "Revancha aceptada pero sin nuevo ID de partida",
            rematchOfferAccepted: "Oferta de revancha aceptada",
            gameOver: "Partida terminada",
            somethingWentWrong: "Algo salió mal",
            opponentResigned: "El oponente se rindió",
            opponentLeftGame: "El oponente abandonó la partida",
            opponentFailedToReconnect: "El oponente no pudo reconectarse",
            gameCancelled: "Partida cancelada",
            gameCancelledWithDetail: "Partida cancelada — {{detail}}",
            waitingForOpponent: "Esperando al oponente…",
            couldNotResolveWebSocketUrl: "No se pudo resolver la URL de WebSocket",
            opponentJoined: "{{name}} se unió",
            opponentDefault: "Oponente",
            connectionError: "Error de conexión",
            playerDisconnectedWaitingRejoin:
                "{{name}} se desconectó — esperando reconexión",
            playerFailedToReconnectWins:
                "{{loser}} no pudo reconectarse — ganan las {{winner}}",
            watcherWaitingForReconnect: "Esperando a que un jugador se reconecte…",
        },
        site: {
            confirm: "Confirmar",
            cancel: "Cancelar",
            notice: "Aviso",
            ok: "Aceptar",
            home: "Inicio",
            search: "Buscar",
            friends: "Amigos",
            groups: "Grupos",
            debug: "Depuración",
            account: "Cuenta",
            preferences: "Preferencias",
            administrate: "Administrar",
            logOut: "Cerrar sesión",
            logIn: "Iniciar sesión",
            admin: "Admin",
            homeAria: "Inicio",
        },
        validation: {
            validEmail: "Introduce un correo electrónico válido",
            passwordsMustMatch: "Asegúrate de que los campos de contraseña sean idénticos.",
            chooseUsername: "Elige un nombre de usuario",
            usernameNotAvailable: "Este nombre de usuario no está disponible",
            passwordNoWhitespace: "La contraseña no debe contener espacios en blanco.",
            passwordUppercase: "La contraseña debe tener al menos una letra mayúscula.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = es;
    } else {
        global.ShmerlingStringsEs = es;
    }
})(typeof window !== "undefined" ? window : globalThis);
