/**
 * French supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const frExtra = {
        validation: {
            passwordLowercase: "Le mot de passe doit contenir au moins une minuscule.",
            passwordDigit: "Le mot de passe doit contenir au moins un chiffre.",
            passwordSymbol: "Le mot de passe doit contenir au moins un caractère spécial.",
            passwordLength: "Le mot de passe doit comporter entre 8 et 30 caractères.",
            noHtml: "{{label}} ne doit pas contenir de HTML.",
            position: {
                headerSave: "Impossible d'enregistrer cette position :\n\n",
                headerPlay: "Impossible de jouer depuis cette position :\n\n",
                headerUse: "Impossible d'utiliser cette position :\n\n",
                headerSaveBookmark: "Impossible d'enregistrer ce signet :\n\n",
                headerAddBookmark: "Impossible d'ajouter ce signet :\n\n",
                boardUnreadable: "Impossible de lire l'échiquier. Réessayez une fois l'échiquier chargé.",
                whiteKingNone: "Il doit y avoir exactement un roi blanc sur l'échiquier. Aucun n'a été trouvé.",
                whiteKingCount: "Il doit y avoir exactement un roi blanc sur l'échiquier. {{count}} rois blancs trouvés.",
                blackKingNone: "Il doit y avoir exactement un roi noir sur l'échiquier. Aucun n'a été trouvé.",
                blackKingCount: "Il doit y avoir exactement un roi noir sur l'échiquier. {{count}} rois noirs trouvés.",
                kingsAdjacent: "Les deux rois ne peuvent pas être sur des cases adjacentes (y compris en diagonale).",
                sideInCheck: "C'est au trait des {{mover}}, mais le roi {{king}} est déjà en échec. Le camp au trait ne peut pas donner échec — changez le trait ou déplacez les pièces.",
                drawInsufficientKings: "Cette position est nulle par matériel insuffisant (roi contre roi). Ajoutez des pièces pour que le mat reste possible.",
                drawInsufficientMinor: "Cette position est nulle par matériel insuffisant (roi et fou ou cavalier contre roi seul). Ajoutez des pièces pour que le mat reste possible.",
                drawBishopsSameColor: "Cette position est nulle par matériel insuffisant (fou contre fou sur la même couleur de case). Ajoutez des pièces pour que le mat reste possible.",
                tooManyQueens: "{{color}} a {{count}} dames ; le maximum est de 9 par couleur.",
                tooManyRooks: "{{color}} a {{count}} tours ; le maximum est de 10 par couleur.",
                tooManyBishops: "{{color}} a {{count}} fous ; le maximum est de 10 par couleur.",
                tooManyKnights: "{{color}} a {{count}} cavaliers ; le maximum est de 10 par couleur.",
                tooManyPawns: "{{color}} a {{count}} pions ; le maximum est de 8 par couleur."
            }
        },
        auth: {
            whoAreYou: "Qui êtes-vous ?",
            enterPassword: "Saisissez votre mot de passe",
            sorry: "Désolé",
            continue: "Continuer",
            usernameField: "Nom d'utilisateur",
            passwordField: "Mot de passe",
            wrongCredentials: "Nom d'utilisateur ou mot de passe incorrect",
            userAdded: "Utilisateur ajouté avec succès",
            couldNotSaveBookmark: "Impossible d'enregistrer le signet",
            invalidUserId: "Identifiant utilisateur invalide",
            generationJobRunning: "Une autre tâche de génération est déjà en cours…",
            listingPgnFiles: "Liste des fichiers PGN…"
        },
        classic: {
            loadGame: "Charger une partie",
            load: "Charger",
            enterGameState: "Collez l'état de la partie ici…",
            rematch: "Revanche",
            drawOffer: "Proposition de nulle",
            lastMove: "Dernier coup",
            bookmarks: "Signets",
            bookmarkAlertTitle: "Signet de position",
            promotion: "Promotion !",
            check: "Échec",
            checkmateWins: "Échec et mat ! {{winner}} gagne !",
            drawReason: "Nulle ! {{reason}}",
            opponentDisconnected: "L'adversaire s'est déconnecté",
            opponentResignedWins: "L'adversaire a abandonné, {{winner}} gagne",
            somethingWentWrong: "Une erreur s'est produite",
            playerRejoined: "{{name}} s'est reconnecté",
            aPlayerRejoined: "Un joueur s'est reconnecté",
            opponentRejoined: "L'adversaire s'est reconnecté",
            rematchOfferAccepted: "Proposition de revanche acceptée",
            rematchOfferDeclined: "Proposition de revanche refusée",
            sideOffersDraw: "{{side}} propose la nulle",
            drawOfferDeclined: "Proposition de nulle refusée",
            watcherWatching: "{{name}} observe la partie",
            drawOfferSent: "Proposition de nulle envoyée",
            rematchOfferSent: "Proposition de revanche envoyée",
            newGameStarted: "Nouvelle partie lancée",
            gameOver: "Partie terminée",
            gameCancelled: "Partie annulée",
            youResignedWins: "Vous avez abandonné, {{winner}} gagne",
            movesCopied: "Coups copiés dans le presse-papiers !",
            failedCopyMoves: "Échec de la copie des coups",
            failedLoadBrainConfig: "Échec du chargement de la configuration du Brain.",
            failedSaveBrainConfig: "Échec de l'enregistrement de la configuration du Brain.",
            offerDrawConfirm: "Proposer la nulle ?",
            drawOfferAccept: "L'adversaire propose la nulle, accepter ?",
            rematchOfferAccept: "L'adversaire propose une revanche, accepter ?",
            rematchOfferAcceptWithTime: "L'adversaire a proposé une revanche ({{minutes}} min par camp). Accepter?",
            rematchTimePrompt: "Minutes par équipe pour le match revanche :",
            connectionLost: "Connexion perdue : les mouvements n'atteignent pas le serveur",
            confirmExitGame: "Voulez-vous vraiment quitter la partie ?",
            mobileResign: "Abandon",
            mobileRematch: "Revanche",
            mobileDraw: "Nulle",
            mobileFlip: "Retourner",
            mobileLastMove: "Dernier coup",
            mobileMovesList: "Liste des coups",
            researchToolbox: "Boîte à outils",
            researchBrainConfig: "Config Brain",
            researchSave: "Enregistrer",
            researchDiscard: "Abandonner",
            researchEditMode: "mode édition",
            researchRun: "Exécuter",
            researchProperty: "Propriété",
            researchValue: "Valeur",
            playerOnline: "En ligne",
            playerDisconnectedStatus: "Déconnecté",
            playerOffline: "Hors ligne",
            humanVsComputer: "Humain contre ordinateur",
            newGameTwoPlayers: "Nouvelle partie à 2 joueurs",
            settings: "Paramètres",
            help: "Aide",
            drawOffersNotVsEngine: "Les propositions de nulle ne sont pas disponibles contre le moteur.",
            failedStartFromBookmark: "Échec du démarrage de la partie depuis le signet.",
            resignConfirm: "Abandonner ?",
            areYouSure: "Êtes-vous sûr ?",
            gameOverOpponentFailedReconnectWinsClassic: "Partie terminée — l'adversaire n'a pas pu se reconnecter. {{winner}} gagne.",
            reconnectTimeoutNoMoves: "Délai de reconnexion dépassé sans coup joué.",
            waitingOpponentRejoin: "En attente de la reconnexion de l'adversaire",
            timeoutOneSec: "Délai : 1 s",
            timeoutSecs: "Délai : {{count}} s",
            whitePieceAlt: "Pièce blanche",
            blackPieceAlt: "Pièce noire",
            eraserTitle: "Gomme",
            eraserAria: "Gomme — retirer la pièce de la case",
            selectTitle: "Sélection",
            selectAria: "Sélection — glissez les pièces pour les déplacer",
            resetAria: "Réinitialiser — effacer toutes les pièces",
            defaultPositionAria: "Position initiale — placer la position de départ standard",
            loading: "Chargement…",
            engineLabel: "Moteur"
        },
        site: {
            home: "Accueil",
            search: "Recherche",
            friends: "Amis",
            groups: "Groupes",
            debug: "Débogage",
            account: "Compte",
            preferences: "Préférences",
            administrate: "Administration",
            logOut: "Se déconnecter",
            logIn: "Se connecter",
            admin: "Admin",
            homeAria: "Accueil",
            confirm: "Confirmer",
            cancel: "Annuler",
            notice: "Avis",
            ok: "OK",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "Pied de page",
                privacy: "Politique de confidentialité",
                terms: "Conditions d’utilisation",
                contact: "Contact",
                copyright: "© {{year}} Shmerling Chess. Tous droits réservés.",
                lastUpdated: "Dernière mise à jour : {{date}}",
                privacyTitle: "Politique de confidentialité",
                privacyLead: "Comment Shmerling Chess traite les informations de compte et de partie.",
                privacyBody: "Nous utilisons vos données de compte pour faire fonctionner le service, conserver les parties et préférences, et améliorer le produit. Nous ne vendons pas d’informations personnelles. Le texte complet de la politique sera publié ici.",
                termsTitle: "Conditions d’utilisation",
                termsLead: "Les règles d’utilisation de Shmerling Chess.",
                termsBody: "En utilisant Shmerling Chess, vous acceptez de jouer loyalement, de respecter les autres joueurs et d’utiliser le service uniquement pour le jeu d’échecs personnel. Les conditions complètes seront publiées ici.",
                contactTitle: "Contact",
                contactLead: "Contacter l’équipe Shmerling Chess.",
                contactBody: "Les coordonnées pour le support et les questions de confidentialité seront publiées ici.",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "Nom d'utilisateur :",
            password: "Mot de passe :",
            login: "Connexion",
            register: {
                submit: "Inscription",
                confirmPassword: "Confirmer le mot de passe :",
                playerLevel: "Niveau du joueur :",
                rookie: "Débutant",
                skilled: "Confirmé",
                elite: "Élite",
                grandMaster: "Grand maître"
            },
            email: "E-mail :",
            welcome: {
                greeting: "Bon retour",
                tagline: "À vous de jouer",
                playNow: "Jouer maintenant !",
                activeGames: "Parties en cours",
                live: "En direct",
                showAll: "Tout afficher",
                viewAllActive: "Voir toutes les parties en cours",
                mostRecent: "Les plus récentes d'abord",
                noGamesNow: "Aucune partie pour le moment",
                myGames: "Mes parties",
                viewAllGames: "Voir toutes les parties",
                recentCompleted: "Vos parties récemment terminées",
                noCompleted: "Aucune partie terminée pour le moment",
                activeGamesAria: "Parties en cours",
                inviteOnlineFriend: "Inviter un ami en ligne à jouer",
                friendsPageTitle: "Page Amis",
                manageFriends: "Gérer",
                colFriend: "Ami",
                colStatus: "Statut",
                findPlayers: "Trouver des joueurs",
                waitingForResponse: "En attente de réponse",
                inviteSentSuffix: "(invitation envoyée)",
                sortByRowNumber: "Trier par numéro de ligne",
                sortBy: "Trier par {{key}}"
            },
            gameList: {
                date: "Date",
                time: "Heure",
                result: "Résultat",
                reason: "Motif",
                type: "Type",
                status: "Statut",
                event: "Événement",
                site: "Site",
                round: "Ronde"
            },
            loginPage: {
                title: "Connexion"
            },
            error: {
                title: "Une erreur s'est produite",
                body: "Une erreur s'est produite.",
                back: "Retour à l'accueil"
            },
            log: {
                title: "Journal du serveur",
                clear: "Effacer l'affichage",
                latest: "Dernier",
                waiting: "En attente de la sortie du journal du serveur…"
            },
            activeGames: {
                moves: "Coups",
                turn: "Trait",
                status: "Statut",
                inProgress: "En cours",
                onHold: "En pause",
                vs: " contre ",
                minutesAgo: "Il y a {{count}} minutes",
                oneMinuteAgo: "Il y a 1 minute",
                justStarted: "Vient de commencer",
                notStarted: "Pas commencée",
                startedTooltip: "Commencée : {{when}}",
                playersVs: "{{white}} contre {{black}}"
            },
            friendsPage: {
                title: "Amis",
                tagline: "Trouvez de nouveaux partenaires d'échecs",
                myFriends: "Mes amis",
                noFriendsYet: "Pas encore d'amis",
                findPlayers: "Trouver des joueurs",
                searchByUsername: "Rechercher par nom d'utilisateur",
                searchPlaceholder: "Saisir pour rechercher…",
                enterCharToSearch: "Saisissez au moins un caractère pour rechercher",
                noMatchingUsers: "Aucun utilisateur correspondant",
                playing: "En jeu",
                pendingFriendshipOffer: "Demande d'amitié en attente",
                joining: "Connexion",
                rejoin: "Rejoindre",
                friendRequest: "Demande d'amitié",
                wantsToBeFriends: "(souhaite être ami)",
                pendingOfferSuffix: "(demande d'amitié en attente)",
                waitingFriendRespond: "En attente de la réponse de votre ami",
                cancelBeforeRemove: "Annulez l'invitation à jouer avant de retirer cet ami",
                friendsTag: "Amis",
                offerReceivedTag: "Offre reçue — voir Vos amis",
                addFriend: "Ajouter un ami",
                withdraw: "Retirer",
                requestFailed: "Échec de la requête",
                removeFriendConfirm: "Retirer cet ami de votre liste ?",
                removeFriendTitle: "Retirer un ami",
                withdrawOfferConfirm: "Retirer cette demande d'amitié ?",
                withdrawOfferTitle: "Retirer l'offre",
                couldNotAccept: "Impossible d'accepter",
                couldNotDecline: "Impossible de refuser",
                couldNotRemove: "Impossible de retirer",
                couldNotCancelInvite: "Impossible d'annuler l'invitation",
                couldNotWithdraw: "Impossible de retirer",
                couldNotSendInvite: "Impossible d'envoyer l'invitation",
                couldNotSendGameInvite: "Impossible d'envoyer l'invitation à jouer",
                gameInvite: "Invitation à jouer",
                gameInvitationsAria: "Invitations à jouer",
                gameInvitationAria: "Invitation à jouer",
                chessInviteTitle: "Invitation aux échecs",
                wantsToPlayAsBlack: "{{name}} souhaite jouer. Vous jouez les Noirs.",
                wantsToPlayYouWhite: "{{name}} veut jouer. Vous incarnez les Blancs.",
                aFriend: "Un ami",
                youPlayAsWhite: "Vous jouez les Blancs",
                youPlayAsBlack: "Vous jouez les Noirs",
                establishingGame: "Création de la partie…",
                yourOpponent: "Votre adversaire",
                declinedYourInvite: "{{name}} a refusé votre invitation à jouer.",
                cancelInvite: "Annuler l'invitation",
                accept: "Accepter",
                decline: "Refuser",
                invite: "Inviter",
                inviteSettingsTitle: "Paramètres d'invitation",
                inviteSettingsFor: "Inviter {{name}}",
                inviteTimeMinutes: "Temps par côté (minutes)",
                inviteYourColor: "Votre couleur",
                inviteColorWhite: "Blanc",
                inviteColorBlack: "Noir",
                inviteColorRandom: "Aléatoire",
                inviteFriendly: "Jeu amical",
                inviteFriendlyHint: "Décochez pour compter plus tard dans l'ELO (jeu classé).",
                invitePrivate: "Jeu privé",
                invitePrivateHint: "Cachez ce jeu du lobby public des jeux actifs.",
                inviteSaveDefaults: "Enregistrer les valeurs par défaut",
                inviteOfferTime: "{{minutes}} min",
                inviteOfferFriendly: "Amical",
                inviteOfferRated: "Noté",
                inviteOfferPrivate: "Privé",
                remove: "Retirer",
                offerSent: "Offre envoyée",
                pending: "En attente",
                online: "En ligne",
                offline: "Hors ligne"
            },
            adminPage: {
                title: "Administration",
                tagline: "Utilisateurs, jeux, moteurs, livre d'ouverture et duels de robots",
                panelTitle: "Console d'administration",
                users: "Utilisateurs",
                generate: "Générer",
                games: "Parties",
                engines: "Moteurs",
                states: "États",
                openingBook: "Livre d'ouverture",
                bots: "Bots",
                addUser: "Ajouter un utilisateur",
                sectionsAria: "Sections d'administration",
                openingBookLabel: "Livre d'ouvertures :",
                openingBookStatusTitle: "Livre d'ouverture actuel",
                openingBookFile: "Déposer",
                openingBookExists: "Statut",
                openingBookExistsYes: "Présent",
                openingBookExistsNo: "Manquant",
                openingBookLines: "Lignes de jeu",
                openingBookSize: "Taille",
                openingBookModified: "Dernière modification",
                openingBookPgnSources: "Sources PGN",
                openingBookPgnCount: "{{count}} Fichier(s) PGN disponible(s) pour la reconstruction à partir de",
                openingBookIntro: "Reconstruisez le livre d'ouverture basé sur les lignes (data/opening-book-lines.txt) à partir des dossiers PGN du serveur. Utilisez Générer un livre d'ouverture ci-dessous : rien ne fonctionne tant que vous n'appuyez pas dessus.",
                generateOpeningBook: "Générer un livre d'ouverture",
                botsIntro: "Démarrez un jeu public moteur contre moteur. Les membres peuvent l'ouvrir depuis Active Games sur Home en tant qu'observateurs.",
                botsWhiteEngine: "Moteur blanc",
                botsBlackEngine: "Moteur noir",
                botsWhiteDifficulty: "Difficulté (1–6)",
                botsBlackDifficulty: "Difficulté (1–6)",
                botsSkillLevel: "Compétence (0-20)",
                botsTimeMinutes: "Horloge (minutes)",
                botsStart: "Commencer le duel",
                botsStarting: "Début du duel…",
                botsStarted: "Duel commencé : {{white}} contre {{black}}.",
                botsWatchLink: "Regardez ce jeu",
                botsListedNote: "Répertorié sur Accueil → Jeux actifs pour les autres utilisateurs.",
                botsStartFailed: "Impossible de commencer le duel.",
                botsStopped: "Arrêt demandé.",
                botsStopFailed: "Impossible d'arrêter le duel.",
                gameLines: "lignes de parties",
                noGamesInDb: "Aucune partie dans la base de données pour le moment.",
                gamesPaginationAria: "Pagination des parties",
                colNum: "#",
                colUsername: "Nom d'utilisateur",
                colType: "Type",
                colEmail: "E-mail",
                colPassword: "Mot de passe",
                colLevel: "Niveau",
                colElo: "Elo",
                colJoined: "Inscription",
                colLastLogin: "Dernière connexion",
                colActiveGames: "Parties actives",
                colFriends: "Amis",
                colBookmarks: "Signets",
                colId: "Id",
                colStatus: "Statut",
                colName: "Nom",
                colAvailable: "Disponible",
                colEnabled: "Activé",
                colBackend: "Back-end",
                colCommand: "Commande",
                colNotes: "Notes",
                colNote: "Note",
                colAction: "Action",
                emptyUsers: "Aucun utilisateur pour le moment.",
                emptyData: "Aucune donnée pour le moment.",
                emptyEngines: "Aucun moteur Play dans le registre.",
                emptyStates: "Utilisez Générer pour ouvrir la page de génération du livre d'ouvertures et des états.",
                engineAvailableYes: "Disponible",
                engineAvailableNo: "Indisponible",
                engineEnable: "Activer",
                engineDisable: "Désactiver",
                enginesLoadFailed: "Impossible de charger les moteurs",
                enginesSaveFailed: "Impossible de mettre à jour le moteur",
                clickToEdit: "Cliquer pour modifier",
                updateFailed: "Échec de la mise à jour",
                couldNotSave: "Impossible d'enregistrer",
                setPassword: "Définir le mot de passe",
                setPasswordTitle: "Cliquer pour définir un nouveau mot de passe (4–30 caractères)",
                passwordLengthInvalid: "Le mot de passe doit comporter entre 4 et 30 caractères.",
                invalidPassword: "Mot de passe invalide",
                saved: "Enregistré",
                newPasswordPlaceholder: "Nouveau mot de passe",
                clickChangeUserType: "Cliquer pour changer le type d'utilisateur",
                userTypeAria: "Type d'utilisateur",
                changeUserTypeTitle: "Changer le type d'utilisateur",
                grantAdminConfirm: "Accorder les privilèges d'administrateur à cet utilisateur ? Il pourra accéder aux outils d'administration et gérer les comptes.",
                demoteAdminConfirm: "Passer cet utilisateur d'Admin à {{type}} ? Il perdra l'accès à la zone d'administration.",
                changeUserTypeConfirm: "Passer cet utilisateur en {{type}} ?",
                clickChangeLevel: "Cliquer pour changer le niveau",
                playerLevelAria: "Niveau du joueur",
                sortByRowNumber: "Trier par numéro de ligne",
                sortBy: "Trier par {{key}}",
                delete: "Supprimer",
                first: "Premier",
                last: "Dernier",
                previous: "Précédent",
                next: "Suivant",
                previous5Pages: "5 pages précédentes",
                next5Pages: "5 pages suivantes",
                previous10Pages: "10 pages précédentes",
                next10Pages: "10 pages suivantes",
                userTypeAdmin: "Admin",
                userTypePartner: "Partenaire",
                userTypeMember: "Membre",
                generateTitle: "Livre d'ouvertures et génération d'états",
                backToAdmin: "← Retour à l'administration",
                generateIntro: "Rejoue tous les fichiers PGN du dossier du gestionnaire de parties du serveur vers la collection Mongo State ou le livre d'ouvertures ligne par ligne (data/opening-book-lines.txt). Choisissez une cible, puis appuyez sur Démarrer la génération — rien ne s'exécute tant que vous ne le faites pas.",
                target: "Cible",
                targetMongo: "MongoDB — ajouter des lignes à la collection State",
                targetBook: "Fichier de lignes — écrire le livre d'ouvertures (opening-book-lines.txt)",
                startGeneration: "Démarrer la génération",
                stop: "Arrêter",
                idle: "Inactif.",
                starting: "Démarrage…",
                running: "En cours ({{mode}})…",
                readingFiles: "Lecture de {{count}} fichier(s)…",
                replayingGames: "Rejeu de {{count}} parties…",
                writingOpeningBook: "Écriture du livre d'ouvertures…",
                readingPgn: "Lecture PGN {{index}} / {{total}} ({{games}} parties)",
                replayGameProgress: "Rejeu partie {{current}} / {{total}} (terminées ok : {{completed}})",
                stopped: "Arrêté.",
                bookUnchanged: "Le livre d'ouvertures existant n'a pas été modifié.",
                bookLinesInFile: "{{count}} ligne(s) de partie dans {{file}}.",
                cancelledBeforeRead: "Annulé avant la lecture des PGN.",
                cancelledAfterRead: "Annulé après la lecture ; le rejeu a été ignoré (rien n'a été écrit).",
                mongoGamesSaved: "{{count}} partie(s) ont eu de nouvelles lignes d'état enregistrées.",
                doneBook: "Terminé. {{count}} lignes de parties → {{file}}",
                doneBookFileOnly: "Terminé. {{file}}",
                doneMongo: "Terminé. Collection MongoDB State mise à jour{{detail}}.",
                doneMongoDetail: " ({{count}} parties rejouées ok)",
                errorPrefix: "Erreur : {{message}}",
                unknownError: "Inconnue",
                connectionClosed: "Connexion fermée (consultez les journaux du serveur ou réessayez).",
                openingBookDefault: "livre d'ouvertures"
            },
            playNow: {
                title: "Nouvelle partie",
                startTitle: "Commencer une nouvelle partie",
                playingColor: "Couleur jouée",
                timeMin: "Temps (min)",
                difficulty: "Difficulté (1–5)",
                mousePreference: "Préférence souris",
                drag: "Glisser",
                doubleClick: "Double-clic",
                showAvailableMoves: "Afficher les coups possibles",
                private: "Privée",
                privateHint: "Les parties privées n’apparaissent pas dans les listes de parties actives des autres membres.",
                playComputer: "Jouer contre l'ordinateur",
                browseAll: "Tout parcourir",
                yourHistory: "Votre historique",
                fullList: "Liste complète",
                gameLibrary: "Bibliothèque de parties",
                openLibrarySearch: "Ouvrir la recherche dans la bibliothèque",
                brain3: "Brain 3",
                brain2: "Brain 2"
            },
            activeGamesList: {
                title: "Parties en cours",
                tagline: "Toutes les parties en cours",
                liveGames: "Parties en direct",
                game: "Partie",
                started: "Commencée"
            },
            list: {
                title: "Toutes les parties",
                tagline: "Vos jeux terminés",
                allGames: "Jeux terminés",
                gamesCount: "Jeux {{count}}",
                action: "Action"
            },
            searchPage: {
                title: "Recherche :",
                tagline: "Trouvez des parties dans l'archive PGN",
                results: "Résultats",
                resultsCount: "{{count}} résultats",
                noResults: "Aucune partie ne correspond à votre recherche",
                button: "Rechercher",
                resultsFound: "{{count}} résultat(s) trouvé(s) :",
                first: "Premier",
                last: "Dernier",
                previous: "Précédent",
                next: "Suivant",
                previous5Pages: "5 pages précédentes",
                next5Pages: "5 pages suivantes",
                previous10Pages: "10 pages précédentes",
                next10Pages: "10 pages suivantes"
            },
            game: {
                moves: "Coups",
                white: "Blanc",
                black: "Noir",
                resign: "Abandon",
                draw: "Nulle",
                undo: "Annuler le coup",
                flip: "Retourner",
                practice: "Entraînement"
            },
            mobileWelcome: {
                title: "Accueil — Échecs",
                play: "Jouer",
                library: "Bibliothèque",
                friends: "Amis"
            },
            mobileGame: {
                title: "Partie",
                moves: "Coups",
                resign: "Abandon"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "Une erreur s'est produite",
                body: "Une erreur s'est produite.",
                back: "Retour à l'accueil"
            },
            chrome: {
                preferences: "Préférences",
                closePreferences: "Fermer les préférences",
                display: "Affichage",
                gameplay: "Jeu",
                pieceSet: "Jeu de pièces",
                boardTheme: "Thème de l'échiquier",
                theme: "Thème",
                themeBlue: "Bleu",
                themeDark: "Sombre",
                customizeTheme: "Personnaliser le thème…",
                builtInThemesAria: "Thèmes intégrés",
                savedCustomThemesAria: "Thèmes personnalisés enregistrés",
                pieceSetsAria: "Jeux de pièces",
                homeAria: "Accueil Échecs Shmerling"
            },
            prefs: {
                language: "Langue",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "Contrôle à la souris",
                mouseDrag: "Traîner",
                mouseClick: "Cliquez",
                thinkingTime: "Temps de réflexion",
                thinkingTimeAria: "Temps de réflexion en secondes",
                immediateResign: "Abandon immédiat",
                secondsOption: "{{count}} s",
                selectedTheme: "Sélectionné : {{name}}",
                selectedPieceSet: "Sélectionné : {{name}}",
                enterFullScreen: "Passer en plein écran",
                exitFullScreen: "Quitter le plein écran",
                fullScreenUnavailable: "Le plein écran n'est pas disponible dans ce navigateur."
            },
            gameRun: {
                yourColor: "Votre couleur",
                engine: "Moteur",
                thinkTime: "Temps de réflexion (secondes)",
                thinkTimeAria: "Temps de réflexion du moteur en secondes",
                play: "Jouer",
                nextMove: "Prochain coup",
                computer: "Ordinateur",
                computerColorHint: "Couleur jouée par l'ordinateur — vous jouez l'autre camp"
            },
            brainConfig: {
                title: "Configuration du Brain",
                save: "Enregistrer",
                reset: "Réinitialiser",
                saved: "Configuration enregistrée",
                failedSave: "Échec de l'enregistrement de la configuration",
                brainLabel: "Brain",
                loading: "Chargement…",
                failedLoad: "Échec du chargement de la configuration du Brain.",
                discardSwitchConfirm: "Abandonner les modifications non enregistrées et changer de version du Brain ?",
                discard: "Abandonner",
                pieceScores: "Scores des pièces",
                specialEvaluations: "Évaluations spéciales",
                gamePhase: "Phase de partie",
                pawnFilesOpeningMid: "Colonnes de pions (ouverture / milieu)",
                pawnFilesEndGame: "Colonnes de pions (finale)"
            },
            customTheme: {
                title: "Thème personnalisé",
                name: "Nom du thème",
                save: "Enregistrer",
                delete: "Supprimer",
                saved: "Enregistré",
                searchProperties: "Rechercher des propriétés",
                filterPlaceholder: "Filtrer par nom de propriété…",
                namePlaceholder: "Mon thème",
                resetPreset: "Réinitialiser au préréglage actuel",
                couldNotSave: "Impossible d'enregistrer le thème. Réessayez.",
                untitled: "Sans titre",
                defaultName: "Thème personnalisé"
            },
            positionSetup: {
                clearBoard: "Vider l'échiquier",
                startingPosition: "Position initiale",
                flipBoard: "Retourner l'échiquier",
                eraser: "Gomme",
                selectAndMove: "Sélectionner et déplacer",
                defaultStartingPosition: "Position de départ par défaut",
                savePosition: "Enregistrer la position",
                saveAsNewPosition: "Enregistrer comme nouvelle position",
                validatePosition: "Valider la position",
                positionFlags: "Indicateurs de position",
                turn: "Trait",
                flagCheck: "Échec",
                flagCheckmate: "Échec et mat",
                flagDraw: "Nulle",
                flagWhiteKingMoved: "Roi blanc déplacé",
                flagBlackKingMoved: "Roi noir déplacé",
                flagWhiteKingsideRookMoved: "Tour blanche côté roi déplacée",
                flagWhiteQueensideRookMoved: "Tour blanche côté dame déplacée",
                flagBlackKingsideRookMoved: "Tour noire côté roi déplacée",
                flagBlackQueensideRookMoved: "Tour noire côté dame déplacée"
            }
        },
        errorPage: {
            code: "Erreur {{code}}",
            notFoundTitle: "Page introuvable",
            notFoundMessage: "La page que vous recherchez n’existe pas.",
            genericTitle: "Une erreur s’est produite",
            genericMessage: "Une erreur inattendue s’est produite. Veuillez réessayer.",
            backHome: "Retour à l’accueil"
        },
        mobile: {
            drawOfferTitle: "Proposition de nulle",
            drawOfferMessage: "L'adversaire propose la nulle. Accepter ?",
            rematchTitle: "Revanche",
            rematchMessage: "L'adversaire propose une revanche. Accepter ?",
            gameId: "ID de partie : {{id}}",
            drawOfferAgree: "L'adversaire propose la nulle, accepter ?",
            rematchOfferAgree: "L'adversaire propose une revanche, accepter ?",
            newGameWatchFromHome: "Nouvelle partie lancée — allez à l'Accueil pour observer."
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = frExtra;
    } else {
        global.ShmerlingStringsFrExtra = frExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
