(function (global) {
    "use strict";
    const frExtra = {
    "validation": {
        "passwordLowercase": "Le mot de passe doit contenir au moins une minuscule.",
        "passwordDigit": "Le mot de passe doit contenir au moins un chiffre.",
        "passwordSymbol": "Le mot de passe doit contenir au moins un caractère spécial.",
        "passwordLength": "Le mot de passe doit comporter entre 8 et 30 caractères.",
        "noHtml": "{{label}} ne doit pas contenir de HTML.",
        "position": {
            "headerSave": "Impossible d'enregistrer cette position :\n\n",
            "headerPlay": "Impossible de jouer depuis cette position :\n\n",
            "headerUse": "Impossible d'utiliser cette position :\n\n",
            "headerSaveBookmark": "Impossible d'enregistrer ce signet :\n\n",
            "headerAddBookmark": "Impossible d'ajouter ce signet :\n\n",
            "boardUnreadable": "Impossible de lire l'échiquier. Réessayez une fois l'échiquier chargé.",
            "whiteKingNone": "Il doit y avoir exactement un roi blanc sur l'échiquier. Aucun n'a été trouvé.",
            "whiteKingCount": "Il doit y avoir exactement un roi blanc sur l'échiquier. {{count}} rois blancs trouvés.",
            "blackKingNone": "Il doit y avoir exactement un roi noir sur l'échiquier. Aucun n'a été trouvé.",
            "blackKingCount": "Il doit y avoir exactement un roi noir sur l'échiquier. {{count}} rois noirs trouvés.",
            "kingsAdjacent": "Les deux rois ne peuvent pas être sur des cases adjacentes (y compris en diagonale).",
            "sideInCheck": "C'est au trait des {{mover}}, mais le roi {{king}} est déjà en échec. Le camp au trait ne peut pas donner échec — changez le trait ou déplacez les pièces.",
            "drawInsufficientKings": "Cette position est nulle par matériel insuffisant (roi contre roi). Ajoutez des pièces pour que le mat reste possible.",
            "drawInsufficientMinor": "Cette position est nulle par matériel insuffisant (roi et fou ou cavalier contre roi seul). Ajoutez des pièces pour que le mat reste possible.",
            "drawBishopsSameColor": "Cette position est nulle par matériel insuffisant (fou contre fou sur la même couleur de case). Ajoutez des pièces pour que le mat reste possible.",
            "tooManyQueens": "{{color}} a {{count}} dames ; le maximum est de 9 par couleur.",
            "tooManyRooks": "{{color}} a {{count}} tours ; le maximum est de 10 par couleur.",
            "tooManyBishops": "{{color}} a {{count}} fous ; le maximum est de 10 par couleur.",
            "tooManyKnights": "{{color}} a {{count}} cavaliers ; le maximum est de 10 par couleur.",
            "tooManyPawns": "{{color}} a {{count}} pions ; le maximum est de 8 par couleur."
        }
    },
    "auth": {
        "wrongCredentials": "Nom d'utilisateur ou mot de passe incorrect",
        "userAdded": "Utilisateur ajouté avec succès",
        "couldNotSaveBookmark": "Impossible d'enregistrer le signet",
        "invalidUserId": "Identifiant utilisateur invalide",
        "generationJobRunning": "Une autre tâche de génération est déjà en cours…",
        "listingPgnFiles": "Liste des fichiers PGN…"
    },
    "classic": {
        "loadGame": "Charger une partie",
        "load": "Charger",
        "enterGameState": "Collez l'état de la partie ici…",
        "rematch": "Revanche",
        "drawOffer": "Proposition de nulle",
        "lastMove": "Dernier coup",
        "bookmarks": "Signets",
        "bookmarkAlertTitle": "Signet de position",
        "promotion": "Promotion !",
        "check": "Échec",
        "checkmateWins": "Échec et mat ! {{winner}} gagne !",
        "drawReason": "Nulle ! {{reason}}",
        "opponentDisconnected": "L'adversaire s'est déconnecté",
        "opponentResignedWins": "L'adversaire a abandonné, {{winner}} gagne",
        "somethingWentWrong": "Une erreur s'est produite",
        "playerRejoined": "{{name}} s'est reconnecté",
        "aPlayerRejoined": "Un joueur s'est reconnecté",
        "opponentRejoined": "L'adversaire s'est reconnecté",
        "rematchOfferAccepted": "Proposition de revanche acceptée",
        "rematchOfferDeclined": "Proposition de revanche refusée",
        "sideOffersDraw": "{{side}} propose la nulle",
        "drawOfferDeclined": "Proposition de nulle refusée",
        "watcherWatching": "{{name}} observe la partie",
        "drawOfferSent": "Proposition de nulle envoyée",
        "rematchOfferSent": "Proposition de revanche envoyée",
        "newGameStarted": "Nouvelle partie lancée",
        "gameOver": "Partie terminée",
        "gameCancelled": "Partie annulée",
        "youResignedWins": "Vous avez abandonné, {{winner}} gagne",
        "movesCopied": "Coups copiés dans le presse-papiers !",
        "failedCopyMoves": "Échec de la copie des coups",
        "failedLoadBrainConfig": "Échec du chargement de la configuration du Brain.",
        "failedSaveBrainConfig": "Échec de l'enregistrement de la configuration du Brain.",
        "offerDrawConfirm": "Proposer la nulle ?",
        "drawOfferAccept": "L'adversaire propose la nulle, accepter ?",
        "rematchOfferAccept": "L'adversaire propose une revanche, accepter ?",
        "confirmExitGame": "Voulez-vous vraiment quitter la partie ?",
        "mobileResign": "Abandon",
        "mobileRematch": "Revanche",
        "mobileDraw": "Nulle",
        "mobileFlip": "Retourner",
        "mobileLastMove": "Dernier coup",
        "mobileMovesList": "Liste des coups",
        "researchToolbox": "Boîte à outils",
        "researchBrainConfig": "Config Brain",
        "researchSave": "Enregistrer",
        "researchDiscard": "Abandonner",
        "researchEditMode": "mode édition",
        "researchRun": "Exécuter",
        "researchProperty": "Propriété",
        "researchValue": "Valeur",
        "playerOnline": "En ligne",
        "playerDisconnectedStatus": "Déconnecté",
        "playerOffline": "Hors ligne",
        "humanVsComputer": "Humain contre ordinateur",
        "newGameTwoPlayers": "Nouvelle partie à 2 joueurs",
        "settings": "Paramètres",
        "help": "Aide",
        "drawOffersNotVsEngine": "Les propositions de nulle ne sont pas disponibles contre le moteur.",
        "failedStartFromBookmark": "Échec du démarrage de la partie depuis le signet.",
        "resignConfirm": "Abandonner ?",
        "areYouSure": "Êtes-vous sûr ?",
        "gameOverOpponentFailedReconnectWinsClassic": "Partie terminée — l'adversaire n'a pas pu se reconnecter. {{winner}} gagne.",
        "reconnectTimeoutNoMoves": "Délai de reconnexion dépassé sans coup joué.",
        "waitingOpponentRejoin": "En attente de la reconnexion de l'adversaire",
        "timeoutOneSec": "Délai : 1 s",
        "timeoutSecs": "Délai : {{count}} s",
        "whitePieceAlt": "Pièce blanche",
        "blackPieceAlt": "Pièce noire",
        "eraserTitle": "Gomme",
        "eraserAria": "Gomme — retirer la pièce de la case",
        "selectTitle": "Sélection",
        "selectAria": "Sélection — glissez les pièces pour les déplacer",
        "resetAria": "Réinitialiser — effacer toutes les pièces",
        "defaultPositionAria": "Position initiale — placer la position de départ standard",
        "loading": "Chargement…",
        "engineLabel": "Moteur"
    },
    "site": {
        "home": "Accueil",
        "search": "Recherche",
        "friends": "Amis",
        "groups": "Groupes",
        "debug": "Débogage",
        "account": "Compte",
        "preferences": "Préférences",
        "administrate": "Administration",
        "logOut": "Se déconnecter",
        "logIn": "Se connecter",
        "admin": "Admin",
        "homeAria": "Accueil",
        "confirm": "Confirmer",
        "cancel": "Annuler",
        "notice": "Avis",
        "ok": "OK",
        "username": "Nom d'utilisateur :",
        "password": "Mot de passe :",
        "login": "Connexion",
        "register": {
            "rookie": "Débutant",
            "skilled": "Confirmé",
            "elite": "Élite",
            "grandMaster": "Grand maître"
        },
        "email": "E-mail :",
        "welcome": {
            "greeting": "Bon retour",
            "tagline": "À vous de jouer",
            "playNow": "Jouer maintenant !",
            "activeGames": "Parties en cours",
            "live": "En direct",
            "showAll": "Tout afficher",
            "viewAllActive": "Voir toutes les parties en cours",
            "mostRecent": "Les plus récentes d'abord",
            "noGamesNow": "Aucune partie pour le moment",
            "myGames": "Mes parties",
            "viewAllGames": "Voir toutes les parties",
            "recentCompleted": "Vos parties récemment terminées",
            "noCompleted": "Aucune partie terminée pour le moment",
            "activeGamesAria": "Parties en cours",
            "inviteOnlineFriend": "Inviter un ami en ligne à jouer",
            "friendsPageTitle": "Page Amis",
            "manageFriends": "Gérer",
            "colFriend": "Ami",
            "colStatus": "Statut",
            "findPlayers": "Trouver des joueurs",
            "waitingForResponse": "En attente de réponse",
            "inviteSentSuffix": "(invitation envoyée)",
            "sortByRowNumber": "Trier par numéro de ligne",
            "sortBy": "Trier par {{key}}"
        },
        "gameList": {
            "date": "Date",
            "time": "Heure",
            "result": "Résultat",
            "reason": "Motif",
            "type": "Type",
            "status": "Statut",
            "event": "Événement",
            "site": "Site",
            "round": "Ronde"
        },
        "loginPage": {
            "title": "Connexion"
        },
        "error": {
            "title": "Une erreur s'est produite",
            "body": "Une erreur s'est produite.",
            "back": "Retour à l'accueil"
        },
        "log": {
            "title": "Journal du serveur",
            "clear": "Effacer l'affichage",
            "latest": "Dernier",
            "waiting": "En attente de la sortie du journal du serveur…"
        },
        "activeGames": {
            "moves": "Coups",
            "turn": "Trait",
            "status": "Statut",
            "inProgress": "En cours",
            "onHold": "En pause",
            "vs": " contre ",
            "minutesAgo": "Il y a {{count}} minutes",
            "oneMinuteAgo": "Il y a 1 minute",
            "justStarted": "Vient de commencer",
            "notStarted": "Pas commencée",
            "startedTooltip": "Commencée : {{when}}",
            "playersVs": "{{white}} contre {{black}}"
        },
        "friendsPage": {
            "title": "Amis",
            "tagline": "Trouvez de nouveaux partenaires d'échecs",
            "myFriends": "Mes amis",
            "noFriendsYet": "Pas encore d'amis",
            "findPlayers": "Trouver des joueurs",
            "searchByUsername": "Rechercher par nom d'utilisateur",
            "searchPlaceholder": "Saisir pour rechercher…",
            "enterCharToSearch": "Saisissez au moins un caractère pour rechercher",
            "noMatchingUsers": "Aucun utilisateur correspondant",
            "playing": "En jeu",
            "pendingFriendshipOffer": "Demande d'amitié en attente",
            "joining": "Connexion",
            "rejoin": "Rejoindre",
            "friendRequest": "Demande d'amitié",
            "wantsToBeFriends": "(souhaite être ami)",
            "pendingOfferSuffix": "(demande d'amitié en attente)",
            "waitingFriendRespond": "En attente de la réponse de votre ami",
            "cancelBeforeRemove": "Annulez l'invitation à jouer avant de retirer cet ami",
            "friendsTag": "Amis",
            "offerReceivedTag": "Offre reçue — voir Vos amis",
            "addFriend": "Ajouter un ami",
            "withdraw": "Retirer",
            "requestFailed": "Échec de la requête",
            "removeFriendConfirm": "Retirer cet ami de votre liste ?",
            "removeFriendTitle": "Retirer un ami",
            "withdrawOfferConfirm": "Retirer cette demande d'amitié ?",
            "withdrawOfferTitle": "Retirer l'offre",
            "couldNotAccept": "Impossible d'accepter",
            "couldNotDecline": "Impossible de refuser",
            "couldNotRemove": "Impossible de retirer",
            "couldNotCancelInvite": "Impossible d'annuler l'invitation",
            "couldNotWithdraw": "Impossible de retirer",
            "couldNotSendInvite": "Impossible d'envoyer l'invitation",
            "couldNotSendGameInvite": "Impossible d'envoyer l'invitation à jouer",
            "gameInvite": "Invitation à jouer",
            "gameInvitationsAria": "Invitations à jouer",
            "gameInvitationAria": "Invitation à jouer",
            "chessInviteTitle": "Invitation aux échecs",
            "wantsToPlayAsBlack": "{{name}} souhaite jouer. Vous jouez les Noirs.",
            "aFriend": "Un ami",
            "youPlayAsWhite": "Vous jouez les Blancs",
            "youPlayAsBlack": "Vous jouez les Noirs",
            "establishingGame": "Création de la partie…",
            "yourOpponent": "Votre adversaire",
            "declinedYourInvite": "{{name}} a refusé votre invitation à jouer.",
            "cancelInvite": "Annuler l'invitation",
            "accept": "Accepter",
            "decline": "Refuser",
            "invite": "Inviter",
            "remove": "Retirer",
            "offerSent": "Offre envoyée",
            "pending": "En attente",
            "online": "En ligne",
            "offline": "Hors ligne"
        },
        "adminPage": {
            "title": "Administration",
            "users": "Utilisateurs",
            "generate": "Générer",
            "games": "Parties",
            "engines": "Moteurs",
            "states": "États",
            "addUser": "Ajouter un utilisateur",
            "sectionsAria": "Sections d'administration",
            "openingBookLabel": "Livre d'ouvertures :",
            "gameLines": "lignes de parties",
            "noGamesInDb": "Aucune partie dans la base de données pour le moment.",
            "gamesPaginationAria": "Pagination des parties",
            "colNum": "#",
            "colUsername": "Nom d'utilisateur",
            "colType": "Type",
            "colEmail": "E-mail",
            "colPassword": "Mot de passe",
            "colLevel": "Niveau",
            "colElo": "Elo",
            "colJoined": "Inscription",
            "colLastLogin": "Dernière connexion",
            "colActiveGames": "Parties actives",
            "colFriends": "Amis",
            "colBookmarks": "Signets",
            "colId": "Id",
            "colStatus": "Statut",
            "colName": "Nom",
            "colAvailable": "Disponible",
            "colNotes": "Notes",
            "colNote": "Note",
            "colAction": "Action",
            "emptyUsers": "Aucun utilisateur pour le moment.",
            "emptyData": "Aucune donnée pour le moment.",
            "emptyStates": "Utilisez Générer pour ouvrir la page de génération du livre d'ouvertures et des états.",
            "clickToEdit": "Cliquer pour modifier",
            "updateFailed": "Échec de la mise à jour",
            "couldNotSave": "Impossible d'enregistrer",
            "setPassword": "Définir le mot de passe",
            "setPasswordTitle": "Cliquer pour définir un nouveau mot de passe (4–30 caractères)",
            "passwordLengthInvalid": "Le mot de passe doit comporter entre 4 et 30 caractères.",
            "invalidPassword": "Mot de passe invalide",
            "saved": "Enregistré",
            "newPasswordPlaceholder": "Nouveau mot de passe",
            "clickChangeUserType": "Cliquer pour changer le type d'utilisateur",
            "userTypeAria": "Type d'utilisateur",
            "changeUserTypeTitle": "Changer le type d'utilisateur",
            "grantAdminConfirm": "Accorder les privilèges d'administrateur à cet utilisateur ? Il pourra accéder aux outils d'administration et gérer les comptes.",
            "demoteAdminConfirm": "Passer cet utilisateur d'Admin à {{type}} ? Il perdra l'accès à la zone d'administration.",
            "changeUserTypeConfirm": "Passer cet utilisateur en {{type}} ?",
            "clickChangeLevel": "Cliquer pour changer le niveau",
            "playerLevelAria": "Niveau du joueur",
            "sortByRowNumber": "Trier par numéro de ligne",
            "sortBy": "Trier par {{key}}",
            "delete": "Supprimer",
            "first": "Premier",
            "last": "Dernier",
            "previous": "Précédent",
            "next": "Suivant",
            "previous5Pages": "5 pages précédentes",
            "next5Pages": "5 pages suivantes",
            "previous10Pages": "10 pages précédentes",
            "next10Pages": "10 pages suivantes",
            "userTypeAdmin": "Admin",
            "userTypePartner": "Partenaire",
            "userTypeMember": "Membre",
            "generateTitle": "Livre d'ouvertures et génération d'états",
            "backToAdmin": "← Retour à l'administration",
            "generateIntro": "Rejoue tous les fichiers PGN du dossier du gestionnaire de parties du serveur vers la collection Mongo State ou le livre d'ouvertures ligne par ligne (data/opening-book-lines.txt). Choisissez une cible, puis appuyez sur Démarrer la génération — rien ne s'exécute tant que vous ne le faites pas.",
            "target": "Cible",
            "targetMongo": "MongoDB — ajouter des lignes à la collection State",
            "targetBook": "Fichier de lignes — écrire le livre d'ouvertures (opening-book-lines.txt)",
            "startGeneration": "Démarrer la génération",
            "stop": "Arrêter",
            "idle": "Inactif.",
            "starting": "Démarrage…",
            "running": "En cours ({{mode}})…",
            "readingFiles": "Lecture de {{count}} fichier(s)…",
            "replayingGames": "Rejeu de {{count}} parties…",
            "writingOpeningBook": "Écriture du livre d'ouvertures…",
            "readingPgn": "Lecture PGN {{index}} / {{total}} ({{games}} parties)",
            "replayGameProgress": "Rejeu partie {{current}} / {{total}} (terminées ok : {{completed}})",
            "stopped": "Arrêté.",
            "bookUnchanged": "Le livre d'ouvertures existant n'a pas été modifié.",
            "bookLinesInFile": "{{count}} ligne(s) de partie dans {{file}}.",
            "cancelledBeforeRead": "Annulé avant la lecture des PGN.",
            "cancelledAfterRead": "Annulé après la lecture ; le rejeu a été ignoré (rien n'a été écrit).",
            "mongoGamesSaved": "{{count}} partie(s) ont eu de nouvelles lignes d'état enregistrées.",
            "doneBook": "Terminé. {{count}} lignes de parties → {{file}}",
            "doneBookFileOnly": "Terminé. {{file}}",
            "doneMongo": "Terminé. Collection MongoDB State mise à jour{{detail}}.",
            "doneMongoDetail": " ({{count}} parties rejouées ok)",
            "errorPrefix": "Erreur : {{message}}",
            "unknownError": "Inconnue",
            "connectionClosed": "Connexion fermée (consultez les journaux du serveur ou réessayez).",
            "openingBookDefault": "livre d'ouvertures"
        },
        "playNow": {
            "title": "Nouvelle partie",
            "startTitle": "Commencer une nouvelle partie",
            "playingColor": "Couleur jouée",
            "timeMin": "Temps (min)",
            "difficulty": "Difficulté (1–5)",
            "mousePreference": "Préférence souris",
            "drag": "Glisser",
            "doubleClick": "Double-clic",
            "showAvailableMoves": "Afficher les coups possibles",
            "private": "Privée",
            "playComputer": "Jouer contre l'ordinateur",
            "browseAll": "Tout parcourir",
            "yourHistory": "Votre historique",
            "fullList": "Liste complète",
            "gameLibrary": "Bibliothèque de parties",
            "openLibrarySearch": "Ouvrir la recherche dans la bibliothèque",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Parties en cours",
            "tagline": "Toutes les parties en cours",
            "liveGames": "Parties en direct",
            "game": "Partie",
            "started": "Commencée"
        },
        "list": {
            "title": "Toutes les parties",
            "action": "Action"
        },
        "searchPage": {
            "title": "Recherche :",
            "button": "Rechercher",
            "resultsFound": "{{count}} résultat(s) trouvé(s) :",
            "first": "Premier",
            "last": "Dernier",
            "previous": "Précédent",
            "next": "Suivant",
            "previous5Pages": "5 pages précédentes",
            "next5Pages": "5 pages suivantes",
            "previous10Pages": "10 pages précédentes",
            "next10Pages": "10 pages suivantes"
        },
        "game": {
            "moves": "Coups",
            "white": "Blanc",
            "black": "Noir",
            "resign": "Abandon",
            "draw": "Nulle",
            "undo": "Annuler le coup",
            "flip": "Retourner",
            "practice": "Entraînement"
        },
        "mobileWelcome": {
            "title": "Accueil — Échecs",
            "play": "Jouer",
            "library": "Bibliothèque",
            "friends": "Amis"
        },
        "mobileGame": {
            "title": "Partie",
            "moves": "Coups",
            "resign": "Abandon"
        }
    },
    "desktop": {
        "error": {
            "title": "Une erreur s'est produite",
            "body": "Une erreur s'est produite.",
            "back": "Retour à l'accueil"
        },
        "chrome": {
            "preferences": "Préférences",
            "display": "Affichage",
            "gameplay": "Jeu",
            "pieceSet": "Jeu de pièces",
            "boardTheme": "Thème de l'échiquier",
            "themeBlue": "Bleu",
            "themeDark": "Sombre",
            "customizeTheme": "Personnaliser le thème…",
            "builtInThemesAria": "Thèmes intégrés",
            "savedCustomThemesAria": "Thèmes personnalisés enregistrés",
            "pieceSetsAria": "Jeux de pièces",
            "homeAria": "Accueil Échecs Shmerling"
        },
        "prefs": {
            "language": "Langue",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "Contrôle à la souris",
            "thinkingTime": "Temps de réflexion",
            "thinkingTimeAria": "Temps de réflexion en secondes",
            "immediateResign": "Abandon immédiat",
            "secondsOption": "{{count}} s",
            "enterFullScreen": "Passer en plein écran",
            "exitFullScreen": "Quitter le plein écran",
            "fullScreenUnavailable": "Le plein écran n'est pas disponible dans ce navigateur."
        },
        "gameRun": {
            "yourColor": "Votre couleur",
            "engine": "Moteur",
            "thinkTime": "Temps de réflexion (secondes)",
            "thinkTimeAria": "Temps de réflexion du moteur en secondes",
            "play": "Jouer",
            "nextMove": "Prochain coup",
            "computer": "Ordinateur",
            "computerColorHint": "Couleur jouée par l'ordinateur — vous jouez l'autre camp"
        },
        "brainConfig": {
            "title": "Configuration du Brain",
            "save": "Enregistrer",
            "reset": "Réinitialiser",
            "saved": "Configuration enregistrée",
            "failedSave": "Échec de l'enregistrement de la configuration",
            "brainLabel": "Brain",
            "loading": "Chargement…",
            "failedLoad": "Échec du chargement de la configuration du Brain.",
            "discardSwitchConfirm": "Abandonner les modifications non enregistrées et changer de version du Brain ?",
            "discard": "Abandonner",
            "pieceScores": "Scores des pièces",
            "specialEvaluations": "Évaluations spéciales",
            "gamePhase": "Phase de partie",
            "pawnFilesOpeningMid": "Colonnes de pions (ouverture / milieu)",
            "pawnFilesEndGame": "Colonnes de pions (finale)"
        },
        "customTheme": {
            "title": "Thème personnalisé",
            "name": "Nom du thème",
            "save": "Enregistrer",
            "delete": "Supprimer",
            "saved": "Enregistré",
            "searchProperties": "Rechercher des propriétés",
            "filterPlaceholder": "Filtrer par nom de propriété…",
            "namePlaceholder": "Mon thème",
            "resetPreset": "Réinitialiser au préréglage actuel",
            "couldNotSave": "Impossible d'enregistrer le thème. Réessayez.",
            "untitled": "Sans titre",
            "defaultName": "Thème personnalisé"
        },
        "positionSetup": {
            "clearBoard": "Vider l'échiquier",
            "startingPosition": "Position initiale",
            "flipBoard": "Retourner l'échiquier",
            "eraser": "Gomme",
            "selectAndMove": "Sélectionner et déplacer",
            "defaultStartingPosition": "Position de départ par défaut",
            "savePosition": "Enregistrer la position",
            "saveAsNewPosition": "Enregistrer comme nouvelle position",
            "validatePosition": "Valider la position",
            "positionFlags": "Indicateurs de position",
            "turn": "Trait",
            "flagCheck": "Échec",
            "flagCheckmate": "Échec et mat",
            "flagDraw": "Nulle",
            "flagWhiteKingMoved": "Roi blanc déplacé",
            "flagBlackKingMoved": "Roi noir déplacé",
            "flagWhiteKingsideRookMoved": "Tour blanche côté roi déplacée",
            "flagWhiteQueensideRookMoved": "Tour blanche côté dame déplacée",
            "flagBlackKingsideRookMoved": "Tour noire côté roi déplacée",
            "flagBlackQueensideRookMoved": "Tour noire côté dame déplacée"
        }
    },
    "mobile": {
        "drawOfferTitle": "Proposition de nulle",
        "drawOfferMessage": "L'adversaire propose la nulle. Accepter ?",
        "rematchTitle": "Revanche",
        "rematchMessage": "L'adversaire propose une revanche. Accepter ?",
        "gameId": "ID de partie : {{id}}",
        "drawOfferAgree": "L'adversaire propose la nulle, accepter ?",
        "rematchOfferAgree": "L'adversaire propose une revanche, accepter ?",
        "newGameWatchFromHome": "Nouvelle partie lancée — allez à l'Accueil pour observer."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = frExtra;
    } else {
        global.ShmerlingStringsFrExtra = frExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
