/**
 * French string catalog — mirrors src/strings/en.js structure with French values.
 */
(function (global) {
    "use strict";

    const fr = {
        common: {
            white: "Blanc",
            black: "Noir",
            draw: "Nulle",
            winner: "Gagnant",
            engine: "Moteur",
            ok: "OK",
            cancel: "Annuler",
            confirm: "Confirmer",
            yes: "Oui",
            no: "Non",
            notice: "Avis",
            input: "Saisie",
            start: "Démarrer",
            collapse: "Réduire",
            expand: "Développer",
            delete: "Supprimer",
            rename: "Renommer",
            save: "Enregistrer",
            aPlayer: "Un joueur",
            pleaseEnterValue: "Veuillez saisir une valeur.",
        },
        play: {
            appTitle: "Échecs Shmerling",
            shell: {
                gameActions: "Actions de partie",
                playersAndClocks: "Joueurs et pendules",
                whitePlayerClock: "Pendule des Blancs",
                blackPlayerClock: "Pendule des Noirs",
                startFromLoadedPosition: "Commencer la partie depuis la position chargée",
                moves: "Coups",
                expandMovesPanel: "Développer le panneau des coups",
                expandMoves: "Développer les coups",
                collapseMovesPanel: "Réduire le panneau des coups",
                reviewNavigation: "Navigation de relecture",
                positionSetup: "Configuration de position",
                pieces: "Pièces",
                collapsePiecesPanel: "Réduire le panneau des pièces",
                brainConfiguration: "Configuration du Brain",
                configuration: "Configuration",
                collapseConfigurationPanel: "Réduire le panneau de configuration",
                games: "Parties",
                expandGamesPanel: "Développer le panneau des parties",
                expandGames: "Développer les parties",
                collapseGamesPanel: "Réduire le panneau des parties",
                chat: "Discussion",
                expandChatPanel: "Développer le panneau de discussion",
                collapseChatPanel: "Réduire le panneau de discussion",
                chatPlaceholder: "Écrire un message…",
                chatWatcherReadonly: "Les spectateurs peuvent seulement lire la discussion",
                sendChat: "Envoyer",
                savedListFilter: "Filtre de la liste enregistrée",
                positions: "Positions",
                gameStatus: "État de la partie",
                capturedPieces: "Pièces capturées",
            },
            sessionMode: {
                play: "Mode jeu",
                positionSetup: "Configuration de position",
                configuration: "Mode configuration",
                playback: "Mode lecture",
                review: "Mode relecture",
                watch: "Mode spectateur",
                practice: "Mode entraînement",
            },
            status: {
                chooseNewGameOrSetup:
                    "Choisissez Nouvelle partie ou Configuration de position dans la barre latérale",
                chooseNewGame: "Choisissez Nouvelle partie dans la barre latérale",
                setMoveColorEngineThinkTime:
                    "Définissez le coup, la couleur, le moteur et le temps de réflexion dans l'en-tête, puis appuyez sur Jouer",
                gameOver: "Partie terminée",
                gameInProgress: "Partie en cours",
                boardLoading: "L'échiquier est encore en cours de chargement…",
                boardNotReady: "L'échiquier n'est pas encore prêt. Veuillez patienter et réessayer.",
                leaveOnlineBeforeConfiguration:
                    "Quittez la partie en ligne avant d'ouvrir la Configuration",
                configurationNotInPractice:
                    "La configuration n'est pas disponible en mode Entraînement",
                configurationModeEdit:
                    "Mode configuration — modifiez les valeurs et enregistrez",
                selectSavedOrSetup:
                    "Sélectionnez d'abord une partie enregistrée ou configurez une position sur l'échiquier",
                gameAlreadyInProgress: "Une partie est déjà en cours",
                yourMove: "À vous de jouer",
                engineToMove: "Le moteur réfléchit…",
                leaveOnlineBeforePositionSetup:
                    "Quittez la partie en ligne avant d'ouvrir la Configuration de position",
                positionSetupNotInPractice:
                    "La configuration de position n'est pas disponible en mode Entraînement",
                positionSetupPlacePieces:
                    "Configuration de position — placez les pièces sur l'échiquier",
                drawWithReason: "Nulle — {{reason}}",
                checkmateWins: "Échec et mat — {{winner}} gagne",
                check: "Échec",
                waitBeforeEvaluate:
                    "Attendez la fin du coup en cours avant d'évaluer",
                evaluationUnavailable:
                    "L'évaluation n'est pas disponible. Redémarrez l'application Échecs Shmerling.",
                evaluatingPosition: "Évaluation de la position…",
                evaluationFailed: "Évaluation échouée",
                evaluationLine: "Évaluation ({{side}} au trait) : {{score}}",
                checkmate: "Échec et mat",
                drawZero: "Nulle (0)",
                totalLabel: "Total : {{value}}",
                openFolderDesktopOnly:
                    "Ouvrir le dossier n'est disponible que dans l'application de bureau",
                couldNotOpenGamesLogFolder: "Impossible d'ouvrir le dossier du journal des parties",
                positionValid: "La position est valide",
                playingFromCustomPosition: "Partie depuis une position personnalisée",
                nothingToSave: "Rien à enregistrer",
                positionSaved: "Position enregistrée",
                couldNotSavePosition: "Impossible d'enregistrer la position",
                savedPositionNotFound: "Position enregistrée introuvable",
                positionUpdated: "Position mise à jour",
                couldNotUpdatePosition: "Impossible de mettre à jour la position",
                nameCannotBeEmpty: "Le nom ne peut pas être vide",
                gameRenamed: "Partie renommée",
                couldNotRenameGame: "Impossible de renommer la partie",
                deletedCount: "{{count}} élément(s) supprimé(s)",
                couldNotDeleteSelected: "Impossible de supprimer les éléments sélectionnés",
                couldNotLoadSavedGame: "Impossible de charger la partie enregistrée",
                editingPositionSaveBookmark:
                    "Modification de position — Enregistrez pour mettre à jour ce signet",
                couldNotOpenPositionForEditing:
                    "Impossible d'ouvrir la position pour modification",
                gameSaved: "Partie enregistrée",
                couldNotSaveGame: "Impossible d'enregistrer la partie",
                engineMoveNotApplied: "Le coup du moteur n'a pas pu être appliqué",
                engineCouldNotFindMove: "Le moteur n'a pas trouvé de coup",
                engineError: "Erreur du moteur",
                engineThinking: "Le moteur réfléchit…",
                sessionError: "Erreur de session",
                timesUpLost: "Temps écoulé ! {{loser}} a perdu",
                drawOfferTitle: "Proposition de nulle",
                drawOfferMessage: "L'adversaire propose la nulle. Accepter ?",
                rematchTitle: "Revanche",
                playerDisconnectedWaiting:
                    "{{who}} s'est déconnecté — en attente de reconnexion ({{countdown}})",
                opponentDisconnectedCountdown:
                    "Adversaire déconnecté — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "Partie annulée — délai de reconnexion dépassé sans coup joué.",
                playerFailedToReconnectWins:
                    "{{loser}} n'a pas pu se reconnecter — {{winner}} gagne",
                gameOverOpponentFailedReconnect:
                    "Partie terminée — l'adversaire n'a pas pu se reconnecter.",
                couldNotStartRematch: "Impossible de lancer la revanche",
                rematchStarted: "Revanche lancée",
                gameCancelled: "Partie annulée",
                gameCancelledWithDetail: "Partie annulée — {{detail}}",
                resignFailed: "Abandon échoué",
                gameResumedYourMove: "Partie reprise — à vous de jouer",
                practiceNotAvailable: "Le mode Entraînement n'est pas disponible",
                couldNotJoinOnPlay: "Impossible de rejoindre cette partie sur /play",
                practiceDebugNotAvailable:
                    "Entraînement / Débogage n'est pas disponible pour ce compte",
                reviewRequiresWebApi: "La relecture nécessite l'API web",
                couldNotLoadReviewGame: "Impossible de charger la partie en relecture",
                notReviewGameLink: "Ce lien n'est pas une partie en relecture",
                onlineRequiresWebApi: "Le jeu en ligne nécessite l'API web",
                couldNotLoadOnlineGame: "Impossible de charger la partie en ligne",
                notOnlineGameOnPlay: "Ce lien n'est pas une partie en ligne sur /play",
                watchingLiveGame: "Observation d'une partie en direct",
                waitingForOpponentToJoin: "En attente de l'adversaire…",
                waitingForOpponent: "En attente de l'adversaire…",
                onlineGameConnected: "Partie en ligne — connecté",
                gameDeleted: "Partie supprimée",
                itemsDeleted: "{{count}} éléments supprimés",
                choosePromotionPiece: "Choisissez la pièce de promotion",
                invalidPromotionPiece: "Pièce de promotion invalide",
                drawOfferNotAvailable: "La proposition de nulle n'est pas disponible pour le moment",
            },
            drawReasons: {
                stalemate: "Pat",
                fiftyMoves: "50 coups",
                insufficientMaterial: "Matériel insuffisant",
                threefoldRepetition: "Triple répétition",
                drawOfferAccepted: "Proposition de nulle des {{by}} acceptée",
            },
            actions: {
                newGame: "Nouvelle partie",
                resign: "Abandon",
                draw: "Nulle",
                undo: "Annuler le coup",
                redo: "Refaire",
                lastMove: "Dernier coup",
                positionSetup: "Configuration de position",
                config: "Config",
                flip: "Retourner",
                save: "Enregistrer",
                exit: "Quitter",
                loadToStart: "Charger pour commencer",
                editPosition: "Modifier la position",
            },
            savedGames: {
                defaultName: "Partie enregistrée",
                nameAriaLabel: "Nom de la partie enregistrée",
                showDetails: "Afficher les détails",
                detailsAriaLabel: "Détails de la partie enregistrée",
                editPosition: "Modifier la position",
                deleteSavedGame: "Supprimer la partie enregistrée",
                renameSavedGame: "Renommer la partie enregistrée",
                noSavedPositions: "Aucune position enregistrée pour le moment.",
                noSavedGames: "Aucune partie enregistrée pour le moment.",
                nextMoveDash: "Prochain coup : —",
                nextMove: "Prochain coup : {{side}}",
                player: "Joueur",
                savedAt: "Enregistré : {{when}}",
                gameId: "ID de partie : {{id}}",
                playersVs: "{{white}} contre {{black}}",
            },
            reviewNav: {
                start: "Début",
                back: "Retour",
                play: "Lecture",
                pause: "Pause",
                forward: "Avancer",
                end: "Fin",
            },
            newGameDialog: {
                title: "Nouvelle partie contre l'IA",
                yourColor: "Votre couleur",
                engine: "Moteur",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "Temps par camp (minutes)",
                allowUndo: "Autoriser l'annulation du coup",
                private: "Privée",
                privateHint:
                    "Les parties privées n’apparaissent pas dans les listes de parties actives des autres membres.",
            },
            prompts: {
                positionName: "Nom de la position",
                savePositionAs: "Enregistrer la position sous",
            },
            dialogs: {
                resignTitle: "Abandonner cette partie ?",
                resignBody: "Vous perdrez la partie.",
                leaveTitle: "Quitter la partie ?",
                leaveBody: "Votre partie sera abandonnée.",
                areYouSure: "Êtes-vous sûr ?",
                discardUnsavedBrainConfig:
                    "Abandonner les modifications non enregistrées de la configuration du Brain ?",
                accept: "Accepter",
                decline: "Refuser",
                saveAs: "Enregistrer sous",
                savePosition: "Enregistrer la position",
                invalidPosition: "Position invalide",
                rematchChooseColor: "Choisissez votre couleur pour la revanche :",
                rematchOfferAgree: "L'adversaire propose une revanche. Accepter ?",
                rematchColorPreference:
                    "L'adversaire souhaite jouer les {{offerer}}. Vous joueriez les {{you}}. Accepter ?",
            },
        },
        session: {
            engineThinking: "Le moteur réfléchit…",
            engineCouldNotFindMove: "Le moteur n'a pas trouvé de coup",
            engineError: "Erreur du moteur",
            positionSetupPlacePieces: "Configuration de position — placez les pièces sur l'échiquier",
            configurationModeEdit: "Mode configuration — modifiez les valeurs et enregistrez",
            practiceBothSides: "Entraînement — les deux camps",
            opponentDisconnected: "Adversaire déconnecté",
            opponentRejoined: "L'adversaire s'est reconnecté",
            playerRejoined: "{{name}} s'est reconnecté",
            drawOfferSent: "Proposition de nulle envoyée",
            drawOfferDeclined: "Proposition de nulle refusée",
            rematchOfferSent: "Proposition de revanche envoyée",
            rematchOfferDeclined: "Proposition de revanche refusée",
            drawAgreed: "Nulle convenue",
            rematchAcceptedNoGameId: "Revanche acceptée mais aucun nouvel identifiant de partie",
            rematchOfferAccepted: "Proposition de revanche acceptée",
            gameOver: "Partie terminée",
            somethingWentWrong: "Une erreur s'est produite",
            opponentResigned: "L'adversaire a abandonné",
            opponentLeftGame: "L'adversaire a quitté la partie",
            opponentFailedToReconnect: "L'adversaire n'a pas pu se reconnecter",
            gameCancelled: "Partie annulée",
            gameCancelledWithDetail: "Partie annulée — {{detail}}",
            waitingForOpponent: "En attente de l'adversaire…",
            couldNotResolveWebSocketUrl: "Impossible de résoudre l'URL WebSocket",
            opponentJoined: "{{name}} a rejoint la partie",
            opponentDefault: "Adversaire",
            connectionError: "Erreur de connexion",
            playerDisconnectedWaitingRejoin:
                "{{name}} s'est déconnecté — en attente de reconnexion",
            playerFailedToReconnectWins:
                "{{loser}} n'a pas pu se reconnecter — {{winner}} gagne",
            watcherWaitingForReconnect: "En attente de la reconnexion d'un joueur…",
        },
        site: {
            confirm: "Confirmer",
            cancel: "Annuler",
            notice: "Avis",
            ok: "OK",
            home: "Accueil",
            search: "Recherche",
            friends: "Amis",
            groups: "Groupes",
            debug: "Débogage",
            account: "Compte",
            preferences: "Préférences",
            administrate: "Administration",
            logOut: "Se déconnecter",
            logIn: "Se connecter",
            admin: "Admin",
            homeAria: "Accueil",
        },
        validation: {
            validEmail: "Veuillez saisir une adresse e-mail valide",
            passwordsMustMatch: "Veuillez vous assurer que les champs Mot de passe sont identiques.",
            chooseUsername: "Veuillez choisir un nom d'utilisateur",
            usernameNotAvailable: "Ce nom d'utilisateur n'est pas disponible",
            passwordNoWhitespace: "Le mot de passe ne doit pas contenir d'espaces.",
            passwordUppercase: "Le mot de passe doit contenir au moins une majuscule.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = fr;
    } else {
        global.ShmerlingStringsFr = fr;
    }
})(typeof window !== "undefined" ? window : globalThis);
