(function (global) {
    "use strict";
    const heExtra = {
    "validation": {
        "passwordLowercase": "הסיסמה חייבת להכיל לפחות אות קטנה אחת.",
        "passwordDigit": "הסיסמה חייבת להכיל לפחות ספרה אחת.",
        "passwordSymbol": "הסיסמה חייבת להכיל לפחות סימן מיוחד אחד.",
        "passwordLength": "הסיסמה חייבת להיות באורך של 8-30 תווים.",
        "noHtml": "{{label}} לא יכול לכלול HTML.",
        "position": {
            "headerSave": "לא ניתן לשמור עמדה זו:\n\n",
            "headerPlay": "לא ניתן לשחק מעמדה זו:\n\n",
            "headerUse": "לא ניתן להשתמש בעמדה זו:\n\n",
            "headerSaveBookmark": "לא ניתן לשמור סימנייה זו:\n\n",
            "headerAddBookmark": "לא ניתן להוסיף סימנייה זו:\n\n",
            "boardUnreadable": "לא ניתן היה לקרוא את הלוח. נסה שוב לאחר שהלוח ייטען.",
            "whiteKingNone": "חייב להיות מלך לבן אחד בדיוק על הלוח. לא נמצא אף אחד.",
            "whiteKingCount": "חייב להיות מלך לבן אחד בדיוק על הלוח. נמצאו {{count}} מלכים לבנים.",
            "blackKingNone": "חייב להיות מלך שחור אחד בדיוק על הלוח. לא נמצא אף אחד.",
            "blackKingCount": "חייב להיות מלך שחור אחד בדיוק על הלוח. נמצאו {{count}} מלכים שחורים.",
            "kingsAdjacent": "שני המלכים לא יכולים להיות בריבועים סמוכים (כולל באלכסון).",
            "sideInCheck": "{{mover}} אמור/ה לזוז, אך המלך של {{king}} כבר נמצא בשח. הצד שעל התור לא יכול להיות זה שנותן שח — שנה את התור או הזז כלים.",
            "drawInsufficientKings": "עמדה זו היא תיקו עקב חומר בלתי מספיק (מלך מול מלך). הוסף כלים כדי שמט יישאר אפשרי.",
            "drawInsufficientMinor": "עמדה זו היא תיקו עקב חומר בלתי מספיק (מלך ורץ או פרש מול מלך בודד). הוסף כלים כדי שמט יישאר אפשרי.",
            "drawBishopsSameColor": "עמדה זו היא תיקו עקב חומר בלתי מספיק (רץ מול רץ באותו צבע משבצת). הוסף כלים כדי שמט יישאר אפשרי.",
            "tooManyQueens": "ל{{color}} יש {{count}} מלכות; המקסימום הוא 9 לכל צבע.",
            "tooManyRooks": "ל{{color}} יש {{count}} צריחים; המקסימום הוא 10 לכל צבע.",
            "tooManyBishops": "ל{{color}} יש {{count}} רצים; המקסימום הוא 10 לכל צבע.",
            "tooManyKnights": "ל{{color}} יש {{count}} פרשים; המקסימום הוא 10 לכל צבע.",
            "tooManyPawns": "ל{{color}} יש {{count}} רגלים; המקסימום הוא 8 לכל צבע."
        }
    },
    "auth": {
        "whoAreYou": "מי אתה?",
        "enterPassword": "הזן את הסיסמה שלך",
        "sorry": "מצטערים",
        "continue": "המשך",
        "usernameField": "שם משתמש",
        "passwordField": "סיסמה",
        "wrongCredentials": "שם משתמש או סיסמה שגויים",
        "userAdded": "המשתמש נוסף בהצלחה",
        "couldNotSaveBookmark": "לא ניתן לשמור את הסימנייה",
        "invalidUserId": "מזהה משתמש לא תקין",
        "generationJobRunning": "משימת יצירה נוספת כבר פועלת…",
        "listingPgnFiles": "מציג רשימת קבצי PGN…"
    },
    "classic": {
        "loadGame": "טען משחק",
        "load": "טען",
        "enterGameState": "הדבק כאן את מצב המשחק...",
        "rematch": "משחק חוזר",
        "drawOffer": "הצעת תיקו",
        "lastMove": "מהלך אחרון",
        "bookmarks": "סימניות",
        "bookmarkAlertTitle": "סמן עמדה",
        "promotion": "הכתרה!",
        "check": "שח",
        "checkmateWins": "מט! {{winner}} מנצח/ת!",
        "drawReason": "תיקו! {{reason}}",
        "opponentDisconnected": "היריב התנתק",
        "opponentResignedWins": "היריב נכנע, {{winner}} מנצח/ת",
        "somethingWentWrong": "משהו השתבש",
        "playerRejoined": "{{name}} חזר/ה",
        "aPlayerRejoined": "שחקן חזר",
        "opponentRejoined": "היריב חזר",
        "rematchOfferAccepted": "הצעת המשחק החוזר התקבלה",
        "rematchOfferDeclined": "הצעת המשחק החוזר נדחתה",
        "sideOffersDraw": "{{side}} מציע/ה תיקו",
        "drawOfferDeclined": "הצעת התיקו נדחתה",
        "watcherWatching": "{{name}} צופה במשחק",
        "drawOfferSent": "הצעת תיקו נשלחה",
        "rematchOfferSent": "הצעת משחק חוזר נשלחה",
        "newGameStarted": "משחק חדש החל",
        "gameOver": "המשחק הסתיים",
        "gameCancelled": "המשחק בוטל",
        "youResignedWins": "נכנעת, {{winner}} מנצח/ת",
        "movesCopied": "המהלכים הועתקו ללוח!",
        "failedCopyMoves": "העתקת המהלכים נכשלה",
        "failedLoadBrainConfig": "טעינת הגדרות המוח נכשלה.",
        "failedSaveBrainConfig": "שמירת הגדרות המוח נכשלה.",
        "offerDrawConfirm": "להציע תיקו?",
        "drawOfferAccept": "היריב שלח הצעת תיקו, לקבל?",
        "rematchOfferAccept": "היריב הציע משחק חוזר, להסכים?",
        "confirmExitGame": "האם אתה בטוח שברצונך לצאת מהמשחק?",
        "mobileResign": "כניעה",
        "mobileRematch": "משחק חוזר",
        "mobileDraw": "תיקו",
        "mobileFlip": "הפוך",
        "mobileLastMove": "מהלך אחרון",
        "mobileMovesList": "רשימת מהלכים",
        "researchToolbox": "ארגז כלים",
        "researchBrainConfig": "הגדרות מוח",
        "researchSave": "שמור",
        "researchDiscard": "בטל",
        "researchEditMode": "מצב עריכה",
        "researchRun": "הרץ",
        "researchProperty": "מאפיין",
        "researchValue": "ערך",
        "playerOnline": "מחובר",
        "playerDisconnectedStatus": "מנותק",
        "playerOffline": "לא מחובר",
        "humanVsComputer": "אדם נגד מחשב",
        "newGameTwoPlayers": "משחק חדש לשני שחקנים",
        "settings": "הגדרות",
        "help": "עזרה",
        "drawOffersNotVsEngine": "הצעות תיקו אינן זמינות במשחק נגד המנוע.",
        "failedStartFromBookmark": "התחלת המשחק מהסימנייה נכשלה.",
        "resignConfirm": "להיכנע?",
        "areYouSure": "האם אתה בטוח?",
        "gameOverOpponentFailedReconnectWinsClassic": "המשחק הסתיים — היריב לא הצליח להתחבר מחדש. {{winner}} מנצח/ת.",
        "reconnectTimeoutNoMoves": "הזמן להתחברות מחדש פג ולא בוצעו מהלכים.",
        "waitingOpponentRejoin": "ממתין ליריב שיחזור",
        "timeoutOneSec": "פסק זמן: שנייה 1",
        "timeoutSecs": "פסק זמן: {{count}} שניות",
        "whitePieceAlt": "כלי לבן",
        "blackPieceAlt": "כלי שחור",
        "eraserTitle": "מחק",
        "eraserAria": "מחק – הסר כלי מהמשבצת",
        "selectTitle": "בחר",
        "selectAria": "בחר – גרור כלים כדי להזיז אותם",
        "resetAria": "איפוס – נקה את כל הכלים",
        "defaultPositionAria": "עמדת ברירת מחדל – הצב את עמדת הפתיחה הסטנדרטית",
        "loading": "טוען...",
        "engineLabel": "מנוע"
    },
    "site": {
        "home": "בית",
        "search": "חיפוש",
        "friends": "חברים",
        "groups": "קבוצות",
        "debug": "דיבוג",
        "account": "חשבון",
        "preferences": "העדפות",
        "administrate": "ניהול",
        "logOut": "התנתק",
        "logIn": "התחבר",
        "admin": "מנהל",
        "homeAria": "בית",
        "confirm": "אשר",
        "cancel": "ביטול",
        "notice": "הודעה",
        "ok": "אישור",
        "username": "שם משתמש:",
        "password": "סיסמה:",
        "login": "התחברות",
        "register": {
            "submit": "הרשמה",
            "confirmPassword": "אימות סיסמה:",
            "playerLevel": "רמת שחקן:",
            "rookie": "מתחיל",
            "skilled": "מתקדם",
            "elite": "אומן",
            "grandMaster": "רב אומן"
        },
        "email": "אימייל:",
        "welcome": {
            "greeting": "ברוך שובך",
            "tagline": "התור שלך מחכה",
            "playNow": "שחק עכשיו!",
            "activeGames": "משחקים פעילים",
            "live": "חי",
            "showAll": "הצג הכל",
            "viewAllActive": "צפה בכל המשחקים הפעילים",
            "mostRecent": "העדכניים ביותר קודם",
            "noGamesNow": "אין משחקים כרגע",
            "myGames": "המשחקים שלי",
            "viewAllGames": "צפה בכל המשחקים",
            "recentCompleted": "המשחקים האחרונים שהסתיימו שלך",
            "noCompleted": "אין עדיין משחקים שהסתיימו",
            "activeGamesAria": "משחקים פעילים",
            "inviteOnlineFriend": "הזמן חבר מחובר למשחק",
            "friendsPageTitle": "עמוד חברים",
            "manageFriends": "ניהול",
            "colFriend": "חבר",
            "colStatus": "סטטוס",
            "findPlayers": "מצא שחקנים",
            "waitingForResponse": "ממתין לתגובה",
            "inviteSentSuffix": "(הזמנה נשלחה)",
            "sortByRowNumber": "מיין לפי מספר שורה",
            "sortBy": "מיין לפי {{key}}"
        },
        "gameList": {
            "date": "תאריך",
            "time": "שעה",
            "result": "תוצאה",
            "reason": "סיבה",
            "type": "סוג",
            "status": "סטטוס",
            "event": "אירוע",
            "site": "אתר",
            "round": "סיבוב"
        },
        "loginPage": {
            "title": "התחברות"
        },
        "error": {
            "title": "משהו השתבש",
            "body": "אירעה שגיאה.",
            "back": "חזרה לעמוד הראשי"
        },
        "log": {
            "title": "יומן שרת",
            "clear": "נקה תצוגה",
            "latest": "אחרון",
            "waiting": "ממתין לפלט יומן השרת…"
        },
        "activeGames": {
            "moves": "מהלכים",
            "turn": "תור",
            "status": "מצב",
            "inProgress": "בתהליך",
            "onHold": "בהמתנה",
            "vs": " נגד ",
            "minutesAgo": "לפני {{count}} דקות",
            "oneMinuteAgo": "לפני דקה",
            "justStarted": "רק התחיל",
            "notStarted": "לא התחיל",
            "startedTooltip": "התחלה: {{when}}",
            "playersVs": "{{white}} נגד {{black}}"
        },
        "friendsPage": {
            "title": "חברים",
            "tagline": "מצא יריבי שחמט חדשים",
            "myFriends": "החברים שלי",
            "noFriendsYet": "אין עדיין חברים",
            "findPlayers": "מצא שחקנים",
            "searchByUsername": "חפש לפי שם משתמש",
            "searchPlaceholder": "הקלד כדי לחפש…",
            "enterCharToSearch": "הזן לפחות תו אחד כדי לחפש",
            "noMatchingUsers": "לא נמצאו משתמשים תואמים",
            "playing": "משחק/ת",
            "pendingFriendshipOffer": "הצעת חברות ממתינה",
            "joining": "מצטרף/ת",
            "rejoin": "הצטרף מחדש",
            "friendRequest": "בקשת חברות",
            "wantsToBeFriends": "(רוצה להיות חבר/ה)",
            "pendingOfferSuffix": "(הצעת חברות ממתינה)",
            "waitingFriendRespond": "ממתין לתגובת החבר/ה שלך",
            "cancelBeforeRemove": "בטל את הזמנת המשחק לפני הסרת חבר זה",
            "friendsTag": "חברים",
            "offerReceivedTag": "התקבלה הצעה — ראה החברים שלך",
            "addFriend": "הוסף חבר",
            "withdraw": "משוך בחזרה",
            "requestFailed": "הבקשה נכשלה",
            "removeFriendConfirm": "להסיר את החבר הזה מהרשימה שלך?",
            "removeFriendTitle": "הסר חבר",
            "withdrawOfferConfirm": "למשוך בחזרה את הצעת החברות הזו?",
            "withdrawOfferTitle": "משוך הצעה בחזרה",
            "couldNotAccept": "לא ניתן לקבל",
            "couldNotDecline": "לא ניתן לדחות",
            "couldNotRemove": "לא ניתן להסיר",
            "couldNotCancelInvite": "לא ניתן לבטל את ההזמנה",
            "couldNotWithdraw": "לא ניתן למשוך בחזרה",
            "couldNotSendInvite": "לא ניתן לשלוח הזמנה",
            "couldNotSendGameInvite": "לא ניתן לשלוח הזמנת משחק",
            "gameInvite": "הזמנת משחק",
            "gameInvitationsAria": "הזמנות למשחק",
            "gameInvitationAria": "הזמנה למשחק",
            "chessInviteTitle": "הזמנה לשחמט",
            "wantsToPlayAsBlack": "{{name}} רוצה לשחק. אתה משחק בשחור.",
            "aFriend": "חבר",
            "youPlayAsWhite": "אתה משחק בלבן",
            "youPlayAsBlack": "אתה משחק בשחור",
            "establishingGame": "יוצרים משחק…",
            "yourOpponent": "היריב שלך",
            "declinedYourInvite": "{{name}} דחה/תה את הזמנת המשחק שלך.",
            "cancelInvite": "בטל הזמנה",
            "accept": "קבל",
            "decline": "דחה",
            "invite": "הזמן",
            "remove": "הסר",
            "offerSent": "ההצעה נשלחה",
            "pending": "ממתין",
            "online": "מחובר",
            "offline": "לא מחובר"
        },
        "adminPage": {
            "title": "ניהול",
            "users": "משתמשים",
            "generate": "יצירה",
            "games": "משחקים",
            "engines": "מנועים",
            "states": "מצבים",
            "addUser": "הוסף משתמש",
            "sectionsAria": "אזורי ניהול",
            "openingBookLabel": "ספר פתיחות:",
            "gameLines": "שורות משחק",
            "noGamesInDb": "אין עדיין משחקים במסד הנתונים.",
            "gamesPaginationAria": "דפדוף משחקים",
            "colNum": "#",
            "colUsername": "שם משתמש",
            "colType": "סוג",
            "colEmail": "אימייל",
            "colPassword": "סיסמה",
            "colLevel": "רמה",
            "colElo": "אלו",
            "colJoined": "הצטרף",
            "colLastLogin": "כניסה אחרונה",
            "colActiveGames": "משחקים פעילים",
            "colFriends": "חברים",
            "colBookmarks": "סימניות",
            "colId": "מזהה",
            "colStatus": "מצב",
            "colName": "שם",
            "colAvailable": "זמין",
            "colNotes": "הערות",
            "colNote": "הערה",
            "colAction": "פעולה",
            "emptyUsers": "אין עדיין משתמשים.",
            "emptyData": "אין עדיין נתונים.",
            "emptyStates": "השתמש ביצירה כדי לפתוח את עמוד יצירת ספר הפתיחות והמצבים.",
            "clickToEdit": "לחץ לעריכה",
            "updateFailed": "העדכון נכשל",
            "couldNotSave": "לא ניתן לשמור",
            "setPassword": "הגדר סיסמה",
            "setPasswordTitle": "לחץ כדי להגדיר סיסמה חדשה (4–30 תווים)",
            "passwordLengthInvalid": "הסיסמה חייבת להיות בין 4 ל-30 תווים.",
            "invalidPassword": "סיסמה לא תקינה",
            "saved": "נשמר",
            "newPasswordPlaceholder": "סיסמה חדשה",
            "clickChangeUserType": "לחץ כדי לשנות את סוג המשתמש",
            "userTypeAria": "סוג משתמש",
            "changeUserTypeTitle": "שנה סוג משתמש",
            "grantAdminConfirm": "להעניק למשתמש זה הרשאות מנהל? הוא/היא יוכל/תוכל לגשת לכלי הניהול ולנהל חשבונות.",
            "demoteAdminConfirm": "לשנות את המשתמש הזה ממנהל ל-{{type}}? הוא/היא יאבד/תאבד גישה לאזור הניהול.",
            "changeUserTypeConfirm": "לשנות את המשתמש הזה ל-{{type}}?",
            "clickChangeLevel": "לחץ כדי לשנות רמה",
            "playerLevelAria": "רמת שחקן",
            "sortByRowNumber": "מיין לפי מספר שורה",
            "sortBy": "מיין לפי {{key}}",
            "delete": "מחק",
            "first": "ראשון",
            "last": "אחרון",
            "previous": "הקודם",
            "next": "הבא",
            "previous5Pages": "5 עמודים אחורה",
            "next5Pages": "5 עמודים קדימה",
            "previous10Pages": "10 עמודים אחורה",
            "next10Pages": "10 עמודים קדימה",
            "userTypeAdmin": "מנהל",
            "userTypePartner": "שותף",
            "userTypeMember": "חבר",
            "generateTitle": "יצירת ספר פתיחות ומצבים",
            "backToAdmin": "← חזרה לניהול",
            "generateIntro": "משחזר את כל קובצי ה-PGN שנמצאים בתיקיית מנהל המשחקים של השרת, אל תוך אוסף המצבים ב-Mongo או אל ספר הפתיחות מבוסס השורות (data/opening-book-lines.txt). בחר יעד, ולאחר מכן לחץ על התחל יצירה — שום דבר לא ירוץ עד שתעשה זאת.",
            "target": "יעד",
            "targetMongo": "MongoDB — הוסף שורות לאוסף המצבים",
            "targetBook": "קובץ שורות — כתוב ספר פתיחות (opening-book-lines.txt)",
            "startGeneration": "התחל יצירה",
            "stop": "עצור",
            "idle": "ממתין.",
            "starting": "מתחיל…",
            "running": "רץ ({{mode}})…",
            "readingFiles": "קורא {{count}} קבצים…",
            "replayingGames": "משחזר {{count}} משחקים…",
            "writingOpeningBook": "כותב ספר פתיחות…",
            "readingPgn": "קורא PGN {{index}} / {{total}} ({{games}} משחקים)",
            "replayGameProgress": "משחזר משחק {{current}} / {{total}} (הושלמו בהצלחה: {{completed}})",
            "stopped": "נעצר.",
            "bookUnchanged": "ספר הפתיחות הקיים לא שונה.",
            "bookLinesInFile": "{{count}} שורות משחק ב-{{file}}.",
            "cancelledBeforeRead": "בוטל לפני קריאת קובצי ה-PGN.",
            "cancelledAfterRead": "בוטל לאחר הקריאה; השחזור דולג (שום דבר לא נכתב).",
            "mongoGamesSaved": "ל-{{count}} משחקים נשמרו שורות מצב חדשות.",
            "doneBook": "הסתיים. {{count}} שורות משחק → {{file}}",
            "doneBookFileOnly": "הסתיים. {{file}}",
            "doneMongo": "הסתיים. אוסף המצבים ב-MongoDB עודכן{{detail}}.",
            "doneMongoDetail": " ({{count}} משחקים שוחזרו בהצלחה)",
            "errorPrefix": "שגיאה: {{message}}",
            "unknownError": "לא ידוע",
            "connectionClosed": "החיבור נסגר (בדוק את יומני השרת או נסה שוב).",
            "openingBookDefault": "ספר פתיחות"
        },
        "playNow": {
            "title": "משחק חדש",
            "startTitle": "התחל משחק חדש",
            "playingColor": "צבע משחק",
            "timeMin": "זמן (דקות)",
            "difficulty": "רמת קושי (1–5)",
            "mousePreference": "העדפת עכבר",
            "drag": "גרירה",
            "doubleClick": "לחיצה כפולה",
            "showAvailableMoves": "הצג מהלכים אפשריים",
            "private": "פרטי",
            "playComputer": "שחק נגד מחשב",
            "browseAll": "עיין בהכל",
            "yourHistory": "ההיסטוריה שלך",
            "fullList": "הרשימה המלאה",
            "gameLibrary": "ספריית משחקים",
            "openLibrarySearch": "פתח חיפוש בספרייה",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "משחקים פעילים",
            "tagline": "כל המשחקים בעיצומם",
            "liveGames": "משחקים חיים",
            "game": "משחק",
            "started": "התחיל"
        },
        "list": {
            "title": "כל המשחקים",
            "action": "פעולה"
        },
        "searchPage": {
            "title": "חיפוש:",
            "tagline": "מצא משחקים בארכיון ה-PGN",
            "results": "תוצאות",
            "resultsCount": "{{count}} תוצאות",
            "noResults": "אין משחקים התואמים לחיפוש",
            "button": "חיפוש",
            "resultsFound": "נמצאו {{count}} תוצאות:",
            "first": "ראשון",
            "last": "אחרון",
            "previous": "הקודם",
            "next": "הבא",
            "previous5Pages": "5 עמודים אחורה",
            "next5Pages": "5 עמודים קדימה",
            "previous10Pages": "10 עמודים אחורה",
            "next10Pages": "10 עמודים קדימה"
        },
        "game": {
            "moves": "מהלכים",
            "white": "לבן",
            "black": "שחור",
            "resign": "כניעה",
            "draw": "תיקו",
            "undo": "בטל מהלך",
            "flip": "הפוך לוח",
            "practice": "תרגול"
        },
        "mobileWelcome": {
            "title": "בית — שחמט",
            "play": "שחק",
            "library": "ספרייה",
            "friends": "חברים"
        },
        "mobileGame": {
            "title": "משחק",
            "moves": "מהלכים",
            "resign": "כניעה"
        }
    },
    "desktop": {
        "error": {
            "title": "משהו השתבש",
            "body": "אירעה שגיאה.",
            "back": "חזרה לעמוד הראשי"
        },
        "chrome": {
            "preferences": "העדפות",
            "display": "תצוגה",
            "gameplay": "משחקיות",
            "pieceSet": "ערכת כלים",
            "boardTheme": "ערכת נושא ללוח",
            "themeBlue": "כחול",
            "themeDark": "כהה",
            "customizeTheme": "התאם ערכת נושא…",
            "builtInThemesAria": "ערכות נושא מובנות",
            "savedCustomThemesAria": "ערכות נושא מותאמות שמורות",
            "pieceSetsAria": "ערכות כלים",
            "homeAria": "בית שחמט שמרלינג"
        },
        "prefs": {
            "language": "שפה",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "שליטת עכבר",
            "thinkingTime": "זמן חשיבה",
            "thinkingTimeAria": "זמן חשיבה בשניות",
            "immediateResign": "כניעה מיידית",
            "secondsOption": "{{count}} שנ׳",
            "enterFullScreen": "מסך מלא",
            "exitFullScreen": "יציאה ממסך מלא",
            "fullScreenUnavailable": "מסך מלא אינו זמין בדפדפן זה."
        },
        "gameRun": {
            "yourColor": "הצבע שלך",
            "engine": "מנוע",
            "thinkTime": "זמן חשיבה (שניות)",
            "thinkTimeAria": "זמן חשיבת המנוע בשניות",
            "play": "שחק",
            "nextMove": "המהלך הבא",
            "computer": "מחשב",
            "computerColorHint": "באיזה צבע משחק המחשב — אתה משחק בצד השני"
        },
        "brainConfig": {
            "title": "הגדרות מוח",
            "save": "שמור",
            "reset": "אפס",
            "saved": "התצורה נשמרה",
            "failedSave": "שמירת התצורה נכשלה",
            "brainLabel": "מוח",
            "loading": "טוען…",
            "failedLoad": "טעינת הגדרות המוח נכשלה.",
            "discardSwitchConfirm": "לבטל שינויים שלא נשמרו ולהחליף גרסת מוח?",
            "discard": "בטל",
            "pieceScores": "ניקוד כלים",
            "specialEvaluations": "הערכות מיוחדות",
            "gamePhase": "שלב המשחק",
            "pawnFilesOpeningMid": "טורי רגלים (פתיחה / אמצע)",
            "pawnFilesEndGame": "טורי רגלים (סיום)"
        },
        "customTheme": {
            "title": "ערכת נושא מותאמת",
            "name": "שם ערכת הנושא",
            "save": "שמור",
            "delete": "מחק",
            "saved": "נשמר",
            "searchProperties": "חפש מאפיינים",
            "filterPlaceholder": "סנן לפי שם מאפיין…",
            "namePlaceholder": "הערכה שלי",
            "resetPreset": "אפס לערכה הנוכחית",
            "couldNotSave": "לא ניתן לשמור את ערכת הנושא. נסה שוב.",
            "untitled": "ללא שם",
            "defaultName": "ערכת נושא מותאמת"
        },
        "positionSetup": {
            "clearBoard": "נקה לוח",
            "startingPosition": "עמדת פתיחה",
            "flipBoard": "הפוך לוח",
            "eraser": "מחק",
            "selectAndMove": "בחר והזז",
            "defaultStartingPosition": "עמדת פתיחה ברירת מחדל",
            "savePosition": "שמור עמדה",
            "saveAsNewPosition": "שמור כעמדה חדשה",
            "validatePosition": "אמת עמדה",
            "positionFlags": "דגלי עמדה",
            "turn": "תור",
            "flagCheck": "שח",
            "flagCheckmate": "מט",
            "flagDraw": "תיקו",
            "flagWhiteKingMoved": "המלך הלבן זז",
            "flagBlackKingMoved": "המלך השחור זז",
            "flagWhiteKingsideRookMoved": "צריח צד־המלך הלבן זז",
            "flagWhiteQueensideRookMoved": "צריח צד־המלכה הלבן זז",
            "flagBlackKingsideRookMoved": "צריח צד־המלך השחור זז",
            "flagBlackQueensideRookMoved": "צריח צד־המלכה השחור זז"
        }
    },
    "mobile": {
        "drawOfferTitle": "הצעת תיקו",
        "drawOfferMessage": "היריב שלח הצעת תיקו. לקבל?",
        "rematchTitle": "משחק חוזר",
        "rematchMessage": "היריב שלח הצעת משחק חוזר. לקבל?",
        "gameId": "מזהה משחק: {{id}}",
        "drawOfferAgree": "היריב הציע תיקו, להסכים?",
        "rematchOfferAgree": "היריב הציע משחק חוזר, להסכים?",
        "newGameWatchFromHome": "משחק חדש החל — עבור לבית כדי לצפות."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = heExtra;
    } else {
        global.ShmerlingStringsHeExtra = heExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
