/**
 * Hebrew string catalog — mirrors src/strings/en.js structure with Hebrew values.
 */
(function (global) {
    "use strict";

    const he = {
        common: {
            white: "לבן",
            black: "שחור",
            draw: "תיקו",
            winner: "מנצח",
            engine: "מנוע",
            ok: "אישור",
            cancel: "ביטול",
            confirm: "אשר",
            yes: "כן",
            no: "לא",
            notice: "הודעה",
            input: "קלט",
            start: "התחל",
            collapse: "כווץ",
            expand: "הרחב",
            delete: "מחק",
            rename: "שנה שם",
            save: "שמור",
            aPlayer: "שחקן",
            pleaseEnterValue: "אנא הזן ערך.",
        },
        play: {
            appTitle: "שחמט שמרלינג",
            shell: {
                gameActions: "פעולות משחק",
                playersAndClocks: "שחקנים ושעונים",
                whitePlayerClock: "שעון שחקן לבן",
                blackPlayerClock: "שעון שחקן שחור",
                startFromLoadedPosition: "התחל משחק מהעמדה הטעונה",
                moves: "מהלכים",
                expandMovesPanel: "הרחב את חלונית המהלכים",
                expandMoves: "הרחב מהלכים",
                collapseMovesPanel: "כווץ את חלונית המהלכים",
                reviewNavigation: "ניווט סקירה",
                positionSetup: "הגדרת עמדה",
                pieces: "כלים",
                collapsePiecesPanel: "כווץ את חלונית הכלים",
                brainConfiguration: "הגדרות מוח",
                configuration: "תצורה",
                collapseConfigurationPanel: "כווץ את חלונית התצורה",
                games: "משחקים",
                expandGamesPanel: "הרחב את חלונית המשחקים",
                expandGames: "הרחב משחקים",
                collapseGamesPanel: "כווץ את חלונית המשחקים",
                savedListFilter: "סינון רשימה שמורה",
                positions: "עמדות",
                gameStatus: "מצב המשחק",
                capturedPieces: "כלים שנאכלו",
            },
            sessionMode: {
                play: "מצב משחק",
                positionSetup: "הגדרת עמדה",
                configuration: "מצב תצורה",
                playback: "מצב הפעלה חוזרת",
                review: "מצב סקירה",
                watch: "מצב צפייה",
                practice: "מצב תרגול",
            },
            status: {
                chooseNewGameOrSetup:
                    "בחר משחק חדש או הגדרת עמדה מהתפריט הצדדי",
                chooseNewGame: "בחר משחק חדש מהתפריט הצדדי",
                setMoveColorEngineThinkTime:
                    "הגדר מהלך, צבע, מנוע וזמן חשיבה בכותרת, ולאחר מכן לחץ על שחק",
                gameOver: "המשחק הסתיים",
                gameInProgress: "משחק בעיצומו",
                boardLoading: "הלוח עדיין נטען…",
                boardNotReady: "הלוח עדיין לא מוכן. אנא המתן ונסה שוב.",
                leaveOnlineBeforeConfiguration:
                    "עזוב את המשחק המקוון לפני פתיחת התצורה",
                configurationNotInPractice:
                    "תצורה אינה זמינה במצב תרגול",
                configurationModeEdit:
                    "מצב תצורה — ערוך ערכים ושמור",
                selectSavedOrSetup:
                    "בחר משחק שמור או הגדר עמדה על הלוח תחילה",
                gameAlreadyInProgress: "משחק כבר בעיצומו",
                yourMove: "התור שלך",
                engineToMove: "המנוע חושב…",
                leaveOnlineBeforePositionSetup:
                    "עזוב את המשחק המקוון לפני פתיחת הגדרת עמדה",
                positionSetupNotInPractice:
                    "הגדרת עמדה אינה זמינה במצב תרגול",
                positionSetupPlacePieces:
                    "הגדרת עמדה — הצב כלים על הלוח",
                drawWithReason: "תיקו — {{reason}}",
                checkmateWins: "מט — {{winner}} מנצח",
                check: "שח",
                waitBeforeEvaluate:
                    "המתן לסיום המהלך הנוכחי לפני ההערכה",
                evaluationUnavailable:
                    "ההערכה אינה זמינה. הפעל מחדש את אפליקציית שחמט שמרלינג.",
                evaluatingPosition: "מעריך עמדה…",
                evaluationFailed: "ההערכה נכשלה",
                evaluationLine: "הערכה ({{side}} למהלך): {{score}}",
                checkmate: "מט",
                drawZero: "תיקו (0)",
                totalLabel: "סה״כ: {{value}}",
                openFolderDesktopOnly:
                    "פתיחת תיקייה זמינה רק באפליקציית שולחן העבודה",
                couldNotOpenGamesLogFolder: "לא ניתן לפתוח את תיקיית יומני המשחקים",
                positionValid: "העמדה תקינה",
                playingFromCustomPosition: "משחק מעמדה מותאמת אישית",
                nothingToSave: "אין מה לשמור",
                positionSaved: "העמדה נשמרה",
                couldNotSavePosition: "לא ניתן לשמור את העמדה",
                savedPositionNotFound: "העמדה השמורה לא נמצאה",
                positionUpdated: "העמדה עודכנה",
                couldNotUpdatePosition: "לא ניתן לעדכן את העמדה",
                nameCannotBeEmpty: "השם לא יכול להיות ריק",
                gameRenamed: "שם המשחק שונה",
                couldNotRenameGame: "לא ניתן לשנות את שם המשחק",
                deletedCount: "נמחקו {{count}} פריטים",
                couldNotDeleteSelected: "לא ניתן למחוק את הפריטים שנבחרו",
                couldNotLoadSavedGame: "לא ניתן לטעון את המשחק השמור",
                editingPositionSaveBookmark:
                    "עריכת עמדה — שמור כדי לעדכן סימנייה זו",
                couldNotOpenPositionForEditing:
                    "לא ניתן לפתוח את העמדה לעריכה",
                gameSaved: "המשחק נשמר",
                couldNotSaveGame: "לא ניתן לשמור את המשחק",
                engineMoveNotApplied: "לא ניתן היה להחיל את מהלך המנוע",
                engineCouldNotFindMove: "המנוע לא הצליח למצוא מהלך",
                engineError: "שגיאת מנוע",
                engineThinking: "המנוע חושב…",
                sessionError: "שגיאת סשן",
                timesUpLost: "הזמן נגמר! {{loser}} הפסיד/ה",
                drawOfferTitle: "הצעת תיקו",
                drawOfferMessage: "היריב שלח הצעת תיקו. לקבל?",
                rematchTitle: "משחק חוזר",
                playerDisconnectedWaiting:
                    "{{who}} התנתק/ה — ממתין לחזרה ({{countdown}})",
                opponentDisconnectedCountdown:
                    "היריב התנתק — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "המשחק בוטל — הזמן להתחברות מחדש פג ולא בוצעו מהלכים.",
                playerFailedToReconnectWins:
                    "{{loser}} לא הצליח/ה להתחבר מחדש — {{winner}} מנצח/ת",
                gameOverOpponentFailedReconnect:
                    "המשחק הסתיים — היריב לא הצליח להתחבר מחדש.",
                couldNotStartRematch: "לא ניתן להתחיל משחק חוזר",
                rematchStarted: "המשחק החוזר החל",
                gameCancelled: "המשחק בוטל",
                gameCancelledWithDetail: "המשחק בוטל — {{detail}}",
                resignFailed: "הכניעה נכשלה",
                gameResumedYourMove: "המשחק חודש — התור שלך",
                practiceNotAvailable: "מצב תרגול אינו זמין",
                couldNotJoinOnPlay: "לא ניתן להצטרף למשחק זה ב-/play",
                practiceDebugNotAvailable:
                    "תרגול / דיבוג אינם זמינים עבור חשבון זה",
                reviewRequiresWebApi: "סקירה דורשת את ה-API של האינטרנט",
                couldNotLoadReviewGame: "לא ניתן לטעון את משחק הסקירה",
                notReviewGameLink: "קישור זה אינו משחק סקירה",
                onlineRequiresWebApi: "משחק מקוון דורש את ה-API של האינטרנט",
                couldNotLoadOnlineGame: "לא ניתן לטעון את המשחק המקוון",
                notOnlineGameOnPlay: "קישור זה אינו משחק מקוון ב-/play",
                watchingLiveGame: "צופה במשחק חי",
                waitingForOpponentToJoin: "ממתין ליריב שיצטרף…",
                waitingForOpponent: "ממתין ליריב…",
                onlineGameConnected: "משחק מקוון — מחובר",
                gameDeleted: "המשחק נמחק",
                itemsDeleted: "{{count}} פריטים נמחקו",
                choosePromotionPiece: "בחר כלי להכתרה",
                invalidPromotionPiece: "כלי הכתרה לא תקין",
                drawOfferNotAvailable: "הצעת תיקו אינה זמינה כרגע",
            },
            actions: {
                newGame: "משחק חדש",
                resign: "כניעה",
                draw: "תיקו",
                undo: "בטל מהלך",
                redo: "שחזר מהלך",
                lastMove: "מהלך אחרון",
                positionSetup: "הגדרת עמדה",
                config: "תצורה",
                flip: "הפוך לוח",
                save: "שמור",
                exit: "יציאה",
                loadToStart: "טען להתחלה",
                editPosition: "ערוך עמדה",
            },
            savedGames: {
                defaultName: "משחק שמור",
                nameAriaLabel: "שם המשחק השמור",
                showDetails: "הצג פרטים",
                detailsAriaLabel: "פרטי המשחק השמור",
                editPosition: "ערוך עמדה",
                deleteSavedGame: "מחק משחק שמור",
                renameSavedGame: "שנה שם למשחק שמור",
                noSavedPositions: "אין עדיין עמדות שמורות.",
                noSavedGames: "אין עדיין משחקים שמורים.",
                nextMoveDash: "המהלך הבא: —",
                nextMove: "המהלך הבא: {{side}}",
                player: "שחקן",
                savedAt: "נשמר: {{when}}",
                gameId: "מזהה משחק: {{id}}",
                playersVs: "{{white}} נגד {{black}}",
            },
            reviewNav: {
                start: "התחלה",
                back: "אחורה",
                play: "נגן",
                pause: "השהה",
                forward: "קדימה",
                end: "סוף",
            },
            newGameDialog: {
                title: "משחק חדש נגד מחשב",
                yourColor: "הצבע שלך",
                engine: "מנוע",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "זמן לכל צד (דקות)",
                allowUndo: "אפשר ביטול מהלך",
            },
            prompts: {
                positionName: "שם העמדה",
                savePositionAs: "שמור עמדה בשם",
            },
        },
        session: {
            engineThinking: "המנוע חושב…",
            engineCouldNotFindMove: "המנוע לא הצליח למצוא מהלך",
            engineError: "שגיאת מנוע",
            positionSetupPlacePieces: "הגדרת עמדה — הצב כלים על הלוח",
            configurationModeEdit: "מצב תצורה — ערוך ערכים ושמור",
            practiceBothSides: "תרגול — שני הצדדים",
            opponentDisconnected: "היריב התנתק",
            opponentRejoined: "היריב חזר",
            playerRejoined: "{{name}} חזר/ה",
            drawOfferSent: "הצעת תיקו נשלחה",
            drawOfferDeclined: "הצעת התיקו נדחתה",
            rematchOfferSent: "הצעת משחק חוזר נשלחה",
            rematchOfferDeclined: "הצעת המשחק החוזר נדחתה",
            drawAgreed: "הוסכם על תיקו",
            rematchAcceptedNoGameId: "הצעת המשחק החוזר התקבלה אך אין מזהה משחק חדש",
            rematchOfferAccepted: "הצעת המשחק החוזר התקבלה",
            gameOver: "המשחק הסתיים",
            somethingWentWrong: "משהו השתבש",
            opponentResigned: "היריב נכנע",
            opponentLeftGame: "היריב עזב את המשחק",
            opponentFailedToReconnect: "היריב לא הצליח להתחבר מחדש",
            gameCancelled: "המשחק בוטל",
            gameCancelledWithDetail: "המשחק בוטל — {{detail}}",
            waitingForOpponent: "ממתין ליריב…",
            couldNotResolveWebSocketUrl: "לא ניתן לפענח את כתובת ה-WebSocket",
            opponentJoined: "{{name}} הצטרף/ה",
            opponentDefault: "יריב",
            connectionError: "שגיאת חיבור",
            playerDisconnectedWaitingRejoin:
                "{{name}} התנתק/ה — ממתין לחזרה",
            playerFailedToReconnectWins:
                "{{loser}} לא הצליח/ה להתחבר מחדש — {{winner}} מנצח/ת",
            watcherWaitingForReconnect: "ממתין לחיבור מחדש של שחקן…",
        },
        site: {
            confirm: "אשר",
            cancel: "ביטול",
            notice: "הודעה",
            ok: "אישור",
            home: "בית",
            search: "חיפוש",
            friends: "חברים",
            groups: "קבוצות",
            debug: "דיבוג",
            account: "חשבון",
            preferences: "העדפות",
            administrate: "ניהול",
            logOut: "התנתק",
            logIn: "התחבר",
            admin: "מנהל",
            homeAria: "בית",
        },
        validation: {
            validEmail: "אנא הזן כתובת אימייל תקינה",
            passwordsMustMatch: "אנא ודא ששדות הסיסמה זהים.",
            chooseUsername: "אנא בחר שם משתמש",
            usernameNotAvailable: "שם המשתמש הזה אינו זמין",
            passwordNoWhitespace: "הסיסמה לא יכולה להכיל רווחים.",
            passwordUppercase: "הסיסמה חייבת להכיל לפחות אות גדולה אחת.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = he;
    } else {
        global.ShmerlingStringsHe = he;
    }
})(typeof window !== "undefined" ? window : globalThis);
