/**
 * Hindi supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const hiExtra = {
        validation: {
            passwordLowercase: "पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए।",
            passwordDigit: "पासवर्ड में कम से कम एक अंक होना चाहिए।",
            passwordSymbol: "पासवर्ड में कम से कम एक विशेष चिह्न होना चाहिए।",
            passwordLength: "पासवर्ड 8-30 अक्षरों का होना चाहिए।",
            noHtml: "{{label}} में HTML नहीं होना चाहिए।",
            position: {
                headerSave: "यह स्थिति सहेजी नहीं जा सकती:\n\n",
                headerPlay: "इस स्थिति से खेल नहीं शुरू किया जा सकता:\n\n",
                headerUse: "यह स्थिति उपयोग नहीं की जा सकती:\n\n",
                headerSaveBookmark: "यह बुकमार्क सहेजा नहीं जा सकता:\n\n",
                headerAddBookmark: "यह बुकमार्क जोड़ा नहीं जा सकता:\n\n",
                boardUnreadable: "बोर्ड पढ़ा नहीं जा सका। बोर्ड लोड होने के बाद पुनः प्रयास करें।",
                whiteKingNone: "बोर्ड पर ठीक एक सफ़ेद राजा होना चाहिए। कोई नहीं मिला।",
                whiteKingCount: "बोर्ड पर ठीक एक सफ़ेद राजा होना चाहिए। {{count}} सफ़ेद राजा मिले।",
                blackKingNone: "बोर्ड पर ठीक एक काला राजा होना चाहिए। कोई नहीं मिला।",
                blackKingCount: "बोर्ड पर ठीक एक काला राजा होना चाहिए। {{count}} काले राजा मिले।",
                kingsAdjacent: "दोनों राजा आसन्न वर्गों (तिरछे सहित) पर नहीं हो सकते।",
                sideInCheck: "{{mover}} की चाल है, लेकिन {{king}} का राजा पहले से शह में है। चाल वाले पक्ष शह नहीं दे सकता — बारी बदलें या मोहरे हटाएँ।",
                drawInsufficientKings: "यह स्थिति अपर्याप्त सामग्री से ड्रॉ है (राजा बनाम राजा)। शहमात संभव रहे, इसलिए मोहरे जोड़ें।",
                drawInsufficientMinor: "यह स्थिति अपर्याप्त सामग्री से ड्रॉ है (राजा और हाथी या घोड़ा बनाम अकेला राजा)। शहमात संभव रहे, इसलिए मोहरे जोड़ें।",
                drawBishopsSameColor: "यह स्थिति अपर्याप्त सामग्री से ड्रॉ है (एक ही रंग के वर्ग पर ऊँट बनाम ऊँट)। शहमात संभव रहे, इसलिए मोहरे जोड़ें।",
                tooManyQueens: "{{color}} के {{count}} वज़ीर हैं; अधिकतम प्रति रंग 9 है।",
                tooManyRooks: "{{color}} के {{count}} हाथी हैं; अधिकतम प्रति रंग 10 है।",
                tooManyBishops: "{{color}} के {{count}} ऊँट हैं; अधिकतम प्रति रंग 10 है।",
                tooManyKnights: "{{color}} के {{count}} घोड़े हैं; अधिकतम प्रति रंग 10 है।",
                tooManyPawns: "{{color}} के {{count}} प्यादे हैं; अधिकतम प्रति रंग 8 है।"
            }
        },
        auth: {
            whoAreYou: "आप कौन हैं?",
            enterPassword: "अपना पासवर्ड दर्ज करें",
            sorry: "क्षमा करें",
            continue: "जारी रखें",
            usernameField: "उपयोगकर्ता नाम",
            passwordField: "पासवर्ड",
            wrongCredentials: "गलत उपयोगकर्ता नाम या पासवर्ड",
            userAdded: "उपयोगकर्ता सफलतापूर्वक जोड़ा गया",
            couldNotSaveBookmark: "बुकमार्क सहेज नहीं सका",
            invalidUserId: "अमान्य उपयोगकर्ता ID",
            generationJobRunning: "एक और जनरेशन कार्य पहले से चल रहा है…",
            listingPgnFiles: "PGN फ़ाइलें सूचीबद्ध…"
        },
        classic: {
            loadGame: "खेल लोड करें",
            load: "लोड करें",
            enterGameState: "यहाँ खेल स्थिति चिपकाएँ…",
            rematch: "पुनर्मैच",
            drawOffer: "ड्रॉ प्रस्ताव",
            lastMove: "अंतिम चाल",
            bookmarks: "बुकमार्क",
            bookmarkAlertTitle: "स्थिति बुकमार्क करें",
            promotion: "प्रमोशन!",
            check: "शह",
            checkmateWins: "शहमात! {{winner}} जीत गया!",
            drawReason: "ड्रॉ! {{reason}}",
            opponentDisconnected: "प्रतिद्वंद्वी डिस्कनेक्ट हो गया",
            opponentResignedWins: "प्रतिद्वंद्वी ने हार मानी, {{winner}} जीत गया",
            somethingWentWrong: "कुछ गलत हो गया",
            playerRejoined: "{{name}} पुनः जुड़ा",
            aPlayerRejoined: "एक खिलाड़ी पुनः जुड़ा",
            opponentRejoined: "प्रतिद्वंद्वी पुनः जुड़ा",
            rematchOfferAccepted: "पुनर्मैच प्रस्ताव स्वीकार",
            rematchOfferDeclined: "पुनर्मैच प्रस्ताव अस्वीकार",
            sideOffersDraw: "{{side}} ड्रॉ प्रस्तावित करता है",
            drawOfferDeclined: "ड्रॉ प्रस्ताव अस्वीकार",
            watcherWatching: "{{name}} खेल देख रहा है",
            drawOfferSent: "ड्रॉ प्रस्ताव भेजा गया",
            rematchOfferSent: "पुनर्मैच प्रस्ताव भेजा गया",
            newGameStarted: "नया खेल शुरू",
            gameOver: "खेल समाप्त",
            gameCancelled: "खेल रद्द",
            youResignedWins: "आपने हार मानी, {{winner}} जीत गया",
            movesCopied: "चालें क्लिपबोर्ड पर कॉपी!",
            failedCopyMoves: "चालें कॉपी नहीं हो सकीं",
            failedLoadBrainConfig: "Brain कॉन्फ़िग लोड नहीं हो सका।",
            failedSaveBrainConfig: "Brain कॉन्फ़िग सहेज नहीं सका।",
            offerDrawConfirm: "ड्रॉ प्रस्तावित करें?",
            drawOfferAccept: "प्रतिद्वंद्वी ने ड्रॉ प्रस्ताव भेजा, स्वीकार करें?",
            rematchOfferAccept: "प्रतिद्वंद्वी ने पुनर्मैच प्रस्तावित किया, सहमत?",
            rematchOfferAcceptWithTime: "प्रतिद्वंद्वी ने दोबारा मैच की पेशकश की ({{minutes}} मिनट प्रति पक्ष)। सहमत होना?",
            rematchTimePrompt: "दोबारा मैच के लिए प्रति पक्ष मिनट:",
            connectionLost: "कनेक्शन टूट गया - चालें सर्वर तक नहीं पहुंच रही हैं",
            confirmExitGame: "क्या आप वाकई खेल से बाहर निकलना चाहते हैं?",
            mobileResign: "हार मानें",
            mobileRematch: "पुनर्मैच",
            mobileDraw: "ड्रॉ",
            mobileFlip: "पलटें",
            mobileLastMove: "अंतिम चाल",
            mobileMovesList: "चाल सूची",
            researchToolbox: "टूलबॉक्स",
            researchBrainConfig: "Brain कॉन्फ़िग",
            researchSave: "सहेजें",
            researchDiscard: "छोड़ें",
            researchEditMode: "संपादन मोड",
            researchRun: "चलाएँ",
            researchProperty: "गुण",
            researchValue: "मान",
            playerOnline: "ऑनलाइन",
            playerDisconnectedStatus: "डिस्कनेक्ट",
            playerOffline: "ऑफ़लाइन",
            humanVsComputer: "मानव बनाम कंप्यूटर",
            newGameTwoPlayers: "नया खेल 2 खिलाड़ी",
            settings: "सेटिंग्स",
            help: "सहायता",
            drawOffersNotVsEngine: "इंजन के विरुद्ध खेलते समय ड्रॉ प्रस्ताव उपलब्ध नहीं हैं।",
            failedStartFromBookmark: "बुकमार्क से खेल शुरू नहीं हो सका।",
            resignConfirm: "हार मानें?",
            areYouSure: "क्या आप सुनिश्चित हैं?",
            gameOverOpponentFailedReconnectWinsClassic: "खेल समाप्त — प्रतिद्वंद्वी पुनः कनेक्ट नहीं हो सका। {{winner}} जीत गया।",
            reconnectTimeoutNoMoves: "कोई चाल न खेले पुनः कनेक्ट समय समाप्त।",
            waitingOpponentRejoin: "प्रतिद्वंद्वी के पुनः जुड़ने की प्रतीक्षा",
            timeoutOneSec: "समय समाप्त: 1 सेकंड",
            timeoutSecs: "समय समाप्त: {{count}} सेकंड",
            whitePieceAlt: "सफ़ेद मोहरा",
            blackPieceAlt: "काला मोहरा",
            eraserTitle: "इरेज़र",
            eraserAria: "इरेज़र – वर्ग से मोहरा हटाएँ",
            selectTitle: "चुनें",
            selectAria: "चुनें – मोहरे खींचकर हिलाएँ",
            resetAria: "रीसेट – सभी मोहरे हटाएँ",
            defaultPositionAria: "डिफ़ॉल्ट स्थिति – मानक शुरुआती स्थिति सेट करें",
            loading: "लोड हो रहा है…",
            engineLabel: "इंजन"
        },
        site: {
            home: "होम",
            search: "खोज",
            friends: "मित्र",
            groups: "समूह",
            debug: "डिबग",
            account: "खाता",
            preferences: "प्राथमिकताएँ",
            administrate: "प्रशासन",
            logOut: "लॉग आउट",
            logIn: "लॉग इन",
            admin: "एडमिन",
            homeAria: "होम",
            confirm: "पुष्टि करें",
            cancel: "रद्द करें",
            notice: "सूचना",
            ok: "ठीक है",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "फुटर",
                privacy: "गोपनीयता नीति",
                terms: "उपयोग की शर्तें",
                contact: "संपर्क",
                copyright: "© {{year}} Shmerling Chess. सर्वाधिकार सुरक्षित।",
                lastUpdated: "अंतिम अपडेट: {{date}}",
                privacyTitle: "गोपनीयता नीति",
                privacyLead: "Shmerling Chess खाता और गेमप्ले जानकारी को कैसे संभालता है।",
                privacyBody: "हम सेवा चलाने, खेल और प्राथमिकताएँ रखने तथा उत्पाद सुधारने के लिए आपके खाते का विवरण उपयोग करते हैं। हम व्यक्तिगत जानकारी नहीं बेचते। पूरी नीति यहाँ प्रकाशित की जाएगी।",
                termsTitle: "उपयोग की शर्तें",
                termsLead: "Shmerling Chess उपयोग करने के नियम।",
                termsBody: "Shmerling Chess का उपयोग करके आप निष्पक्ष खेलने, अन्य खिलाड़ियों का सम्मान करने और सेवा केवल व्यक्तिगत शतरंज के लिए उपयोग करने पर सहमत होते हैं। पूरी शर्तें यहाँ प्रकाशित की जाएँगी।",
                contactTitle: "संपर्क",
                contactLead: "Shmerling Chess टीम से संपर्क करें।",
                contactBody: "सहायता और गोपनीयता प्रश्नों के संपर्क विवरण यहाँ प्रकाशित किए जाएँगे।",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "उपयोगकर्ता नाम:",
            password: "पासवर्ड:",
            login: "लॉग इन",
            register: {
                submit: "पंजीकरण",
                confirmPassword: "पासवर्ड की पुष्टि करें:",
                playerLevel: "खिलाड़ी स्तर:",
                rookie: "नौसिखिया",
                skilled: "कुशल",
                elite: "उत्कृष्ट",
                grandMaster: "ग्रैंड मास्टर"
            },
            email: "ईमेल:",
            welcome: {
                greeting: "वापसी पर स्वागत है",
                tagline: "आपकी चाल प्रतीक्षा कर रही है",
                playNow: "अभी खेलें!",
                activeGames: "सक्रिय खेल",
                live: "लाइव",
                showAll: "सभी दिखाएँ",
                viewAllActive: "सभी सक्रिय खेल देखें",
                mostRecent: "नवीनतम पहले",
                noGamesNow: "अभी कोई खेल नहीं",
                myGames: "मेरे खेल",
                viewAllGames: "सभी खेल देखें",
                recentCompleted: "आपके हाल के पूर्ण खेल",
                noCompleted: "अभी तक कोई पूर्ण खेल नहीं",
                activeGamesAria: "सक्रिय खेल",
                inviteOnlineFriend: "ऑनलाइन मित्र को खेलने के लिए आमंत्रित करें",
                friendsPageTitle: "मित्र पृष्ठ",
                manageFriends: "प्रबंधित करें",
                colFriend: "मित्र",
                colStatus: "स्थिति",
                findPlayers: "खिलाड़ी खोजें",
                waitingForResponse: "प्रतिक्रिया की प्रतीक्षा",
                inviteSentSuffix: "(आमंत्रण भेजा)",
                sortByRowNumber: "पंक्ति संख्या से क्रमबद्ध करें",
                sortBy: "{{key}} से क्रमबद्ध करें"
            },
            gameList: {
                date: "तारीख",
                time: "समय",
                result: "परिणाम",
                reason: "कारण",
                type: "प्रकार",
                status: "स्थिति",
                event: "इवेंट",
                site: "साइट",
                round: "राउंड"
            },
            loginPage: {
                title: "लॉग इन"
            },
            error: {
                title: "कुछ गलत हो गया",
                body: "एक त्रुटि हुई।",
                back: "मुख्य पर वापस"
            },
            log: {
                title: "सर्वर लॉग",
                clear: "दृश्य साफ़ करें",
                latest: "नवीनतम",
                waiting: "सर्वर लॉग आउटपुट की प्रतीक्षा…"
            },
            activeGames: {
                moves: "चालें",
                turn: "बारी",
                status: "स्थिति",
                inProgress: "जारी",
                onHold: "रुका हुआ",
                vs: " बनाम ",
                minutesAgo: "{{count}} मिनट पहले",
                oneMinuteAgo: "1 मिनट पहले",
                justStarted: "अभी शुरू",
                notStarted: "शुरू नहीं",
                startedTooltip: "शुरू: {{when}}",
                playersVs: "{{white}} बनाम {{black}}"
            },
            friendsPage: {
                title: "मित्र",
                tagline: "नए शतरंज साथी खोजें",
                myFriends: "मेरे मित्र",
                noFriendsYet: "अभी तक कोई मित्र नहीं",
                findPlayers: "खिलाड़ी खोजें",
                searchByUsername: "उपयोगकर्ता नाम से खोजें",
                searchPlaceholder: "खोजने के लिए टाइप करें…",
                enterCharToSearch: "खोज के लिए कम से कम एक अक्षर दर्ज करें",
                noMatchingUsers: "कोई मेल खाता उपयोगकर्ता नहीं",
                playing: "खेल रहा है",
                pendingFriendshipOffer: "लंबित मित्रता प्रस्ताव",
                joining: "शामिल हो रहा है",
                rejoin: "पुनः शामिल",
                friendRequest: "मित्र अनुरोध",
                wantsToBeFriends: "(मित्र बनना चाहता है)",
                pendingOfferSuffix: "(लंबित मित्रता प्रस्ताव)",
                waitingFriendRespond: "आपके मित्र की प्रतिक्रिया की प्रतीक्षा",
                cancelBeforeRemove: "इस मित्र को हटाने से पहले खेल आमंत्रण रद्द करें",
                friendsTag: "मित्र",
                offerReceivedTag: "प्रस्ताव प्राप्त — अपने मित्र देखें",
                addFriend: "मित्र जोड़ें",
                withdraw: "वापस लें",
                requestFailed: "अनुरोध विफल",
                removeFriendConfirm: "इस मित्र को अपनी सूची से हटाएँ?",
                removeFriendTitle: "मित्र हटाएँ",
                withdrawOfferConfirm: "यह मित्रता प्रस्ताव वापस लें?",
                withdrawOfferTitle: "प्रस्ताव वापस लें",
                couldNotAccept: "स्वीकार नहीं कर सका",
                couldNotDecline: "अस्वीकार नहीं कर सका",
                couldNotRemove: "हटा नहीं सका",
                couldNotCancelInvite: "आमंत्रण रद्द नहीं कर सका",
                couldNotWithdraw: "वापस नहीं ले सका",
                couldNotSendInvite: "आमंत्रण भेज नहीं सका",
                couldNotSendGameInvite: "खेल आमंत्रण भेज नहीं सका",
                gameInvite: "खेल आमंत्रण",
                gameInvitationsAria: "खेल आमंत्रण",
                gameInvitationAria: "खेल आमंत्रण",
                chessInviteTitle: "शतरंज आमंत्रण",
                wantsToPlayAsBlack: "{{name}} खेलना चाहता है। आप काले के रूप में खेलेंगे।",
                wantsToPlayYouWhite: "{{name}} खेलना चाहता है. आप श्वेत के रूप में खेलते हैं।",
                aFriend: "एक मित्र",
                youPlayAsWhite: "आप सफ़ेद के रूप में खेलेंगे",
                youPlayAsBlack: "आप काले के रूप में खेलेंगे",
                establishingGame: "खेल स्थापित…",
                yourOpponent: "आपका प्रतिद्वंद्वी",
                declinedYourInvite: "{{name}} ने आपका खेल आमंत्रण अस्वीकार किया।",
                cancelInvite: "आमंत्रण रद्द करें",
                accept: "स्वीकार करें",
                decline: "अस्वीकार करें",
                invite: "आमंत्रित करें",
                inviteSettingsTitle: "आमंत्रण सेटिंग",
                inviteSettingsFor: "आमंत्रित करें {{name}}",
                inviteTimeMinutes: "प्रति पक्ष समय (मिनट)",
                inviteYourColor: "आपका रंग",
                inviteColorWhite: "सफ़ेद",
                inviteColorBlack: "काला",
                inviteColorRandom: "यादृच्छिक",
                inviteFriendly: "मैत्रीपूर्ण खेल",
                inviteFriendlyHint: "बाद में ईएलओ की ओर गिनती करने के लिए अनचेक करें (रेटेड प्ले)।",
                invitePrivate: "निजी खेल",
                invitePrivateHint: "इस गेम को सार्वजनिक सक्रिय-गेम लॉबी से छिपाएँ।",
                inviteSaveDefaults: "डिफ़ॉल्ट सहेजें",
                inviteOfferTime: "{{minutes}} मिनट",
                inviteOfferFriendly: "दोस्ताना",
                inviteOfferRated: "रेटेड",
                inviteOfferPrivate: "निजी",
                remove: "हटाएँ",
                offerSent: "प्रस्ताव भेजा",
                pending: "लंबित",
                online: "ऑनलाइन",
                offline: "ऑफ़लाइन"
            },
            adminPage: {
                title: "प्रशासन",
                tagline: "उपयोगकर्ता, गेम, इंजन, प्रारंभिक पुस्तक और बॉट द्वंद्व",
                panelTitle: "एडमिन कंसोल",
                users: "उपयोगकर्ता",
                generate: "जनरेट",
                games: "खेल",
                engines: "इंजन",
                states: "स्थितियाँ",
                openingBook: "किताब खोलना",
                bots: "बॉट",
                addUser: "उपयोगकर्ता जोड़ें",
                sectionsAria: "एडमिन अनुभाग",
                openingBookLabel: "ओपनिंग बुक:",
                openingBookStatusTitle: "वर्तमान आरंभिक पुस्तक",
                openingBookFile: "फ़ाइल",
                openingBookExists: "स्थिति",
                openingBookExistsYes: "उपस्थित",
                openingBookExistsNo: "गुम",
                openingBookLines: "खेल पंक्तियाँ",
                openingBookSize: "आकार",
                openingBookModified: "अंतिम बार संशोधित",
                openingBookPgnSources: "पीजीएन स्रोत",
                openingBookPgnCount: "{{count}} PGN फ़ाइल(फ़ाइलें) पुनर्निर्माण के लिए उपलब्ध हैं",
                openingBookIntro: "सर्वर के पीजीएन फ़ोल्डर्स से लाइन-आधारित ओपनिंग बुक (डेटा/ओपनिंग-बुक-लाइन्स.txt) का पुनर्निर्माण करें। नीचे जनरेट ओपनिंग बुक का उपयोग करें—जब तक आप इसे नहीं दबाते, कुछ भी नहीं चलता।",
                generateOpeningBook: "आरंभिक पुस्तक तैयार करें",
                botsIntro: "सार्वजनिक इंजन-बनाम-इंजन खेल शुरू करें। सदस्य इसे होम पर एक्टिव गेम्स से दर्शक के रूप में खोल सकते हैं।",
                botsWhiteEngine: "सफेद इंजन",
                botsBlackEngine: "काला इंजन",
                botsWhiteDifficulty: "कठिनाई (1-6)",
                botsBlackDifficulty: "कठिनाई (1-6)",
                botsSkillLevel: "कौशल (0-20)",
                botsTimeMinutes: "घड़ी (मिनट)",
                botsStart: "द्वंद्व शुरू करो",
                botsStarting: "द्वंद्व शुरू हो रहा है...",
                botsStarted: "द्वंद्व शुरू हुआ: {{white}} बनाम {{black}}।",
                botsWatchLink: "यह गेम देखें",
                botsListedNote: "होम पर सूचीबद्ध → अन्य उपयोगकर्ताओं के लिए सक्रिय गेम।",
                botsStartFailed: "द्वंद्व शुरू नहीं हो सका.",
                botsStopped: "अनुरोधित को रोकें।",
                botsStopFailed: "द्वंद्व को रोक नहीं सका.",
                gameLines: "खेल पंक्तियाँ",
                noGamesInDb: "डेटाबेस में अभी तक कोई खेल नहीं।",
                gamesPaginationAria: "खेल पेजिनेशन",
                colNum: "#",
                colUsername: "उपयोगकर्ता नाम",
                colType: "प्रकार",
                colEmail: "ईमेल",
                colPassword: "पासवर्ड",
                colLevel: "स्तर",
                colElo: "Elo",
                colJoined: "शामिल",
                colLastLogin: "अंतिम लॉगिन",
                colActiveGames: "सक्रिय खेल",
                colFriends: "मित्र",
                colBookmarks: "बुकमार्क",
                colId: "Id",
                colStatus: "स्थिति",
                colName: "नाम",
                colAvailable: "उपलब्ध",
                colEnabled: "सक्रिय",
                colBackend: "बैकएंड",
                colCommand: "आज्ञा",
                colNotes: "नोट्स",
                colNote: "नोट",
                colAction: "क्रिया",
                emptyUsers: "अभी तक कोई उपयोगकर्ता नहीं।",
                emptyData: "अभी तक कोई डेटा नहीं।",
                emptyEngines: "रजिस्ट्री में कोई प्ले इंजन नहीं.",
                emptyStates: "ओपनिंग-बुक और स्थिति जनरेशन पृष्ठ खोलने के लिए Generate उपयोग करें।",
                engineAvailableYes: "उपलब्ध",
                engineAvailableNo: "अनुपलब्ध",
                engineEnable: "सक्षम",
                engineDisable: "अक्षम करना",
                enginesLoadFailed: "इंजन लोड नहीं हो सका",
                enginesSaveFailed: "इंजन अपडेट नहीं हो सका",
                clickToEdit: "संपादित करने के लिए क्लिक करें",
                updateFailed: "अपडेट विफल",
                couldNotSave: "सहेज नहीं सका",
                setPassword: "पासवर्ड सेट करें",
                setPasswordTitle: "नया पासवर्ड सेट करने के लिए क्लिक करें (4–30 अक्षर)",
                passwordLengthInvalid: "पासवर्ड 4 से 30 अक्षरों का होना चाहिए।",
                invalidPassword: "अमान्य पासवर्ड",
                saved: "सहेजा गया",
                newPasswordPlaceholder: "नया पासवर्ड",
                clickChangeUserType: "उपयोगकर्ता प्रकार बदलने के लिए क्लिक करें",
                userTypeAria: "उपयोगकर्ता प्रकार",
                changeUserTypeTitle: "उपयोगकर्ता प्रकार बदलें",
                grantAdminConfirm: "इस उपयोगकर्ता को एडमिन अधिकार दें? वे एडमिन टूल और खातों का प्रबंधन कर सकेंगे।",
                demoteAdminConfirm: "इस उपयोगकर्ता को Admin से {{type}} में बदलें? उन्हें एडमिन क्षेत्र की पहुँच खो जाएगी।",
                changeUserTypeConfirm: "इस उपयोगकर्ता को {{type}} में बदलें?",
                clickChangeLevel: "स्तर बदलने के लिए क्लिक करें",
                playerLevelAria: "खिलाड़ी स्तर",
                sortByRowNumber: "पंक्ति संख्या से क्रमबद्ध करें",
                sortBy: "{{key}} से क्रमबद्ध करें",
                delete: "हटाएँ",
                first: "पहला",
                last: "अंतिम",
                previous: "पिछला",
                next: "अगला",
                previous5Pages: "पिछले 5 पृष्ठ",
                next5Pages: "अगले 5 पृष्ठ",
                previous10Pages: "पिछले 10 पृष्ठ",
                next10Pages: "अगले 10 पृष्ठ",
                userTypeAdmin: "एडमिन",
                userTypePartner: "साझेदार",
                userTypeMember: "सदस्य",
                generateTitle: "ओपनिंग बुक और स्थिति जनरेशन",
                backToAdmin: "← एडमिन पर वापस",
                generateIntro: "सर्वर के games manager फ़ोल्डर के अंतर्गत सभी PGN फ़ाइलें State Mongo संग्रह या पंक्ति-आधारित ओपनिंग बुक (data/opening-book-lines.txt) में पुनः चलाती है। लक्ष्य चुनें, फिर Start generation दबाएँ — आप दबाने तक कुछ नहीं चलता।",
                target: "लक्ष्य",
                targetMongo: "MongoDB — State संग्रह में पंक्तियाँ जोड़ें",
                targetBook: "पंक्ति फ़ाइल — ओपनिंग बुक लिखें (opening-book-lines.txt)",
                startGeneration: "जनरेशन शुरू करें",
                stop: "रोकें",
                idle: "निष्क्रिय।",
                starting: "शुरू हो रहा है…",
                running: "चल रहा है ({{mode}})…",
                readingFiles: "{{count}} फ़ाइल(एँ) पढ़ी जा रही…",
                replayingGames: "{{count}} खेल पुनः चलाए जा रहे…",
                writingOpeningBook: "ओपनिंग बुक लिखी जा रही…",
                readingPgn: "PGN {{index}} / {{total}} पढ़ा जा रहा ({{games}} खेल)",
                replayGameProgress: "खेल {{current}} / {{total}} पुनः चलाया (सफल: {{completed}})",
                stopped: "रोका गया।",
                bookUnchanged: "मौजूदा ओपनिंग बुक संशोधित नहीं की गई।",
                bookLinesInFile: "{{file}} में {{count}} खेल पंक्ति(याँ)।",
                cancelledBeforeRead: "PGN पढ़ने से पहले रद्द।",
                cancelledAfterRead: "पढ़ने के बाद रद्द; पुनः चलाना छोड़ा (कुछ नहीं लिखा)।",
                mongoGamesSaved: "{{count}} खेल(ों) की नई स्थिति पंक्तियाँ सहेजी गईं।",
                doneBook: "पूर्ण। {{count}} खेल पंक्तियाँ → {{file}}",
                doneBookFileOnly: "पूर्ण। {{file}}",
                doneMongo: "पूर्ण। MongoDB State संग्रह अपडेट{{detail}}।",
                doneMongoDetail: " ({{count}} खेल सफलतापूर्वक पुनः चले)",
                errorPrefix: "त्रुटि: {{message}}",
                unknownError: "अज्ञात",
                connectionClosed: "कनेक्शन बंद (सर्वर लॉग देखें या पुनः प्रयास करें)।",
                openingBookDefault: "ओपनिंग बुक"
            },
            playNow: {
                title: "नया खेल",
                startTitle: "नया खेल शुरू करें",
                playingColor: "खेलने का रंग",
                timeMin: "समय (मिन)",
                difficulty: "कठिनाई (1–5)",
                mousePreference: "माउस प्राथमिकता",
                drag: "खींचें",
                doubleClick: "डबल क्लिक",
                showAvailableMoves: "उपलब्ध चालें दिखाएँ",
                private: "निजी",
                privateHint: "निजी खेल अन्य सदस्यों की सक्रिय खेल सूचियों में नहीं दिखते।",
                playComputer: "कंप्यूटर से खेलें",
                browseAll: "सभी ब्राउज़ करें",
                yourHistory: "आपका इतिहास",
                fullList: "पूरी सूची",
                gameLibrary: "खेल पुस्तकालय",
                openLibrarySearch: "पुस्तकालय खोज खोलें",
                brain3: "Brain 3",
                brain2: "Brain 2"
            },
            activeGamesList: {
                title: "सक्रिय खेल",
                tagline: "सभी चल रहे खेल",
                liveGames: "लाइव खेल",
                game: "खेल",
                started: "शुरू"
            },
            list: {
                title: "सभी खेल",
                tagline: "आपके पूर्ण खेल",
                allGames: "पूरा खेल",
                gamesCount: "{{count}} गेम्स",
                action: "क्रिया"
            },
            searchPage: {
                title: "खोज:",
                tagline: "PGN संग्रह में खेल खोजें",
                results: "परिणाम",
                resultsCount: "{{count}} परिणाम",
                noResults: "आपकी खोज से कोई खेल मेल नहीं खाता",
                button: "खोज",
                resultsFound: "{{count}} परिणाम मिले:",
                first: "पहला",
                last: "अंतिम",
                previous: "पिछला",
                next: "अगला",
                previous5Pages: "पिछले 5 पृष्ठ",
                next5Pages: "अगले 5 पृष्ठ",
                previous10Pages: "पिछले 10 पृष्ठ",
                next10Pages: "अगले 10 पृष्ठ"
            },
            game: {
                moves: "चालें",
                white: "सफ़ेद",
                black: "काला",
                resign: "हार मानें",
                draw: "ड्रॉ",
                undo: "पूर्ववत",
                flip: "पलटें",
                practice: "अभ्यास"
            },
            mobileWelcome: {
                title: "होम — शतरंज",
                play: "खेलें",
                library: "पुस्तकालय",
                friends: "मित्र"
            },
            mobileGame: {
                title: "खेल",
                moves: "चालें",
                resign: "हार मानें"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "कुछ गलत हो गया",
                body: "एक त्रुटि हुई।",
                back: "मुख्य पर वापस"
            },
            chrome: {
                preferences: "प्राथमिकताएँ",
                closePreferences: "वरीयताएँ बंद करें",
                display: "प्रदर्शन",
                gameplay: "गेमप्ले",
                pieceSet: "मोहरा सेट",
                boardTheme: "बोर्ड थीम",
                theme: "विषय",
                themeBlue: "नीला",
                themeDark: "गहरा",
                customizeTheme: "थीम अनुकूलित करें…",
                builtInThemesAria: "अंतर्निहित थीम",
                savedCustomThemesAria: "सहेजी गई कस्टम थीम",
                pieceSetsAria: "मोहरा सेट",
                homeAria: "श्मर्लिंग चेस होम"
            },
            prefs: {
                language: "भाषा",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "माउस नियंत्रण",
                mouseDrag: "खींचना",
                mouseClick: "क्लिक",
                thinkingTime: "सोचने का समय",
                thinkingTimeAria: "सोचने का समय (सेकंड)",
                immediateResign: "तुरंत हार मानें",
                secondsOption: "{{count}}s",
                selectedTheme: "चयनित: {{name}}",
                selectedPieceSet: "चयनित: {{name}}",
                enterFullScreen: "पूर्ण स्क्रीन",
                exitFullScreen: "पूर्ण स्क्रीन से बाहर",
                fullScreenUnavailable: "इस ब्राउज़र में पूर्ण स्क्रीन उपलब्ध नहीं है।"
            },
            gameRun: {
                yourColor: "आपका रंग",
                engine: "इंजन",
                thinkTime: "सोचने का समय (सेकंड)",
                thinkTimeAria: "इंजन सोचने का समय (सेकंड)",
                play: "खेलें",
                nextMove: "अगली चाल",
                computer: "कंप्यूटर",
                computerColorHint: "कंप्यूटर किस रंग से खेलता है — आप दूसरी ओर खेलते हैं"
            },
            brainConfig: {
                title: "Brain कॉन्फ़िगरेशन",
                save: "सहेजें",
                reset: "रीसेट",
                saved: "कॉन्फ़िगरेशन सहेजा गया",
                failedSave: "कॉन्फ़िगरेशन सहेज नहीं सका",
                brainLabel: "Brain",
                loading: "लोड हो रहा है…",
                failedLoad: "Brain कॉन्फ़िग लोड नहीं हो सका।",
                discardSwitchConfirm: "सहेजे न गए परिवर्तन छोड़कर Brain संस्करण बदलें?",
                discard: "छोड़ें",
                pieceScores: "मोहरा अंक",
                specialEvaluations: "विशेष मूल्यांकन",
                gamePhase: "खेल चरण",
                pawnFilesOpeningMid: "प्यादा फ़ाइलें (ओपनिंग / मध्य)",
                pawnFilesEndGame: "प्यादा फ़ाइलें (एंडगेम)"
            },
            customTheme: {
                title: "कस्टम थीम",
                name: "थीम का नाम",
                save: "सहेजें",
                delete: "हटाएँ",
                saved: "सहेजा गया",
                searchProperties: "गुण खोजें",
                filterPlaceholder: "गुण नाम से फ़िल्टर…",
                namePlaceholder: "मेरी थीम",
                resetPreset: "वर्तमान प्रीसेट पर रीसेट",
                couldNotSave: "थीम सहेज नहीं सकी। पुनः प्रयास करें।",
                untitled: "शीर्षक रहित",
                defaultName: "कस्टम थीम"
            },
            positionSetup: {
                clearBoard: "बोर्ड साफ़ करें",
                startingPosition: "शुरुआती स्थिति",
                flipBoard: "बोर्ड पलटें",
                eraser: "इरेज़र",
                selectAndMove: "चुनें और हिलाएँ",
                defaultStartingPosition: "डिफ़ॉल्ट शुरुआती स्थिति",
                savePosition: "स्थिति सहेजें",
                saveAsNewPosition: "नई स्थिति के रूप में सहेजें",
                validatePosition: "स्थिति मान्य करें",
                positionFlags: "स्थिति ध्वज",
                turn: "बारी",
                flagCheck: "शह",
                flagCheckmate: "शहमात",
                flagDraw: "ड्रॉ",
                flagWhiteKingMoved: "सफ़ेद राजा चला",
                flagBlackKingMoved: "काला राजा चला",
                flagWhiteKingsideRookMoved: "सफ़ेद kingside हाथी चला",
                flagWhiteQueensideRookMoved: "सफ़ेद queenside हाथी चला",
                flagBlackKingsideRookMoved: "काला kingside हाथी चला",
                flagBlackQueensideRookMoved: "काला queenside हाथी चला"
            }
        },
        errorPage: {
            code: "त्रुटि {{code}}",
            notFoundTitle: "पृष्ठ नहीं मिला",
            notFoundMessage: "आप जिस पृष्ठ को खोज रहे हैं वह मौजूद नहीं है।",
            genericTitle: "कुछ गलत हो गया",
            genericMessage: "एक अप्रत्याशित त्रुटि हुई। कृपया फिर से प्रयास करें।",
            backHome: "होम पर वापस जाएँ"
        },
        mobile: {
            drawOfferTitle: "ड्रॉ प्रस्ताव",
            drawOfferMessage: "प्रतिद्वंद्वी ने ड्रॉ प्रस्ताव भेजा। स्वीकार करें?",
            rematchTitle: "पुनर्मैच",
            rematchMessage: "प्रतिद्वंद्वी ने पुनर्मैच प्रस्ताव भेजा। स्वीकार करें?",
            gameId: "खेल ID: {{id}}",
            drawOfferAgree: "प्रतिद्वंद्वी ने ड्रॉ प्रस्तावित किया, सहमत?",
            rematchOfferAgree: "प्रतिद्वंद्वी ने पुनर्मैच प्रस्तावित किया, सहमत?",
            newGameWatchFromHome: "नया खेल शुरू — देखने के लिए होम पर जाएँ।"
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = hiExtra;
    } else {
        global.ShmerlingStringsHiExtra = hiExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
