/**
 * Hindi string catalog — mirrors src/strings/en.js structure with Hindi values.
 */
(function (global) {
    "use strict";

    const hi = {
        common: {
            white: "सफ़ेद",
            black: "काला",
            draw: "ड्रॉ",
            winner: "विजेता",
            engine: "इंजन",
            ok: "ठीक है",
            cancel: "रद्द करें",
            confirm: "पुष्टि करें",
            yes: "हाँ",
            no: "नहीं",
            notice: "सूचना",
            input: "इनपुट",
            start: "शुरू करें",
            collapse: "संक्षिप्त करें",
            expand: "विस्तार करें",
            delete: "हटाएँ",
            rename: "नाम बदलें",
            save: "सहेजें",
            aPlayer: "एक खिलाड़ी",
            pleaseEnterValue: "कृपया एक मान दर्ज करें।",
        },
        play: {
            appTitle: "श्मर्लिंग चेस",
            shell: {
                gameActions: "खेल क्रियाएँ",
                playersAndClocks: "खिलाड़ी और घड़ियाँ",
                whitePlayerClock: "सफ़ेद खिलाड़ी की घड़ी",
                blackPlayerClock: "काले खिलाड़ी की घड़ी",
                startFromLoadedPosition: "लोड की गई स्थिति से खेल शुरू करें",
                moves: "चालें",
                expandMovesPanel: "चाल पैनल विस्तार करें",
                expandMoves: "चालें विस्तार करें",
                collapseMovesPanel: "चाल पैनल संक्षिप्त करें",
                reviewNavigation: "समीक्षा नेविगेशन",
                positionSetup: "स्थिति सेटअप",
                pieces: "मोहरे",
                collapsePiecesPanel: "मोहरा पैनल संक्षिप्त करें",
                brainConfiguration: "Brain कॉन्फ़िगरेशन",
                configuration: "कॉन्फ़िगरेशन",
                collapseConfigurationPanel: "कॉन्फ़िगरेशन पैनल संक्षिप्त करें",
                games: "खेल",
                expandGamesPanel: "खेल पैनल विस्तार करें",
                expandGames: "खेल विस्तार करें",
                collapseGamesPanel: "खेल पैनल संक्षिप्त करें",
                chat: "चैट",
                expandChatPanel: "चैट पैनल विस्तारित करें",
                collapseChatPanel: "चैट पैनल संक्षिप्त करें",
                chatPlaceholder: "संदेश लिखें…",
                chatWatcherReadonly: "दर्शक केवल चैट पढ़ सकते हैं",
                sendChat: "भेजें",
                savedListFilter: "सहेजी गई सूची फ़िल्टर",
                positions: "स्थितियाँ",
                gameStatus: "खेल स्थिति",
                capturedPieces: "मारे गए मोहरे",
            },
            sessionMode: {
                play: "खेल मोड",
                positionSetup: "स्थिति सेटअप",
                configuration: "कॉन्फ़िगरेशन मोड",
                playback: "प्लेबैक मोड",
                review: "समीक्षा मोड",
                watch: "देखने का मोड",
                practice: "अभ्यास मोड",
            },
            status: {
                chooseNewGameOrSetup:
                    "साइडबार से नया खेल या स्थिति सेटअप चुनें",
                chooseNewGame: "साइडबार से नया खेल चुनें",
                setMoveColorEngineThinkTime:
                    "हेडर में चाल, रंग, इंजन और सोचने का समय सेट करें, फिर Play दबाएँ",
                gameOver: "खेल समाप्त",
                gameInProgress: "खेल जारी है",
                boardLoading: "बोर्ड अभी लोड हो रहा है…",
                boardNotReady: "बोर्ड अभी तैयार नहीं है। कृपया प्रतीक्षा करें और पुनः प्रयास करें।",
                leaveOnlineBeforeConfiguration:
                    "कॉन्फ़िगरेशन खोलने से पहले ऑनलाइन खेल छोड़ें",
                configurationNotInPractice:
                    "अभ्यास मोड में कॉन्फ़िगरेशन उपलब्ध नहीं है",
                configurationModeEdit:
                    "कॉन्फ़िगरेशन मोड — मान संपादित करें और सहेजें",
                selectSavedOrSetup:
                    "पहले कोई सहेजा गया खेल चुनें या बोर्ड पर स्थिति सेट करें",
                gameAlreadyInProgress: "एक खेल पहले से जारी है",
                yourMove: "आपकी चाल",
                engineToMove: "इंजन की चाल…",
                leaveOnlineBeforePositionSetup:
                    "स्थिति सेटअप खोलने से पहले ऑनलाइन खेल छोड़ें",
                positionSetupNotInPractice:
                    "अभ्यास मोड में स्थिति सेटअप उपलब्ध नहीं है",
                positionSetupPlacePieces:
                    "स्थिति सेटअप — बोर्ड पर मोहरे रखें",
                drawWithReason: "ड्रॉ — {{reason}}",
                checkmateWins: "शहमात — {{winner}} जीत गया",
                check: "शह",
                waitBeforeEvaluate:
                    "मूल्यांकन से पहले वर्तमान चाल पूरी होने की प्रतीक्षा करें",
                evaluationUnavailable:
                    "मूल्यांकन उपलब्ध नहीं है। Shmerling Chess ऐप पुनः आरंभ करें।",
                evaluatingPosition: "स्थिति का मूल्यांकन…",
                evaluationFailed: "मूल्यांकन विफल",
                evaluationLine: "मूल्यांकन ({{side}} की चाल): {{score}}",
                checkmate: "शहमात",
                drawZero: "ड्रॉ (0)",
                totalLabel: "कुल: {{value}}",
                openFolderDesktopOnly:
                    "फ़ोल्डर खोलना केवल डेस्कटॉप ऐप में उपलब्ध है",
                couldNotOpenGamesLogFolder: "खेल लॉग फ़ोल्डर नहीं खोल सका",
                positionValid: "स्थिति मान्य है",
                playingFromCustomPosition: "कस्टम स्थिति से खेल रहे हैं",
                nothingToSave: "सहेजने के लिए कुछ नहीं",
                positionSaved: "स्थिति सहेजी गई",
                couldNotSavePosition: "स्थिति सहेज नहीं सकी",
                savedPositionNotFound: "सहेजी गई स्थिति नहीं मिली",
                positionUpdated: "स्थिति अपडेट की गई",
                couldNotUpdatePosition: "स्थिति अपडेट नहीं कर सका",
                nameCannotBeEmpty: "नाम खाली नहीं हो सकता",
                gameRenamed: "खेल का नाम बदला गया",
                couldNotRenameGame: "खेल का नाम नहीं बदल सका",
                deletedCount: "{{count}} आइटम हटाए गए",
                couldNotDeleteSelected: "चयनित आइटम हटाए नहीं जा सके",
                couldNotLoadSavedGame: "सहेजा गया खेल लोड नहीं हो सका",
                editingPositionSaveBookmark:
                    "स्थिति संपादित — इस बुकमार्क को अपडेट करने के लिए सहेजें",
                couldNotOpenPositionForEditing:
                    "संपादन के लिए स्थिति नहीं खोल सका",
                gameSaved: "खेल सहेजा गया",
                couldNotSaveGame: "खेल सहेज नहीं सका",
                engineMoveNotApplied: "इंजन की चाल लागू नहीं हो सकी",
                engineCouldNotFindMove: "इंजन को कोई चाल नहीं मिली",
                engineError: "इंजन त्रुटि",
                engineThinking: "इंजन सोच रहा है…",
                sessionError: "सत्र त्रुटि",
                timesUpLost: "समय समाप्त! {{loser}} हार गया",
                drawOfferTitle: "ड्रॉ प्रस्ताव",
                drawOfferMessage: "प्रतिद्वंद्वी ने ड्रॉ प्रस्ताव भेजा। स्वीकार करें?",
                rematchTitle: "पुनर्मैच",
                playerDisconnectedWaiting:
                    "{{who}} डिस्कनेक्ट — पुनः जुड़ने की प्रतीक्षा ({{countdown}})",
                opponentDisconnectedCountdown:
                    "प्रतिद्वंद्वी डिस्कनेक्ट — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "खेल रद्द — कोई चाल न खेले पुनः कनेक्ट समय समाप्त।",
                playerFailedToReconnectWins:
                    "{{loser}} पुनः कनेक्ट नहीं हो सका — {{winner}} जीत गया",
                gameOverOpponentFailedReconnect:
                    "खेल समाप्त — प्रतिद्वंद्वी पुनः कनेक्ट नहीं हो सका।",
                couldNotStartRematch: "पुनर्मैच शुरू नहीं हो सका",
                rematchStarted: "पुनर्मैच शुरू",
                gameCancelled: "खेल रद्द",
                gameCancelledWithDetail: "खेल रद्द — {{detail}}",
                resignFailed: "हार मानना विफल",
                gameResumedYourMove: "खेल फिर शुरू — आपकी चाल",
                practiceNotAvailable: "अभ्यास मोड उपलब्ध नहीं है",
                couldNotJoinOnPlay: "इस खेल में /play पर शामिल नहीं हो सके",
                practiceDebugNotAvailable:
                    "इस खाते के लिए अभ्यास / डिबग उपलब्ध नहीं है",
                reviewRequiresWebApi: "समीक्षा के लिए वेब API आवश्यक है",
                couldNotLoadReviewGame: "समीक्षा खेल लोड नहीं हो सका",
                notReviewGameLink: "यह लिंक समीक्षा खेल नहीं है",
                onlineRequiresWebApi: "ऑनलाइन खेल के लिए वेब API आवश्यक है",
                couldNotLoadOnlineGame: "ऑनलाइन खेल लोड नहीं हो सका",
                notOnlineGameOnPlay: "यह लिंक /play पर ऑनलाइन खेल नहीं है",
                watchingLiveGame: "लाइव खेल देख रहे हैं",
                waitingForOpponentToJoin: "प्रतिद्वंद्वी के शामिल होने की प्रतीक्षा…",
                waitingForOpponent: "प्रतिद्वंद्वी की प्रतीक्षा…",
                onlineGameConnected: "ऑनलाइन खेल — कनेक्टेड",
                gameDeleted: "खेल हटाया गया",
                itemsDeleted: "{{count}} आइटम हटाए गए",
                choosePromotionPiece: "प्रमोशन मोहरा चुनें",
                invalidPromotionPiece: "अमान्य प्रमोशन मोहरा",
                drawOfferNotAvailable: "ड्रॉ प्रस्ताव अभी उपलब्ध नहीं है",
            },
            drawReasons: {
                stalemate: "गतिरोध",
                fiftyMoves: "50 चालें",
                insufficientMaterial: "अपर्याप्त सामग्री",
                threefoldRepetition: "त्रिगुण पुनरावृत्ति",
                drawOfferAccepted: "{{by}} खिलाड़ी का ड्रॉ प्रस्ताव स्वीकार",
            },
            actions: {
                newGame: "नया खेल",
                resign: "हार मानें",
                draw: "ड्रॉ",
                undo: "पूर्ववत",
                redo: "फिर करें",
                lastMove: "अंतिम चाल",
                positionSetup: "स्थिति सेटअप",
                config: "कॉन्फ़िग",
                flip: "पलटें",
                save: "सहेजें",
                exit: "बाहर निकलें",
                loadToStart: "शुरू करने के लिए लोड करें",
                editPosition: "स्थिति संपादित करें",
            },
            savedGames: {
                defaultName: "सहेजा गया खेल",
                nameAriaLabel: "सहेजे गए खेल का नाम",
                showDetails: "विवरण दिखाएँ",
                detailsAriaLabel: "सहेजे गए खेल का विवरण",
                editPosition: "स्थिति संपादित करें",
                deleteSavedGame: "सहेजा गया खेल हटाएँ",
                renameSavedGame: "सहेजे गए खेल का नाम बदलें",
                noSavedPositions: "अभी तक कोई सहेजी गई स्थिति नहीं।",
                noSavedGames: "अभी तक कोई सहेजा गया खेल नहीं।",
                nextMoveDash: "अगली चाल: —",
                nextMove: "अगली चाल: {{side}}",
                player: "खिलाड़ी",
                savedAt: "सहेजा गया: {{when}}",
                gameId: "खेल ID: {{id}}",
                playersVs: "{{white}} बनाम {{black}}",
            },
            reviewNav: {
                start: "शुरू",
                back: "पीछे",
                play: "चलाएँ",
                pause: "रोकें",
                forward: "आगे",
                end: "अंत",
            },
            newGameDialog: {
                title: "AI के विरुद्ध नया खेल",
                yourColor: "आपका रंग",
                engine: "इंजन",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "प्रति पक्ष समय (मिनट)",
                allowUndo: "पूर्ववत की अनुमति",
                private: "निजी",
                privateHint:
                    "निजी खेल अन्य सदस्यों की सक्रिय खेल सूचियों में नहीं दिखते।",
            },
            prompts: {
                positionName: "स्थिति का नाम",
                savePositionAs: "स्थिति इस नाम से सहेजें",
            },
            dialogs: {
                resignTitle: "इस खेल में हार मानें?",
                resignBody: "आप यह खेल हार जाएँगे।",
                leaveTitle: "खेल छोड़ें?",
                leaveBody: "आपका खेल हार मान लिया जाएगा।",
                areYouSure: "क्या आप सुनिश्चित हैं?",
                discardUnsavedBrainConfig:
                    "सहेजे न गए Brain कॉन्फ़िगरेशन परिवर्तन छोड़ दें?",
                accept: "स्वीकार करें",
                decline: "अस्वीकार करें",
                saveAs: "इस नाम से सहेजें",
                savePosition: "स्थिति सहेजें",
                invalidPosition: "अमान्य स्थिति",
                rematchChooseColor: "पुनर्मैच के लिए अपना रंग चुनें:",
                rematchOfferAgree: "प्रतिद्वंद्वी ने पुनर्मैच प्रस्तावित किया। सहमत?",
                rematchColorPreference:
                    "प्रतिद्वंद्वी {{offerer}} के रूप में खेलना चाहता है। आप {{you}} के रूप में खेलेंगे। सहमत?",
            },
        },
        session: {
            engineThinking: "इंजन सोच रहा है…",
            engineCouldNotFindMove: "इंजन को कोई चाल नहीं मिली",
            engineError: "इंजन त्रुटि",
            positionSetupPlacePieces: "स्थिति सेटअप — बोर्ड पर मोहरे रखें",
            configurationModeEdit: "कॉन्फ़िगरेशन मोड — मान संपादित करें और सहेजें",
            practiceBothSides: "अभ्यास — दोनों पक्ष",
            opponentDisconnected: "प्रतिद्वंद्वी डिस्कनेक्ट",
            opponentRejoined: "प्रतिद्वंद्वी पुनः जुड़ा",
            playerRejoined: "{{name}} पुनः जुड़ा",
            drawOfferSent: "ड्रॉ प्रस्ताव भेजा गया",
            drawOfferDeclined: "ड्रॉ प्रस्ताव अस्वीकार",
            rematchOfferSent: "पुनर्मैच प्रस्ताव भेजा गया",
            rematchOfferDeclined: "पुनर्मैच प्रस्ताव अस्वीकार",
            drawAgreed: "ड्रॉ पर सहमति",
            rematchAcceptedNoGameId: "पुनर्मैच स्वीकार, लेकिन नया खेल ID नहीं",
            rematchOfferAccepted: "पुनर्मैच प्रस्ताव स्वीकार",
            gameOver: "खेल समाप्त",
            somethingWentWrong: "कुछ गलत हो गया",
            opponentResigned: "प्रतिद्वंद्वी ने हार मानी",
            opponentLeftGame: "प्रतिद्वंद्वी ने खेल छोड़ दिया",
            opponentFailedToReconnect: "प्रतिद्वंद्वी पुनः कनेक्ट नहीं हो सका",
            gameCancelled: "खेल रद्द",
            gameCancelledWithDetail: "खेल रद्द — {{detail}}",
            waitingForOpponent: "प्रतिद्वंद्वी की प्रतीक्षा…",
            couldNotResolveWebSocketUrl: "WebSocket URL हल नहीं हो सका",
            opponentJoined: "{{name}} शामिल हुआ",
            opponentDefault: "प्रतिद्वंद्वी",
            connectionError: "कनेक्शन त्रुटि",
            playerDisconnectedWaitingRejoin:
                "{{name}} डिस्कनेक्ट — पुनः जुड़ने की प्रतीक्षा",
            playerFailedToReconnectWins:
                "{{loser}} पुनः कनेक्ट नहीं हो सका — {{winner}} जीत गया",
            watcherWaitingForReconnect: "किसी खिलाड़ी के पुनः कनेक्ट होने की प्रतीक्षा…",
        },
        site: {
            confirm: "पुष्टि करें",
            cancel: "रद्द करें",
            notice: "सूचना",
            ok: "ठीक है",
            home: "होम",
            search: "खोज",
            friends: "मित्र",
            groups: "समूह",
            debug: "डिबग",
            account: "खाता",
            preferences: "प्राथमिकताएँ",
            administrate: "प्रशासन",
            logOut: "लॉग आउट",
            logIn: "लॉग इन",
            admin: "एडमिन",
            homeAria: "होम",
        },
        validation: {
            validEmail: "कृपया मान्य ईमेल दर्ज करें",
            passwordsMustMatch: "कृपया सुनिश्चित करें कि पासवर्ड फ़ील्ड समान हैं।",
            chooseUsername: "कृपया उपयोगकर्ता नाम चुनें",
            usernameNotAvailable: "यह उपयोगकर्ता नाम उपलब्ध नहीं है",
            passwordNoWhitespace: "पासवर्ड में रिक्त स्थान नहीं होना चाहिए।",
            passwordUppercase: "पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए।",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = hi;
    } else {
        global.ShmerlingStringsHi = hi;
    }
})(typeof window !== "undefined" ? window : globalThis);
