(function (global) {
    "use strict";
    const jaExtra = {
    "validation": {
        "passwordLowercase": "パスワードには小文字を1文字以上含めてください。",
        "passwordDigit": "パスワードには数字を1文字以上含めてください。",
        "passwordSymbol": "パスワードには記号を1文字以上含めてください。",
        "passwordLength": "パスワードは8〜30文字である必要があります。",
        "noHtml": "{{label}} に HTML を含めることはできません。",
        "position": {
            "headerSave": "この局面は保存できません:\n\n",
            "headerPlay": "この局面から対局できません:\n\n",
            "headerUse": "この局面は使用できません:\n\n",
            "headerSaveBookmark": "このブックマークは保存できません:\n\n",
            "headerAddBookmark": "このブックマークは追加できません:\n\n",
            "boardUnreadable": "盤面を読み取れませんでした。盤面の読み込み後にもう一度お試しください。",
            "whiteKingNone": "盤上には白のキングがちょうど1つ必要です。見つかりませんでした。",
            "whiteKingCount": "盤上には白のキングがちょうど1つ必要です。{{count}} 個の白キングが見つかりました。",
            "blackKingNone": "盤上には黒のキングがちょうど1つ必要です。見つかりませんでした。",
            "blackKingCount": "盤上には黒のキングがちょうど1つ必要です。{{count}} 個の黒キングが見つかりました。",
            "kingsAdjacent": "2つのキングは隣接したマス（斜めを含む）に置くことはできません。",
            "sideInCheck": "{{mover}} の手番ですが、{{king}} のキングはすでにチェックされています。手番側がチェックをかけている状態にはできません — 手番を変えるか駒を動かしてください。",
            "drawInsufficientKings": "この局面は持ち駒不足による引き分けです（キング対キング）。詰みが可能になるよう駒を追加してください。",
            "drawInsufficientMinor": "この局面は持ち駒不足による引き分けです（キング＋ビショップまたはナイト対キングのみ）。詰みが可能になるよう駒を追加してください。",
            "drawBishopsSameColor": "この局面は持ち駒不足による引き分けです（同色のビショップ同士）。詰みが可能になるよう駒を追加してください。",
            "tooManyQueens": "{{color}} にクイーンが {{count}} 個あります。各色の上限は9個です。",
            "tooManyRooks": "{{color}} にルークが {{count}} 個あります。各色の上限は10個です。",
            "tooManyBishops": "{{color}} にビショップが {{count}} 個あります。各色の上限は10個です。",
            "tooManyKnights": "{{color}} にナイトが {{count}} 個あります。各色の上限は10個です。",
            "tooManyPawns": "{{color}} にポーンが {{count}} 個あります。各色の上限は8個です。"
        }
    },
    "auth": {
        "whoAreYou": "あなたは誰ですか？",
        "enterPassword": "パスワードを入力してください",
        "sorry": "申し訳ありません",
        "continue": "続行",
        "usernameField": "ユーザー名",
        "passwordField": "パスワード",
        "wrongCredentials": "ユーザー名またはパスワードが正しくありません",
        "userAdded": "ユーザーを追加しました",
        "couldNotSaveBookmark": "ブックマークを保存できませんでした",
        "invalidUserId": "無効なユーザー ID です",
        "generationJobRunning": "別の生成ジョブがすでに実行中です…",
        "listingPgnFiles": "PGN ファイルを一覧表示中…"
    },
    "classic": {
        "loadGame": "ゲームを読み込む",
        "load": "読み込む",
        "enterGameState": "ここにゲーム状態を貼り付け…",
        "rematch": "再戦",
        "drawOffer": "引き分けの提案",
        "lastMove": "最後の手",
        "bookmarks": "ブックマーク",
        "bookmarkAlertTitle": "局面をブックマーク",
        "promotion": "昇格！",
        "check": "チェック",
        "checkmateWins": "詰み！{{winner}} の勝ち！",
        "drawReason": "引き分け！{{reason}}",
        "opponentDisconnected": "相手が切断されました",
        "opponentResignedWins": "相手が投了しました。{{winner}} の勝ち",
        "somethingWentWrong": "問題が発生しました",
        "playerRejoined": "{{name}} が再接続しました",
        "aPlayerRejoined": "プレイヤーが再接続しました",
        "opponentRejoined": "相手が再接続しました",
        "rematchOfferAccepted": "再戦の提案が受け入れられました",
        "rematchOfferDeclined": "再戦の提案が拒否されました",
        "sideOffersDraw": "{{side}} が引き分けを提案",
        "drawOfferDeclined": "引き分けの提案が拒否されました",
        "watcherWatching": "{{name}} が対局を観戦中",
        "drawOfferSent": "引き分けを提案しました",
        "rematchOfferSent": "再戦を提案しました",
        "newGameStarted": "新しいゲームを開始しました",
        "gameOver": "ゲーム終了",
        "gameCancelled": "ゲームがキャンセルされました",
        "youResignedWins": "あなたが投了しました。{{winner}} の勝ち",
        "movesCopied": "棋譜をクリップボードにコピーしました！",
        "failedCopyMoves": "棋譜のコピーに失敗しました",
        "failedLoadBrainConfig": "Brain 設定の読み込みに失敗しました。",
        "failedSaveBrainConfig": "Brain 設定の保存に失敗しました。",
        "offerDrawConfirm": "引き分けを提案しますか？",
        "drawOfferAccept": "相手が引き分けを提案しました。受け入れますか？",
        "rematchOfferAccept": "相手が再戦を提案しました。同意しますか？",
        "confirmExitGame": "本当にゲームを終了しますか？",
        "mobileResign": "投了",
        "mobileRematch": "再戦",
        "mobileDraw": "引き分け",
        "mobileFlip": "反転",
        "mobileLastMove": "最後の手",
        "mobileMovesList": "棋譜リスト",
        "researchToolbox": "ツールボックス",
        "researchBrainConfig": "Brain 設定",
        "researchSave": "保存",
        "researchDiscard": "破棄",
        "researchEditMode": "編集モード",
        "researchRun": "実行",
        "researchProperty": "プロパティ",
        "researchValue": "値",
        "playerOnline": "オンライン",
        "playerDisconnectedStatus": "切断",
        "playerOffline": "オフライン",
        "humanVsComputer": "人間 対 コンピュータ",
        "newGameTwoPlayers": "2人対局の新しいゲーム",
        "settings": "設定",
        "help": "ヘルプ",
        "drawOffersNotVsEngine": "エンジンとの対局では引き分けの提案はできません。",
        "failedStartFromBookmark": "ブックマークからゲームを開始できませんでした。",
        "resignConfirm": "投了しますか？",
        "areYouSure": "よろしいですか？",
        "gameOverOpponentFailedReconnectWinsClassic": "ゲーム終了 — 相手が再接続できませんでした。{{winner}} の勝ち。",
        "reconnectTimeoutNoMoves": "手が指されないまま再接続がタイムアウトしました。",
        "waitingOpponentRejoin": "相手の再接続を待っています",
        "timeoutOneSec": "タイムアウト: 1 秒",
        "timeoutSecs": "タイムアウト: {{count}} 秒",
        "whitePieceAlt": "白の駒",
        "blackPieceAlt": "黒の駒",
        "eraserTitle": "消しゴム",
        "eraserAria": "消しゴム — マスから駒を削除",
        "selectTitle": "選択",
        "selectAria": "選択 — 駒をドラッグして移動",
        "resetAria": "リセット — すべての駒を消去",
        "defaultPositionAria": "初期配置 — 標準の開始局面を設定",
        "loading": "読み込み中…",
        "engineLabel": "エンジン"
    },
    "site": {
        "home": "ホーム",
        "search": "検索",
        "friends": "フレンド",
        "groups": "グループ",
        "debug": "デバッグ",
        "account": "アカウント",
        "preferences": "環境設定",
        "administrate": "管理",
        "logOut": "ログアウト",
        "logIn": "ログイン",
        "admin": "管理者",
        "homeAria": "ホーム",
        "confirm": "確認",
        "cancel": "キャンセル",
        "notice": "お知らせ",
        "ok": "OK",
        "username": "ユーザー名:",
        "password": "パスワード:",
        "login": "ログイン",
        "register": {
            "submit": "登録",
            "confirmPassword": "パスワード確認:",
            "playerLevel": "プレイヤーレベル:",
            "rookie": "ルーキー",
            "skilled": "スキルド",
            "elite": "エリート",
            "grandMaster": "グランドマスター"
        },
        "email": "メール:",
        "welcome": {
            "greeting": "おかえりなさい",
            "tagline": "あなたの手番が待っています",
            "playNow": "今すぐ対局！",
            "activeGames": "進行中のゲーム",
            "live": "ライブ",
            "showAll": "すべて表示",
            "viewAllActive": "進行中のゲームをすべて表示",
            "mostRecent": "新しい順",
            "noGamesNow": "現在ゲームはありません",
            "myGames": "マイゲーム",
            "viewAllGames": "すべてのゲームを表示",
            "recentCompleted": "最近終了したゲーム",
            "noCompleted": "終了したゲームはまだありません",
            "activeGamesAria": "進行中のゲーム",
            "inviteOnlineFriend": "オンラインのフレンドを対局に招待",
            "friendsPageTitle": "フレンドページ",
            "manageFriends": "管理",
            "colFriend": "フレンド",
            "colStatus": "状態",
            "findPlayers": "プレイヤーを探す",
            "waitingForResponse": "返答待ち",
            "inviteSentSuffix": "（招待送信済み）",
            "sortByRowNumber": "行番号で並べ替え",
            "sortBy": "{{key}} で並べ替え"
        },
        "gameList": {
            "date": "日付",
            "time": "時間",
            "result": "結果",
            "reason": "理由",
            "type": "種類",
            "status": "状態",
            "event": "イベント",
            "site": "サイト",
            "round": "ラウンド"
        },
        "loginPage": {
            "title": "ログイン"
        },
        "error": {
            "title": "問題が発生しました",
            "body": "エラーが発生しました。",
            "back": "メインに戻る"
        },
        "log": {
            "title": "サーバーログ",
            "clear": "表示をクリア",
            "latest": "最新",
            "waiting": "サーバーログの出力を待っています…"
        },
        "activeGames": {
            "moves": "手数",
            "turn": "手番",
            "status": "状態",
            "inProgress": "進行中",
            "onHold": "保留中",
            "vs": " 対 ",
            "minutesAgo": "{{count}} 分前",
            "oneMinuteAgo": "1 分前",
            "justStarted": "開始したばかり",
            "notStarted": "未開始",
            "startedTooltip": "開始: {{when}}",
            "playersVs": "{{white}} 対 {{black}}"
        },
        "friendsPage": {
            "title": "フレンド",
            "tagline": "新しいチェス仲間を見つけよう",
            "myFriends": "マイフレンド",
            "noFriendsYet": "フレンドはまだいません",
            "findPlayers": "プレイヤーを探す",
            "searchByUsername": "ユーザー名で検索",
            "searchPlaceholder": "入力して検索…",
            "enterCharToSearch": "検索するには1文字以上入力してください",
            "noMatchingUsers": "一致するユーザーがいません",
            "playing": "対局中",
            "pendingFriendshipOffer": "フレンド申請保留中",
            "joining": "参加中",
            "rejoin": "再参加",
            "friendRequest": "フレンド申請",
            "wantsToBeFriends": "（フレンドになりたい）",
            "pendingOfferSuffix": "（フレンド申請保留中）",
            "waitingFriendRespond": "フレンドの返答を待っています",
            "cancelBeforeRemove": "フレンドを削除する前にゲーム招待をキャンセルしてください",
            "friendsTag": "フレンド",
            "offerReceivedTag": "申請受信 — 「マイフレンド」を確認",
            "addFriend": "フレンドを追加",
            "withdraw": "取り消す",
            "requestFailed": "リクエストに失敗しました",
            "removeFriendConfirm": "このフレンドをリストから削除しますか？",
            "removeFriendTitle": "フレンドを削除",
            "withdrawOfferConfirm": "このフレンド申請を取り消しますか？",
            "withdrawOfferTitle": "申請を取り消す",
            "couldNotAccept": "承認できませんでした",
            "couldNotDecline": "拒否できませんでした",
            "couldNotRemove": "削除できませんでした",
            "couldNotCancelInvite": "招待をキャンセルできませんでした",
            "couldNotWithdraw": "取り消せませんでした",
            "couldNotSendInvite": "招待を送信できませんでした",
            "couldNotSendGameInvite": "ゲーム招待を送信できませんでした",
            "gameInvite": "ゲーム招待",
            "gameInvitationsAria": "ゲーム招待",
            "gameInvitationAria": "ゲーム招待",
            "chessInviteTitle": "チェス招待",
            "wantsToPlayAsBlack": "{{name}} が対局したいと言っています。あなたは黒です。",
            "aFriend": "フレンド",
            "youPlayAsWhite": "あなたは白です",
            "youPlayAsBlack": "あなたは黒です",
            "establishingGame": "ゲームを準備中…",
            "yourOpponent": "あなたの相手",
            "declinedYourInvite": "{{name}} がゲーム招待を拒否しました。",
            "cancelInvite": "招待をキャンセル",
            "accept": "受け入れる",
            "decline": "拒否",
            "invite": "招待",
            "remove": "削除",
            "offerSent": "送信済み",
            "pending": "保留中",
            "online": "オンライン",
            "offline": "オフライン"
        },
        "adminPage": {
            "title": "管理",
            "users": "ユーザー",
            "generate": "生成",
            "games": "ゲーム",
            "engines": "エンジン",
            "states": "状態",
            "addUser": "ユーザーを追加",
            "sectionsAria": "管理セクション",
            "openingBookLabel": "オープニングブック:",
            "gameLines": "ゲームライン",
            "noGamesInDb": "データベースにゲームはまだありません。",
            "gamesPaginationAria": "ゲームのページネーション",
            "colNum": "#",
            "colUsername": "ユーザー名",
            "colType": "種類",
            "colEmail": "メール",
            "colPassword": "パスワード",
            "colLevel": "レベル",
            "colElo": "Elo",
            "colJoined": "登録日",
            "colLastLogin": "最終ログイン",
            "colActiveGames": "進行中ゲーム",
            "colFriends": "フレンド",
            "colBookmarks": "ブックマーク",
            "colId": "Id",
            "colStatus": "状態",
            "colName": "名前",
            "colAvailable": "利用可能",
            "colNotes": "メモ",
            "colNote": "メモ",
            "colAction": "操作",
            "emptyUsers": "ユーザーはまだいません。",
            "emptyData": "データはまだありません。",
            "emptyStates": "「生成」を使ってオープニングブックと状態生成ページを開いてください。",
            "clickToEdit": "クリックして編集",
            "updateFailed": "更新に失敗しました",
            "couldNotSave": "保存できませんでした",
            "setPassword": "パスワードを設定",
            "setPasswordTitle": "クリックして新しいパスワードを設定（4〜30文字）",
            "passwordLengthInvalid": "パスワードは4〜30文字である必要があります。",
            "invalidPassword": "無効なパスワード",
            "saved": "保存しました",
            "newPasswordPlaceholder": "新しいパスワード",
            "clickChangeUserType": "クリックしてユーザータイプを変更",
            "userTypeAria": "ユーザータイプ",
            "changeUserTypeTitle": "ユーザータイプを変更",
            "grantAdminConfirm": "このユーザーに管理者権限を付与しますか？管理ツールへのアクセスとアカウント管理が可能になります。",
            "demoteAdminConfirm": "このユーザーを管理者から {{type}} に変更しますか？管理エリアへのアクセスが失われます。",
            "changeUserTypeConfirm": "このユーザーを {{type}} に変更しますか？",
            "clickChangeLevel": "クリックしてレベルを変更",
            "playerLevelAria": "プレイヤーレベル",
            "sortByRowNumber": "行番号で並べ替え",
            "sortBy": "{{key}} で並べ替え",
            "delete": "削除",
            "first": "最初",
            "last": "最後",
            "previous": "前へ",
            "next": "次へ",
            "previous5Pages": "前の5ページ",
            "next5Pages": "次の5ページ",
            "previous10Pages": "前の10ページ",
            "next10Pages": "次の10ページ",
            "userTypeAdmin": "管理者",
            "userTypePartner": "パートナー",
            "userTypeMember": "メンバー",
            "generateTitle": "オープニングブックと状態生成",
            "backToAdmin": "← 管理に戻る",
            "generateIntro": "サーバーのゲームマネージャーフォルダ内のすべての PGN ファイルを、State Mongo コレクションまたは行ベースのオープニングブック（data/opening-book-lines.txt）に再生します。ターゲットを選んで「生成開始」を押してください — 押すまで何も実行されません。",
            "target": "ターゲット",
            "targetMongo": "MongoDB — State コレクションに行を追加",
            "targetBook": "ラインファイル — オープニングブックを書き出し（opening-book-lines.txt）",
            "startGeneration": "生成開始",
            "stop": "停止",
            "idle": "待機中。",
            "starting": "開始中…",
            "running": "実行中（{{mode}}）…",
            "readingFiles": "{{count}} ファイルを読み込み中…",
            "replayingGames": "{{count}} ゲームを再生中…",
            "writingOpeningBook": "オープニングブックを書き込み中…",
            "readingPgn": "PGN {{index}} / {{total}} を読み込み中（{{games}} ゲーム）",
            "replayGameProgress": "ゲーム再生 {{current}} / {{total}}（正常完了: {{completed}}）",
            "stopped": "停止しました。",
            "bookUnchanged": "既存のオープニングブックは変更されませんでした。",
            "bookLinesInFile": "{{file}} に {{count}} ゲームライン。",
            "cancelledBeforeRead": "PGN 読み込み前にキャンセルされました。",
            "cancelledAfterRead": "読み込み後にキャンセルされました。再生はスキップされ（何も書き込まれません）。",
            "mongoGamesSaved": "{{count}} ゲームに新しい状態行が保存されました。",
            "doneBook": "完了。{{count}} ゲームライン → {{file}}",
            "doneBookFileOnly": "完了。{{file}}",
            "doneMongo": "完了。MongoDB State コレクションを更新しました{{detail}}。",
            "doneMongoDetail": "（{{count}} ゲームを正常に再生）",
            "errorPrefix": "エラー: {{message}}",
            "unknownError": "不明",
            "connectionClosed": "接続が閉じられました（サーバーログを確認するか、再度お試しください）。",
            "openingBookDefault": "オープニングブック"
        },
        "playNow": {
            "title": "新しいゲーム",
            "startTitle": "新しいゲームを開始",
            "playingColor": "対局する色",
            "timeMin": "時間（分）",
            "difficulty": "難易度（1〜5）",
            "mousePreference": "マウス操作",
            "drag": "ドラッグ",
            "doubleClick": "ダブルクリック",
            "showAvailableMoves": "合法手を表示",
            "private": "非公開",
            "playComputer": "コンピュータと対局",
            "browseAll": "すべて閲覧",
            "yourHistory": "あなたの履歴",
            "fullList": "全リスト",
            "gameLibrary": "ゲームライブラリ",
            "openLibrarySearch": "ライブラリ検索を開く",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "進行中のゲーム",
            "tagline": "進行中のすべてのゲーム",
            "liveGames": "ライブゲーム",
            "game": "ゲーム",
            "started": "開始"
        },
        "list": {
            "title": "すべてのゲーム",
            "action": "操作"
        },
        "searchPage": {
            "title": "検索:",
            "tagline": "PGN アーカイブから対局を探す",
            "results": "検索結果",
            "resultsCount": "{{count}} 件",
            "noResults": "検索条件に一致する対局はありません",
            "button": "検索",
            "resultsFound": "{{count}} 件見つかりました:",
            "first": "最初",
            "last": "最後",
            "previous": "前へ",
            "next": "次へ",
            "previous5Pages": "前の5ページ",
            "next5Pages": "次の5ページ",
            "previous10Pages": "前の10ページ",
            "next10Pages": "次の10ページ"
        },
        "game": {
            "moves": "棋譜",
            "white": "白",
            "black": "黒",
            "resign": "投了",
            "draw": "引き分け",
            "undo": "待った",
            "flip": "反転",
            "practice": "練習"
        },
        "mobileWelcome": {
            "title": "ホーム — チェス",
            "play": "対局",
            "library": "ライブラリ",
            "friends": "フレンド"
        },
        "mobileGame": {
            "title": "ゲーム",
            "moves": "棋譜",
            "resign": "投了"
        }
    },
    "desktop": {
        "error": {
            "title": "問題が発生しました",
            "body": "エラーが発生しました。",
            "back": "メインに戻る"
        },
        "chrome": {
            "preferences": "環境設定",
            "display": "表示",
            "gameplay": "ゲームプレイ",
            "pieceSet": "駒セット",
            "boardTheme": "盤のテーマ",
            "themeBlue": "ブルー",
            "themeDark": "ダーク",
            "customizeTheme": "テーマをカスタマイズ…",
            "builtInThemesAria": "組み込みテーマ",
            "savedCustomThemesAria": "保存したカスタムテーマ",
            "pieceSetsAria": "駒セット",
            "homeAria": "シュマーリングチェス ホーム"
        },
        "prefs": {
            "language": "言語",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "マウス操作",
            "thinkingTime": "思考時間",
            "thinkingTimeAria": "思考時間（秒）",
            "immediateResign": "即時投了",
            "secondsOption": "{{count}}秒",
            "enterFullScreen": "全画面表示",
            "exitFullScreen": "全画面を終了",
            "fullScreenUnavailable": "このブラウザでは全画面表示は利用できません。"
        },
        "gameRun": {
            "yourColor": "あなたの色",
            "engine": "エンジン",
            "thinkTime": "思考時間（秒）",
            "thinkTimeAria": "エンジンの思考時間（秒）",
            "play": "対局",
            "nextMove": "次の手",
            "computer": "コンピュータ",
            "computerColorHint": "コンピュータが指す色 — あなたは反対側です"
        },
        "brainConfig": {
            "title": "Brain 設定",
            "save": "保存",
            "reset": "リセット",
            "saved": "設定を保存しました",
            "failedSave": "設定の保存に失敗しました",
            "brainLabel": "Brain",
            "loading": "読み込み中…",
            "failedLoad": "Brain 設定の読み込みに失敗しました。",
            "discardSwitchConfirm": "保存していない変更を破棄して Brain バージョンを切り替えますか？",
            "discard": "破棄",
            "pieceScores": "駒の評価値",
            "specialEvaluations": "特殊評価",
            "gamePhase": "ゲームフェーズ",
            "pawnFilesOpeningMid": "ポーンの筋（序盤 / 中盤）",
            "pawnFilesEndGame": "ポーンの筋（終盤）"
        },
        "customTheme": {
            "title": "カスタムテーマ",
            "name": "テーマ名",
            "save": "保存",
            "delete": "削除",
            "saved": "保存しました",
            "searchProperties": "プロパティを検索",
            "filterPlaceholder": "プロパティ名でフィルター…",
            "namePlaceholder": "マイテーマ",
            "resetPreset": "現在のプリセットにリセット",
            "couldNotSave": "テーマを保存できませんでした。もう一度お試しください。",
            "untitled": "無題",
            "defaultName": "カスタムテーマ"
        },
        "positionSetup": {
            "clearBoard": "盤面をクリア",
            "startingPosition": "開始局面",
            "flipBoard": "盤面を反転",
            "eraser": "消しゴム",
            "selectAndMove": "選択して移動",
            "defaultStartingPosition": "標準の開始局面",
            "savePosition": "局面を保存",
            "saveAsNewPosition": "新しい局面として保存",
            "validatePosition": "局面を検証",
            "positionFlags": "局面フラグ",
            "turn": "手番",
            "flagCheck": "チェック",
            "flagCheckmate": "詰み",
            "flagDraw": "引き分け",
            "flagWhiteKingMoved": "白キング移動済み",
            "flagBlackKingMoved": "黒キング移動済み",
            "flagWhiteKingsideRookMoved": "白キング側ルーク移動済み",
            "flagWhiteQueensideRookMoved": "白クイーン側ルーク移動済み",
            "flagBlackKingsideRookMoved": "黒キング側ルーク移動済み",
            "flagBlackQueensideRookMoved": "黒クイーン側ルーク移動済み"
        }
    },
    "mobile": {
        "drawOfferTitle": "引き分けの提案",
        "drawOfferMessage": "相手が引き分けを提案しました。受け入れますか？",
        "rematchTitle": "再戦",
        "rematchMessage": "相手が再戦を提案しました。受け入れますか？",
        "gameId": "ゲーム ID: {{id}}",
        "drawOfferAgree": "相手が引き分けを提案しました。同意しますか？",
        "rematchOfferAgree": "相手が再戦を提案しました。同意しますか？",
        "newGameWatchFromHome": "新しいゲームが開始されました — ホームから観戦してください。"
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = jaExtra;
    } else {
        global.ShmerlingStringsJaExtra = jaExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
