/**
 * Japanese string catalog — mirrors src/strings/en.js structure with Japanese values.
 */
(function (global) {
    "use strict";

    const ja = {
        common: {
            white: "白",
            black: "黒",
            draw: "引き分け",
            winner: "勝者",
            engine: "エンジン",
            ok: "OK",
            cancel: "キャンセル",
            confirm: "確認",
            yes: "はい",
            no: "いいえ",
            notice: "お知らせ",
            input: "入力",
            start: "開始",
            collapse: "折りたたむ",
            expand: "展開",
            delete: "削除",
            rename: "名前を変更",
            save: "保存",
            aPlayer: "プレイヤー",
            pleaseEnterValue: "値を入力してください。",
        },
        play: {
            appTitle: "シュマーリングチェス",
            shell: {
                gameActions: "ゲーム操作",
                playersAndClocks: "プレイヤーと時計",
                whitePlayerClock: "白の時計",
                blackPlayerClock: "黒の時計",
                startFromLoadedPosition: "読み込んだ局面からゲームを開始",
                moves: "棋譜",
                expandMovesPanel: "棋譜パネルを展開",
                expandMoves: "棋譜を展開",
                collapseMovesPanel: "棋譜パネルを折りたたむ",
                reviewNavigation: "再生ナビゲーション",
                positionSetup: "局面設定",
                pieces: "駒",
                collapsePiecesPanel: "駒パネルを折りたたむ",
                brainConfiguration: "Brain 設定",
                configuration: "設定",
                collapseConfigurationPanel: "設定パネルを折りたたむ",
                games: "ゲーム",
                expandGamesPanel: "ゲームパネルを展開",
                expandGames: "ゲームを展開",
                collapseGamesPanel: "ゲームパネルを折りたたむ",
                savedListFilter: "保存リストのフィルター",
                positions: "局面",
                gameStatus: "ゲーム状態",
                capturedPieces: "取った駒",
            },
            sessionMode: {
                play: "対局モード",
                positionSetup: "局面設定",
                configuration: "設定モード",
                playback: "再生モード",
                review: "レビューモード",
                watch: "観戦モード",
                practice: "練習モード",
            },
            status: {
                chooseNewGameOrSetup:
                    "サイドバーから「新しいゲーム」または「局面設定」を選択してください",
                chooseNewGame: "サイドバーから「新しいゲーム」を選択してください",
                setMoveColorEngineThinkTime:
                    "ヘッダーで手番・色・エンジン・思考時間を設定し、「対局」を押してください",
                gameOver: "ゲーム終了",
                gameInProgress: "対局中",
                boardLoading: "盤面を読み込み中…",
                boardNotReady: "盤面の準備ができていません。しばらく待ってから再度お試しください。",
                leaveOnlineBeforeConfiguration:
                    "設定を開く前にオンライン対局を終了してください",
                configurationNotInPractice:
                    "練習モードでは設定は利用できません",
                configurationModeEdit:
                    "設定モード — 値を編集して保存",
                selectSavedOrSetup:
                    "保存したゲームを選択するか、盤面に局面を設定してください",
                gameAlreadyInProgress: "すでに対局中です",
                yourMove: "あなたの手番",
                engineToMove: "エンジン思考中…",
                leaveOnlineBeforePositionSetup:
                    "局面設定を開く前にオンライン対局を終了してください",
                positionSetupNotInPractice:
                    "練習モードでは局面設定は利用できません",
                positionSetupPlacePieces:
                    "局面設定 — 盤面に駒を配置してください",
                drawWithReason: "引き分け — {{reason}}",
                checkmateWins: "詰み — {{winner}} の勝ち",
                check: "チェック",
                waitBeforeEvaluate:
                    "評価する前に現在の手が終わるまでお待ちください",
                evaluationUnavailable:
                    "評価は利用できません。シュマーリングチェスアプリを再起動してください。",
                evaluatingPosition: "局面を評価中…",
                evaluationFailed: "評価に失敗しました",
                evaluationLine: "評価（{{side}} の手番）: {{score}}",
                checkmate: "詰み",
                drawZero: "引き分け (0)",
                totalLabel: "合計: {{value}}",
                openFolderDesktopOnly:
                    "フォルダを開くのはデスクトップアプリでのみ利用できます",
                couldNotOpenGamesLogFolder: "ゲームログフォルダを開けませんでした",
                positionValid: "局面は有効です",
                playingFromCustomPosition: "カスタム局面から対局",
                nothingToSave: "保存するものがありません",
                positionSaved: "局面を保存しました",
                couldNotSavePosition: "局面を保存できませんでした",
                savedPositionNotFound: "保存した局面が見つかりません",
                positionUpdated: "局面を更新しました",
                couldNotUpdatePosition: "局面を更新できませんでした",
                nameCannotBeEmpty: "名前を空にすることはできません",
                gameRenamed: "ゲーム名を変更しました",
                couldNotRenameGame: "ゲーム名を変更できませんでした",
                deletedCount: "{{count}} 件を削除しました",
                couldNotDeleteSelected: "選択した項目を削除できませんでした",
                couldNotLoadSavedGame: "保存したゲームを読み込めませんでした",
                editingPositionSaveBookmark:
                    "局面を編集中 — 保存してこのブックマークを更新",
                couldNotOpenPositionForEditing:
                    "編集用に局面を開けませんでした",
                gameSaved: "ゲームを保存しました",
                couldNotSaveGame: "ゲームを保存できませんでした",
                engineMoveNotApplied: "エンジンの手を適用できませんでした",
                engineCouldNotFindMove: "エンジンは手を見つけられませんでした",
                engineError: "エンジンエラー",
                engineThinking: "エンジン思考中…",
                sessionError: "セッションエラー",
                timesUpLost: "時間切れ！{{loser}} の負け",
                drawOfferTitle: "引き分けの提案",
                drawOfferMessage: "相手が引き分けを提案しました。受け入れますか？",
                rematchTitle: "再戦",
                playerDisconnectedWaiting:
                    "{{who}} が切断されました — 再接続を待っています（{{countdown}}）",
                opponentDisconnectedCountdown:
                    "相手が切断されました — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "ゲームがキャンセルされました — 手が指されないまま再接続がタイムアウトしました。",
                playerFailedToReconnectWins:
                    "{{loser}} が再接続できませんでした — {{winner}} の勝ち",
                gameOverOpponentFailedReconnect:
                    "ゲーム終了 — 相手が再接続できませんでした。",
                couldNotStartRematch: "再戦を開始できませんでした",
                rematchStarted: "再戦を開始しました",
                gameCancelled: "ゲームがキャンセルされました",
                gameCancelledWithDetail: "ゲームがキャンセルされました — {{detail}}",
                resignFailed: "投了に失敗しました",
                gameResumedYourMove: "対局再開 — あなたの手番",
                practiceNotAvailable: "練習モードは利用できません",
                couldNotJoinOnPlay: "/play でこのゲームに参加できませんでした",
                practiceDebugNotAvailable:
                    "このアカウントでは練習 / デバッグは利用できません",
                reviewRequiresWebApi: "レビューには Web API が必要です",
                couldNotLoadReviewGame: "レビューゲームを読み込めませんでした",
                notReviewGameLink: "このリンクはレビューゲームではありません",
                onlineRequiresWebApi: "オンライン対局には Web API が必要です",
                couldNotLoadOnlineGame: "オンラインゲームを読み込めませんでした",
                notOnlineGameOnPlay: "このリンクは /play のオンラインゲームではありません",
                watchingLiveGame: "ライブ対局を観戦中",
                waitingForOpponentToJoin: "相手の参加を待っています…",
                waitingForOpponent: "相手を待っています…",
                onlineGameConnected: "オンライン対局 — 接続済み",
                gameDeleted: "ゲームを削除しました",
                itemsDeleted: "{{count}} 件を削除しました",
                choosePromotionPiece: "昇格する駒を選択",
                invalidPromotionPiece: "無効な昇格駒です",
                drawOfferNotAvailable: "現在引き分けの提案はできません",
            },
            drawReasons: {
                stalemate: "ステイルメイト",
                fiftyMoves: "50手ルール",
                insufficientMaterial: "持ち駒不足",
                threefoldRepetition: "同一局面三回",
                drawOfferAccepted: "{{by}} の引き分け提案が受け入れられました",
            },
            actions: {
                newGame: "新しいゲーム",
                resign: "投了",
                draw: "引き分け",
                undo: "待った",
                redo: "やり直し",
                lastMove: "最後の手",
                positionSetup: "局面設定",
                config: "設定",
                flip: "反転",
                save: "保存",
                exit: "終了",
                loadToStart: "読み込んで開始",
                editPosition: "局面を編集",
            },
            savedGames: {
                defaultName: "保存したゲーム",
                nameAriaLabel: "保存したゲーム名",
                showDetails: "詳細を表示",
                detailsAriaLabel: "保存したゲームの詳細",
                editPosition: "局面を編集",
                deleteSavedGame: "保存したゲームを削除",
                renameSavedGame: "保存したゲームの名前を変更",
                noSavedPositions: "保存した局面はまだありません。",
                noSavedGames: "保存したゲームはまだありません。",
                nextMoveDash: "次の手: —",
                nextMove: "次の手: {{side}}",
                player: "プレイヤー",
                savedAt: "保存: {{when}}",
                gameId: "ゲーム ID: {{id}}",
                playersVs: "{{white}} 対 {{black}}",
            },
            reviewNav: {
                start: "最初",
                back: "戻る",
                play: "再生",
                pause: "一時停止",
                forward: "進む",
                end: "最後",
            },
            newGameDialog: {
                title: "AI との新しいゲーム",
                yourColor: "あなたの色",
                engine: "エンジン",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "各側の持ち時間（分）",
                allowUndo: "待ったを許可",
            },
            prompts: {
                positionName: "局面名",
                savePositionAs: "局面名を入力",
            },
            dialogs: {
                resignTitle: "このゲームを投了しますか？",
                resignBody: "あなたの負けになります。",
                leaveTitle: "ゲームを終了しますか？",
                leaveBody: "ゲームは投了扱いになります。",
                areYouSure: "よろしいですか？",
                discardUnsavedBrainConfig:
                    "保存していない Brain 設定の変更を破棄しますか？",
                accept: "受け入れる",
                decline: "拒否",
                saveAs: "名前を付けて保存",
                savePosition: "局面を保存",
                invalidPosition: "無効な局面",
                rematchChooseColor: "再戦で使う色を選択してください:",
                rematchOfferAgree: "相手が再戦を提案しました。同意しますか？",
                rematchColorPreference:
                    "相手は {{offerer}} で指したいと言っています。あなたは {{you}} になります。同意しますか？",
            },
        },
        session: {
            engineThinking: "エンジン思考中…",
            engineCouldNotFindMove: "エンジンは手を見つけられませんでした",
            engineError: "エンジンエラー",
            positionSetupPlacePieces: "局面設定 — 盤面に駒を配置してください",
            configurationModeEdit: "設定モード — 値を編集して保存",
            practiceBothSides: "練習 — 両側",
            opponentDisconnected: "相手が切断されました",
            opponentRejoined: "相手が再接続しました",
            playerRejoined: "{{name}} が再接続しました",
            drawOfferSent: "引き分けを提案しました",
            drawOfferDeclined: "引き分けの提案が拒否されました",
            rematchOfferSent: "再戦を提案しました",
            rematchOfferDeclined: "再戦の提案が拒否されました",
            drawAgreed: "引き分けで合意",
            rematchAcceptedNoGameId: "再戦は承諾されましたが、新しいゲーム ID がありません",
            rematchOfferAccepted: "再戦の提案が受け入れられました",
            gameOver: "ゲーム終了",
            somethingWentWrong: "問題が発生しました",
            opponentResigned: "相手が投了しました",
            opponentLeftGame: "相手がゲームを退出しました",
            opponentFailedToReconnect: "相手が再接続できませんでした",
            gameCancelled: "ゲームがキャンセルされました",
            gameCancelledWithDetail: "ゲームがキャンセルされました — {{detail}}",
            waitingForOpponent: "相手を待っています…",
            couldNotResolveWebSocketUrl: "WebSocket URL を解決できませんでした",
            opponentJoined: "{{name}} が参加しました",
            opponentDefault: "相手",
            connectionError: "接続エラー",
            playerDisconnectedWaitingRejoin:
                "{{name}} が切断されました — 再接続を待っています",
            playerFailedToReconnectWins:
                "{{loser}} が再接続できませんでした — {{winner}} の勝ち",
            watcherWaitingForReconnect: "プレイヤーの再接続を待っています…",
        },
        site: {
            confirm: "確認",
            cancel: "キャンセル",
            notice: "お知らせ",
            ok: "OK",
            home: "ホーム",
            search: "検索",
            friends: "フレンド",
            groups: "グループ",
            debug: "デバッグ",
            account: "アカウント",
            preferences: "環境設定",
            administrate: "管理",
            logOut: "ログアウト",
            logIn: "ログイン",
            admin: "管理者",
            homeAria: "ホーム",
        },
        validation: {
            validEmail: "有効なメールアドレスを入力してください",
            passwordsMustMatch: "パスワードが一致していることを確認してください。",
            chooseUsername: "ユーザー名を選択してください",
            usernameNotAvailable: "このユーザー名は利用できません",
            passwordNoWhitespace: "パスワードに空白を含めることはできません。",
            passwordUppercase: "パスワードには大文字を1文字以上含めてください。",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = ja;
    } else {
        global.ShmerlingStringsJa = ja;
    }
})(typeof window !== "undefined" ? window : globalThis);
