(function (global) {
    "use strict";
    const noExtra = {
    "validation": {
        "passwordLowercase": "Passordet må ha minst én liten bokstav.",
        "passwordDigit": "Passordet må inneholde minst ett siffer.",
        "passwordSymbol": "Passordet må inneholde minst ett spesialtegn.",
        "passwordLength": "Passordet må være 8–30 tegn langt.",
        "noHtml": "{{label}} kan ikke inneholde HTML.",
        "position": {
            "headerSave": "Kan ikke lagre denne stillingen:\n\n",
            "headerPlay": "Kan ikke spille fra denne stillingen:\n\n",
            "headerUse": "Kan ikke bruke denne stillingen:\n\n",
            "headerSaveBookmark": "Kan ikke lagre dette bokmerket:\n\n",
            "headerAddBookmark": "Kan ikke legge til dette bokmerket:\n\n",
            "boardUnreadable": "Kunne ikke lese brettet. Prøv igjen etter at brettet er lastet.",
            "whiteKingNone": "Det må være nøyaktig én hvit konge på brettet. Ingen ble funnet.",
            "whiteKingCount": "Det må være nøyaktig én hvit konge på brettet. Fant {{count}} hvite konger.",
            "blackKingNone": "Det må være nøyaktig én svart konge på brettet. Ingen ble funnet.",
            "blackKingCount": "Det må være nøyaktig én svart konge på brettet. Fant {{count}} svarte konger.",
            "kingsAdjacent": "De to kongene kan ikke stå på tilstøtende ruter (inkludert diagonalt).",
            "sideInCheck": "{{mover}} skal flytte, men {{king}}s konge står allerede i sjakk. Siden som skal flytte kan ikke gi sjakk — bytt tur eller flytt brikker.",
            "drawInsufficientKings": "Denne stillingen er remis på grunn av utilstrekkelig materiale (konge mot konge). Legg til brikker slik at sjakkmatt fortsatt er mulig.",
            "drawInsufficientMinor": "Denne stillingen er remis på grunn av utilstrekkelig materiale (konge og løper eller springer mot ensom konge). Legg til brikker slik at sjakkmatt fortsatt er mulig.",
            "drawBishopsSameColor": "Denne stillingen er remis på grunn av utilstrekkelig materiale (løper mot løper på samme feltfarge). Legg til brikker slik at sjakkmatt fortsatt er mulig.",
            "tooManyQueens": "{{color}} har {{count}} dronninger; maksimum er 9 per farge.",
            "tooManyRooks": "{{color}} har {{count}} tårn; maksimum er 10 per farge.",
            "tooManyBishops": "{{color}} har {{count}} løpere; maksimum er 10 per farge.",
            "tooManyKnights": "{{color}} har {{count}} springere; maksimum er 10 per farge.",
            "tooManyPawns": "{{color}} har {{count}} bønder; maksimum er 8 per farge."
        }
    },
    "auth": {
        "whoAreYou": "Hvem er du?",
        "enterPassword": "Skriv inn passordet ditt",
        "sorry": "Beklager",
        "continue": "Fortsett",
        "usernameField": "Brukernavn",
        "passwordField": "Passord",
        "wrongCredentials": "Feil brukernavn eller passord",
        "userAdded": "Bruker lagt til",
        "couldNotSaveBookmark": "Kunne ikke lagre bokmerke",
        "invalidUserId": "Ugyldig bruker-ID",
        "generationJobRunning": "En annen genereringsjobb kjører allerede…",
        "listingPgnFiles": "Lister PGN-filer…"
    },
    "classic": {
        "loadGame": "Last parti",
        "load": "Last",
        "enterGameState": "Lim inn partistilling her...",
        "rematch": "Omkamp",
        "drawOffer": "Remistilbud",
        "lastMove": "Siste trekk",
        "bookmarks": "Bokmerker",
        "bookmarkAlertTitle": "Bokmerk stilling",
        "promotion": "Underpromovering!",
        "check": "Sjakk",
        "checkmateWins": "Sjakkmatt! {{winner}} vinner!",
        "drawReason": "Remis! {{reason}}",
        "opponentDisconnected": "Motstanderen koblet fra",
        "opponentResignedWins": "Motstanderen ga opp, {{winner}} vinner",
        "somethingWentWrong": "Noe gikk galt",
        "playerRejoined": "{{name}} koblet til igjen",
        "aPlayerRejoined": "En spiller koblet til igjen",
        "opponentRejoined": "Motstanderen koblet til igjen",
        "rematchOfferAccepted": "Omkamptilbud godtatt",
        "rematchOfferDeclined": "Omkamptilbud avslått",
        "sideOffersDraw": "{{side}} tilbyr remis",
        "drawOfferDeclined": "Remistilbud avslått",
        "watcherWatching": "{{name}} ser på partiet",
        "drawOfferSent": "Remistilbud sendt",
        "rematchOfferSent": "Omkamptilbud sendt",
        "newGameStarted": "Nytt parti startet",
        "gameOver": "Partiet er avsluttet",
        "gameCancelled": "Parti avbrutt",
        "youResignedWins": "Du ga opp, {{winner}} vinner",
        "movesCopied": "Trekk kopiert til utklippstavlen!",
        "failedCopyMoves": "Kunne ikke kopiere trekk",
        "failedLoadBrainConfig": "Kunne ikke laste brain-konfigurasjon.",
        "failedSaveBrainConfig": "Kunne ikke lagre brain-konfigurasjon.",
        "offerDrawConfirm": "Tilby remis?",
        "drawOfferAccept": "Motstanderen tilbød remis, godta?",
        "rematchOfferAccept": "Motstanderen tilbød omkamp, godta?",
        "confirmExitGame": "Er du sikker på at du vil avslutte partiet?",
        "mobileResign": "Gi opp",
        "mobileRematch": "Omkamp",
        "mobileDraw": "Remis",
        "mobileFlip": "Snu",
        "mobileLastMove": "Siste trekk",
        "mobileMovesList": "Trekkliste",
        "researchToolbox": "Verktøykasse",
        "researchBrainConfig": "Brain-konfig.",
        "researchSave": "Lagre",
        "researchDiscard": "Forkast",
        "researchEditMode": "redigeringsmodus",
        "researchRun": "Kjør",
        "researchProperty": "Egenskap",
        "researchValue": "Verdi",
        "playerOnline": "Pålogget",
        "playerDisconnectedStatus": "Frakoblet",
        "playerOffline": "Frakoblet",
        "humanVsComputer": "Menneske mot datamaskin",
        "newGameTwoPlayers": "Nytt parti — 2 spillere",
        "settings": "Innstillinger",
        "help": "Hjelp",
        "drawOffersNotVsEngine": "Remistilbud er ikke tilgjengelig når du spiller mot motoren.",
        "failedStartFromBookmark": "Kunne ikke starte parti fra bokmerke.",
        "resignConfirm": "Gi opp?",
        "areYouSure": "Er du sikker?",
        "gameOverOpponentFailedReconnectWinsClassic": "Partiet er avsluttet — motstanderen klarte ikke å koble til igjen. {{winner}} vinner.",
        "reconnectTimeoutNoMoves": "Gjenopptakelse tidsavbrutt uten at trekk ble spilt.",
        "waitingOpponentRejoin": "Venter på at motstander kobler til igjen",
        "timeoutOneSec": "Tidsavbrudd: 1 sek",
        "timeoutSecs": "Tidsavbrudd: {{count}} sek",
        "whitePieceAlt": "Hvit brikke",
        "blackPieceAlt": "Svart brikke",
        "eraserTitle": "Viskelær",
        "eraserAria": "Viskelær – fjern brikke fra rute",
        "selectTitle": "Velg",
        "selectAria": "Velg – dra brikker for å flytte dem",
        "resetAria": "Tilbakestill – fjern alle brikker",
        "defaultPositionAria": "Standardstilling – sett opp normal startstilling",
        "loading": "Laster...",
        "engineLabel": "Motor"
    },
    "site": {
        "home": "Hjem",
        "search": "Søk",
        "friends": "Venner",
        "groups": "Grupper",
        "debug": "Feilsøking",
        "account": "Konto",
        "preferences": "Innstillinger",
        "administrate": "Administrer",
        "logOut": "Logg ut",
        "logIn": "Logg inn",
        "admin": "Admin",
        "homeAria": "Hjem",
        "confirm": "Bekreft",
        "cancel": "Avbryt",
        "notice": "Melding",
        "ok": "OK",
        "footer": {
            "logoAlt": "Shmerling Chess",
            "navAria": "Bunntekst",
            "privacy": "Personvernerklæring",
            "terms": "Bruksvilkår",
            "contact": "Kontakt",
            "copyright": "© {{year}} Shmerling Chess. Alle rettigheter forbeholdt.",
            "lastUpdated": "Sist oppdatert: {{date}}",
            "privacyTitle": "Personvernerklæring",
            "privacyLead": "Hvordan Shmerling Chess behandler konto- og spillinformasjon.",
            "privacyBody": "Vi bruker kontodetaljene dine for å drive tjenesten, lagre partier og preferanser, og forbedre produktet. Vi selger ikke personopplysninger. Full policytekst publiseres her.",
            "termsTitle": "Bruksvilkår",
            "termsLead": "Reglene for bruk av Shmerling Chess.",
            "termsBody": "Ved å bruke Shmerling Chess godtar du å spille fair, respektere andre spillere og bruke tjenesten kun til personlig sjakkspill. Fullstendige vilkår publiseres her.",
            "contactTitle": "Kontakt",
            "contactLead": "Ta kontakt med Shmerling Chess-teamet.",
            "contactBody": "Kontaktinformasjon for support og personvernspørsmål publiseres her."
        },
        "username": "Brukernavn:",
        "password": "Passord:",
        "login": "Logg inn",
        "register": {
            "submit": "Registrer",
            "confirmPassword": "Bekreft passord:",
            "playerLevel": "Spillernivå:",
            "rookie": "Nybegynner",
            "skilled": "Dyktig",
            "elite": "Elite",
            "grandMaster": "Stormester"
        },
        "email": "E-post:",
        "welcome": {
            "greeting": "Velkommen tilbake",
            "tagline": "Ditt trekk venter",
            "playNow": "Spill nå!",
            "activeGames": "Aktive partier",
            "live": "Live",
            "showAll": "Vis alle",
            "viewAllActive": "Se alle aktive partier",
            "mostRecent": "Nyeste først",
            "noGamesNow": "Ingen partier akkurat nå",
            "myGames": "Mine partier",
            "viewAllGames": "Se alle partier",
            "recentCompleted": "Dine nylig avsluttede partier",
            "noCompleted": "Ingen avsluttede partier ennå",
            "activeGamesAria": "Aktive partier",
            "inviteOnlineFriend": "Inviter en nettvenn til å spille",
            "friendsPageTitle": "Vennerside",
            "manageFriends": "Administrer",
            "colFriend": "Venn",
            "colStatus": "Status",
            "findPlayers": "Finn spillere",
            "waitingForResponse": "Venter på svar",
            "inviteSentSuffix": "(invitasjon sendt)",
            "sortByRowNumber": "Sorter etter radnummer",
            "sortBy": "Sorter etter {{key}}"
        },
        "gameList": {
            "date": "Dato",
            "time": "Tid",
            "result": "Resultat",
            "reason": "Årsak",
            "type": "Type",
            "status": "Status",
            "event": "Turnering",
            "site": "Sted",
            "round": "Runde"
        },
        "loginPage": {
            "title": "Logg inn"
        },
        "error": {
            "title": "Noe gikk galt",
            "body": "Det oppstod en feil.",
            "back": "Tilbake til forsiden"
        },
        "log": {
            "title": "Serverlogg",
            "clear": "Tøm visning",
            "latest": "Siste",
            "waiting": "Venter på serverlogg…"
        },
        "activeGames": {
            "moves": "Trekk",
            "turn": "Tur",
            "status": "Status",
            "inProgress": "Pågår",
            "onHold": "På vent",
            "vs": " mot ",
            "minutesAgo": "for {{count}} minutter siden",
            "oneMinuteAgo": "for 1 minutt siden",
            "justStarted": "Nettopp startet",
            "notStarted": "Ikke startet",
            "startedTooltip": "Startet: {{when}}",
            "playersVs": "{{white}} mot {{black}}"
        },
        "friendsPage": {
            "title": "Venner",
            "tagline": "Finn nye sjakkvenner",
            "myFriends": "Mine venner",
            "noFriendsYet": "Ingen venner ennå",
            "findPlayers": "Finn spillere",
            "searchByUsername": "Søk etter brukernavn",
            "searchPlaceholder": "Skriv for å søke…",
            "enterCharToSearch": "Skriv minst ett tegn for å søke",
            "noMatchingUsers": "Ingen treff",
            "playing": "Spiller",
            "pendingFriendshipOffer": "Ventende venneforespørsel",
            "joining": "Blir med",
            "rejoin": "Koble til igjen",
            "friendRequest": "Venneforespørsel",
            "wantsToBeFriends": "(vil bli venner)",
            "pendingOfferSuffix": "(ventende venneforespørsel)",
            "waitingFriendRespond": "Venter på svar fra vennen din",
            "cancelBeforeRemove": "Avbryt partinvitasjonen før du fjerner denne vennen",
            "friendsTag": "Venner",
            "offerReceivedTag": "Tilbud mottatt — se Dine venner",
            "addFriend": "Legg til venn",
            "withdraw": "Trekk tilbake",
            "requestFailed": "Forespørsel mislyktes",
            "removeFriendConfirm": "Fjerne denne vennen fra listen?",
            "removeFriendTitle": "Fjern venn",
            "withdrawOfferConfirm": "Trekke tilbake denne venneforespørselen?",
            "withdrawOfferTitle": "Trekk tilbake tilbud",
            "couldNotAccept": "Kunne ikke godta",
            "couldNotDecline": "Kunne ikke avslå",
            "couldNotRemove": "Kunne ikke fjerne",
            "couldNotCancelInvite": "Kunne ikke avbryte invitasjon",
            "couldNotWithdraw": "Kunne ikke trekke tilbake",
            "couldNotSendInvite": "Kunne ikke sende invitasjon",
            "couldNotSendGameInvite": "Kunne ikke sende partinvitasjon",
            "gameInvite": "Partinvitasjon",
            "gameInvitationsAria": "Partinvitasjoner",
            "gameInvitationAria": "Partinvitasjon",
            "chessInviteTitle": "Sjaktinvitasjon",
            "wantsToPlayAsBlack": "{{name}} vil spille. Du spiller som svart.",
            "aFriend": "En venn",
            "youPlayAsWhite": "Du spiller som hvit",
            "youPlayAsBlack": "Du spiller som svart",
            "establishingGame": "Etablerer parti…",
            "yourOpponent": "Din motstander",
            "declinedYourInvite": "{{name}} avslo partinvitasjonen din.",
            "cancelInvite": "Avbryt invitasjon",
            "accept": "Godta",
            "decline": "Avslå",
            "invite": "Inviter",
            "remove": "Fjern",
            "offerSent": "Tilbud sendt",
            "pending": "Venter",
            "online": "Pålogget",
            "offline": "Frakoblet"
        },
        "adminPage": {
            "title": "Administrasjon",
            "users": "Brukere",
            "generate": "Generer",
            "games": "Partier",
            "engines": "Motorer",
            "states": "Tilstander",
            "addUser": "Legg til bruker",
            "sectionsAria": "Admin-seksjoner",
            "openingBookLabel": "Åpningsbok:",
            "gameLines": "partilinjer",
            "noGamesInDb": "Ingen partier i databasen ennå.",
            "gamesPaginationAria": "Partipaginering",
            "colNum": "#",
            "colUsername": "Brukernavn",
            "colType": "Type",
            "colEmail": "E-post",
            "colPassword": "Passord",
            "colLevel": "Nivå",
            "colElo": "Elo",
            "colJoined": "Registrert",
            "colLastLogin": "Siste innlogging",
            "colActiveGames": "Aktive partier",
            "colFriends": "Venner",
            "colBookmarks": "Bokmerker",
            "colId": "Id",
            "colStatus": "Status",
            "colName": "Navn",
            "colAvailable": "Tilgjengelig",
            "colNotes": "Notater",
            "colNote": "Notat",
            "colAction": "Handling",
            "emptyUsers": "Ingen brukere ennå.",
            "emptyData": "Ingen data ennå.",
            "emptyStates": "Bruk Generer for å åpne siden for åpningsbok og tilstandsgenerering.",
            "clickToEdit": "Klikk for å redigere",
            "updateFailed": "Oppdatering mislyktes",
            "couldNotSave": "Kunne ikke lagre",
            "setPassword": "Sett passord",
            "setPasswordTitle": "Klikk for å sette nytt passord (4–30 tegn)",
            "passwordLengthInvalid": "Passordet må være mellom 4 og 30 tegn.",
            "invalidPassword": "Ugyldig passord",
            "saved": "Lagret",
            "newPasswordPlaceholder": "Nytt passord",
            "clickChangeUserType": "Klikk for å endre brukertype",
            "userTypeAria": "Brukertype",
            "changeUserTypeTitle": "Endre brukertype",
            "grantAdminConfirm": "Gi denne brukeren admin-rettigheter? De får tilgang til adminverktøy og kan administrere kontoer.",
            "demoteAdminConfirm": "Endre denne brukeren fra Admin til {{type}}? De mister tilgang til adminområdet.",
            "changeUserTypeConfirm": "Endre denne brukeren til {{type}}?",
            "clickChangeLevel": "Klikk for å endre nivå",
            "playerLevelAria": "Spillernivå",
            "sortByRowNumber": "Sorter etter radnummer",
            "sortBy": "Sorter etter {{key}}",
            "delete": "Slett",
            "first": "Første",
            "last": "Siste",
            "previous": "Forrige",
            "next": "Neste",
            "previous5Pages": "Forrige 5 sider",
            "next5Pages": "Neste 5 sider",
            "previous10Pages": "Forrige 10 sider",
            "next10Pages": "Neste 10 sider",
            "userTypeAdmin": "Admin",
            "userTypePartner": "Partner",
            "userTypeMember": "Medlem",
            "generateTitle": "Åpningsbok og tilstandsgenerering",
            "backToAdmin": "← Tilbake til admin",
            "generateIntro": "Spiller av alle PGN-filer under serverens partimappe til enten State MongoDB-samlingen eller den linjebaserte åpningsboken (data/opening-book-lines.txt). Velg mål, og trykk Start generering — ingenting kjører før du gjør det.",
            "target": "Mål",
            "targetMongo": "MongoDB — legg til rader i State-samlingen",
            "targetBook": "Linjefil — skriv åpningsbok (opening-book-lines.txt)",
            "startGeneration": "Start generering",
            "stop": "Stopp",
            "idle": "Inaktiv.",
            "starting": "Starter…",
            "running": "Kjører ({{mode}})…",
            "readingFiles": "Leser {{count}} fil(er)…",
            "replayingGames": "Spiller av {{count}} partier…",
            "writingOpeningBook": "Skriver åpningsbok…",
            "readingPgn": "Leser PGN {{index}} / {{total}} ({{games}} partier)",
            "replayGameProgress": "Spiller av parti {{current}} / {{total}} (fullført ok: {{completed}})",
            "stopped": "Stoppet.",
            "bookUnchanged": "Eksisterende åpningsbok ble ikke endret.",
            "bookLinesInFile": "{{count}} partilinje(r) i {{file}}.",
            "cancelledBeforeRead": "Avbrutt før lesing av PGN-er.",
            "cancelledAfterRead": "Avbrutt etter lesing; avspilling ble hoppet over (ingenting skrevet).",
            "mongoGamesSaved": "{{count}} parti(er) fikk nye tilstandsrader lagret.",
            "doneBook": "Ferdig. {{count}} partilinjer → {{file}}",
            "doneBookFileOnly": "Ferdig. {{file}}",
            "doneMongo": "Ferdig. MongoDB State-samling oppdatert{{detail}}.",
            "doneMongoDetail": " ({{count}} partier spilt av ok)",
            "errorPrefix": "Feil: {{message}}",
            "unknownError": "Ukjent",
            "connectionClosed": "Tilkoblingen ble lukket (sjekk serverlogger eller prøv igjen).",
            "openingBookDefault": "åpningsbok"
        },
        "playNow": {
            "title": "Nytt parti",
            "startTitle": "Start et nytt parti",
            "playingColor": "Spillefarge",
            "timeMin": "Tid (min)",
            "difficulty": "Vanskelighetsgrad (1–5)",
            "mousePreference": "Muspreferanse",
            "drag": "Dra",
            "doubleClick": "Dobbeltklikk",
            "showAvailableMoves": "Vis mulige trekk",
            "private": "Privat",
            "privateHint": "Private partier vises ikke i andre medlemmers lister over aktive partier.",
            "playComputer": "Spill mot datamaskin",
            "browseAll": "Bla gjennom alle",
            "yourHistory": "Din historikk",
            "fullList": "Full liste",
            "gameLibrary": "Partibibliotek",
            "openLibrarySearch": "Åpne biblioteksøk",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Aktive partier",
            "tagline": "Alle partier som pågår",
            "liveGames": "Live-partier",
            "game": "Parti",
            "started": "Startet"
        },
        "list": {
            "title": "Alle partier",
            "action": "Handling"
        },
        "searchPage": {
            "title": "Søk:",
            "tagline": "Finn partier i PGN-arkivet",
            "results": "Treff",
            "resultsCount": "{{count}} treff",
            "noResults": "Ingen partier samsvarer med søket",
            "button": "Søk",
            "resultsFound": "{{count}} treff:",
            "first": "Første",
            "last": "Siste",
            "previous": "Forrige",
            "next": "Neste",
            "previous5Pages": "Forrige 5 sider",
            "next5Pages": "Neste 5 sider",
            "previous10Pages": "Forrige 10 sider",
            "next10Pages": "Neste 10 sider"
        },
        "game": {
            "moves": "Trekk",
            "white": "Hvit",
            "black": "Svart",
            "resign": "Gi opp",
            "draw": "Remis",
            "undo": "Angre",
            "flip": "Snu",
            "practice": "Trening"
        },
        "mobileWelcome": {
            "title": "Hjem — Sjakk",
            "play": "Spill",
            "library": "Bibliotek",
            "friends": "Venner"
        },
        "mobileGame": {
            "title": "Parti",
            "moves": "Trekk",
            "resign": "Gi opp"
        }
    },
    "desktop": {
        "error": {
            "title": "Noe gikk galt",
            "body": "Det oppstod en feil.",
            "back": "Tilbake til forsiden"
        },
        "chrome": {
            "preferences": "Innstillinger",
            "closePreferences": "Lukk innstillinger",
            "display": "Visning",
            "gameplay": "Spill",
            "pieceSet": "Brikkesett",
            "boardTheme": "Bretttema",
            "themeBlue": "Blått",
            "themeDark": "Mørkt",
            "customizeTheme": "Tilpass tema…",
            "builtInThemesAria": "Innebygde temaer",
            "savedCustomThemesAria": "Lagrede egendefinerte temaer",
            "pieceSetsAria": "Brikkesett",
            "homeAria": "Shmerling Chess hjem"
        },
        "prefs": {
            "language": "Språk",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "Muskontroll",
            "thinkingTime": "Tenketid",
            "thinkingTimeAria": "Tenketid i sekunder",
            "immediateResign": "Gi opp umiddelbart",
            "secondsOption": "{{count}} s",
            "enterFullScreen": "Fullskjerm",
            "exitFullScreen": "Avslutt fullskjerm",
            "fullScreenUnavailable": "Fullskjerm er ikke tilgjengelig i denne nettleseren."
        },
        "gameRun": {
            "yourColor": "Din farge",
            "engine": "Motor",
            "thinkTime": "Tenketid (sekunder)",
            "thinkTimeAria": "Motorens tenketid i sekunder",
            "play": "Spill",
            "nextMove": "Neste trekk",
            "computer": "Datamaskin",
            "computerColorHint": "Hvilken farge datamaskinen spiller — du spiller den andre siden"
        },
        "brainConfig": {
            "title": "Brain-konfigurasjon",
            "save": "Lagre",
            "reset": "Tilbakestill",
            "saved": "Konfigurasjon lagret",
            "failedSave": "Kunne ikke lagre konfigurasjon",
            "brainLabel": "Brain",
            "loading": "Laster…",
            "failedLoad": "Kunne ikke laste brain-konfigurasjon.",
            "discardSwitchConfirm": "Forkaste ulagrede endringer og bytte brain-versjon?",
            "discard": "Forkast",
            "pieceScores": "Brikkeverdier",
            "specialEvaluations": "Spesielle evalueringer",
            "gamePhase": "Partifase",
            "pawnFilesOpeningMid": "Bondelinjer (åpning / midtspill)",
            "pawnFilesEndGame": "Bondelinjer (sluttspill)"
        },
        "customTheme": {
            "title": "Egendefinert tema",
            "name": "Temanavn",
            "save": "Lagre",
            "delete": "Slett",
            "saved": "Lagret",
            "searchProperties": "Søk egenskaper",
            "filterPlaceholder": "Filtrer etter egenskapsnavn…",
            "namePlaceholder": "Mitt tema",
            "resetPreset": "Tilbakestill til gjeldende forvalg",
            "couldNotSave": "Kunne ikke lagre tema. Prøv igjen.",
            "untitled": "Uten tittel",
            "defaultName": "Egendefinert tema"
        },
        "positionSetup": {
            "clearBoard": "Tøm brett",
            "startingPosition": "Startstilling",
            "flipBoard": "Snu brett",
            "eraser": "Viskelær",
            "selectAndMove": "Velg og flytt",
            "defaultStartingPosition": "Standard startstilling",
            "savePosition": "Lagre stilling",
            "saveAsNewPosition": "Lagre som ny stilling",
            "validatePosition": "Valider stilling",
            "positionFlags": "Stillingsflagg",
            "turn": "Tur",
            "flagCheck": "Sjakk",
            "flagCheckmate": "Sjakkmatt",
            "flagDraw": "Remis",
            "flagWhiteKingMoved": "Hvit konge har flyttet",
            "flagBlackKingMoved": "Svart konge har flyttet",
            "flagWhiteKingsideRookMoved": "Hvits kongeside-tårn har flyttet",
            "flagWhiteQueensideRookMoved": "Hvits dronning-side-tårn har flyttet",
            "flagBlackKingsideRookMoved": "Svarts kongeside-tårn har flyttet",
            "flagBlackQueensideRookMoved": "Svarts dronning-side-tårn har flyttet"
        }
    },
    "errorPage": {
        "code": "Feil {{code}}",
        "notFoundTitle": "Siden ble ikke funnet",
        "notFoundMessage": "Siden du leter etter finnes ikke.",
        "genericTitle": "Noe gikk galt",
        "genericMessage": "Det oppstod en uventet feil. Prøv igjen.",
        "backHome": "Tilbake til startsiden"
    },
    "mobile": {
        "drawOfferTitle": "Remistilbud",
        "drawOfferMessage": "Motstanderen tilbød remis. Godta?",
        "rematchTitle": "Omkamp",
        "rematchMessage": "Motstanderen tilbød omkamp. Godta?",
        "gameId": "Parti-ID: {{id}}",
        "drawOfferAgree": "Motstanderen tilbød remis, godta?",
        "rematchOfferAgree": "Motstanderen tilbød omkamp, godta?",
        "newGameWatchFromHome": "Nytt parti startet — gå til Hjem for å se på."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = noExtra;
    } else {
        global.ShmerlingStringsNoExtra = noExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
