/**
 * Norwegian (Bokmål) string catalog — mirrors src/strings/en.js structure.
 */
(function (global) {
    "use strict";

    const noStrings = {
        common: {
            white: "Hvit",
            black: "Svart",
            draw: "Remis",
            winner: "Vinner",
            engine: "Motor",
            ok: "OK",
            cancel: "Avbryt",
            confirm: "Bekreft",
            yes: "Ja",
            no: "Nei",
            notice: "Melding",
            input: "Inndata",
            start: "Start",
            collapse: "Skjul",
            expand: "Vis",
            delete: "Slett",
            rename: "Gi nytt navn",
            save: "Lagre",
            aPlayer: "En spiller",
            pleaseEnterValue: "Skriv inn en verdi.",
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Partihandlinger",
                playersAndClocks: "Spillere og klokker",
                whitePlayerClock: "Klokke for hvit",
                blackPlayerClock: "Klokke for svart",
                startFromLoadedPosition: "Start parti fra lastet stilling",
                moves: "Trekk",
                expandMovesPanel: "Vis trekkpanel",
                expandMoves: "Vis trekk",
                collapseMovesPanel: "Skjul trekkpanel",
                reviewNavigation: "Gjennomgang-navigasjon",
                positionSetup: "Stillingsoppsett",
                pieces: "Brikker",
                collapsePiecesPanel: "Skjul brikkepanel",
                brainConfiguration: "Brain-konfigurasjon",
                configuration: "Konfigurasjon",
                collapseConfigurationPanel: "Skjul konfigurasjonspanel",
                games: "Partier",
                expandGamesPanel: "Vis partipanel",
                expandGames: "Vis partier",
                collapseGamesPanel: "Skjul partipanel",
                chat: "Chat",
                expandChatPanel: "Utvid chat-panelet",
                collapseChatPanel: "Skjul chat-panelet",
                chatPlaceholder: "Skriv en melding…",
                chatWatcherReadonly: "Tilskuere kan bare lese chatten",
                sendChat: "Send",
                savedListFilter: "Filter for lagret liste",
                positions: "Stillinger",
                gameStatus: "Partistatus",
                capturedPieces: "Slåtte brikker",
            },
            sessionMode: {
                play: "Spillmodus",
                positionSetup: "Stillingsoppsett",
                configuration: "Konfigurasjonsmodus",
                playback: "Avspillingsmodus",
                review: "Gjennomgangsmodus",
                watch: "Tittemodus",
                practice: "Treningsmodus",
            },
            status: {
                chooseNewGameOrSetup:
                    "Velg Nytt parti eller Stillingsoppsett i sidepanelet",
                chooseNewGame: "Velg Nytt parti i sidepanelet",
                setMoveColorEngineThinkTime:
                    "Angi trekk, farge, motor og tenketid i topplinjen, og trykk Spill",
                gameOver: "Partiet er avsluttet",
                gameInProgress: "Parti pågår",
                boardLoading: "Brekket lastes fortsatt…",
                boardNotReady: "Brekket er ikke klart ennå. Vent litt og prøv igjen.",
                leaveOnlineBeforeConfiguration:
                    "Forlat nettpartiet før du åpner Konfigurasjon",
                configurationNotInPractice:
                    "Konfigurasjon er ikke tilgjengelig i treningsmodus",
                configurationModeEdit:
                    "Konfigurasjonsmodus — rediger verdier og lagre",
                selectSavedOrSetup:
                    "Velg et lagret parti eller sett opp en stilling på brettet først",
                gameAlreadyInProgress: "Et parti pågår allerede",
                yourMove: "Ditt trekk",
                engineToMove: "Motor skal flytte…",
                leaveOnlineBeforePositionSetup:
                    "Forlat nettpartiet før du åpner Stillingsoppsett",
                positionSetupNotInPractice:
                    "Stillingsoppsett er ikke tilgjengelig i treningsmodus",
                positionSetupPlacePieces:
                    "Stillingsoppsett — plasser brikker på brettet",
                drawWithReason: "Remis — {{reason}}",
                checkmateWins: "Sjakkmatt — {{winner}} vinner",
                check: "Sjakk",
                waitBeforeEvaluate:
                    "Vent til det nåværende trekket er ferdig før du evaluerer",
                evaluationUnavailable:
                    "Evaluering er ikke tilgjengelig. Start Shmerling Chess-appen på nytt.",
                evaluatingPosition: "Evaluerer stilling…",
                evaluationFailed: "Evaluering mislyktes",
                evaluationLine: "Evaluering ({{side}} skal flytte): {{score}}",
                checkmate: "Sjakkmatt",
                drawZero: "Remis (0)",
                totalLabel: "Totalt: {{value}}",
                openFolderDesktopOnly:
                    "Åpne mappe er bare tilgjengelig i skrivebordsappen",
                couldNotOpenGamesLogFolder: "Kunne ikke åpne partilogg-mappen",
                positionValid: "Stillingen er gyldig",
                playingFromCustomPosition: "Spiller fra egendefinert stilling",
                nothingToSave: "Ingenting å lagre",
                positionSaved: "Stilling lagret",
                couldNotSavePosition: "Kunne ikke lagre stilling",
                savedPositionNotFound: "Lagret stilling ble ikke funnet",
                positionUpdated: "Stilling oppdatert",
                couldNotUpdatePosition: "Kunne ikke oppdatere stilling",
                nameCannotBeEmpty: "Navn kan ikke være tomt",
                gameRenamed: "Parti har fått nytt navn",
                couldNotRenameGame: "Kunne ikke gi partiet nytt navn",
                deletedCount: "Slettet {{count}} element(er)",
                couldNotDeleteSelected: "Kunne ikke slette valgte elementer",
                couldNotLoadSavedGame: "Kunne ikke laste lagret parti",
                editingPositionSaveBookmark:
                    "Redigerer stilling — Lagre for å oppdatere dette bokmerket",
                couldNotOpenPositionForEditing:
                    "Kunne ikke åpne stilling for redigering",
                gameSaved: "Parti lagret",
                couldNotSaveGame: "Kunne ikke lagre parti",
                engineMoveNotApplied: "Motorens trekk kunne ikke utføres",
                engineCouldNotFindMove: "Motoren fant ikke noe trekk",
                engineError: "Motorfeil",
                engineThinking: "Motoren tenker…",
                sessionError: "Øktfeil",
                timesUpLost: "Tiden er ute! {{loser}} tapte",
                drawOfferTitle: "Remistilbud",
                drawOfferMessage: "Motstanderen tilbød remis. Godta?",
                rematchTitle: "Omkamp",
                playerDisconnectedWaiting:
                    "{{who}} koblet fra — venter på gjenopptakelse ({{countdown}})",
                opponentDisconnectedCountdown:
                    "Motstander koblet fra — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "Parti avbrutt — gjenopptakelse tidsavbrutt uten at trekk ble spilt.",
                playerFailedToReconnectWins:
                    "{{loser}} klarte ikke å koble til igjen — {{winner}} vinner",
                gameOverOpponentFailedReconnect:
                    "Partiet er avsluttet — motstanderen klarte ikke å koble til igjen.",
                couldNotStartRematch: "Kunne ikke starte omkamp",
                rematchStarted: "Omkamp startet",
                gameCancelled: "Parti avbrutt",
                gameCancelledWithDetail: "Parti avbrutt — {{detail}}",
                resignFailed: "Oppgivelse mislyktes",
                gameResumedYourMove: "Parti gjenopptatt — ditt trekk",
                practiceNotAvailable: "Treningsmodus er ikke tilgjengelig",
                couldNotJoinOnPlay: "Kunne ikke bli med i dette partiet på /play",
                practiceDebugNotAvailable:
                    "Trening / feilsøking er ikke tilgjengelig for denne kontoen",
                reviewRequiresWebApi: "Gjennomgang krever web-API",
                couldNotLoadReviewGame: "Kunne ikke laste gjennomgangsparti",
                notReviewGameLink: "Denne lenken er ikke et gjennomgangsparti",
                onlineRequiresWebApi: "Nettspill krever web-API",
                couldNotLoadOnlineGame: "Kunne ikke laste nettparti",
                notOnlineGameOnPlay: "Denne lenken er ikke et nettparti på /play",
                watchingLiveGame: "Ser på live-parti",
                waitingForOpponentToJoin: "Venter på at motstander blir med…",
                waitingForOpponent: "Venter på motstander…",
                onlineGameConnected: "Nettparti — tilkoblet",
                gameDeleted: "Parti slettet",
                itemsDeleted: "{{count}} elementer slettet",
                choosePromotionPiece: "Velg bondeunderpromovering",
                invalidPromotionPiece: "Ugyldig underpromoveringsbrikke",
                drawOfferNotAvailable: "Remistilbud er ikke tilgjengelig nå",
            },
            drawReasons: {
                stalemate: "Patt",
                fiftyMoves: "50-trekksregelen",
                insufficientMaterial: "Utilstrekkelig materiale",
                threefoldRepetition: "Tredobbel gjentakelse",
                drawOfferAccepted: "Remistilbud fra {{by}} godtatt",
            },
            actions: {
                newGame: "Nytt parti",
                resign: "Gi opp",
                draw: "Remis",
                undo: "Angre",
                redo: "Gjør om",
                lastMove: "Siste trekk",
                positionSetup: "Stillingsoppsett",
                config: "Konfig.",
                flip: "Snu",
                save: "Lagre",
                exit: "Avslutt",
                loadToStart: "Last for å starte",
                editPosition: "Rediger stilling",
            },
            savedGames: {
                defaultName: "Lagret parti",
                nameAriaLabel: "Navn på lagret parti",
                showDetails: "Vis detaljer",
                detailsAriaLabel: "Detaljer om lagret parti",
                editPosition: "Rediger stilling",
                deleteSavedGame: "Slett lagret parti",
                renameSavedGame: "Gi lagret parti nytt navn",
                noSavedPositions: "Ingen lagrede stillinger ennå.",
                noSavedGames: "Ingen lagrede partier ennå.",
                nextMoveDash: "Neste trekk: —",
                nextMove: "Neste trekk: {{side}}",
                player: "Spiller",
                savedAt: "Lagret: {{when}}",
                gameId: "Parti-ID: {{id}}",
                playersVs: "{{white}} mot {{black}}",
            },
            reviewNav: {
                start: "Start",
                back: "Tilbake",
                play: "Spill av",
                pause: "Pause",
                forward: "Frem",
                end: "Slutt",
            },
            newGameDialog: {
                title: "Nytt parti mot AI",
                yourColor: "Din farge",
                engine: "Motor",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "Tid per side (minutter)",
                allowUndo: "Tillat angre",
                private: "Privat",
                privateHint:
                    "Private partier vises ikke i andre medlemmers lister over aktive partier.",
            },
            prompts: {
                positionName: "Stillingsnavn",
                savePositionAs: "Lagre stilling som",
            },
            dialogs: {
                resignTitle: "Gi opp dette partiet?",
                resignBody: "Du taper partiet.",
                leaveTitle: "Forlate partiet?",
                leaveBody: "Partiet ditt blir gitt opp.",
                areYouSure: "Er du sikker?",
                discardUnsavedBrainConfig:
                    "Forkaste ulagrede endringer i brain-konfigurasjonen?",
                accept: "Godta",
                decline: "Avslå",
                saveAs: "Lagre som",
                savePosition: "Lagre stilling",
                invalidPosition: "Ugyldig stilling",
                rematchChooseColor: "Velg farge for omkampen:",
                rematchOfferAgree: "Motstanderen tilbød omkamp. Godta?",
                rematchColorPreference:
                    "Motstanderen vil spille som {{offerer}}. Du ville spille som {{you}}. Godta?",
            },
        },
        session: {
            engineThinking: "Motoren tenker…",
            engineCouldNotFindMove: "Motoren fant ikke noe trekk",
            engineError: "Motorfeil",
            positionSetupPlacePieces: "Stillingsoppsett — plasser brikker på brettet",
            configurationModeEdit: "Konfigurasjonsmodus — rediger verdier og lagre",
            practiceBothSides: "Trening — begge sider",
            opponentDisconnected: "Motstander koblet fra",
            opponentRejoined: "Motstander koblet til igjen",
            playerRejoined: "{{name}} koblet til igjen",
            drawOfferSent: "Remistilbud sendt",
            drawOfferDeclined: "Remistilbud avslått",
            rematchOfferSent: "Omkamptilbud sendt",
            rematchOfferDeclined: "Omkamptilbud avslått",
            drawAgreed: "Remis avtalt",
            rematchAcceptedNoGameId: "Omkamp godtatt, men ingen ny parti-ID",
            rematchOfferAccepted: "Omkamptilbud godtatt",
            gameOver: "Partiet er avsluttet",
            somethingWentWrong: "Noe gikk galt",
            opponentResigned: "Motstanderen ga opp",
            opponentLeftGame: "Motstanderen forlot partiet",
            opponentFailedToReconnect: "Motstanderen klarte ikke å koble til igjen",
            gameCancelled: "Parti avbrutt",
            gameCancelledWithDetail: "Parti avbrutt — {{detail}}",
            waitingForOpponent: "Venter på motstander…",
            couldNotResolveWebSocketUrl: "Kunne ikke finne WebSocket-URL",
            opponentJoined: "{{name}} ble med",
            opponentDefault: "Motstander",
            connectionError: "Tilkoblingsfeil",
            playerDisconnectedWaitingRejoin:
                "{{name}} koblet fra — venter på gjenopptakelse",
            playerFailedToReconnectWins:
                "{{loser}} klarte ikke å koble til igjen — {{winner}} vinner",
            watcherWaitingForReconnect: "Venter på at en spiller kobler til igjen…",
        },
        site: {
            confirm: "Bekreft",
            cancel: "Avbryt",
            notice: "Melding",
            ok: "OK",
            home: "Hjem",
            search: "Søk",
            friends: "Venner",
            groups: "Grupper",
            debug: "Feilsøking",
            account: "Konto",
            preferences: "Innstillinger",
            administrate: "Administrer",
            logOut: "Logg ut",
            logIn: "Logg inn",
            admin: "Admin",
            homeAria: "Hjem",
        },
        validation: {
            validEmail: "Fyll inn en gyldig e-postadresse",
            passwordsMustMatch: "Passordfeltene må være like.",
            chooseUsername: "Velg et brukernavn",
            usernameNotAvailable: "Dette brukernavnet er ikke tilgjengelig",
            passwordNoWhitespace: "Passordet kan ikke inneholde mellomrom.",
            passwordUppercase: "Passordet må ha minst én stor bokstav.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = noStrings;
    } else {
        global.ShmerlingStringsNo = noStrings;
    }
})(typeof window !== "undefined" ? window : globalThis);
