/**
 * Portuguese supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const ptExtra = {
        validation: {
            passwordLowercase: "A senha deve ter pelo menos um caractere minúsculo.",
            passwordDigit: "A senha deve conter pelo menos um dígito.",
            passwordSymbol: "A senha deve conter pelo menos um símbolo especial.",
            passwordLength: "A senha deve ter de 8 a 30 caracteres.",
            noHtml: "{{label}} não deve incluir HTML.",
            position: {
                headerSave: "Não é possível salvar esta posição:",
                headerPlay: "Não é possível jogar nesta posição:",
                headerUse: "Não é possível usar esta posição:",
                headerSaveBookmark: "Não é possível salvar este favorito:",
                headerAddBookmark: "Não é possível adicionar este marcador:",
                boardUnreadable: "Não foi possível ler o quadro. Tente novamente depois que a placa for carregada.",
                whiteKingNone: "Deve haver exatamente um rei branco no tabuleiro. Nenhum foi encontrado.",
                whiteKingCount: "Deve haver exatamente um rei branco no tabuleiro. Encontrados {{count}} reis brancos.",
                blackKingNone: "Deve haver exatamente um rei preto no tabuleiro. Nenhum foi encontrado.",
                blackKingCount: "Deve haver exatamente um rei preto no tabuleiro. Encontrados {{count}} reis pretos.",
                kingsAdjacent: "Os dois reis não podem estar em casas adjacentes (inclusive na diagonal).",
                sideInCheck: "{{mover}} deve se mover, mas o rei de {{king}} já está em xeque. O lado a ser movido não pode estar dando xeque – mudar de turno ou mover peças.",
                drawInsufficientKings: "Esta posição é um empate por material insuficiente (rei contra rei). Adicione peças para que o xeque-mate seja possível.",
                drawInsufficientMinor: "Esta posição é um empate por material insuficiente (rei e bispo ou cavalo versus rei solitário). Adicione peças para que o xeque-mate seja possível.",
                drawBishopsSameColor: "Esta posição é um empate por material insuficiente (bispo versus bispo na mesma cor do quadrado). Adicione peças para que o xeque-mate seja possível.",
                tooManyQueens: "{{color}} tem {{count}} rainhas; o máximo é 9 por cor.",
                tooManyRooks: "{{color}} tem torres {{count}}; o máximo é 10 por cor.",
                tooManyBishops: "{{color}} tem {{count}} bispos; o máximo é 10 por cor.",
                tooManyKnights: "{{color}} tem {{count}} cavaleiros; o máximo é 10 por cor.",
                tooManyPawns: "{{color}} tem peões {{count}}; o máximo é 8 por cor."
            }
        },
        auth: {
            whoAreYou: "Quem é você?",
            enterPassword: "Senha por favor",
            sorry: "Desculpe",
            continue: "Continuar",
            usernameField: "Nome de usuário",
            passwordField: "Senha",
            wrongCredentials: "Nome de usuário ou senha errados",
            userAdded: "Usuário adicionado com sucesso",
            couldNotSaveBookmark: "Não foi possível salvar o favorito",
            invalidUserId: "ID de usuário inválido",
            generationJobRunning: "Outro trabalho de geração já está em execução…",
            listingPgnFiles: "Listando arquivos PGN…"
        },
        classic: {
            loadGame: "Carregar jogo",
            load: "Carregar",
            enterGameState: "Cole o estado do jogo aqui...",
            rematch: "Revanche",
            drawOffer: "Oferta de empate",
            lastMove: "Último movimento",
            bookmarks: "Favoritos",
            bookmarkAlertTitle: "Posição do marcador",
            promotion: "Promoção!",
            check: "Verificar",
            checkmateWins: "Xeque-mate! {{winner}} vence!",
            drawReason: "Empate! {{reason}}",
            opponentDisconnected: "O adversário desconectou",
            opponentResignedWins: "O oponente renunciou, {{winner}} vence",
            somethingWentWrong: "Algo deu errado",
            playerRejoined: "{{name}} voltou",
            aPlayerRejoined: "Um jogador voltou",
            opponentRejoined: "O oponente voltou",
            rematchOfferAccepted: "Oferta de revanche aceita",
            rematchOfferDeclined: "Oferta de revanche recusada",
            sideOffersDraw: "{{side}} oferece empate",
            drawOfferDeclined: "Oferta de empate recusada",
            watcherWatching: "{{name}} está assistindo ao jogo",
            drawOfferSent: "Oferta de empate enviada",
            rematchOfferSent: "Oferta de revanche enviada",
            newGameStarted: "Novo jogo iniciado",
            gameOver: "Game Over",
            gameCancelled: "Jogo cancelado",
            youResignedWins: "Você renunciou, {{winner}} vence",
            movesCopied: "Move copiado para a área de transferência!",
            failedCopyMoves: "Falha ao copiar movimentos",
            failedLoadBrainConfig: "Falha ao carregar a configuração do cérebro.",
            failedSaveBrainConfig: "Falha ao salvar a configuração do cérebro.",
            offerDrawConfirm: "Oferecer um empate?",
            drawOfferAccept: "O oponente enviou uma oferta de empate, aceita?",
            rematchOfferAccept: "Opponenet oferece uma revanche, concorda?",
            rematchOfferAcceptWithTime: "O oponente ofereceu uma revanche ({{minutes}} min de cada lado). Concordar?",
            rematchTimePrompt: "Minutos de cada lado para a revanche:",
            connectionLost: "Conexão perdida – as movimentações não estão alcançando o servidor",
            confirmExitGame: "Tem certeza de que deseja sair do jogo?",
            mobileResign: "Renunciar",
            mobileRematch: "Revanche",
            mobileDraw: "Empate",
            mobileFlip: "Virar",
            mobileLastMove: "Última jogada",
            mobileMovesList: "Lista de movimentos",
            researchToolbox: "Caixa de ferramentas",
            researchBrainConfig: "Configuração cerebral",
            researchSave: "Salvar",
            researchDiscard: "Descartar",
            researchEditMode: "modo de edição",
            researchRun: "Correr",
            researchProperty: "Propriedade",
            researchValue: "Valor",
            playerOnline: "On-line",
            playerDisconnectedStatus: "Desconectado",
            playerOffline: "Off-line",
            humanVsComputer: "Humano vs. Computador",
            newGameTwoPlayers: "Novo jogo 2 jogadores",
            settings: "Configurações",
            help: "Ajuda",
            drawOffersNotVsEngine: "As ofertas de empate não estão disponíveis ao jogar contra o motor.",
            failedStartFromBookmark: "Falha ao iniciar o jogo a partir dos favoritos.",
            resignConfirm: "Demitir-se?",
            areYouSure: "Tem certeza?",
            gameOverOpponentFailedReconnectWinsClassic: "Fim do jogo — o oponente não conseguiu se reconectar. {{winner}} vence.",
            reconnectTimeoutNoMoves: "O tempo limite de reconexão expirou e nenhum movimento foi executado.",
            waitingOpponentRejoin: "Esperando o oponente voltar",
            timeoutOneSec: "Tempo limite: 1 segundo",
            timeoutSecs: "Tempo limite: {{count}} seg.",
            whitePieceAlt: "Peça branca",
            blackPieceAlt: "Peça preta",
            eraserTitle: "Apagador",
            eraserAria: "Borracha – remova a peça do quadrado",
            selectTitle: "Selecione",
            selectAria: "Selecionar – arraste as peças para movê-las",
            resetAria: "Redefinir – limpe todas as peças",
            defaultPositionAria: "Posição padrão – configure a posição inicial padrão",
            loading: "Carregando...",
            engineLabel: "Motor"
        },
        site: {
            home: "Lar",
            search: "Procurar",
            friends: "Amigos",
            groups: "Grupos",
            debug: "Depurar",
            account: "Conta",
            preferences: "Preferências",
            administrate: "Administrar",
            logOut: "Sair",
            logIn: "Conecte-se",
            admin: "Administrador",
            homeAria: "Lar",
            confirm: "Confirmar",
            cancel: "Cancelar",
            notice: "Perceber",
            ok: "OK",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "Rodapé",
                privacy: "política de Privacidade",
                terms: "Termos de Uso",
                contact: "Contato",
                copyright: "© {{year}} Xadrez Shmerling. Todos os direitos reservados.",
                lastUpdated: "Última atualização: {{date}}",
                privacyTitle: "política de Privacidade",
                privacyLead: "Como o Shmerling Chess lida com informações de conta e jogo.",
                privacyBody: "Usamos os detalhes da sua conta para operar o serviço, manter jogos e preferências e melhorar o produto. Não vendemos informações pessoais. O texto completo da política será publicado aqui.",
                termsTitle: "Termos de Uso",
                termsLead: "As regras para usar o Xadrez Shmerling.",
                termsBody: "Ao usar o Shmerling Chess você concorda em jogar de forma justa, respeitar os outros jogadores e usar o serviço apenas para jogos de xadrez pessoais. Os termos completos serão publicados aqui.",
                contactTitle: "Contato",
                contactLead: "Entre em contato com a equipe Shmerling Chess.",
                contactBody: "Os detalhes de contato para suporte e questões de privacidade serão publicados aqui.",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "Nome de usuário:",
            password: "Senha:",
            login: "Conecte-se",
            register: {
                submit: "Cadastre-se",
                confirmPassword: "Confirme sua senha:",
                playerLevel: "Nível do jogador:",
                rookie: "Novato",
                skilled: "Habilidoso",
                elite: "Elite",
                grandMaster: "Grão-Mestre"
            },
            email: "E-mail:",
            welcome: {
                greeting: "Bem vindo de volta",
                tagline: "Sua mudança aguarda",
                playNow: "Jogue agora!",
                activeGames: "Jogos ativos",
                live: "Ao vivo",
                showAll: "Mostrar tudo",
                viewAllActive: "Ver todos os jogos ativos",
                mostRecent: "Mais recente primeiro",
                noGamesNow: "Nenhum jogo no momento",
                myGames: "Meus últimos jogos",
                viewAllGames: "Ver todos os jogos",
                recentCompleted: "Seus jogos concluídos recentemente",
                noCompleted: "Nenhum jogo concluído ainda",
                activeGamesAria: "Jogos ativos",
                inviteOnlineFriend: "Convide um amigo online para jogar",
                friendsPageTitle: "Página de amigos",
                manageFriends: "Gerenciar",
                colFriend: "Amigo",
                colStatus: "Status",
                findPlayers: "Encontre jogadores",
                waitingForResponse: "Aguardando resposta",
                inviteSentSuffix: "(convite enviado)",
                sortByRowNumber: "Classificar por número de linha",
                sortBy: "Classificar por {{key}}"
            },
            gameList: {
                date: "Data",
                time: "Tempo",
                result: "Resultado",
                reason: "Razão",
                type: "Tipo",
                status: "Status",
                event: "Evento",
                site: "Site",
                round: "Redondo"
            },
            loginPage: {
                title: "Conecte-se"
            },
            error: {
                title: "Algo deu errado",
                body: "Ocorreu um erro.",
                back: "Voltar ao principal"
            },
            log: {
                title: "Registro do servidor",
                clear: "Visão clara",
                latest: "Mais recente",
                waiting: "Aguardando saída do log do servidor…"
            },
            activeGames: {
                moves: "Movimentos",
                turn: "Vez",
                status: "Status",
                inProgress: "Em andamento",
                onHold: "Em espera",
                vs: "contra",
                minutesAgo: "{{count}} minutos atrás",
                oneMinuteAgo: "1 minuto atrás",
                justStarted: "Acabei de começar",
                notStarted: "Não iniciado",
                startedTooltip: "Iniciado: {{when}}",
                playersVs: "{{white}} vs. {{black}}"
            },
            friendsPage: {
                title: "Amigos",
                tagline: "Encontre novos companheiros de xadrez",
                myFriends: "Meus amigos",
                noFriendsYet: "Ainda não há amigos",
                findPlayers: "Encontre jogadores",
                searchByUsername: "Pesquisar por nome de usuário",
                searchPlaceholder: "Digite para pesquisar…",
                enterCharToSearch: "Digite pelo menos um caractere para pesquisar",
                noMatchingUsers: "Nenhum usuário correspondente",
                playing: "Jogando",
                pendingFriendshipOffer: "Oferta de amizade pendente",
                joining: "Juntando-se",
                rejoin: "Junte-se novamente",
                friendRequest: "Pedido de amizade",
                wantsToBeFriends: "(quer ser amigo)",
                pendingOfferSuffix: "(aguardando oferta de amizade)",
                waitingFriendRespond: "Esperando a resposta do seu amigo",
                cancelBeforeRemove: "Cancele o convite do jogo antes de remover este amigo",
                friendsTag: "Amigos",
                offerReceivedTag: "Oferta recebida – veja seus amigos",
                addFriend: "Adicionar amigo",
                withdraw: "Retirar",
                requestFailed: "Falha na solicitação",
                removeFriendConfirm: "Remover este amigo da sua lista?",
                removeFriendTitle: "Remover amigo",
                withdrawOfferConfirm: "Retirar esta oferta de amizade?",
                withdrawOfferTitle: "Retirar oferta",
                couldNotAccept: "Não foi possível aceitar",
                couldNotDecline: "Não foi possível recusar",
                couldNotRemove: "Não foi possível remover",
                couldNotCancelInvite: "Não foi possível cancelar o convite",
                couldNotWithdraw: "Não foi possível retirar",
                couldNotSendInvite: "Não foi possível enviar o convite",
                couldNotSendGameInvite: "Não foi possível enviar o convite do jogo",
                gameInvite: "Convite para jogo",
                gameInvitationsAria: "Convites para jogos",
                gameInvitationAria: "Convite para jogo",
                chessInviteTitle: "Convite de xadrez",
                wantsToPlayAsBlack: "{{name}} quer jogar. Você joga como Pretas.",
                wantsToPlayYouWhite: "{{name}} quer jogar. Você joga como brancas.",
                aFriend: "Um amigo",
                youPlayAsWhite: "Você joga como Branco",
                youPlayAsBlack: "Você joga como preto",
                establishingGame: "Estabelecendo jogo…",
                yourOpponent: "Seu oponente",
                declinedYourInvite: "{{name}} recusou seu convite para jogo.",
                cancelInvite: "Cancelar convite",
                accept: "Aceitar",
                decline: "Declínio",
                invite: "Convidar",
                inviteSettingsTitle: "Configurações de convite",
                inviteSettingsFor: "Convidar {{name}}",
                inviteTimeMinutes: "Tempo por lado (minutos)",
                inviteYourColor: "Sua cor",
                inviteColorWhite: "Branco",
                inviteColorBlack: "Preto",
                inviteColorRandom: "Aleatório",
                inviteFriendly: "Jogo amigável",
                inviteFriendlyHint: "Desmarque para contar para ELO mais tarde (jogo classificado).",
                invitePrivate: "Jogo privado",
                invitePrivateHint: "Oculte este jogo do lobby público de jogos ativos.",
                inviteSaveDefaults: "Salvar padrões",
                inviteOfferTime: "{{minutes}} minutos",
                inviteOfferFriendly: "Amigável",
                inviteOfferRated: "Avaliado",
                inviteOfferPrivate: "Privado",
                remove: "Remover",
                offerSent: "Oferta enviada",
                pending: "Pendente",
                online: "On-line",
                offline: "Off-line"
            },
            adminPage: {
                title: "Administração",
                tagline: "Usuários, jogos, motores, livro de abertura e duelos de bots",
                panelTitle: "Consola de administração",
                users: "Usuários",
                generate: "Gerar",
                games: "Jogos",
                engines: "Motores",
                states: "Estados",
                openingBook: "Livro de abertura",
                bots: "Robôs",
                addUser: "Adicionar usuário",
                sectionsAria: "Seções administrativas",
                openingBookLabel: "Livro de abertura:",
                openingBookStatusTitle: "Livro de abertura atual",
                openingBookFile: "Arquivo",
                openingBookExists: "Status",
                openingBookExistsYes: "Presente",
                openingBookExistsNo: "Ausente",
                openingBookLines: "Linhas de jogo",
                openingBookSize: "Tamanho",
                openingBookModified: "Última modificação",
                openingBookPgnSources: "Fontes PGN",
                openingBookPgnCount: "{{count}} Arquivo(s) PGN disponíveis para reconstrução",
                openingBookIntro: "Reconstrua o livro de abertura baseado em linha (data/opening-book-lines.txt) a partir das pastas PGN do servidor. Use Gerar livro de abertura abaixo – nada é executado até que você pressione-o.",
                generateOpeningBook: "Gerar livro de abertura",
                botsIntro: "Inicie um jogo público de motor contra motor. Os membros podem abri-lo no Active Games on Home como observadores.",
                botsWhiteEngine: "Motor branco",
                botsBlackEngine: "Motor preto",
                botsWhiteDifficulty: "Dificuldade (1–6)",
                botsBlackDifficulty: "Dificuldade (1–6)",
                botsSkillLevel: "Habilidade (0–20)",
                botsTimeMinutes: "Relógio (minutos)",
                botsStart: "Começar o duelo",
                botsStarting: "Começando o duelo…",
                botsStarted: "Duelo iniciado: {{white}} vs {{black}}.",
                botsWatchLink: "Assista a este jogo",
                botsListedNote: "Listado em Home → Jogos ativos para outros usuários.",
                botsStartFailed: "Não foi possível iniciar o duelo.",
                botsStopped: "Parada solicitada.",
                botsStopFailed: "Não foi possível parar o duelo.",
                gameLines: "linhas de jogo",
                noGamesInDb: "Nenhum jogo no banco de dados ainda.",
                gamesPaginationAria: "Paginação de jogos",
                colNum: "#",
                colUsername: "Nome de usuário",
                colType: "Tipo",
                colEmail: "E-mail",
                colPassword: "Senha",
                colLevel: "Nível",
                colElo: "Elo",
                colJoined: "Ingressou",
                colLastLogin: "Último login",
                colActiveGames: "Jogos ativos",
                colFriends: "Amigos",
                colBookmarks: "Favoritos",
                colId: "Eu ia",
                colStatus: "Status",
                colName: "Nome",
                colAvailable: "Disponível",
                colEnabled: "Habilitado",
                colBackend: "Back-end",
                colCommand: "Comando",
                colNotes: "Notas",
                colNote: "Observação",
                colAction: "Ação",
                emptyUsers: "Nenhum usuário ainda.",
                emptyData: "Ainda não há dados.",
                emptyEngines: "Nenhum mecanismo Play no registro.",
                emptyStates: "Use Gerar para abrir o livro de abertura e a página de geração de estado.",
                engineAvailableYes: "Disponível",
                engineAvailableNo: "Indisponível",
                engineEnable: "Habilitar",
                engineDisable: "Desativar",
                enginesLoadFailed: "Não foi possível carregar os motores",
                enginesSaveFailed: "Não foi possível atualizar o mecanismo",
                clickToEdit: "Clique para editar",
                updateFailed: "Falha na atualização",
                couldNotSave: "Não foi possível salvar",
                setPassword: "Definir senha",
                setPasswordTitle: "Clique para definir uma nova senha (4–30 caracteres)",
                passwordLengthInvalid: "A senha deve ter entre 4 e 30 caracteres.",
                invalidPassword: "Senha inválida",
                saved: "Salvo",
                newPasswordPlaceholder: "Nova Senha",
                clickChangeUserType: "Clique para alterar o tipo de usuário",
                userTypeAria: "Tipo de usuário",
                changeUserTypeTitle: "Alterar tipo de usuário",
                grantAdminConfirm: "Conceder privilégios de administrador a este usuário? Eles poderão acessar ferramentas administrativas e gerenciar contas.",
                demoteAdminConfirm: "Alterar este usuário de Admin para {{type}}? Eles perderão o acesso à área administrativa.",
                changeUserTypeConfirm: "Alterar este usuário para {{type}}?",
                clickChangeLevel: "Clique para mudar de nível",
                playerLevelAria: "Nível do jogador",
                sortByRowNumber: "Classificar por número de linha",
                sortBy: "Classificar por {{key}}",
                delete: "Excluir",
                first: "Primeiro",
                last: "Durar",
                previous: "Anterior",
                next: "Próximo",
                previous5Pages: "5 páginas anteriores",
                next5Pages: "Próximas 5 páginas",
                previous10Pages: "10 páginas anteriores",
                next10Pages: "Próximas 10 páginas",
                userTypeAdmin: "Administrador",
                userTypePartner: "Parceiro",
                userTypeMember: "Membro",
                generateTitle: "Livro de abertura e geração de estado",
                backToAdmin: "← Voltar para administrador",
                generateIntro: "Reproduz todos os arquivos PGN na pasta do gerenciador de jogos do servidor na coleção State Mongo ou no livro de abertura baseado em linha (data/opening-book-lines.txt). Escolha um alvo e pressione Iniciar geração – nada funciona até que você o faça.",
                target: "Alvo",
                targetMongo: "MongoDB — acrescenta linhas à coleção State",
                targetBook: "Arquivo de linha - escreva o livro de abertura (opening-book-lines.txt)",
                startGeneration: "Iniciar geração",
                stop: "Parar",
                idle: "Parado.",
                starting: "Começando…",
                running: "Executando ({{mode}})…",
                readingFiles: "Lendo arquivo(s) {{count}}…",
                replayingGames: "Repetindo jogos {{count}}…",
                writingOpeningBook: "Escrevendo livro de abertura…",
                readingPgn: "Lendo PGN {{index}} / {{total}} (jogos {{games}})",
                replayGameProgress: "Jogo de repetição {{current}} / {{total}} (concluído ok: {{completed}})",
                stopped: "Parou.",
                bookUnchanged: "O livro de abertura existente não foi modificado.",
                bookLinesInFile: "Linha(s) de jogo {{count}} em {{file}}.",
                cancelledBeforeRead: "Cancelado antes da leitura dos PGNs.",
                cancelledAfterRead: "Cancelado após leitura; a repetição foi ignorada (nada escrito).",
                mongoGamesSaved: "Os jogos {{count}} tiveram novas linhas de estado salvas.",
                doneBook: "Feito. Linhas de jogo {{count}} → {{file}}",
                doneBookFileOnly: "Feito. {{file}}",
                doneMongo: "Feito. Coleção de estados do MongoDB atualizada{{detail}}.",
                doneMongoDetail: "(jogos {{count}} repetidos ok)",
                errorPrefix: "Erro: {{message}}",
                unknownError: "Desconhecido",
                connectionClosed: "Conexão fechada (verifique os logs do servidor ou tente novamente).",
                openingBookDefault: "livro de abertura"
            },
            playNow: {
                title: "Novo jogo",
                startTitle: "Comece um novo jogo",
                playingColor: "Jogando cor",
                timeMin: "Tempo (min)",
                difficulty: "Dificuldade (1–5)",
                mousePreference: "Preferência do mouse",
                drag: "Arrastar",
                doubleClick: "Clique duas vezes",
                showAvailableMoves: "Mostrar movimentos disponíveis",
                private: "Privado",
                privateHint: "Os jogos privados não são exibidos nas listas de jogos ativos de outros membros.",
                playComputer: "Jogar no computador",
                browseAll: "Navegar por tudo",
                yourHistory: "Sua história",
                fullList: "Lista completa",
                gameLibrary: "Biblioteca de jogos",
                openLibrarySearch: "Pesquisa de biblioteca aberta",
                brain3: "Cérebro 3",
                brain2: "Cérebro 2"
            },
            activeGamesList: {
                title: "Jogos ativos",
                tagline: "Todos os jogos em andamento",
                liveGames: "Jogos ao vivo",
                game: "Jogo",
                started: "Iniciado"
            },
            list: {
                title: "Todos os jogos",
                tagline: "Seus jogos concluídos",
                allGames: "Jogos concluídos",
                gamesCount: "{{count}} jogos",
                action: "Ação"
            },
            searchPage: {
                title: "Procurar:",
                tagline: "Encontre jogos famosos no arquivo",
                results: "Resultados",
                resultsCount: "Resultados {{count}}",
                noResults: "Nenhum jogo corresponde à sua pesquisa",
                button: "Procurar",
                resultsFound: "{{count}} Resultados encontrados:",
                first: "Primeiro",
                last: "Durar",
                previous: "Anterior",
                next: "Próximo",
                previous5Pages: "5 páginas anteriores",
                next5Pages: "Próximas 5 páginas",
                previous10Pages: "10 páginas anteriores",
                next10Pages: "Próximas 10 páginas"
            },
            game: {
                moves: "Movimentos",
                white: "Branco",
                black: "Preto",
                resign: "Renunciar",
                draw: "Empate",
                undo: "Desfazer",
                flip: "Virar",
                practice: "Prática"
            },
            mobileWelcome: {
                title: "Página inicial — Xadrez",
                play: "Jogar",
                library: "Biblioteca",
                friends: "Amigos"
            },
            mobileGame: {
                title: "Jogo",
                moves: "Movimentos",
                resign: "Renunciar"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "Algo deu errado",
                body: "Ocorreu um erro.",
                back: "Voltar ao principal"
            },
            chrome: {
                preferences: "Preferências",
                closePreferences: "Fechar preferências",
                display: "Mostrar",
                gameplay: "Jogabilidade",
                pieceSet: "Conjunto de peças",
                boardTheme: "Tema",
                theme: "Tema",
                themeBlue: "Azul",
                themeDark: "Escuro",
                customizeTheme: "Gerenciar temas…",
                builtInThemesAria: "Temas integrados",
                savedCustomThemesAria: "Temas personalizados salvos",
                pieceSetsAria: "Conjuntos de peças",
                homeAria: "Casa de Xadrez Shmerling"
            },
            prefs: {
                language: "Idioma",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "Controle do mouse",
                mouseDrag: "Arrastar",
                mouseClick: "Clique",
                thinkingTime: "Tempo de pensamento do motor",
                thinkingTimeAria: "Tempo de pensamento do motor em segundos",
                immediateResign: "Renúncia imediata",
                secondsOption: "{{count}}s",
                selectedTheme: "Selecionado: {{name}}",
                selectedPieceSet: "Selecionado: {{name}}",
                enterFullScreen: "Entrar em tela cheia",
                exitFullScreen: "Sair da tela inteira",
                fullScreenUnavailable: "A tela inteira não está disponível neste navegador."
            },
            gameRun: {
                yourColor: "Sua cor",
                engine: "Motor",
                thinkTime: "Pense no tempo (segundos)",
                thinkTimeAria: "Tempo de pensamento do motor em segundos",
                play: "Jogar",
                nextMove: "Próximo passo",
                computer: "Computador",
                computerColorHint: "Qual cor o computador joga – você joga do outro lado"
            },
            brainConfig: {
                title: "Configuração cerebral",
                save: "Salvar",
                reset: "Reiniciar",
                saved: "Configuração salva",
                failedSave: "Falha ao salvar a configuração",
                brainLabel: "Cérebro",
                loading: "Carregando…",
                failedLoad: "Falha ao carregar a configuração do cérebro.",
                discardSwitchConfirm: "Descartar alterações não salvas e mudar a versão do cérebro?",
                discard: "Descartar",
                pieceScores: "Pontuações de peças",
                specialEvaluations: "Avaliações especiais",
                gamePhase: "Fase do jogo",
                pawnFilesOpeningMid: "Arquivos de peão (abertura/meio)",
                pawnFilesEndGame: "Arquivos de peão (final do jogo)"
            },
            customTheme: {
                title: "Tema",
                name: "Nome do tema",
                save: "Salvar",
                delete: "Excluir",
                saved: "Temas",
                searchProperties: "Pesquisar propriedades",
                filterPlaceholder: "Filtrar por nome de propriedade…",
                namePlaceholder: "Meu tema",
                resetPreset: "Redefinir alterações",
                couldNotSave: "Não foi possível salvar o tema. Tente novamente.",
                untitled: "Sem título",
                defaultName: "Novo tema"
            },
            positionSetup: {
                clearBoard: "Limpar quadro",
                startingPosition: "Posição inicial",
                flipBoard: "Virar tabuleiro",
                eraser: "Apagador",
                selectAndMove: "Selecione e mova",
                defaultStartingPosition: "Posição inicial padrão",
                savePosition: "Salvar posição",
                saveAsNewPosition: "Salvar como nova posição",
                validatePosition: "Validar posição",
                positionFlags: "Bandeiras de posição",
                turn: "Vez",
                flagCheck: "Verificar",
                flagCheckmate: "Xeque-mate",
                flagDraw: "Empate",
                flagWhiteKingMoved: "Rei branco moveu-se",
                flagBlackKingMoved: "Rei preto movido",
                flagWhiteKingsideRookMoved: "Torre branca do lado do rei movida",
                flagWhiteQueensideRookMoved: "Torre branca da ala da dama movida",
                flagBlackKingsideRookMoved: "Torre preta do lado do rei movida",
                flagBlackQueensideRookMoved: "Torre preta da ala de dama movida"
            }
        },
        errorPage: {
            code: "Erro {{code}}",
            notFoundTitle: "Página não encontrada",
            notFoundMessage: "A página que você procura não existe.",
            genericTitle: "Algo deu errado",
            genericMessage: "Ocorreu um erro inesperado. Por favor, tente novamente.",
            backHome: "Voltar ao início"
        },
        mobile: {
            drawOfferTitle: "Oferta de empate",
            drawOfferMessage: "O oponente enviou uma oferta de empate. Aceitar?",
            rematchTitle: "Revanche",
            rematchMessage: "O oponente enviou uma oferta de revanche. Aceitar?",
            gameId: "ID do jogo: {{id}}",
            drawOfferAgree: "O adversário ofereceu empate, concorda?",
            rematchOfferAgree: "O oponente ofereceu revanche, concorda?",
            newGameWatchFromHome: "Novo jogo iniciado – vá para a página inicial para assistir."
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = ptExtra;
    } else {
        global.ShmerlingStringsPtExtra = ptExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
