/**
 * Portuguese string catalog — mirrors src/strings/en.js structure.
 */
(function (global) {
    "use strict";

    const pt = {
        common: {
            white: "Branco",
            black: "Preto",
            draw: "Empate",
            winner: "Vencedor",
            engine: "Motor",
            ok: "OK",
            cancel: "Cancelar",
            confirm: "Confirmar",
            yes: "Sim",
            no: "Não",
            notice: "Aviso",
            input: "Entrada",
            start: "Começar",
            collapse: "Recolher",
            expand: "Expandir",
            delete: "Excluir",
            rename: "Renomear",
            save: "Salvar",
            aPlayer: "Um jogador",
            pleaseEnterValue: "Insira um valor."
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Ações do jogo",
                playersAndClocks: "Jogadores e relógios",
                whitePlayerClock: "Relógio do jogador branco",
                blackPlayerClock: "Relógio do jogador preto",
                startFromLoadedPosition: "Comece o jogo da posição carregada",
                moves: "Jogadas",
                expandMovesPanel: "Expandir painel de jogadas",
                expandMoves: "Mostrar jogadas",
                collapseMovesPanel: "Recolher painel de jogadas",
                reviewNavigation: "Revise a navegação",
                positionSetup: "Configuração de posição",
                pieces: "Peças",
                collapsePiecesPanel: "Recolher painel de peças",
                brainConfiguration: "Configuração cerebral",
                configuration: "Configuração",
                collapseConfigurationPanel: "Recolher painel de configuração",
                games: "Jogos",
                expandGamesPanel: "Expandir painel de jogos",
                expandGames: "Expandir jogos",
                expandGamesLocked: "Painel de jogos indisponível durante um jogo",
                collapseGamesPanel: "Recolher painel de jogos",
                chat: "Chat",
                expandChatPanel: "Expandir painel de bate-papo",
                collapseChatPanel: "Recolher painel de bate-papo",
                chatPlaceholder: "Digite uma mensagem…",
                chatWatcherReadonly: "Os espectadores só podem ler o bate-papo",
                sendChat: "Enviar",
                savedListFilter: "Filtro de lista salva",
                positions: "Posições",
                gameStatus: "Status do jogo",
                capturedPieces: "Peças capturadas"
            },
            sessionMode: {
                play: "Modo de jogo",
                positionSetup: "Configuração de posição",
                configuration: "Modo de configuração",
                playback: "Modo de reprodução",
                review: "Modo de revisão",
                watch: "Modo Assistir",
                practice: "Modo de prática"
            },
            status: {
                chooseNewGameOrSetup: "Escolha Novo jogo ou Configuração de posição na barra lateral",
                chooseNewGame: "Escolha Novo jogo na barra lateral",
                setMoveColorEngineThinkTime: "Defina o movimento, a cor, o mecanismo e o tempo de reflexão no cabeçalho e pressione Reproduzir",
                gameOver: "Fim de jogo",
                gameInProgress: "Jogo em andamento",
                boardLoading: "A placa ainda está carregando…",
                boardNotReady: "A diretoria ainda não está pronta. Aguarde e tente novamente.",
                leaveOnlineBeforeConfiguration: "Saia do jogo online antes de abrir a Configuração",
                configurationNotInPractice: "A configuração não está disponível no modo Prática",
                configurationModeEdit: "Modo de configuração — edite valores e salve",
                selectSavedOrSetup: "Selecione um jogo salvo ou configure primeiro uma posição no tabuleiro",
                gameAlreadyInProgress: "Um jogo já está em andamento",
                yourMove: "Sua jogada",
                engineToMove: "Motor para mover…",
                leaveOnlineBeforePositionSetup: "Saia do jogo online antes de abrir a Configuração de Posição",
                positionSetupNotInPractice: "A configuração de posição não está disponível no modo Practice",
                positionSetupPlacePieces: "Configuração de posição – coloque as peças no tabuleiro",
                drawWithReason: "Empate — {{reason}}",
                checkmateWins: "Xeque-mate — {{winner}} vitórias",
                check: "Xeque",
                waitBeforeEvaluate: "Aguarde a conclusão da movimentação atual antes de avaliar",
                evaluationUnavailable: "A avaliação não está disponível. Reinicie o aplicativo Shmerling Chess.",
                evaluatingPosition: "Avaliando posição…",
                evaluationFailed: "Falha na avaliação",
                evaluationLine: "Avaliação ({{side}} para mover): {{score}}",
                checkmate: "Xeque-mate",
                drawZero: "Empate (0)",
                totalLabel: "Total: {{value}}",
                openFolderDesktopOnly: "A pasta aberta está disponível apenas no aplicativo de desktop",
                couldNotOpenGamesLogFolder: "Não foi possível abrir a pasta de log dos jogos",
                positionValid: "A posição é válida",
                playingFromCustomPosition: "Jogando em posição personalizada",
                nothingToSave: "Nada para salvar",
                positionSaved: "Posição salva",
                couldNotSavePosition: "Não foi possível salvar a posição",
                savedPositionNotFound: "Posição salva não encontrada",
                positionUpdated: "Posição atualizada",
                couldNotUpdatePosition: "Não foi possível atualizar a posição",
                nameCannotBeEmpty: "O nome não pode ficar vazio",
                gameRenamed: "Jogo renomeado",
                couldNotRenameGame: "Não foi possível renomear o jogo",
                deletedCount: "Item(s) {{count}} excluído(s)",
                couldNotDeleteSelected: "Não foi possível excluir os itens selecionados",
                couldNotLoadSavedGame: "Não foi possível carregar o jogo salvo",
                editingPositionSaveBookmark: "Posição de edição — Salve para atualizar este favorito",
                couldNotOpenPositionForEditing: "Não foi possível abrir posição para edição",
                gameSaved: "Jogo salvo",
                couldNotSaveGame: "Não foi possível salvar o jogo",
                engineMoveNotApplied: "Não foi possível aplicar o movimento do motor",
                engineCouldNotFindMove: "O motor não conseguiu encontrar um movimento",
                engineError: "Erro do motor",
                engineThinking: "Pensamento do motor…",
                sessionError: "Erro de sessão",
                timesUpLost: "{{loser}} perdido no tempo",
                drawOfferTitle: "Oferta de empate",
                drawOfferMessage: "O oponente enviou uma oferta de empate. Aceitar?",
                rematchTitle: "Revanche",
                playerDisconnectedWaiting: "{{who}} desconectado — aguardando reingresso ({{countdown}})",
                opponentDisconnectedCountdown: "Oponente desconectado — {{countdown}}",
                gameCancelledReconnectTimeout: "Jogo cancelado — O tempo de reconexão expirou e nenhum movimento foi executado.",
                playerFailedToReconnectWins: "{{loser}} não conseguiu reconectar — {{winner}} vence",
                gameOverOpponentFailedReconnect: "Fim do jogo — o oponente não conseguiu se reconectar.",
                couldNotStartRematch: "Não foi possível iniciar a revanche",
                rematchStarted: "Revanche iniciada",
                gameCancelled: "Jogo cancelado",
                gameCancelledWithDetail: "Jogo cancelado — {{detail}}",
                gameCancelledOpponentLeftBeforeFirstMove: "Jogo cancelado — O oponente saiu antes do primeiro movimento.",
                resignFailed: "Falha na renúncia",
                gameResumedYourMove: "Jogo retomado – sua jogada",
                practiceNotAvailable: "O modo de prática não está disponível",
                couldNotJoinOnPlay: "Não foi possível entrar neste jogo em /play",
                practiceDebugNotAvailable: "Prática/Depuração não está disponível para esta conta",
                reviewRequiresWebApi: "A revisão requer a API Web",
                couldNotLoadReviewGame: "Não foi possível carregar o jogo de revisão",
                notReviewGameLink: "Este link não é um jogo de revisão",
                onlineRequiresWebApi: "O jogo online requer a API da web",
                couldNotLoadOnlineGame: "Não foi possível carregar o jogo online",
                notOnlineGameOnPlay: "Este link não é um jogo online em /play",
                watchingLiveGame: "Assistindo ao jogo ao vivo",
                waitingForOpponentToJoin: "Esperando o oponente entrar…",
                waitingForOpponent: "Esperando pelo adversário…",
                onlineGameConnected: "Jogo online – conectado",
                gameDeleted: "Jogo excluído",
                itemsDeleted: "{{count}} itens excluídos",
                choosePromotionPiece: "Escolha a peça promocional",
                invalidPromotionPiece: "Peça promocional inválida",
                drawOfferNotAvailable: "A oferta de empate não está disponível agora"
            },
            drawReasons: {
                stalemate: "Afogamento",
                fiftyMoves: "50 movimentos",
                insufficientMaterial: "Material insuficiente",
                threefoldRepetition: "Repetição tripla",
                drawOfferAccepted: "{{by}} oferta de empate do jogador aceita"
            },
            actions: {
                newGame: "Novo jogo",
                resign: "Desistir",
                draw: "Empate",
                undo: "Desfazer",
                redo: "Refazer",
                lastMove: "Última jogada",
                positionSetup: "Configuração de posição",
                config: "Configuração",
                flip: "Virar",
                save: "Salvar",
                exit: "Saída",
                backToLobby: "Voltar ao lobby",
                loadToStart: "Carregar para começar",
                editPosition: "Editar posição",
                loadGame: "Carregar partida",
                loadPosition: "Carregar posição"
            },
            savedGames: {
                defaultName: "Jogo salvo",
                nameAriaLabel: "Nome do jogo salvo",
                showDetails: "Mostrar detalhes",
                detailsAriaLabel: "Detalhes do jogo salvo",
                editPosition: "Editar posição",
                deleteSavedGame: "Excluir jogo salvo",
                renameSavedGame: "Renomear jogo salvo",
                noSavedPositions: "Nenhuma posição salva ainda.",
                noSavedGames: "Nenhum jogo salvo ainda.",
                nextMoveDash: "Próximo passo: -",
                nextMove: "Próximo passo: {{side}}",
                player: "Jogador",
                savedAt: "Salvo: {{when}}",
                gameId: "ID do jogo: {{id}}",
                playersVs: "{{white}} versus {{black}}",
                defaultPositionName: "Posição salva",
                itemsSelected: "{{count}} itens selecionados"
            },
            reviewNav: {
                start: "Começar",
                back: "Voltar",
                play: "Jogar",
                pause: "Pausa",
                forward: "Avançar",
                end: "Fim"
            },
            newGameDialog: {
                title: "Novo jogo contra IA",
                yourColor: "Sua cor",
                engine: "Motor",
                brain43: "Cérebro 4.3",
                brain42: "Cérebro 4.2",
                brain41: "Cérebro 4.1",
                brain4: "Cérebro 4.0",
                stockfish: "Stockfish",
                timePerSideMinutes: "Tempo por lado (minutos)",
                allowUndo: "Permitir desfazer",
                private: "Privado",
                privateHint: "Os jogos privados não são exibidos nas listas de jogos ativos de outros membros."
            },
            prompts: {
                positionName: "Nome da posição",
                savePositionAs: "Salvar posição como"
            },
            dialogs: {
                resignTitle: "Desistir deste jogo?",
                resignBody: "Você perderá o jogo.",
                leaveTitle: "Sair do jogo?",
                leaveBody: "Seu jogo será abandonado.",
                areYouSure: "Tem certeza?",
                discardUnsavedBrainConfig: "Descartar alterações de configuração cerebral não salvas?",
                accept: "Aceitar",
                decline: "Declínio",
                saveAs: "Salvar como",
                savePosition: "Salvar posição",
                invalidPosition: "Posição inválida",
                rematchChooseColor: "Escolha sua cor para a revanche:",
                rematchOfferAgree: "O oponente ofereceu uma revanche. Concordar?",
                rematchOfferAgreeWithTime: "O oponente ofereceu uma revanche ({{minutes}} min de cada lado). Concordar?",
                rematchColorPreference: "O oponente quer jogar como {{offerer}}. Você jogaria como {{you}}. Concordar?",
                rematchColorPreferenceWithTime: "O oponente quer jogar como {{offerer}} ({{minutes}} min de cada lado). Você jogaria como {{you}}. Concordar?"
            }
        },
        session: {
            engineThinking: "Pensamento do motor…",
            engineCouldNotFindMove: "O motor não conseguiu encontrar um movimento",
            engineError: "Erro do motor",
            positionSetupPlacePieces: "Configuração de posição – coloque as peças no tabuleiro",
            configurationModeEdit: "Modo de configuração — edite valores e salve",
            practiceBothSides: "Prática – ambos os lados",
            opponentDisconnected: "Oponente desconectado",
            opponentRejoined: "O oponente voltou",
            playerRejoined: "{{name}} voltou",
            drawOfferSent: "Oferta de empate enviada",
            drawOfferDeclined: "Oferta de empate recusada",
            rematchOfferSent: "Oferta de revanche enviada",
            rematchOfferDeclined: "Oferta de revanche recusada",
            rematchUnavailable: "O adversário não está mais disponível para uma revanche",
            drawAgreed: "Empate acordado",
            rematchAcceptedNoGameId: "Revanche aceita, mas sem novo ID de jogo",
            rematchOfferAccepted: "Oferta de revanche aceita",
            gameOver: "Game Over",
            somethingWentWrong: "Algo deu errado",
            opponentResigned: "Oponente renunciou",
            opponentLeftGame: "O adversário saiu do jogo",
            opponentFailedToReconnect: "O oponente não conseguiu se reconectar",
            gameCancelled: "Jogo cancelado",
            gameCancelledWithDetail: "Jogo cancelado — {{detail}}",
            gameCancelledOpponentLeftBeforeFirstMove: "Jogo cancelado — O oponente saiu antes do primeiro movimento.",
            gameCancelledReconnectTimeout: "Jogo cancelado — O tempo de reconexão expirou e nenhum movimento foi executado.",
            waitingForOpponent: "Esperando pelo adversário…",
            couldNotResolveWebSocketUrl: "Não foi possível resolver o URL do WebSocket",
            opponentJoined: "{{name}} entrou",
            opponentDefault: "Adversário",
            connectionError: "Erro de conexão",
            connectionLost: "Conexão perdida – as movimentações não estão alcançando o servidor",
            reconnecting: "Reconectando…",
            connectionRestored: "Conexão restaurada",
            flagReported: "Sinalizador — confirmando com o servidor…",
            playerDisconnectedWaitingRejoin: "{{name}} desconectado — aguardando reingresso",
            playerFailedToReconnectWins: "{{loser}} não conseguiu reconectar — {{winner}} vence",
            watcherWaitingForReconnect: "Esperando que um jogador se reconecte…"
        },
        site: {
            confirm: "Confirmar",
            cancel: "Cancelar",
            notice: "Perceber",
            ok: "OK",
            home: "Lar",
            search: "Procurar",
            friends: "Amigos",
            groups: "Grupos",
            debug: "Depurar",
            account: "Conta",
            preferences: "Preferências",
            administrate: "Administrar",
            logOut: "Sair",
            logIn: "Conecte-se",
            admin: "Administrador",
            homeAria: "Lar"
        },
        validation: {
            validEmail: "Por favor preencha um e-mail válido",
            passwordsMustMatch: "Certifique-se de que os campos de senha sejam idênticos.",
            chooseUsername: "Por favor escolha um nome de usuário",
            usernameNotAvailable: "Este nome de usuário não está disponível",
            passwordNoWhitespace: "A senha não deve conter espaços em branco.",
            passwordUppercase: "A senha deve ter pelo menos um caractere maiúsculo."
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = pt;
    } else {
        global.ShmerlingStringsPt = pt;
    }
})(typeof window !== "undefined" ? window : globalThis);
