(function (global) {
    "use strict";
    const ruExtra = {
    "validation": {
        "passwordLowercase": "Пароль должен содержать хотя бы одну строчную букву.",
        "passwordDigit": "Пароль должен содержать хотя бы одну цифру.",
        "passwordSymbol": "Пароль должен содержать хотя бы один специальный символ.",
        "passwordLength": "Пароль должен быть длиной от 8 до 30 символов.",
        "noHtml": "{{label}} не должен содержать HTML.",
        "position": {
            "headerSave": "Невозможно сохранить эту позицию:\n\n",
            "headerPlay": "Невозможно играть с этой позиции:\n\n",
            "headerUse": "Невозможно использовать эту позицию:\n\n",
            "headerSaveBookmark": "Невозможно сохранить эту закладку:\n\n",
            "headerAddBookmark": "Невозможно добавить эту закладку:\n\n",
            "boardUnreadable": "Не удалось прочитать доску. Попробуйте снова после загрузки доски.",
            "whiteKingNone": "На доске должен быть ровно один белый король. Король не найден.",
            "whiteKingCount": "На доске должен быть ровно один белый король. Найдено белых королей: {{count}}.",
            "blackKingNone": "На доске должен быть ровно один чёрный король. Король не найден.",
            "blackKingCount": "На доске должен быть ровно один чёрный король. Найдено чёрных королей: {{count}}.",
            "kingsAdjacent": "Два короля не могут стоять на соседних полях (включая диагональ).",
            "sideInCheck": "Ход {{mover}}, но король {{king}} уже под шахом. Сторона, которая ходит, не может давать шах — смените очередь хода или передвиньте фигуры.",
            "drawInsufficientKings": "Эта позиция — ничья из-за недостатка материала (король против короля). Добавьте фигуры, чтобы мат оставался возможен.",
            "drawInsufficientMinor": "Эта позиция — ничья из-за недостатка материала (король и слон или конь против одинокого короля). Добавьте фигуры, чтобы мат оставался возможен.",
            "drawBishopsSameColor": "Эта позиция — ничья из-за недостатка материала (слон против слона на полях одного цвета). Добавьте фигуры, чтобы мат оставался возможен.",
            "tooManyQueens": "У {{color}} {{count}} ферзей; максимум — 9 на сторону.",
            "tooManyRooks": "У {{color}} {{count}} ладей; максимум — 10 на сторону.",
            "tooManyBishops": "У {{color}} {{count}} слонов; максимум — 10 на сторону.",
            "tooManyKnights": "У {{color}} {{count}} коней; максимум — 10 на сторону.",
            "tooManyPawns": "У {{color}} {{count}} пешек; максимум — 8 на сторону."
        }
    },
    "auth": {
        "whoAreYou": "Кто вы?",
        "enterPassword": "Введите пароль",
        "sorry": "Извините",
        "continue": "Продолжить",
        "usernameField": "Имя пользователя",
        "passwordField": "Пароль",
        "wrongCredentials": "Неверное имя пользователя или пароль",
        "userAdded": "Пользователь успешно добавлен",
        "couldNotSaveBookmark": "Не удалось сохранить закладку",
        "invalidUserId": "Недопустимый ID пользователя",
        "generationJobRunning": "Другая задача генерации уже выполняется…",
        "listingPgnFiles": "Список файлов PGN…"
    },
    "classic": {
        "loadGame": "Загрузить партию",
        "load": "Загрузить",
        "enterGameState": "Вставьте состояние партии сюда...",
        "rematch": "Реванш",
        "drawOffer": "Предложение ничьей",
        "lastMove": "Последний ход",
        "bookmarks": "Закладки",
        "bookmarkAlertTitle": "Закладка позиции",
        "promotion": "Превращение!",
        "check": "Шах",
        "checkmateWins": "Мат! Победа {{winner}}!",
        "drawReason": "Ничья! {{reason}}",
        "opponentDisconnected": "Соперник отключился",
        "opponentResignedWins": "Соперник сдался, победа {{winner}}",
        "somethingWentWrong": "Что-то пошло не так",
        "playerRejoined": "{{name}} переподключился",
        "aPlayerRejoined": "Игрок переподключился",
        "opponentRejoined": "Соперник переподключился",
        "rematchOfferAccepted": "Предложение реванша принято",
        "rematchOfferDeclined": "Предложение реванша отклонено",
        "sideOffersDraw": "{{side}} предлагает ничью",
        "drawOfferDeclined": "Предложение ничьей отклонено",
        "watcherWatching": "{{name}} наблюдает за партией",
        "drawOfferSent": "Предложение ничьей отправлено",
        "rematchOfferSent": "Предложение реванша отправлено",
        "newGameStarted": "Новая партия начата",
        "gameOver": "Партия окончена",
        "gameCancelled": "Партия отменена",
        "youResignedWins": "Вы сдались, победа {{winner}}",
        "movesCopied": "Ходы скопированы в буфер обмена!",
        "failedCopyMoves": "Не удалось скопировать ходы",
        "failedLoadBrainConfig": "Не удалось загрузить настройки движка.",
        "failedSaveBrainConfig": "Не удалось сохранить настройки движка.",
        "offerDrawConfirm": "Предложить ничью?",
        "drawOfferAccept": "Соперник предложил ничью, принять?",
        "rematchOfferAccept": "Соперник предложил реванш, согласиться?",
        "confirmExitGame": "Вы уверены, что хотите выйти из партии?",
        "mobileResign": "Сдаться",
        "mobileRematch": "Реванш",
        "mobileDraw": "Ничья",
        "mobileFlip": "Перевернуть",
        "mobileLastMove": "Последний ход",
        "mobileMovesList": "Список ходов",
        "researchToolbox": "Инструменты",
        "researchBrainConfig": "Настройка движка",
        "researchSave": "Сохранить",
        "researchDiscard": "Отменить",
        "researchEditMode": "режим редактирования",
        "researchRun": "Запуск",
        "researchProperty": "Свойство",
        "researchValue": "Значение",
        "playerOnline": "В сети",
        "playerDisconnectedStatus": "Отключён",
        "playerOffline": "Не в сети",
        "humanVsComputer": "Человек против компьютера",
        "newGameTwoPlayers": "Новая партия на двоих",
        "settings": "Настройки",
        "help": "Справка",
        "drawOffersNotVsEngine": "Предложение ничьей недоступно при игре против движка.",
        "failedStartFromBookmark": "Не удалось начать партию с закладки.",
        "resignConfirm": "Сдаться?",
        "areYouSure": "Вы уверены?",
        "gameOverOpponentFailedReconnectWinsClassic": "Партия окончена — соперник не переподключился. Победа {{winner}}.",
        "reconnectTimeoutNoMoves": "Время переподключения истекло, ходов не было.",
        "waitingOpponentRejoin": "Ожидание переподключения соперника",
        "timeoutOneSec": "Таймаут: 1 сек",
        "timeoutSecs": "Таймаут: {{count}} сек",
        "whitePieceAlt": "Белая фигура",
        "blackPieceAlt": "Чёрная фигура",
        "eraserTitle": "Ластик",
        "eraserAria": "Ластик — убрать фигуру с поля",
        "selectTitle": "Выбор",
        "selectAria": "Выбор — перетаскивайте фигуры",
        "resetAria": "Сброс — убрать все фигуры",
        "defaultPositionAria": "Начальная позиция — стандартная расстановка",
        "loading": "Загрузка...",
        "engineLabel": "Движок"
    },
    "site": {
        "home": "Главная",
        "search": "Поиск",
        "friends": "Друзья",
        "groups": "Группы",
        "debug": "Отладка",
        "account": "Аккаунт",
        "preferences": "Настройки",
        "administrate": "Администрирование",
        "logOut": "Выйти",
        "logIn": "Войти",
        "admin": "Админ",
        "homeAria": "Главная",
        "confirm": "Подтвердить",
        "cancel": "Отмена",
        "notice": "Уведомление",
        "ok": "ОК",
        "footer": {
            "logoAlt": "Shmerling Chess",
            "navAria": "Подвал",
            "privacy": "Политика конфиденциальности",
            "terms": "Условия использования",
            "contact": "Контакты",
            "copyright": "© {{year}} Shmerling Chess. Все права защищены.",
            "lastUpdated": "Последнее обновление: {{date}}",
            "privacyTitle": "Политика конфиденциальности",
            "privacyLead": "Как Shmerling Chess обрабатывает данные аккаунта и партий.",
            "privacyBody": "Мы используем данные вашего аккаунта для работы сервиса, хранения партий и настроек и улучшения продукта. Мы не продаём персональные данные. Полный текст политики будет опубликован здесь.",
            "termsTitle": "Условия использования",
            "termsLead": "Правила использования Shmerling Chess.",
            "termsBody": "Используя Shmerling Chess, вы соглашаетесь играть честно, уважать других игроков и использовать сервис только для личной игры в шахматы. Полные условия будут опубликованы здесь.",
            "contactTitle": "Контакты",
            "contactLead": "Свяжитесь с командой Shmerling Chess.",
            "contactBody": "Контактные данные для поддержки и вопросов о конфиденциальности будут опубликованы здесь."
        },
        "username": "Имя пользователя:",
        "password": "Пароль:",
        "login": "Вход",
        "register": {
            "submit": "Регистрация",
            "confirmPassword": "Подтвердите пароль:",
            "playerLevel": "Уровень игрока:",
            "rookie": "Новичок",
            "skilled": "Опытный",
            "elite": "Элита",
            "grandMaster": "Гроссмейстер"
        },
        "email": "Электронная почта:",
        "welcome": {
            "greeting": "С возвращением",
            "tagline": "Ваш ход ждёт",
            "playNow": "Играть!",
            "activeGames": "Активные партии",
            "live": "В эфире",
            "showAll": "Показать все",
            "viewAllActive": "Все активные партии",
            "mostRecent": "Сначала новые",
            "noGamesNow": "Сейчас партий нет",
            "myGames": "Мои партии",
            "viewAllGames": "Все партии",
            "recentCompleted": "Недавно завершённые партии",
            "noCompleted": "Завершённых партий пока нет",
            "activeGamesAria": "Активные партии",
            "inviteOnlineFriend": "Пригласить друга онлайн",
            "friendsPageTitle": "Страница друзей",
            "manageFriends": "Управление",
            "colFriend": "Друг",
            "colStatus": "Статус",
            "findPlayers": "Найти игроков",
            "waitingForResponse": "Ожидание ответа",
            "inviteSentSuffix": "(приглашение отправлено)",
            "sortByRowNumber": "Сортировать по номеру строки",
            "sortBy": "Сортировать по {{key}}"
        },
        "gameList": {
            "date": "Дата",
            "time": "Время",
            "result": "Результат",
            "reason": "Причина",
            "type": "Тип",
            "status": "Статус",
            "event": "Турнир",
            "site": "Сайт",
            "round": "Тур"
        },
        "loginPage": {
            "title": "Вход"
        },
        "error": {
            "title": "Что-то пошло не так",
            "body": "Произошла ошибка.",
            "back": "На главную"
        },
        "log": {
            "title": "Журнал сервера",
            "clear": "Очистить вид",
            "latest": "Последние",
            "waiting": "Ожидание вывода журнала сервера…"
        },
        "activeGames": {
            "moves": "Ходы",
            "turn": "Ход",
            "status": "Статус",
            "inProgress": "Идёт",
            "onHold": "На паузе",
            "vs": " против ",
            "minutesAgo": "{{count}} мин. назад",
            "oneMinuteAgo": "1 мин. назад",
            "justStarted": "Только что начата",
            "notStarted": "Не начата",
            "startedTooltip": "Начата: {{when}}",
            "playersVs": "{{white}} против {{black}}"
        },
        "friendsPage": {
            "title": "Друзья",
            "tagline": "Найдите новых партнёров по шахматам",
            "myFriends": "Мои друзья",
            "noFriendsYet": "Друзей пока нет",
            "findPlayers": "Найти игроков",
            "searchByUsername": "Поиск по имени пользователя",
            "searchPlaceholder": "Введите для поиска…",
            "enterCharToSearch": "Введите хотя бы один символ для поиска",
            "noMatchingUsers": "Подходящих пользователей нет",
            "playing": "Играет",
            "pendingFriendshipOffer": "Ожидает ответа на заявку в друзья",
            "joining": "Присоединение",
            "rejoin": "Вернуться",
            "friendRequest": "Заявка в друзья",
            "wantsToBeFriends": "(хочет дружить)",
            "pendingOfferSuffix": "(ожидает ответа на заявку в друзья)",
            "waitingFriendRespond": "Ожидание ответа друга",
            "cancelBeforeRemove": "Отмените приглашение в партию перед удалением этого друга",
            "friendsTag": "Друзья",
            "offerReceivedTag": "Получена заявка — см. «Ваши друзья»",
            "addFriend": "Добавить в друзья",
            "withdraw": "Отозвать",
            "requestFailed": "Запрос не выполнен",
            "removeFriendConfirm": "Удалить этого друга из списка?",
            "removeFriendTitle": "Удалить друга",
            "withdrawOfferConfirm": "Отозвать эту заявку в друзья?",
            "withdrawOfferTitle": "Отозвать заявку",
            "couldNotAccept": "Не удалось принять",
            "couldNotDecline": "Не удалось отклонить",
            "couldNotRemove": "Не удалось удалить",
            "couldNotCancelInvite": "Не удалось отменить приглашение",
            "couldNotWithdraw": "Не удалось отозвать",
            "couldNotSendInvite": "Не удалось отправить приглашение",
            "couldNotSendGameInvite": "Не удалось отправить приглашение в партию",
            "gameInvite": "Приглашение в партию",
            "gameInvitationsAria": "Приглашения в партию",
            "gameInvitationAria": "Приглашение в партию",
            "chessInviteTitle": "Шахматное приглашение",
            "wantsToPlayAsBlack": "{{name}} хочет играть. Вы играете чёрными.",
            "aFriend": "Друг",
            "youPlayAsWhite": "Вы играете белыми",
            "youPlayAsBlack": "Вы играете чёрными",
            "establishingGame": "Создание партии…",
            "yourOpponent": "Ваш соперник",
            "declinedYourInvite": "{{name}} отклонил ваше приглашение в партию.",
            "cancelInvite": "Отменить приглашение",
            "accept": "Принять",
            "decline": "Отклонить",
            "invite": "Пригласить",
            "remove": "Удалить",
            "offerSent": "Заявка отправлена",
            "pending": "Ожидание",
            "online": "В сети",
            "offline": "Не в сети"
        },
        "adminPage": {
            "title": "Администрирование",
            "users": "Пользователи",
            "generate": "Генерация",
            "games": "Партии",
            "engines": "Движки",
            "states": "Состояния",
            "addUser": "Добавить пользователя",
            "sectionsAria": "Разделы администрирования",
            "openingBookLabel": "Дебютная книга:",
            "gameLines": "линий партий",
            "noGamesInDb": "В базе данных пока нет партий.",
            "gamesPaginationAria": "Постраничная навигация по партиям",
            "colNum": "№",
            "colUsername": "Имя пользователя",
            "colType": "Тип",
            "colEmail": "Эл. почта",
            "colPassword": "Пароль",
            "colLevel": "Уровень",
            "colElo": "Рейтинг",
            "colJoined": "Регистрация",
            "colLastLogin": "Последний вход",
            "colActiveGames": "Активные партии",
            "colFriends": "Друзья",
            "colBookmarks": "Закладки",
            "colId": "Id",
            "colStatus": "Статус",
            "colName": "Имя",
            "colAvailable": "Доступен",
            "colNotes": "Заметки",
            "colNote": "Заметка",
            "colAction": "Действие",
            "emptyUsers": "Пользователей пока нет.",
            "emptyData": "Данных пока нет.",
            "emptyStates": "Используйте «Генерация» для страницы генерации дебютной книги и состояний.",
            "clickToEdit": "Нажмите для редактирования",
            "updateFailed": "Ошибка обновления",
            "couldNotSave": "Не удалось сохранить",
            "setPassword": "Задать пароль",
            "setPasswordTitle": "Нажмите, чтобы задать новый пароль (4–30 символов)",
            "passwordLengthInvalid": "Пароль должен быть от 4 до 30 символов.",
            "invalidPassword": "Недопустимый пароль",
            "saved": "Сохранено",
            "newPasswordPlaceholder": "Новый пароль",
            "clickChangeUserType": "Нажмите, чтобы изменить тип пользователя",
            "userTypeAria": "Тип пользователя",
            "changeUserTypeTitle": "Изменить тип пользователя",
            "grantAdminConfirm": "Выдать этому пользователю права администратора? Он сможет использовать инструменты администрирования и управлять аккаунтами.",
            "demoteAdminConfirm": "Изменить тип пользователя с «Админ» на «{{type}}»? Доступ к разделу администрирования будет закрыт.",
            "changeUserTypeConfirm": "Изменить тип этого пользователя на «{{type}}»?",
            "clickChangeLevel": "Нажмите, чтобы изменить уровень",
            "playerLevelAria": "Уровень игрока",
            "sortByRowNumber": "Сортировать по номеру строки",
            "sortBy": "Сортировать по {{key}}",
            "delete": "Удалить",
            "first": "Первая",
            "last": "Последняя",
            "previous": "Назад",
            "next": "Вперёд",
            "previous5Pages": "На 5 страниц назад",
            "next5Pages": "На 5 страниц вперёд",
            "previous10Pages": "На 10 страниц назад",
            "next10Pages": "На 10 страниц вперёд",
            "userTypeAdmin": "Админ",
            "userTypePartner": "Партнёр",
            "userTypeMember": "Участник",
            "generateTitle": "Генерация дебютной книги и состояний",
            "backToAdmin": "← Назад к администрированию",
            "generateIntro": "Воспроизводит все файлы PGN в папке менеджера партий сервера либо в коллекцию State MongoDB, либо в построчную дебютную книгу (data/opening-book-lines.txt). Выберите цель и нажмите «Начать генерацию» — ничего не запускается, пока вы не нажмёте.",
            "target": "Цель",
            "targetMongo": "MongoDB — добавить строки в коллекцию State",
            "targetBook": "Файл строк — записать дебютную книгу (opening-book-lines.txt)",
            "startGeneration": "Начать генерацию",
            "stop": "Остановить",
            "idle": "Ожидание.",
            "starting": "Запуск…",
            "running": "Выполняется ({{mode}})…",
            "readingFiles": "Чтение файлов: {{count}}…",
            "replayingGames": "Воспроизведение партий: {{count}}…",
            "writingOpeningBook": "Запись дебютной книги…",
            "readingPgn": "Чтение PGN {{index}} / {{total}} ({{games}} партий)",
            "replayGameProgress": "Воспроизведение партии {{current}} / {{total}} (успешно: {{completed}})",
            "stopped": "Остановлено.",
            "bookUnchanged": "Существующая дебютная книга не изменена.",
            "bookLinesInFile": "{{count}} линий партий в {{file}}.",
            "cancelledBeforeRead": "Отменено до чтения PGN.",
            "cancelledAfterRead": "Отменено после чтения; воспроизведение пропущено (ничего не записано).",
            "mongoGamesSaved": "Для {{count}} партий сохранены новые строки состояния.",
            "doneBook": "Готово. {{count}} линий партий → {{file}}",
            "doneBookFileOnly": "Готово. {{file}}",
            "doneMongo": "Готово. Коллекция State MongoDB обновлена{{detail}}.",
            "doneMongoDetail": " (успешно воспроизведено партий: {{count}})",
            "errorPrefix": "Ошибка: {{message}}",
            "unknownError": "Неизвестная",
            "connectionClosed": "Соединение закрыто (проверьте журнал сервера или попробуйте снова).",
            "openingBookDefault": "дебютная книга"
        },
        "playNow": {
            "title": "Новая партия",
            "startTitle": "Начать новую партию",
            "playingColor": "Цвет фигур",
            "timeMin": "Время (мин)",
            "difficulty": "Сложность (1–5)",
            "mousePreference": "Управление мышью",
            "drag": "Перетаскивание",
            "doubleClick": "Двойной щелчок",
            "showAvailableMoves": "Показывать возможные ходы",
            "private": "Приватная",
            "privateHint": "Приватные партии не отображаются в списках активных партий других участников.",
            "playComputer": "Игра с компьютером",
            "browseAll": "Просмотреть все",
            "yourHistory": "Ваша история",
            "fullList": "Полный список",
            "gameLibrary": "Библиотека партий",
            "openLibrarySearch": "Открыть поиск в библиотеке",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Активные партии",
            "tagline": "Все партии в процессе",
            "liveGames": "Живые партии",
            "game": "Партия",
            "started": "Начата"
        },
        "list": {
            "title": "Все партии",
            "action": "Действие"
        },
        "searchPage": {
            "title": "Поиск:",
            "tagline": "Найдите партии в архиве PGN",
            "results": "Результаты",
            "resultsCount": "Результатов: {{count}}",
            "noResults": "Нет партий, соответствующих запросу",
            "button": "Искать",
            "resultsFound": "Найдено результатов: {{count}}",
            "first": "Первая",
            "last": "Последняя",
            "previous": "Назад",
            "next": "Вперёд",
            "previous5Pages": "На 5 страниц назад",
            "next5Pages": "На 5 страниц вперёд",
            "previous10Pages": "На 10 страниц назад",
            "next10Pages": "На 10 страниц вперёд"
        },
        "game": {
            "moves": "Ходы",
            "white": "Белые",
            "black": "Чёрные",
            "resign": "Сдаться",
            "draw": "Ничья",
            "undo": "Отменить",
            "flip": "Перевернуть",
            "practice": "Тренировка"
        },
        "mobileWelcome": {
            "title": "Главная — Шахматы",
            "play": "Играть",
            "library": "Библиотека",
            "friends": "Друзья"
        },
        "mobileGame": {
            "title": "Партия",
            "moves": "Ходы",
            "resign": "Сдаться"
        }
    },
    "desktop": {
        "error": {
            "title": "Что-то пошло не так",
            "body": "Произошла ошибка.",
            "back": "На главную"
        },
        "chrome": {
            "preferences": "Настройки",
            "closePreferences": "Закрыть настройки",
            "display": "Отображение",
            "gameplay": "Игра",
            "pieceSet": "Набор фигур",
            "boardTheme": "Тема доски",
            "themeBlue": "Синяя",
            "themeDark": "Тёмная",
            "customizeTheme": "Настроить тему…",
            "builtInThemesAria": "Встроенные темы",
            "savedCustomThemesAria": "Сохранённые пользовательские темы",
            "pieceSetsAria": "Наборы фигур",
            "homeAria": "Главная Shmerling Chess"
        },
        "prefs": {
            "language": "Язык",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "Управление мышью",
            "thinkingTime": "Время обдумывания",
            "thinkingTimeAria": "Время обдумывания в секундах",
            "immediateResign": "Мгновенная сдача",
            "secondsOption": "{{count}} с",
            "enterFullScreen": "Полноэкранный режим",
            "exitFullScreen": "Выйти из полноэкранного режима",
            "fullScreenUnavailable": "Полноэкранный режим недоступен в этом браузере."
        },
        "gameRun": {
            "yourColor": "Ваш цвет",
            "engine": "Движок",
            "thinkTime": "Время обдумывания (секунды)",
            "thinkTimeAria": "Время обдумывания движка в секундах",
            "play": "Играть",
            "nextMove": "Следующий ход",
            "computer": "Компьютер",
            "computerColorHint": "Цвет, которым играет компьютер — вы играете другой стороной"
        },
        "brainConfig": {
            "title": "Настройка движка",
            "save": "Сохранить",
            "reset": "Сброс",
            "saved": "Настройки сохранены",
            "failedSave": "Не удалось сохранить настройки",
            "brainLabel": "Движок",
            "loading": "Загрузка…",
            "failedLoad": "Не удалось загрузить настройки движка.",
            "discardSwitchConfirm": "Отменить несохранённые изменения и переключить версию движка?",
            "discard": "Отменить",
            "pieceScores": "Оценки фигур",
            "specialEvaluations": "Специальные оценки",
            "gamePhase": "Фаза партии",
            "pawnFilesOpeningMid": "Вертикали пешек (дебют / миттельшпиль)",
            "pawnFilesEndGame": "Вертикали пешек (эндшпиль)"
        },
        "customTheme": {
            "title": "Пользовательская тема",
            "name": "Имя темы",
            "save": "Сохранить",
            "delete": "Удалить",
            "saved": "Сохранено",
            "searchProperties": "Поиск свойств",
            "filterPlaceholder": "Фильтр по имени свойства…",
            "namePlaceholder": "Моя тема",
            "resetPreset": "Сбросить к текущему пресету",
            "couldNotSave": "Не удалось сохранить тему. Попробуйте снова.",
            "untitled": "Без названия",
            "defaultName": "Пользовательская тема"
        },
        "positionSetup": {
            "clearBoard": "Очистить доску",
            "startingPosition": "Начальная позиция",
            "flipBoard": "Перевернуть доску",
            "eraser": "Ластик",
            "selectAndMove": "Выбор и перемещение",
            "defaultStartingPosition": "Стандартная начальная позиция",
            "savePosition": "Сохранить позицию",
            "saveAsNewPosition": "Сохранить как новую позицию",
            "validatePosition": "Проверить позицию",
            "positionFlags": "Флаги позиции",
            "turn": "Ход",
            "flagCheck": "Шах",
            "flagCheckmate": "Мат",
            "flagDraw": "Ничья",
            "flagWhiteKingMoved": "Белый король ходил",
            "flagBlackKingMoved": "Чёрный король ходил",
            "flagWhiteKingsideRookMoved": "Белая королевская ладья ходила",
            "flagWhiteQueensideRookMoved": "Белая ферзевая ладья ходила",
            "flagBlackKingsideRookMoved": "Чёрная королевская ладья ходила",
            "flagBlackQueensideRookMoved": "Чёрная ферзевая ладья ходила"
        }
    },
    "errorPage": {
        "code": "Ошибка {{code}}",
        "notFoundTitle": "Страница не найдена",
        "notFoundMessage": "Запрашиваемая страница не существует.",
        "genericTitle": "Что-то пошло не так",
        "genericMessage": "Произошла непредвиденная ошибка. Попробуйте ещё раз.",
        "backHome": "На главную"
    },
    "mobile": {
        "drawOfferTitle": "Предложение ничьей",
        "drawOfferMessage": "Соперник предложил ничью. Принять?",
        "rematchTitle": "Реванш",
        "rematchMessage": "Соперник предложил реванш. Принять?",
        "gameId": "ID партии: {{id}}",
        "drawOfferAgree": "Соперник предложил ничью, согласиться?",
        "rematchOfferAgree": "Соперник предложил реванш, согласиться?",
        "newGameWatchFromHome": "Начата новая партия — перейдите на главную, чтобы наблюдать."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = ruExtra;
    } else {
        global.ShmerlingStringsRuExtra = ruExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
