/**
 * Russian string catalog — mirrors src/strings/en.js structure with Russian values.
 */
(function (global) {
    "use strict";

    const ru = {
        common: {
            white: "Белые",
            black: "Чёрные",
            draw: "Ничья",
            winner: "Победитель",
            engine: "Движок",
            ok: "ОК",
            cancel: "Отмена",
            confirm: "Подтвердить",
            yes: "Да",
            no: "Нет",
            notice: "Уведомление",
            input: "Ввод",
            start: "Начать",
            collapse: "Свернуть",
            expand: "Развернуть",
            delete: "Удалить",
            rename: "Переименовать",
            save: "Сохранить",
            aPlayer: "Игрок",
            pleaseEnterValue: "Введите значение."
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Действия в партии",
                playersAndClocks: "Игроки и часы",
                whitePlayerClock: "Часы белых",
                blackPlayerClock: "Часы чёрных",
                startFromLoadedPosition: "Начать партию с загруженной позиции",
                moves: "Ходы",
                expandMovesPanel: "Развернуть панель ходов",
                expandMoves: "Развернуть ходы",
                collapseMovesPanel: "Свернуть панель ходов",
                reviewNavigation: "Навигация по просмотру",
                positionSetup: "Редактор позиции",
                pieces: "Фигуры",
                collapsePiecesPanel: "Свернуть панель фигур",
                brainConfiguration: "Настройка движка",
                configuration: "Настройка",
                collapseConfigurationPanel: "Свернуть панель настроек",
                games: "Партии",
                expandGamesPanel: "Развернуть панель партий",
                expandGames: "Развернуть партии",
                expandGamesLocked: "Панель игр недоступна во время игры",
                collapseGamesPanel: "Свернуть панель партий",
                chat: "Чат",
                expandChatPanel: "Развернуть панель чата",
                collapseChatPanel: "Свернуть панель чата",
                chatPlaceholder: "Введите сообщение…",
                chatWatcherReadonly: "Зрители могут только читать чат",
                sendChat: "Отправить",
                savedListFilter: "Фильтр сохранённого списка",
                positions: "Позиции",
                gameStatus: "Статус партии",
                capturedPieces: "Сбитые фигуры"
            },
            sessionMode: {
                play: "Режим игры",
                positionSetup: "Редактор позиции",
                configuration: "Режим настройки",
                playback: "Режим воспроизведения",
                review: "Режим просмотра",
                watch: "Режим наблюдения",
                practice: "Режим тренировки"
            },
            status: {
                chooseNewGameOrSetup: "Выберите «Новая партия» или «Редактор позиции» на боковой панели",
                chooseNewGame: "Выберите «Новая партия» на боковой панели",
                setMoveColorEngineThinkTime: "Укажите ход, цвет, движок и время обдумывания в заголовке, затем нажмите «Играть»",
                gameOver: "Партия окончена",
                gameInProgress: "Партия идёт",
                boardLoading: "Доска ещё загружается…",
                boardNotReady: "Доска ещё не готова. Подождите и попробуйте снова.",
                leaveOnlineBeforeConfiguration: "Выйдите из онлайн-партии перед открытием настроек",
                configurationNotInPractice: "Настройка недоступна в режиме тренировки",
                configurationModeEdit: "Режим настройки — измените значения и сохраните",
                selectSavedOrSetup: "Сначала выберите сохранённую партию или расставьте позицию на доске",
                gameAlreadyInProgress: "Партия уже идёт",
                yourMove: "Ваш ход",
                engineToMove: "Ход движка…",
                leaveOnlineBeforePositionSetup: "Выйдите из онлайн-партии перед открытием редактора позиции",
                positionSetupNotInPractice: "Редактор позиции недоступен в режиме тренировки",
                positionSetupPlacePieces: "Редактор позиции — расставьте фигуры на доске",
                drawWithReason: "Ничья — {{reason}}",
                checkmateWins: "Мат — победа {{winner}}",
                check: "Шах",
                waitBeforeEvaluate: "Дождитесь завершения текущего хода перед оценкой",
                evaluationUnavailable: "Оценка недоступна. Перезапустите приложение Shmerling Chess.",
                evaluatingPosition: "Оценка позиции…",
                evaluationFailed: "Ошибка оценки",
                evaluationLine: "Оценка (ход {{side}}): {{score}}",
                checkmate: "Мат",
                drawZero: "Ничья (0)",
                totalLabel: "Итого: {{value}}",
                openFolderDesktopOnly: "Открытие папки доступно только в настольном приложении",
                couldNotOpenGamesLogFolder: "Не удалось открыть папку журнала партий",
                positionValid: "Позиция корректна",
                playingFromCustomPosition: "Игра с пользовательской позиции",
                nothingToSave: "Нечего сохранять",
                positionSaved: "Позиция сохранена",
                couldNotSavePosition: "Не удалось сохранить позицию",
                savedPositionNotFound: "Сохранённая позиция не найдена",
                positionUpdated: "Позиция обновлена",
                couldNotUpdatePosition: "Не удалось обновить позицию",
                nameCannotBeEmpty: "Имя не может быть пустым",
                gameRenamed: "Партия переименована",
                couldNotRenameGame: "Не удалось переименовать партию",
                deletedCount: "Удалено элементов: {{count}}",
                couldNotDeleteSelected: "Не удалось удалить выбранные элементы",
                couldNotLoadSavedGame: "Не удалось загрузить сохранённую партию",
                editingPositionSaveBookmark: "Редактирование позиции — сохраните, чтобы обновить закладку",
                couldNotOpenPositionForEditing: "Не удалось открыть позицию для редактирования",
                gameSaved: "Партия сохранена",
                couldNotSaveGame: "Не удалось сохранить партию",
                engineMoveNotApplied: "Не удалось выполнить ход движка",
                engineCouldNotFindMove: "Движок не нашёл ход",
                engineError: "Ошибка движка",
                engineThinking: "Движок думает…",
                sessionError: "Ошибка сессии",
                timesUpLost: "Время вышло! {{loser}} проиграли",
                drawOfferTitle: "Предложение ничьей",
                drawOfferMessage: "Соперник предложил ничью. Принять?",
                rematchTitle: "Реванш",
                playerDisconnectedWaiting: "{{who}} отключился — ожидание переподключения ({{countdown}})",
                opponentDisconnectedCountdown: "Соперник отключён — {{countdown}}",
                gameCancelledReconnectTimeout: "Партия отменена — время переподключения истекло, ходов не было.",
                playerFailedToReconnectWins: "{{loser}} не переподключился — победа {{winner}}",
                gameOverOpponentFailedReconnect: "Партия окончена — соперник не переподключился.",
                couldNotStartRematch: "Не удалось начать реванш",
                rematchStarted: "Реванш начат",
                gameCancelled: "Партия отменена",
                gameCancelledWithDetail: "Партия отменена — {{detail}}",
                gameCancelledOpponentLeftBeforeFirstMove: "Игра отменена — противник ушел до первого хода.",
                resignFailed: "Не удалось сдаться",
                gameResumedYourMove: "Партия возобновлена — ваш ход",
                practiceNotAvailable: "Режим тренировки недоступен",
                couldNotJoinOnPlay: "Не удалось присоединиться к этой партии на /play",
                practiceDebugNotAvailable: "Тренировка / отладка недоступна для этой учётной записи",
                reviewRequiresWebApi: "Просмотр требует веб-API",
                couldNotLoadReviewGame: "Не удалось загрузить партию для просмотра",
                notReviewGameLink: "Эта ссылка не ведёт к партии для просмотра",
                onlineRequiresWebApi: "Онлайн-игра требует веб-API",
                couldNotLoadOnlineGame: "Не удалось загрузить онлайн-партию",
                notOnlineGameOnPlay: "Эта ссылка не ведёт к онлайн-партии на /play",
                watchingLiveGame: "Наблюдение за живой партией",
                waitingForOpponentToJoin: "Ожидание соперника…",
                waitingForOpponent: "Ожидание соперника…",
                onlineGameConnected: "Онлайн-партия — подключено",
                gameDeleted: "Партия удалена",
                itemsDeleted: "Удалено элементов: {{count}}",
                choosePromotionPiece: "Выберите фигуру для превращения",
                invalidPromotionPiece: "Недопустимая фигура превращения",
                drawOfferNotAvailable: "Предложение ничьей сейчас недоступно"
            },
            drawReasons: {
                stalemate: "Пат",
                fiftyMoves: "50 ходов",
                insufficientMaterial: "Недостаточно материала",
                threefoldRepetition: "Троекратное повторение",
                drawOfferAccepted: "Предложение ничьей от {{by}} принято"
            },
            actions: {
                newGame: "Новая партия",
                resign: "Сдаться",
                draw: "Ничья",
                undo: "Отменить",
                redo: "Повторить",
                lastMove: "Последний ход",
                positionSetup: "Редактор позиции",
                config: "Настр.",
                flip: "Перевернуть",
                save: "Сохранить",
                exit: "Выход",
                backToLobby: "Вернуться в лобби",
                loadToStart: "Загрузить для старта",
                editPosition: "Редактировать позицию",
                loadGame: "Загрузить партию",
                loadPosition: "Загрузить позицию"
            },
            savedGames: {
                defaultName: "Сохранённая партия",
                nameAriaLabel: "Имя сохранённой партии",
                showDetails: "Показать подробности",
                detailsAriaLabel: "Подробности сохранённой партии",
                editPosition: "Редактировать позицию",
                deleteSavedGame: "Удалить сохранённую партию",
                renameSavedGame: "Переименовать сохранённую партию",
                noSavedPositions: "Сохранённых позиций пока нет.",
                noSavedGames: "Сохранённых партий пока нет.",
                nextMoveDash: "Следующий ход: —",
                nextMove: "Следующий ход: {{side}}",
                player: "Игрок",
                savedAt: "Сохранено: {{when}}",
                gameId: "ID партии: {{id}}",
                playersVs: "{{white}} против {{black}}",
                defaultPositionName: "Сохранённая позиция",
                itemsSelected: "Выбрано элементов: {{count}}"
            },
            reviewNav: {
                start: "Начало",
                back: "Назад",
                play: "Воспроизвести",
                pause: "Пауза",
                forward: "Вперёд",
                end: "Конец"
            },
            newGameDialog: {
                title: "Новая партия против ИИ",
                yourColor: "Ваш цвет",
                engine: "Движок",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                stockfish: "Stockfish",
                timePerSideMinutes: "Время на сторону (минуты)",
                allowUndo: "Разрешить отмену хода",
                private: "Приватная",
                privateHint: "Приватные партии не отображаются в списках активных партий других участников."
            },
            prompts: {
                positionName: "Имя позиции",
                savePositionAs: "Сохранить позицию как"
            },
            dialogs: {
                resignTitle: "Сдаться в этой партии?",
                resignBody: "Вы проиграете партию.",
                leaveTitle: "Покинуть партию?",
                leaveBody: "Ваша партия будет засчитана как сдача.",
                areYouSure: "Вы уверены?",
                discardUnsavedBrainConfig: "Отменить несохранённые изменения настроек движка?",
                accept: "Принять",
                decline: "Отклонить",
                saveAs: "Сохранить как",
                savePosition: "Сохранить позицию",
                invalidPosition: "Некорректная позиция",
                rematchChooseColor: "Выберите цвет для реванша:",
                rematchOfferAgree: "Соперник предложил реванш. Согласиться?",
                rematchOfferAgreeWithTime: "Соперник предложил матч-реванш ({{minutes}} мин на каждую сторону). Соглашаться?",
                rematchColorPreference: "Соперник хочет играть {{offerer}}. Вы будете играть {{you}}. Согласиться?",
                rematchColorPreferenceWithTime: "Противник хочет играть как {{offerer}} ({{minutes}} мин на каждую сторону). Вы будете играть как {{you}}. Соглашаться?"
            }
        },
        session: {
            engineThinking: "Движок думает…",
            engineCouldNotFindMove: "Движок не нашёл ход",
            engineError: "Ошибка движка",
            positionSetupPlacePieces: "Редактор позиции — расставьте фигуры на доске",
            configurationModeEdit: "Режим настройки — измените значения и сохраните",
            practiceBothSides: "Тренировка — обе стороны",
            opponentDisconnected: "Соперник отключён",
            opponentRejoined: "Соперник переподключился",
            playerRejoined: "{{name}} переподключился",
            drawOfferSent: "Предложение ничьей отправлено",
            drawOfferDeclined: "Предложение ничьей отклонено",
            rematchOfferSent: "Предложение реванша отправлено",
            rematchOfferDeclined: "Предложение реванша отклонено",
            rematchUnavailable: "Соперник больше не доступен для матча-реванша",
            drawAgreed: "Ничья согласована",
            rematchAcceptedNoGameId: "Реванш принят, но новый ID партии не получен",
            rematchOfferAccepted: "Предложение реванша принято",
            gameOver: "Партия окончена",
            somethingWentWrong: "Что-то пошло не так",
            opponentResigned: "Соперник сдался",
            opponentLeftGame: "Соперник покинул партию",
            opponentFailedToReconnect: "Соперник не переподключился",
            gameCancelled: "Партия отменена",
            gameCancelledWithDetail: "Партия отменена — {{detail}}",
            gameCancelledOpponentLeftBeforeFirstMove: "Игра отменена — противник ушел до первого хода.",
            gameCancelledReconnectTimeout: "Игра отменена — время повторного подключения истекло, ходы не были сыграны.",
            waitingForOpponent: "Ожидание соперника…",
            couldNotResolveWebSocketUrl: "Не удалось определить URL WebSocket",
            opponentJoined: "{{name}} присоединился",
            opponentDefault: "Соперник",
            connectionError: "Ошибка подключения",
            connectionLost: "Соединение потеряно — ходы не доходят до сервера",
            reconnecting: "Повторное подключение…",
            connectionRestored: "Соединение восстановлено",
            flagReported: "Флаг — подтверждение с сервером…",
            playerDisconnectedWaitingRejoin: "{{name}} отключился — ожидание переподключения",
            playerFailedToReconnectWins: "{{loser}} не переподключился — победа {{winner}}",
            watcherWaitingForReconnect: "Ожидание переподключения игрока…"
        },
        site: {
            confirm: "Подтвердить",
            cancel: "Отмена",
            notice: "Уведомление",
            ok: "ОК",
            home: "Главная",
            search: "Поиск",
            friends: "Друзья",
            groups: "Группы",
            debug: "Отладка",
            account: "Аккаунт",
            preferences: "Настройки",
            administrate: "Администрирование",
            logOut: "Выйти",
            logIn: "Войти",
            admin: "Админ",
            homeAria: "Главная"
        },
        validation: {
            validEmail: "Введите корректный адрес электронной почты",
            passwordsMustMatch: "Поля пароля должны совпадать.",
            chooseUsername: "Выберите имя пользователя",
            usernameNotAvailable: "Это имя пользователя недоступно",
            passwordNoWhitespace: "Пароль не должен содержать пробелы.",
            passwordUppercase: "Пароль должен содержать хотя бы одну заглавную букву."
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = ru;
    } else {
        global.ShmerlingStringsRu = ru;
    }
})(typeof window !== "undefined" ? window : globalThis);
