(function (global) {
    "use strict";
    const ukExtra = {
    "validation": {
        "passwordLowercase": "Пароль має містити принаймні одну малу літеру.",
        "passwordDigit": "Пароль має містити принаймні одну цифру.",
        "passwordSymbol": "Пароль має містити принаймні один спеціальний символ.",
        "passwordLength": "Пароль має містити від 8 до 30 символів.",
        "noHtml": "{{label}} не повинно містити HTML.",
        "position": {
            "headerSave": "Неможливо зберегти цю позицію:\n\n",
            "headerPlay": "Неможливо грати з цієї позиції:\n\n",
            "headerUse": "Неможливо використати цю позицію:\n\n",
            "headerSaveBookmark": "Неможливо зберегти цю закладку:\n\n",
            "headerAddBookmark": "Неможливо додати цю закладку:\n\n",
            "boardUnreadable": "Не вдалося прочитати дошку. Спробуйте знову після завантаження дошки.",
            "whiteKingNone": "На дошці має бути рівно один білий король. Жодного не знайдено.",
            "whiteKingCount": "На дошці має бути рівно один білий король. Знайдено білих королів: {{count}}.",
            "blackKingNone": "На дошці має бути рівно один чорний король. Жодного не знайдено.",
            "blackKingCount": "На дошці має бути рівно один чорний король. Знайдено чорних королів: {{count}}.",
            "kingsAdjacent": "Два королі не можуть стояти на сусідніх полях (включно з діагональними).",
            "sideInCheck": "Хід {{mover}}, але король {{king}} уже під шахом. Сторона, що ходить, не може давати шах — змініть чергу ходу або переставте фігури.",
            "drawInsufficientKings": "Ця позиція — нічия через недостатній матеріал (король проти короля). Додайте фігури, щоб мат залишався можливим.",
            "drawInsufficientMinor": "Ця позиція — нічия через недостатній матеріал (король і слон або кінь проти самотнього короля). Додайте фігури, щоб мат залишався можливим.",
            "drawBishopsSameColor": "Ця позиція — нічия через недостатній матеріал (слони одного кольорових полів). Додайте фігури, щоб мат залишався можливим.",
            "tooManyQueens": "У {{color}} {{count}} ферзів; максимум — 9 на колір.",
            "tooManyRooks": "У {{color}} {{count}} тур; максимум — 10 на колір.",
            "tooManyBishops": "У {{color}} {{count}} слонів; максимум — 10 на колір.",
            "tooManyKnights": "У {{color}} {{count}} коней; максимум — 10 на колір.",
            "tooManyPawns": "У {{color}} {{count}} пішаків; максимум — 8 на колір."
        }
    },
    "auth": {
        "whoAreYou": "Хто ви?",
        "enterPassword": "Введіть пароль",
        "sorry": "Вибачте",
        "continue": "Продовжити",
        "usernameField": "Ім'я користувача",
        "passwordField": "Пароль",
        "wrongCredentials": "Невірне ім'я користувача або пароль",
        "userAdded": "Користувача успішно додано",
        "couldNotSaveBookmark": "Не вдалося зберегти закладку",
        "invalidUserId": "Некоректний ID користувача",
        "generationJobRunning": "Інше завдання генерації вже виконується…",
        "listingPgnFiles": "Отримання списку PGN-файлів…"
    },
    "classic": {
        "loadGame": "Завантажити партію",
        "load": "Завантажити",
        "enterGameState": "Вставте стан партії сюди...",
        "rematch": "Реванш",
        "drawOffer": "Пропозиція нічиєї",
        "lastMove": "Останній хід",
        "bookmarks": "Закладки",
        "bookmarkAlertTitle": "Закладка позиції",
        "promotion": "Перетворення!",
        "check": "Шах",
        "checkmateWins": "Мат! Перемагають {{winner}}!",
        "drawReason": "Нічия! {{reason}}",
        "opponentDisconnected": "Суперник відключився",
        "opponentResignedWins": "Суперник здався, перемагають {{winner}}",
        "somethingWentWrong": "Щось пішло не так",
        "playerRejoined": "{{name}} повернувся",
        "aPlayerRejoined": "Гравець повернувся",
        "opponentRejoined": "Суперник повернувся",
        "rematchOfferAccepted": "Пропозицію реваншу прийнято",
        "rematchOfferDeclined": "Пропозицію реваншу відхилено",
        "sideOffersDraw": "{{side}} пропонують нічию",
        "drawOfferDeclined": "Пропозицію нічиєї відхилено",
        "watcherWatching": "{{name}} переглядає партію",
        "drawOfferSent": "Пропозицію нічиєї надіслано",
        "rematchOfferSent": "Пропозицію реваншу надіслано",
        "newGameStarted": "Розпочато нову партію",
        "gameOver": "Партія завершена",
        "gameCancelled": "Партію скасовано",
        "youResignedWins": "Ви здались, перемагають {{winner}}",
        "movesCopied": "Ходи скопійовано в буфер обміну!",
        "failedCopyMoves": "Не вдалося скопіювати ходи",
        "failedLoadBrainConfig": "Не вдалося завантажити налаштування рушія.",
        "failedSaveBrainConfig": "Не вдалося зберегти налаштування рушія.",
        "offerDrawConfirm": "Запропонувати нічию?",
        "drawOfferAccept": "Суперник запропонував нічию, прийняти?",
        "rematchOfferAccept": "Суперник запропонував реванш, погодитися?",
        "confirmExitGame": "Ви впевнені, що хочете вийти з партії?",
        "mobileResign": "Здатися",
        "mobileRematch": "Реванш",
        "mobileDraw": "Нічия",
        "mobileFlip": "Перевернути",
        "mobileLastMove": "Останній хід",
        "mobileMovesList": "Список ходів",
        "researchToolbox": "Панель інструментів",
        "researchBrainConfig": "Налаштування рушія",
        "researchSave": "Зберегти",
        "researchDiscard": "Скасувати",
        "researchEditMode": "режим редагування",
        "researchRun": "Запустити",
        "researchProperty": "Властивість",
        "researchValue": "Значення",
        "playerOnline": "Онлайн",
        "playerDisconnectedStatus": "Відключено",
        "playerOffline": "Офлайн",
        "humanVsComputer": "Людина проти комп'ютера",
        "newGameTwoPlayers": "Нова партія на двох",
        "settings": "Налаштування",
        "help": "Допомога",
        "drawOffersNotVsEngine": "Пропозиції нічиєї недоступні в грі проти рушія.",
        "failedStartFromBookmark": "Не вдалося розпочати партію з закладки.",
        "resignConfirm": "Здатися?",
        "areYouSure": "Ви впевнені?",
        "gameOverOpponentFailedReconnectWinsClassic": "Партія завершена — суперник не зміг перепідключитися. Перемагають {{winner}}.",
        "reconnectTimeoutNoMoves": "Час на повторне підключення минув, ходів не було зроблено.",
        "waitingOpponentRejoin": "Очікування повернення суперника",
        "timeoutOneSec": "Таймаут: 1 с",
        "timeoutSecs": "Таймаут: {{count}} с",
        "whitePieceAlt": "Біла фігура",
        "blackPieceAlt": "Чорна фігура",
        "eraserTitle": "Гумка",
        "eraserAria": "Гумка — прибрати фігуру з поля",
        "selectTitle": "Вибір",
        "selectAria": "Вибір — перетягніть фігури, щоб перемістити їх",
        "resetAria": "Скинути — очистити всі фігури",
        "defaultPositionAria": "Початкова позиція — установити стандартну стартову позицію",
        "loading": "Завантаження...",
        "engineLabel": "Рушій"
    },
    "site": {
        "home": "Головна",
        "search": "Пошук",
        "friends": "Друзі",
        "groups": "Групи",
        "debug": "Debug",
        "account": "Обліковий запис",
        "preferences": "Налаштування",
        "administrate": "Адміністрування",
        "logOut": "Вийти",
        "logIn": "Увійти",
        "admin": "Адмін",
        "homeAria": "Головна",
        "confirm": "Підтвердити",
        "cancel": "Скасувати",
        "notice": "Повідомлення",
        "ok": "OK",
        "username": "Ім'я користувача:",
        "password": "Пароль:",
        "login": "Увійти",
        "register": {
            "submit": "Реєстрація",
            "confirmPassword": "Підтвердіть пароль:",
            "playerLevel": "Рівень гравця:",
            "rookie": "Новачок",
            "skilled": "Досвідчений",
            "elite": "Еліта",
            "grandMaster": "Гросмейстер"
        },
        "email": "Електронна пошта:",
        "welcome": {
            "greeting": "З поверненням",
            "tagline": "Ваш хід чекає",
            "playNow": "Грати зараз!",
            "activeGames": "Активні партії",
            "live": "Наживо",
            "showAll": "Показати все",
            "viewAllActive": "Переглянути всі активні партії",
            "mostRecent": "Спочатку найновіші",
            "noGamesNow": "Наразі немає партій",
            "myGames": "Мої партії",
            "viewAllGames": "Переглянути всі партії",
            "recentCompleted": "Ваші недавно завершені партії",
            "noCompleted": "Ще немає завершених партій",
            "activeGamesAria": "Активні партії",
            "inviteOnlineFriend": "Запросіть онлайн-друга зіграти",
            "friendsPageTitle": "Сторінка друзів",
            "manageFriends": "Керувати",
            "colFriend": "Друг",
            "colStatus": "Статус",
            "findPlayers": "Знайти гравців",
            "waitingForResponse": "Очікування відповіді",
            "inviteSentSuffix": "(запрошення надіслано)",
            "sortByRowNumber": "Сортувати за номером рядка",
            "sortBy": "Сортувати за {{key}}"
        },
        "gameList": {
            "date": "Дата",
            "time": "Час",
            "result": "Результат",
            "reason": "Причина",
            "type": "Тип",
            "status": "Статус",
            "event": "Турнір",
            "site": "Місце",
            "round": "Тур"
        },
        "loginPage": {
            "title": "Вхід"
        },
        "error": {
            "title": "Щось пішло не так",
            "body": "Сталася помилка.",
            "back": "На головну"
        },
        "log": {
            "title": "Журнал сервера",
            "clear": "Очистити перегляд",
            "latest": "Останні",
            "waiting": "Очікування виводу журналу сервера…"
        },
        "activeGames": {
            "moves": "Ходи",
            "turn": "Хід",
            "status": "Статус",
            "inProgress": "Триває",
            "onHold": "На паузі",
            "vs": " проти ",
            "minutesAgo": "{{count}} хвилин тому",
            "oneMinuteAgo": "1 хвилину тому",
            "justStarted": "Щойно розпочато",
            "notStarted": "Не розпочато",
            "startedTooltip": "Розпочато: {{when}}",
            "playersVs": "{{white}} проти {{black}}"
        },
        "friendsPage": {
            "title": "Друзі",
            "tagline": "Знайдіть нових партнерів для шахів",
            "myFriends": "Мої друзі",
            "noFriendsYet": "Ще немає друзів",
            "findPlayers": "Знайти гравців",
            "searchByUsername": "Пошук за іменем користувача",
            "searchPlaceholder": "Почніть вводити для пошуку…",
            "enterCharToSearch": "Введіть принаймні один символ для пошуку",
            "noMatchingUsers": "Відповідних користувачів не знайдено",
            "playing": "Грає",
            "pendingFriendshipOffer": "Очікує пропозиція дружби",
            "joining": "Приєднання",
            "rejoin": "Повернутися",
            "friendRequest": "Запит у друзі",
            "wantsToBeFriends": "(хоче дружити)",
            "pendingOfferSuffix": "(очікує пропозиція дружби)",
            "waitingFriendRespond": "Очікування відповіді друга",
            "cancelBeforeRemove": "Скасуйте запрошення на партію перед видаленням цього друга",
            "friendsTag": "Друзі",
            "offerReceivedTag": "Отримано пропозицію — див. «Ваші друзі»",
            "addFriend": "Додати друга",
            "withdraw": "Відкликати",
            "requestFailed": "Запит не вдався",
            "removeFriendConfirm": "Видалити цього друга зі списку?",
            "removeFriendTitle": "Видалити друга",
            "withdrawOfferConfirm": "Відкликати цю пропозицію дружби?",
            "withdrawOfferTitle": "Відкликати пропозицію",
            "couldNotAccept": "Не вдалося прийняти",
            "couldNotDecline": "Не вдалося відхилити",
            "couldNotRemove": "Не вдалося видалити",
            "couldNotCancelInvite": "Не вдалося скасувати запрошення",
            "couldNotWithdraw": "Не вдалося відкликати",
            "couldNotSendInvite": "Не вдалося надіслати запрошення",
            "couldNotSendGameInvite": "Не вдалося надіслати запрошення на партію",
            "gameInvite": "Запрошення на партію",
            "gameInvitationsAria": "Запрошення на партії",
            "gameInvitationAria": "Запрошення на партію",
            "chessInviteTitle": "Шахове запрошення",
            "wantsToPlayAsBlack": "{{name}} хоче зіграти. Ви граєте чорними.",
            "aFriend": "Друг",
            "youPlayAsWhite": "Ви граєте білими",
            "youPlayAsBlack": "Ви граєте чорними",
            "establishingGame": "Створення партії…",
            "yourOpponent": "Ваш суперник",
            "declinedYourInvite": "{{name}} відхилив(ла) ваше запрошення на партію.",
            "cancelInvite": "Скасувати запрошення",
            "accept": "Прийняти",
            "decline": "Відхилити",
            "invite": "Запросити",
            "remove": "Видалити",
            "offerSent": "Пропозицію надіслано",
            "pending": "Очікує",
            "online": "Онлайн",
            "offline": "Офлайн"
        },
        "adminPage": {
            "title": "Адміністрування",
            "users": "Користувачі",
            "generate": "Генерація",
            "games": "Партії",
            "engines": "Рушії",
            "states": "Стани",
            "addUser": "Додати користувача",
            "sectionsAria": "Розділи адміністрування",
            "openingBookLabel": "Дебютна книга:",
            "gameLines": "ліній партій",
            "noGamesInDb": "У базі даних ще немає партій.",
            "gamesPaginationAria": "Пагінація партій",
            "colNum": "№",
            "colUsername": "Ім'я користувача",
            "colType": "Тип",
            "colEmail": "Електронна пошта",
            "colPassword": "Пароль",
            "colLevel": "Рівень",
            "colElo": "Elo",
            "colJoined": "Приєднався",
            "colLastLogin": "Останній вхід",
            "colActiveGames": "Активні партії",
            "colFriends": "Друзі",
            "colBookmarks": "Закладки",
            "colId": "Id",
            "colStatus": "Статус",
            "colName": "Назва",
            "colAvailable": "Доступний",
            "colNotes": "Примітки",
            "colNote": "Примітка",
            "colAction": "Дія",
            "emptyUsers": "Ще немає користувачів.",
            "emptyData": "Ще немає даних.",
            "emptyStates": "Використайте «Генерація», щоб відкрити сторінку генерації дебютної книги та станів.",
            "clickToEdit": "Натисніть для редагування",
            "updateFailed": "Не вдалося оновити",
            "couldNotSave": "Не вдалося зберегти",
            "setPassword": "Встановити пароль",
            "setPasswordTitle": "Натисніть, щоб встановити новий пароль (4–30 символів)",
            "passwordLengthInvalid": "Пароль має містити від 4 до 30 символів.",
            "invalidPassword": "Некоректний пароль",
            "saved": "Збережено",
            "newPasswordPlaceholder": "Новий пароль",
            "clickChangeUserType": "Натисніть, щоб змінити тип користувача",
            "userTypeAria": "Тип користувача",
            "changeUserTypeTitle": "Змінити тип користувача",
            "grantAdminConfirm": "Надати цьому користувачу права адміністратора? Він зможе використовувати інструменти адміністрування та керувати обліковими записами.",
            "demoteAdminConfirm": "Змінити тип цього користувача з Admin на {{type}}? Доступ до адмін-зони буде втрачено.",
            "changeUserTypeConfirm": "Змінити тип цього користувача на {{type}}?",
            "clickChangeLevel": "Натисніть, щоб змінити рівень",
            "playerLevelAria": "Рівень гравця",
            "sortByRowNumber": "Сортувати за номером рядка",
            "sortBy": "Сортувати за {{key}}",
            "delete": "Видалити",
            "first": "Перша",
            "last": "Остання",
            "previous": "Попередня",
            "next": "Наступна",
            "previous5Pages": "Попередні 5 сторінок",
            "next5Pages": "Наступні 5 сторінок",
            "previous10Pages": "Попередні 10 сторінок",
            "next10Pages": "Наступні 10 сторінок",
            "userTypeAdmin": "Адмін",
            "userTypePartner": "Партнер",
            "userTypeMember": "Учасник",
            "generateTitle": "Генерація дебютної книги та станів",
            "backToAdmin": "← Назад до адміністрування",
            "generateIntro": "Повторно відтворює всі PGN-файли з папки менеджера партій сервера у колекцію State MongoDB або у рядкову дебютну книгу (data/opening-book-lines.txt). Оберіть ціль і натисніть «Почати генерацію» — нічого не запускається, доки ви цього не зробите.",
            "target": "Ціль",
            "targetMongo": "MongoDB — додати рядки до колекції State",
            "targetBook": "Файл ліній — записати дебютну книгу (opening-book-lines.txt)",
            "startGeneration": "Почати генерацію",
            "stop": "Зупинити",
            "idle": "Очікування.",
            "starting": "Запуск…",
            "running": "Виконується ({{mode}})…",
            "readingFiles": "Читання файлів: {{count}}…",
            "replayingGames": "Відтворення партій: {{count}}…",
            "writingOpeningBook": "Запис дебютної книги…",
            "readingPgn": "Читання PGN {{index}} / {{total}} ({{games}} партій)",
            "replayGameProgress": "Відтворення партії {{current}} / {{total}} (успішно завершено: {{completed}})",
            "stopped": "Зупинено.",
            "bookUnchanged": "Існуючу дебютну книгу не змінено.",
            "bookLinesInFile": "{{count}} ліній партій у {{file}}.",
            "cancelledBeforeRead": "Скасовано до читання PGN.",
            "cancelledAfterRead": "Скасовано після читання; відтворення пропущено (нічого не записано).",
            "mongoGamesSaved": "Для {{count}} партій збережено нові рядки станів.",
            "doneBook": "Готово. {{count}} ліній партій → {{file}}",
            "doneBookFileOnly": "Готово. {{file}}",
            "doneMongo": "Готово. Колекцію State MongoDB оновлено{{detail}}.",
            "doneMongoDetail": " (успішно відтворено партій: {{count}})",
            "errorPrefix": "Помилка: {{message}}",
            "unknownError": "Невідома",
            "connectionClosed": "З'єднання закрито (перевірте журнали сервера або спробуйте знову).",
            "openingBookDefault": "дебютна книга"
        },
        "playNow": {
            "title": "Нова партія",
            "startTitle": "Розпочати нову партію",
            "playingColor": "Колір",
            "timeMin": "Час (хв)",
            "difficulty": "Складність (1–5)",
            "mousePreference": "Керування мишею",
            "drag": "Перетягувати",
            "doubleClick": "Подвійний клік",
            "showAvailableMoves": "Показувати можливі ходи",
            "private": "Приватна",
            "playComputer": "Грати з комп'ютером",
            "browseAll": "Переглянути все",
            "yourHistory": "Ваша історія",
            "fullList": "Повний список",
            "gameLibrary": "Бібліотека партій",
            "openLibrarySearch": "Відкрити пошук у бібліотеці",
            "brain3": "Brain 3",
            "brain2": "Brain 2"
        },
        "activeGamesList": {
            "title": "Активні партії",
            "tagline": "Усі партії, що тривають",
            "liveGames": "Живі партії",
            "game": "Партія",
            "started": "Розпочато"
        },
        "list": {
            "title": "Усі партії",
            "action": "Дія"
        },
        "searchPage": {
            "title": "Пошук:",
            "tagline": "Знайдіть партії в архіві PGN",
            "results": "Результати",
            "resultsCount": "Результатів: {{count}}",
            "noResults": "Немає партій, що відповідають запиту",
            "button": "Шукати",
            "resultsFound": "Знайдено результатів: {{count}}",
            "first": "Перша",
            "last": "Остання",
            "previous": "Попередня",
            "next": "Наступна",
            "previous5Pages": "Попередні 5 сторінок",
            "next5Pages": "Наступні 5 сторінок",
            "previous10Pages": "Попередні 10 сторінок",
            "next10Pages": "Наступні 10 сторінок"
        },
        "game": {
            "moves": "Ходи",
            "white": "Білі",
            "black": "Чорні",
            "resign": "Здатися",
            "draw": "Нічия",
            "undo": "Скасувати",
            "flip": "Перевернути",
            "practice": "Тренування"
        },
        "mobileWelcome": {
            "title": "Головна — Шахи",
            "play": "Грати",
            "library": "Бібліотека",
            "friends": "Друзі"
        },
        "mobileGame": {
            "title": "Партія",
            "moves": "Ходи",
            "resign": "Здатися"
        }
    },
    "desktop": {
        "error": {
            "title": "Щось пішло не так",
            "body": "Сталася помилка.",
            "back": "На головну"
        },
        "chrome": {
            "preferences": "Налаштування",
            "display": "Вигляд",
            "gameplay": "Ігровий процес",
            "pieceSet": "Набір фігур",
            "boardTheme": "Тема дошки",
            "themeBlue": "Синя",
            "themeDark": "Темна",
            "customizeTheme": "Налаштувати тему…",
            "builtInThemesAria": "Вбудовані теми",
            "savedCustomThemesAria": "Збережені користувацькі теми",
            "pieceSetsAria": "Набори фігур",
            "homeAria": "Головна Shmerling Chess"
        },
        "prefs": {
            "language": "Мова",
            "languageHebrew": "עברית",
            "languageEnglish": "English",
            "languageJapanese": "日本語",
            "languageFrench": "Français",
            "languageGerman": "Deutsch",
            "languageChinese": "简体中文",
            "languageArabic": "العربية",
            "languageHindi": "हिन्दी",
            "languageSpanish": "Español",
            "languageRussian": "Русский",
            "languageUkrainian": "Українська",
            "languageNorwegian": "Norsk",
            "mouseControl": "Керування мишею",
            "thinkingTime": "Час обдумування",
            "thinkingTimeAria": "Час обдумування в секундах",
            "immediateResign": "Миттєва здача",
            "secondsOption": "{{count}} с",
            "enterFullScreen": "На весь екран",
            "exitFullScreen": "Вийти з повноекранного режиму",
            "fullScreenUnavailable": "Повноекранний режим недоступний у цьому браузері."
        },
        "gameRun": {
            "yourColor": "Ваш колір",
            "engine": "Рушій",
            "thinkTime": "Час обдумування (секунди)",
            "thinkTimeAria": "Час обдумування рушія в секундах",
            "play": "Грати",
            "nextMove": "Наступний хід",
            "computer": "Комп'ютер",
            "computerColorHint": "Який колір грає комп'ютер — ви граєте іншою стороною"
        },
        "brainConfig": {
            "title": "Налаштування рушія",
            "save": "Зберегти",
            "reset": "Скинути",
            "saved": "Налаштування збережено",
            "failedSave": "Не вдалося зберегти налаштування",
            "brainLabel": "Рушій",
            "loading": "Завантаження…",
            "failedLoad": "Не вдалося завантажити налаштування рушія.",
            "discardSwitchConfirm": "Скасувати незбережені зміни та переключити версію рушія?",
            "discard": "Скасувати",
            "pieceScores": "Оцінка фігур",
            "specialEvaluations": "Спеціальні оцінки",
            "gamePhase": "Фаза партії",
            "pawnFilesOpeningMid": "Вертикалі пішаків (дебют / мітельшпіль)",
            "pawnFilesEndGame": "Вертикалі пішаків (ендшпіль)"
        },
        "customTheme": {
            "title": "Користувацька тема",
            "name": "Назва теми",
            "save": "Зберегти",
            "delete": "Видалити",
            "saved": "Збережено",
            "searchProperties": "Пошук властивостей",
            "filterPlaceholder": "Фільтр за назвою властивості…",
            "namePlaceholder": "Моя тема",
            "resetPreset": "Скинути до поточного пресету",
            "couldNotSave": "Не вдалося зберегти тему. Спробуйте знову.",
            "untitled": "Без назви",
            "defaultName": "Користувацька тема"
        },
        "positionSetup": {
            "clearBoard": "Очистити дошку",
            "startingPosition": "Початкова позиція",
            "flipBoard": "Перевернути дошку",
            "eraser": "Гумка",
            "selectAndMove": "Вибір і переміщення",
            "defaultStartingPosition": "Стандартна початкова позиція",
            "savePosition": "Зберегти позицію",
            "saveAsNewPosition": "Зберегти як нову позицію",
            "validatePosition": "Перевірити позицію",
            "positionFlags": "Прапорці позиції",
            "turn": "Хід",
            "flagCheck": "Шах",
            "flagCheckmate": "Мат",
            "flagDraw": "Нічия",
            "flagWhiteKingMoved": "Білий король ходив",
            "flagBlackKingMoved": "Чорний король ходив",
            "flagWhiteKingsideRookMoved": "Біла королівська тура ходила",
            "flagWhiteQueensideRookMoved": "Біла ферзева тура ходила",
            "flagBlackKingsideRookMoved": "Чорна королівська тура ходила",
            "flagBlackQueensideRookMoved": "Чорна ферзева тура ходила"
        }
    },
    "mobile": {
        "drawOfferTitle": "Пропозиція нічиєї",
        "drawOfferMessage": "Суперник запропонував нічию. Прийняти?",
        "rematchTitle": "Реванш",
        "rematchMessage": "Суперник запропонував реванш. Прийняти?",
        "gameId": "ID партії: {{id}}",
        "drawOfferAgree": "Суперник запропонував нічию, погодитися?",
        "rematchOfferAgree": "Суперник запропонував реванш, погодитися?",
        "newGameWatchFromHome": "Розпочато нову партію — перейдіть на головну, щоб переглянути."
    }
};
    if (typeof module === "object" && module && module.exports) {
        module.exports = ukExtra;
    } else {
        global.ShmerlingStringsUkExtra = ukExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
