/**
 * Ukrainian string catalog — mirrors src/strings/en.js structure with Ukrainian values.
 */
(function (global) {
    "use strict";

    const uk = {
        common: {
            white: "Білі",
            black: "Чорні",
            draw: "Нічия",
            winner: "Переможець",
            engine: "Рушій",
            ok: "OK",
            cancel: "Скасувати",
            confirm: "Підтвердити",
            yes: "Так",
            no: "Ні",
            notice: "Повідомлення",
            input: "Введення",
            start: "Почати",
            collapse: "Згорнути",
            expand: "Розгорнути",
            delete: "Видалити",
            rename: "Перейменувати",
            save: "Зберегти",
            aPlayer: "Гравець",
            pleaseEnterValue: "Будь ласка, введіть значення.",
        },
        play: {
            appTitle: "Shmerling Chess",
            shell: {
                gameActions: "Дії в партії",
                playersAndClocks: "Гравці та годинники",
                whitePlayerClock: "Годинник білих",
                blackPlayerClock: "Годинник чорних",
                startFromLoadedPosition: "Почати партію з завантаженої позиції",
                moves: "Ходи",
                expandMovesPanel: "Розгорнути панель ходів",
                expandMoves: "Розгорнути ходи",
                collapseMovesPanel: "Згорнути панель ходів",
                reviewNavigation: "Навігація перегляду",
                positionSetup: "Редагування позиції",
                pieces: "Фігури",
                collapsePiecesPanel: "Згорнути панель фігур",
                brainConfiguration: "Налаштування рушія",
                configuration: "Налаштування",
                collapseConfigurationPanel: "Згорнути панель налаштувань",
                games: "Партії",
                expandGamesPanel: "Розгорнути панель партій",
                expandGames: "Розгорнути партії",
                collapseGamesPanel: "Згорнути панель партій",
                savedListFilter: "Фільтр збереженого списку",
                positions: "Позиції",
                gameStatus: "Статус партії",
                capturedPieces: "Збиті фігури",
            },
            sessionMode: {
                play: "Режим гри",
                positionSetup: "Редагування позиції",
                configuration: "Режим налаштувань",
                playback: "Режим відтворення",
                review: "Режим перегляду",
                watch: "Режим перегляду онлайн",
                practice: "Режим тренування",
            },
            status: {
                chooseNewGameOrSetup:
                    "Оберіть «Нова партія» або «Редагування позиції» на бічній панелі",
                chooseNewGame: "Оберіть «Нова партія» на бічній панелі",
                setMoveColorEngineThinkTime:
                    "Установіть хід, колір, рушій і час обдумування у заголовку, потім натисніть «Грати»",
                gameOver: "Партія завершена",
                gameInProgress: "Партія триває",
                boardLoading: "Дошка ще завантажується…",
                boardNotReady: "Дошка ще не готова. Зачекайте і спробуйте знову.",
                leaveOnlineBeforeConfiguration:
                    "Вийдіть з онлайн-партії перед відкриттям налаштувань",
                configurationNotInPractice:
                    "Налаштування недоступні в режимі тренування",
                configurationModeEdit:
                    "Режим налаштувань — редагуйте значення та збережіть",
                selectSavedOrSetup:
                    "Спочатку оберіть збережену партію або налаштуйте позицію на дошці",
                gameAlreadyInProgress: "Партія вже триває",
                yourMove: "Ваш хід",
                engineToMove: "Хід рушія…",
                leaveOnlineBeforePositionSetup:
                    "Вийдіть з онлайн-партії перед відкриттям редагування позиції",
                positionSetupNotInPractice:
                    "Редагування позиції недоступне в режимі тренування",
                positionSetupPlacePieces:
                    "Редагування позиції — розставте фігури на дошці",
                drawWithReason: "Нічия — {{reason}}",
                checkmateWins: "Мат — перемагають {{winner}}",
                check: "Шах",
                waitBeforeEvaluate:
                    "Дочекайтеся завершення поточного ходу перед оцінкою",
                evaluationUnavailable:
                    "Оцінка позиції недоступна. Перезапустіть застосунок Shmerling Chess.",
                evaluatingPosition: "Оцінка позиції…",
                evaluationFailed: "Не вдалося оцінити позицію",
                evaluationLine: "Оцінка (хід {{side}}): {{score}}",
                checkmate: "Мат",
                drawZero: "Нічия (0)",
                totalLabel: "Разом: {{value}}",
                openFolderDesktopOnly:
                    "Відкриття папки доступне лише в настільному застосунку",
                couldNotOpenGamesLogFolder: "Не вдалося відкрити папку журналу партій",
                positionValid: "Позиція коректна",
                playingFromCustomPosition: "Гра з користувацької позиції",
                nothingToSave: "Немає чого зберігати",
                positionSaved: "Позицію збережено",
                couldNotSavePosition: "Не вдалося зберегти позицію",
                savedPositionNotFound: "Збережену позицію не знайдено",
                positionUpdated: "Позицію оновлено",
                couldNotUpdatePosition: "Не вдалося оновити позицію",
                nameCannotBeEmpty: "Назва не може бути порожньою",
                gameRenamed: "Партію перейменовано",
                couldNotRenameGame: "Не вдалося перейменувати партію",
                deletedCount: "Видалено елементів: {{count}}",
                couldNotDeleteSelected: "Не вдалося видалити обрані елементи",
                couldNotLoadSavedGame: "Не вдалося завантажити збережену партію",
                editingPositionSaveBookmark:
                    "Редагування позиції — збережіть, щоб оновити цю закладку",
                couldNotOpenPositionForEditing:
                    "Не вдалося відкрити позицію для редагування",
                gameSaved: "Партію збережено",
                couldNotSaveGame: "Не вдалося зберегти партію",
                engineMoveNotApplied: "Не вдалося застосувати хід рушія",
                engineCouldNotFindMove: "Рушій не знайшов хід",
                engineError: "Помилка рушія",
                engineThinking: "Рушій обдумує…",
                sessionError: "Помилка сесії",
                timesUpLost: "Час вичерпано! {{loser}} програли",
                drawOfferTitle: "Пропозиція нічиєї",
                drawOfferMessage: "Суперник запропонував нічию. Прийняти?",
                rematchTitle: "Реванш",
                playerDisconnectedWaiting:
                    "{{who}} відключився — очікування повторного підключення ({{countdown}})",
                opponentDisconnectedCountdown:
                    "Суперник відключився — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "Партію скасовано — час на повторне підключення минув, ходів не було зроблено.",
                playerFailedToReconnectWins:
                    "{{loser}} не вдалося перепідключитися — перемагають {{winner}}",
                gameOverOpponentFailedReconnect:
                    "Партія завершена — суперник не зміг перепідключитися.",
                couldNotStartRematch: "Не вдалося розпочати реванш",
                rematchStarted: "Реванш розпочато",
                gameCancelled: "Партію скасовано",
                gameCancelledWithDetail: "Партію скасовано — {{detail}}",
                resignFailed: "Не вдалося здатися",
                gameResumedYourMove: "Партію відновлено — ваш хід",
                practiceNotAvailable: "Режим тренування недоступний",
                couldNotJoinOnPlay: "Не вдалося приєднатися до цієї партії на /play",
                practiceDebugNotAvailable:
                    "Тренування / Debug недоступні для цього облікового запису",
                reviewRequiresWebApi: "Перегляд потребує веб-API",
                couldNotLoadReviewGame: "Не вдалося завантажити партію для перегляду",
                notReviewGameLink: "Це посилання не веде до партії для перегляду",
                onlineRequiresWebApi: "Онлайн-гра потребує веб-API",
                couldNotLoadOnlineGame: "Не вдалося завантажити онлайн-партію",
                notOnlineGameOnPlay: "Це посилання не веде до онлайн-партії на /play",
                watchingLiveGame: "Перегляд живої партії",
                waitingForOpponentToJoin: "Очікування суперника…",
                waitingForOpponent: "Очікування суперника…",
                onlineGameConnected: "Онлайн-партія — підключено",
                gameDeleted: "Партію видалено",
                itemsDeleted: "Видалено елементів: {{count}}",
                choosePromotionPiece: "Оберіть фігуру для перетворення",
                invalidPromotionPiece: "Некоректна фігура для перетворення",
                drawOfferNotAvailable: "Пропозиція нічиєї зараз недоступна",
            },
            drawReasons: {
                stalemate: "Пат",
                fiftyMoves: "50 ходів",
                insufficientMaterial: "Недостатньо матеріалу",
                threefoldRepetition: "Триразове повторення",
                drawOfferAccepted: "Пропозицію нічиєї від {{by}} прийнято",
            },
            actions: {
                newGame: "Нова партія",
                resign: "Здатися",
                draw: "Нічия",
                undo: "Скасувати",
                redo: "Повторити",
                lastMove: "Останній хід",
                positionSetup: "Редагування позиції",
                config: "Налаштування",
                flip: "Перевернути",
                save: "Зберегти",
                exit: "Вийти",
                loadToStart: "Завантажити для старту",
                editPosition: "Редагувати позицію",
            },
            savedGames: {
                defaultName: "Збережена партія",
                nameAriaLabel: "Назва збереженої партії",
                showDetails: "Показати деталі",
                detailsAriaLabel: "Деталі збереженої партії",
                editPosition: "Редагувати позицію",
                deleteSavedGame: "Видалити збережену партію",
                renameSavedGame: "Перейменувати збережену партію",
                noSavedPositions: "Ще немає збережених позицій.",
                noSavedGames: "Ще немає збережених партій.",
                nextMoveDash: "Наступний хід: —",
                nextMove: "Наступний хід: {{side}}",
                player: "Гравець",
                savedAt: "Збережено: {{when}}",
                gameId: "ID партії: {{id}}",
                playersVs: "{{white}} проти {{black}}",
            },
            reviewNav: {
                start: "Початок",
                back: "Назад",
                play: "Грати",
                pause: "Пауза",
                forward: "Вперед",
                end: "Кінець",
            },
            newGameDialog: {
                title: "Нова партія проти ШІ",
                yourColor: "Ваш колір",
                engine: "Рушій",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "Час на сторону (хвилини)",
                allowUndo: "Дозволити скасування ходу",
            },
            prompts: {
                positionName: "Назва позиції",
                savePositionAs: "Зберегти позицію як",
            },
            dialogs: {
                resignTitle: "Здатися в цій партії?",
                resignBody: "Ви програєте партію.",
                leaveTitle: "Вийти з партії?",
                leaveBody: "Вашу партію буде здано.",
                areYouSure: "Ви впевнені?",
                discardUnsavedBrainConfig:
                    "Скасувати незбережені зміни налаштувань рушія?",
                accept: "Прийняти",
                decline: "Відхилити",
                saveAs: "Зберегти як",
                savePosition: "Зберегти позицію",
                invalidPosition: "Некоректна позиція",
                rematchChooseColor: "Оберіть свій колір для реваншу:",
                rematchOfferAgree: "Суперник запропонував реванш. Погодитися?",
                rematchColorPreference:
                    "Суперник хоче грати {{offerer}}. Ви гратимете {{you}}. Погодитися?",
            },
        },
        session: {
            engineThinking: "Рушій обдумує…",
            engineCouldNotFindMove: "Рушій не знайшов хід",
            engineError: "Помилка рушія",
            positionSetupPlacePieces: "Редагування позиції — розставте фігури на дошці",
            configurationModeEdit: "Режим налаштувань — редагуйте значення та збережіть",
            practiceBothSides: "Тренування — обидві сторони",
            opponentDisconnected: "Суперник відключився",
            opponentRejoined: "Суперник повернувся",
            playerRejoined: "{{name}} повернувся",
            drawOfferSent: "Пропозицію нічиєї надіслано",
            drawOfferDeclined: "Пропозицію нічиєї відхилено",
            rematchOfferSent: "Пропозицію реваншу надіслано",
            rematchOfferDeclined: "Пропозицію реваншу відхилено",
            drawAgreed: "Нічию погоджено",
            rematchAcceptedNoGameId: "Реванш прийнято, але немає ID нової партії",
            rematchOfferAccepted: "Пропозицію реваншу прийнято",
            gameOver: "Партія завершена",
            somethingWentWrong: "Щось пішло не так",
            opponentResigned: "Суперник здався",
            opponentLeftGame: "Суперник покинув партію",
            opponentFailedToReconnect: "Суперник не зміг перепідключитися",
            gameCancelled: "Партію скасовано",
            gameCancelledWithDetail: "Партію скасовано — {{detail}}",
            waitingForOpponent: "Очікування суперника…",
            couldNotResolveWebSocketUrl: "Не вдалося визначити URL WebSocket",
            opponentJoined: "{{name}} приєднався",
            opponentDefault: "Суперник",
            connectionError: "Помилка з'єднання",
            playerDisconnectedWaitingRejoin:
                "{{name}} відключився — очікування повторного підключення",
            playerFailedToReconnectWins:
                "{{loser}} не вдалося перепідключитися — перемагають {{winner}}",
            watcherWaitingForReconnect: "Очікування повторного підключення гравця…",
        },
        site: {
            confirm: "Підтвердити",
            cancel: "Скасувати",
            notice: "Повідомлення",
            ok: "OK",
            home: "Головна",
            search: "Пошук",
            friends: "Друзі",
            groups: "Групи",
            debug: "Debug",
            account: "Обліковий запис",
            preferences: "Налаштування",
            administrate: "Адміністрування",
            logOut: "Вийти",
            logIn: "Увійти",
            admin: "Адмін",
            homeAria: "Головна",
        },
        validation: {
            validEmail: "Будь ласка, введіть коректну адресу електронної пошти",
            passwordsMustMatch: "Поля пароля мають збігатися.",
            chooseUsername: "Будь ласка, оберіть ім'я користувача",
            usernameNotAvailable: "Це ім'я користувача недоступне",
            passwordNoWhitespace: "Пароль не повинен містити пробілів.",
            passwordUppercase: "Пароль має містити принаймні одну велику літеру.",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = uk;
    } else {
        global.ShmerlingStringsUk = uk;
    }
})(typeof window !== "undefined" ? window : globalThis);
