/**
 * Simplified Chinese supplemental string catalog — mirrors src/strings/en-extra.js.
 */
(function (global) {
    "use strict";

    const zhExtra = {
        validation: {
            passwordLowercase: "密码至少包含一个小写字母。",
            passwordDigit: "密码至少包含一个数字。",
            passwordSymbol: "密码至少包含一个特殊符号。",
            passwordLength: "密码长度须为 8–30 个字符。",
            noHtml: "{{label}} 不能包含 HTML。",
            position: {
                headerSave: "无法保存此局面：\n\n",
                headerPlay: "无法从此局面开始对局：\n\n",
                headerUse: "无法使用此局面：\n\n",
                headerSaveBookmark: "无法保存此书签：\n\n",
                headerAddBookmark: "无法添加此书签：\n\n",
                boardUnreadable: "无法读取棋盘。请在棋盘加载完成后重试。",
                whiteKingNone: "棋盘上必须有且仅有一个白王。未找到白王。",
                whiteKingCount: "棋盘上必须有且仅有一个白王。找到 {{count}} 个白王。",
                blackKingNone: "棋盘上必须有且仅有一个黑王。未找到黑王。",
                blackKingCount: "棋盘上必须有且仅有一个黑王。找到 {{count}} 个黑王。",
                kingsAdjacent: "两王不能位于相邻格（含斜邻）。",
                sideInCheck: "轮到 {{mover}} 走棋，但 {{king}} 的王已处于被将军状态。行棋方不能同时将军 — 请更改行棋方或移动棋子。",
                drawInsufficientKings: "此局面因子力不足而和棋（王对王）。请添加棋子以使将死仍有可能。",
                drawInsufficientMinor: "此局面因子力不足而和棋（王加象或马对单王）。请添加棋子以使将死仍有可能。",
                drawBishopsSameColor: "此局面因子力不足而和棋（同色象对同色象）。请添加棋子以使将死仍有可能。",
                tooManyQueens: "{{color}} 有 {{count}} 个后；每方最多 9 个。",
                tooManyRooks: "{{color}} 有 {{count}} 个车；每方最多 10 个。",
                tooManyBishops: "{{color}} 有 {{count}} 个象；每方最多 10 个。",
                tooManyKnights: "{{color}} 有 {{count}} 个马；每方最多 10 个。",
                tooManyPawns: "{{color}} 有 {{count}} 个兵；每方最多 8 个。"
            }
        },
        auth: {
            whoAreYou: "你是谁？",
            enterPassword: "请输入密码",
            sorry: "抱歉",
            continue: "继续",
            usernameField: "用户名",
            passwordField: "密码",
            wrongCredentials: "用户名或密码错误",
            userAdded: "用户添加成功",
            couldNotSaveBookmark: "无法保存书签",
            invalidUserId: "无效的用户 ID",
            generationJobRunning: "已有其他生成任务正在运行…",
            listingPgnFiles: "正在列出 PGN 文件…"
        },
        classic: {
            loadGame: "加载对局",
            load: "加载",
            enterGameState: "在此粘贴对局状态…",
            rematch: "重赛",
            drawOffer: "和棋提议",
            lastMove: "上一步",
            bookmarks: "书签",
            bookmarkAlertTitle: "书签局面",
            promotion: "升变！",
            check: "将军",
            checkmateWins: "将死！{{winner}} 胜！",
            drawReason: "和棋！{{reason}}",
            opponentDisconnected: "对手已断开连接",
            opponentResignedWins: "对手认输，{{winner}} 胜",
            somethingWentWrong: "出现问题",
            playerRejoined: "{{name}} 已重新加入",
            aPlayerRejoined: "某棋手已重新加入",
            opponentRejoined: "对手已重新加入",
            rematchOfferAccepted: "已接受重赛提议",
            rematchOfferDeclined: "已拒绝重赛提议",
            sideOffersDraw: "{{side}} 提议和棋",
            drawOfferDeclined: "和棋提议被拒绝",
            watcherWatching: "{{name}} 正在观战",
            drawOfferSent: "已发送和棋提议",
            rematchOfferSent: "已发送重赛提议",
            newGameStarted: "新对局已开始",
            gameOver: "对局结束",
            gameCancelled: "对局已取消",
            youResignedWins: "您已认输，{{winner}} 胜",
            movesCopied: "棋谱已复制到剪贴板！",
            failedCopyMoves: "复制棋谱失败",
            failedLoadBrainConfig: "加载 Brain 配置失败。",
            failedSaveBrainConfig: "保存 Brain 配置失败。",
            offerDrawConfirm: "提议和棋？",
            drawOfferAccept: "对手提议和棋，是否接受？",
            rematchOfferAccept: "对手提议重赛，是否同意？",
            rematchOfferAcceptWithTime: "对手提出重赛（每方{{minutes}}分钟）。同意？",
            rematchTimePrompt: "复赛每方分钟数：",
            connectionLost: "连接丢失 - 移动未到达服务器",
            confirmExitGame: "确定要退出对局吗？",
            mobileResign: "认输",
            mobileRematch: "重赛",
            mobileDraw: "和棋",
            mobileFlip: "翻转",
            mobileLastMove: "上一步",
            mobileMovesList: "棋谱列表",
            researchToolbox: "工具箱",
            researchBrainConfig: "Brain 配置",
            researchSave: "保存",
            researchDiscard: "放弃",
            researchEditMode: "编辑模式",
            researchRun: "运行",
            researchProperty: "属性",
            researchValue: "值",
            playerOnline: "在线",
            playerDisconnectedStatus: "已断开",
            playerOffline: "离线",
            humanVsComputer: "人对电脑",
            newGameTwoPlayers: "双人对局",
            settings: "设置",
            help: "帮助",
            drawOffersNotVsEngine: "与引擎对局时无法提议和棋。",
            failedStartFromBookmark: "无法从书签开始对局。",
            resignConfirm: "认输？",
            areYouSure: "确定吗？",
            gameOverOpponentFailedReconnectWinsClassic: "对局结束 — 对手未能重连。{{winner}} 胜。",
            reconnectTimeoutNoMoves: "重连超时且未走任何棋。",
            waitingOpponentRejoin: "等待对手重新加入",
            timeoutOneSec: "超时：1 秒",
            timeoutSecs: "超时：{{count}} 秒",
            whitePieceAlt: "白棋",
            blackPieceAlt: "黑棋",
            eraserTitle: "橡皮擦",
            eraserAria: "橡皮擦 — 从格子上移除棋子",
            selectTitle: "选择",
            selectAria: "选择 — 拖动棋子以移动",
            resetAria: "重置 — 清除所有棋子",
            defaultPositionAria: "初始局面 — 设置标准开局",
            loading: "加载中…",
            engineLabel: "引擎"
        },
        site: {
            home: "首页",
            search: "搜索",
            friends: "好友",
            groups: "群组",
            debug: "调试",
            account: "账户",
            preferences: "偏好设置",
            administrate: "管理",
            logOut: "退出登录",
            logIn: "登录",
            admin: "管理员",
            homeAria: "首页",
            confirm: "确认",
            cancel: "取消",
            notice: "提示",
            ok: "确定",
            footer: {
                logoAlt: "Shmerling Chess",
                navAria: "页脚",
                privacy: "隐私政策",
                terms: "使用条款",
                contact: "联系我们",
                copyright: "© {{year}} Shmerling Chess。保留所有权利。",
                lastUpdated: "最后更新：{{date}}",
                privacyTitle: "隐私政策",
                privacyLead: "Shmerling Chess 如何处理账户与对局信息。",
                privacyBody: "我们使用您的账户信息来运营服务、保存对局与偏好并改进产品。我们不会出售个人信息。完整政策文本将在此发布。",
                termsTitle: "使用条款",
                termsLead: "使用 Shmerling Chess 的规则。",
                termsBody: "使用 Shmerling Chess 即表示您同意公平对弈、尊重其他玩家，并仅将服务用于个人国际象棋对局。完整条款将在此发布。",
                contactTitle: "联系我们",
                contactLead: "联系 Shmerling Chess 团队。",
                contactBody: "支持与隐私问题的联系方式将在此发布。",
                accessibility: "Accessibility",
                accessibilityTitle: "Accessibility statement",
                accessibilityLead: "Shmerling Chess aims to meet WCAG 2.1 Level AA for web chrome used in the United States (ADA / Section 508), Israel (IS 5568), and the European Union (European Accessibility Act / EN 301 549)."
            },
            username: "用户名：",
            password: "密码：",
            login: "登录",
            register: {
                submit: "注册",
                confirmPassword: "确认密码：",
                playerLevel: "棋手等级：",
                rookie: "新手",
                skilled: "熟练",
                elite: "精英",
                grandMaster: "特级大师"
            },
            email: "电子邮箱：",
            welcome: {
                greeting: "欢迎回来",
                tagline: "您的棋步在等待",
                playNow: "立即对局！",
                activeGames: "进行中的对局",
                live: "直播",
                showAll: "显示全部",
                viewAllActive: "查看所有进行中的对局",
                mostRecent: "最新优先",
                noGamesNow: "当前没有对局",
                myGames: "我的对局",
                viewAllGames: "查看全部对局",
                recentCompleted: "您最近完成的对局",
                noCompleted: "尚无已完成的对局",
                activeGamesAria: "进行中的对局",
                inviteOnlineFriend: "邀请在线好友对局",
                friendsPageTitle: "好友页面",
                manageFriends: "管理",
                colFriend: "好友",
                colStatus: "状态",
                findPlayers: "查找棋手",
                waitingForResponse: "等待回复",
                inviteSentSuffix: "（已发送邀请）",
                sortByRowNumber: "按行号排序",
                sortBy: "按 {{key}} 排序"
            },
            gameList: {
                date: "日期",
                time: "时间",
                result: "结果",
                reason: "原因",
                type: "类型",
                status: "状态",
                event: "赛事",
                site: "站点",
                round: "轮次"
            },
            loginPage: {
                title: "登录"
            },
            error: {
                title: "出现问题",
                body: "发生错误。",
                back: "返回首页"
            },
            log: {
                title: "服务器日志",
                clear: "清空视图",
                latest: "最新",
                waiting: "等待服务器日志输出…"
            },
            activeGames: {
                moves: "步数",
                turn: "行棋方",
                status: "状态",
                inProgress: "进行中",
                onHold: "暂停",
                vs: " 对 ",
                minutesAgo: "{{count}} 分钟前",
                oneMinuteAgo: "1 分钟前",
                justStarted: "刚刚开始",
                notStarted: "未开始",
                startedTooltip: "开始于：{{when}}",
                playersVs: "{{white}} 对 {{black}}"
            },
            friendsPage: {
                title: "好友",
                tagline: "寻找新棋友",
                myFriends: "我的好友",
                noFriendsYet: "尚无好友",
                findPlayers: "查找棋手",
                searchByUsername: "按用户名搜索",
                searchPlaceholder: "输入以搜索…",
                enterCharToSearch: "请至少输入一个字符进行搜索",
                noMatchingUsers: "没有匹配的用户",
                playing: "对局中",
                pendingFriendshipOffer: "待处理的好友请求",
                joining: "加入中",
                rejoin: "重新加入",
                friendRequest: "好友请求",
                wantsToBeFriends: "（想成为好友）",
                pendingOfferSuffix: "（待处理的好友请求）",
                waitingFriendRespond: "等待好友回复",
                cancelBeforeRemove: "删除此好友前请先取消对局邀请",
                friendsTag: "好友",
                offerReceivedTag: "收到请求 — 见「我的好友」",
                addFriend: "添加好友",
                withdraw: "撤回",
                requestFailed: "请求失败",
                removeFriendConfirm: "从列表中删除此好友？",
                removeFriendTitle: "删除好友",
                withdrawOfferConfirm: "撤回此好友请求？",
                withdrawOfferTitle: "撤回请求",
                couldNotAccept: "无法接受",
                couldNotDecline: "无法拒绝",
                couldNotRemove: "无法删除",
                couldNotCancelInvite: "无法取消邀请",
                couldNotWithdraw: "无法撤回",
                couldNotSendInvite: "无法发送邀请",
                couldNotSendGameInvite: "无法发送对局邀请",
                gameInvite: "对局邀请",
                gameInvitationsAria: "对局邀请",
                gameInvitationAria: "对局邀请",
                chessInviteTitle: "国际象棋邀请",
                wantsToPlayAsBlack: "{{name}} 想与您对局。您执黑。",
                wantsToPlayYouWhite: "{{name}}想玩。你扮演白方。",
                aFriend: "某好友",
                youPlayAsWhite: "您执白",
                youPlayAsBlack: "您执黑",
                establishingGame: "正在建立对局…",
                yourOpponent: "您的对手",
                declinedYourInvite: "{{name}} 拒绝了您的对局邀请。",
                cancelInvite: "取消邀请",
                accept: "接受",
                decline: "拒绝",
                invite: "邀请",
                inviteSettingsTitle: "邀请设置",
                inviteSettingsFor: "邀请{{name}}",
                inviteTimeMinutes: "每边时间（分钟）",
                inviteYourColor: "你的颜色",
                inviteColorWhite: "白色的",
                inviteColorBlack: "黑色的",
                inviteColorRandom: "随机的",
                inviteFriendly: "友谊赛",
                inviteFriendlyHint: "取消选中稍后计入 ELO（评级比赛）。",
                invitePrivate: "私人游戏",
                invitePrivateHint: "在公共活跃游戏大厅中隐藏此游戏。",
                inviteSaveDefaults: "保存默认值",
                inviteOfferTime: "{{minutes}}分钟",
                inviteOfferFriendly: "友好的",
                inviteOfferRated: "额定",
                inviteOfferPrivate: "私人的",
                remove: "删除",
                offerSent: "已发送",
                pending: "待处理",
                online: "在线",
                offline: "离线"
            },
            adminPage: {
                title: "管理",
                tagline: "用户、游戏、引擎、开书和机器人决斗",
                panelTitle: "管理控制台",
                users: "用户",
                generate: "生成",
                games: "对局",
                engines: "引擎",
                states: "状态",
                openingBook: "开本",
                bots: "机器人",
                addUser: "添加用户",
                sectionsAria: "管理分区",
                openingBookLabel: "开局库：",
                openingBookStatusTitle: "当前开本",
                openingBookFile: "文件",
                openingBookExists: "地位",
                openingBookExistsYes: "展示",
                openingBookExistsNo: "丢失的",
                openingBookLines: "游戏线",
                openingBookSize: "尺寸",
                openingBookModified: "最后修改时间",
                openingBookPgnSources: "PGN 来源",
                openingBookPgnCount: "{{count}} PGN 文件可用于重建",
                openingBookIntro: "从服务器的 PGN 文件夹重建基于行的开本 (data/opening-book-lines.txt)。使用下面的“生成开本”——按下它之前不会运行任何内容。",
                generateOpeningBook: "生成开本",
                botsIntro: "开始一场公共引擎对引擎游戏。会员可以作为观察者从 Home 上的 Active Games 打开它。",
                botsWhiteEngine: "白色发动机",
                botsBlackEngine: "黑色发动机",
                botsWhiteDifficulty: "难度（1-6）",
                botsBlackDifficulty: "难度（1-6）",
                botsSkillLevel: "技能 (0–20)",
                botsTimeMinutes: "时钟（分钟）",
                botsStart: "开始决斗",
                botsStarting: "决斗开始……",
                botsStarted: "决斗开始：{{white}} vs {{black}}。",
                botsWatchLink: "观看这场比赛",
                botsListedNote: "列在主页 → 其他用户的活跃游戏中。",
                botsStartFailed: "无法开始决斗。",
                botsStopped: "要求停止。",
                botsStopFailed: "无法阻止决斗。",
                gameLines: "对局线路",
                noGamesInDb: "数据库中尚无对局。",
                gamesPaginationAria: "对局分页",
                colNum: "#",
                colUsername: "用户名",
                colType: "类型",
                colEmail: "电子邮箱",
                colPassword: "密码",
                colLevel: "等级",
                colElo: "Elo",
                colJoined: "加入时间",
                colLastLogin: "上次登录",
                colActiveGames: "进行中对局",
                colFriends: "好友",
                colBookmarks: "书签",
                colId: "Id",
                colStatus: "状态",
                colName: "名称",
                colAvailable: "可用",
                colEnabled: "启用",
                colBackend: "后端",
                colCommand: "命令",
                colNotes: "备注",
                colNote: "备注",
                colAction: "操作",
                emptyUsers: "尚无用户。",
                emptyData: "尚无数据。",
                emptyEngines: "注册表中没有 Play 引擎。",
                emptyStates: "使用「生成」打开开局库与状态生成页面。",
                engineAvailableYes: "可用的",
                engineAvailableNo: "不可用",
                engineEnable: "使能够",
                engineDisable: "禁用",
                enginesLoadFailed: "无法加载引擎",
                enginesSaveFailed: "无法更新引擎",
                clickToEdit: "点击编辑",
                updateFailed: "更新失败",
                couldNotSave: "无法保存",
                setPassword: "设置密码",
                setPasswordTitle: "点击设置新密码（4–30 个字符）",
                passwordLengthInvalid: "密码长度须为 4–30 个字符。",
                invalidPassword: "无效密码",
                saved: "已保存",
                newPasswordPlaceholder: "新密码",
                clickChangeUserType: "点击更改用户类型",
                userTypeAria: "用户类型",
                changeUserTypeTitle: "更改用户类型",
                grantAdminConfirm: "授予此用户管理员权限？他们将可访问管理工具并管理账户。",
                demoteAdminConfirm: "将此用户从管理员改为 {{type}}？他们将失去管理区域访问权限。",
                changeUserTypeConfirm: "将此用户改为 {{type}}？",
                clickChangeLevel: "点击更改等级",
                playerLevelAria: "棋手等级",
                sortByRowNumber: "按行号排序",
                sortBy: "按 {{key}} 排序",
                delete: "删除",
                first: "首页",
                last: "末页",
                previous: "上一页",
                next: "下一页",
                previous5Pages: "向前 5 页",
                next5Pages: "向后 5 页",
                previous10Pages: "向前 10 页",
                next10Pages: "向后 10 页",
                userTypeAdmin: "管理员",
                userTypePartner: "合作伙伴",
                userTypeMember: "成员",
                generateTitle: "开局库与状态生成",
                backToAdmin: "← 返回管理",
                generateIntro: "将服务器对局管理文件夹下的所有 PGN 文件重播到 State Mongo 集合或基于行的开局库（data/opening-book-lines.txt）。选择目标后按「开始生成」— 在此之前不会执行任何操作。",
                target: "目标",
                targetMongo: "MongoDB — 向 State 集合追加行",
                targetBook: "线路文件 — 写入开局库（opening-book-lines.txt）",
                startGeneration: "开始生成",
                stop: "停止",
                idle: "空闲。",
                starting: "正在启动…",
                running: "运行中（{{mode}}）…",
                readingFiles: "正在读取 {{count}} 个文件…",
                replayingGames: "正在重播 {{count}} 局对局…",
                writingOpeningBook: "正在写入开局库…",
                readingPgn: "正在读取 PGN {{index}} / {{total}}（{{games}} 局）",
                replayGameProgress: "重播对局 {{current}} / {{total}}（成功完成：{{completed}}）",
                stopped: "已停止。",
                bookUnchanged: "现有开局库未作修改。",
                bookLinesInFile: "{{file}} 中有 {{count}} 条对局线路。",
                cancelledBeforeRead: "读取 PGN 前已取消。",
                cancelledAfterRead: "读取后已取消；跳过重播（未写入任何内容）。",
                mongoGamesSaved: "{{count}} 局对局已保存新的状态行。",
                doneBook: "完成。{{count}} 条对局线路 → {{file}}",
                doneBookFileOnly: "完成。{{file}}",
                doneMongo: "完成。MongoDB State 集合已更新{{detail}}。",
                doneMongoDetail: "（{{count}} 局重播成功）",
                errorPrefix: "错误：{{message}}",
                unknownError: "未知",
                connectionClosed: "连接已关闭（请查看服务器日志或重试）。",
                openingBookDefault: "开局库"
            },
            playNow: {
                title: "新对局",
                startTitle: "开始新对局",
                playingColor: "执棋颜色",
                timeMin: "时间（分钟）",
                difficulty: "难度（1–5）",
                mousePreference: "鼠标操作",
                drag: "拖动",
                doubleClick: "双击",
                showAvailableMoves: "显示可走步",
                private: "私人",
                privateHint: "私人对局不会显示在其他会员的进行中对局列表中。",
                playComputer: "对电脑",
                browseAll: "浏览全部",
                yourHistory: "您的历史",
                fullList: "完整列表",
                gameLibrary: "对局库",
                openLibrarySearch: "打开库搜索",
                brain3: "Brain 3",
                brain2: "Brain 2"
            },
            activeGamesList: {
                title: "进行中的对局",
                tagline: "所有进行中的对局",
                liveGames: "直播对局",
                game: "对局",
                started: "开始"
            },
            list: {
                title: "全部对局",
                tagline: "您已完成的游戏",
                allGames: "已完成的游戏",
                gamesCount: "{{count}}游戏",
                action: "操作"
            },
            searchPage: {
                title: "搜索：",
                tagline: "在 PGN 存档中查找对局",
                results: "结果",
                resultsCount: "{{count}} 条结果",
                noResults: "没有符合搜索条件的对局",
                button: "搜索",
                resultsFound: "找到 {{count}} 条结果：",
                first: "首页",
                last: "末页",
                previous: "上一页",
                next: "下一页",
                previous5Pages: "向前 5 页",
                next5Pages: "向后 5 页",
                previous10Pages: "向前 10 页",
                next10Pages: "向后 10 页"
            },
            game: {
                moves: "棋谱",
                white: "白",
                black: "黑",
                resign: "认输",
                draw: "和棋",
                undo: "悔棋",
                flip: "翻转",
                practice: "练习"
            },
            mobileWelcome: {
                title: "首页 — 国际象棋",
                play: "对局",
                library: "棋库",
                friends: "好友"
            },
            mobileGame: {
                title: "对局",
                moves: "棋谱",
                resign: "认输"
            },
            accessibility: {
                skipToMain: "Skip to main content",
                themeToggle: "Toggle color theme",
                chatInput: "Chat message",
                sendChat: "Send chat message",
                boardRegion: "Chessboard",
                pieceAlt: "{{color}} {{piece}}",
                squareLabel: "{{square}}{{piece}}",
                emptySquare: "empty",
                statementCommitmentHeading: "Our commitment",
                statementCommitmentBody: "We design Shmerling Chess so people can navigate accounts, friends, preferences, and game chrome with a keyboard and assistive technologies. We treat accessibility as an ongoing program aligned with WCAG 2.1 Level AA.",
                statementScopeHeading: "What this covers",
                statementScopeBody: "Covered today: document language and text direction, skip links, visible keyboard focus, labeled forms and dialogs with focus trapping, reduced-motion support, status live regions, and an accessibility statement. Play shell controls expose accessible names where implemented.",
                statementLimitsHeading: "Known limitations",
                statementLimitsBody: "The interactive chessboard is still progressing toward full keyboard and screen-reader parity (square-by-square navigation and complete spoken move alternatives). Some legacy click-only patterns may remain outside the Play shell. We document these limits while we close them.",
                statementContactHeading: "Feedback and requests",
                statementContactBody: "If you encounter an accessibility barrier, contact us through the Contact page and include the page URL, your browser or assistive technology, and a short description of the issue. We aim to respond and provide a reasonable alternative where needed.",
                statementStandardsHeading: "Standards reference",
                statementStandardsBody: "Target standard: Web Content Accessibility Guidelines (WCAG) 2.1 Level AA, which informs U.S. ADA / Section 508 expectations, Israeli Standard 5568, and EU EN 301 549 under the European Accessibility Act for applicable consumer services."
            }
        },
        desktop: {
            error: {
                title: "出现问题",
                body: "发生错误。",
                back: "返回首页"
            },
            chrome: {
                preferences: "偏好设置",
                closePreferences: "关闭偏好设置",
                display: "显示",
                gameplay: "对局",
                pieceSet: "棋子样式",
                boardTheme: "棋盘主题",
                theme: "主题",
                themeBlue: "蓝色",
                themeDark: "深色",
                customizeTheme: "自定义主题…",
                builtInThemesAria: "内置主题",
                savedCustomThemesAria: "已保存的自定义主题",
                pieceSetsAria: "棋子样式",
                homeAria: "Shmerling Chess 首页"
            },
            prefs: {
                language: "语言",
                languageHebrew: "עברית",
                languageEnglish: "English",
                languageJapanese: "日本語",
                languageFrench: "Français",
                languageGerman: "Deutsch",
                languageChinese: "简体中文",
                languageArabic: "العربية",
                languageHindi: "हिन्दी",
                languageSpanish: "Español",
                languageRussian: "Русский",
                languageUkrainian: "Українська",
                languageNorwegian: "Norsk",
                languageBengali: "বাংলা",
                languagePortuguese: "Português",
                mouseControl: "鼠标控制",
                mouseDrag: "拖",
                mouseClick: "点击",
                thinkingTime: "思考时间",
                thinkingTimeAria: "思考时间（秒）",
                immediateResign: "立即认输",
                secondsOption: "{{count}} 秒",
                selectedTheme: "已选择： {{name}}",
                selectedPieceSet: "已选择： {{name}}",
                enterFullScreen: "进入全屏",
                exitFullScreen: "退出全屏",
                fullScreenUnavailable: "此浏览器不支持全屏。"
            },
            gameRun: {
                yourColor: "您的颜色",
                engine: "引擎",
                thinkTime: "思考时间（秒）",
                thinkTimeAria: "引擎思考时间（秒）",
                play: "开始对局",
                nextMove: "下一步",
                computer: "电脑",
                computerColorHint: "电脑执哪一方 — 您执另一方"
            },
            brainConfig: {
                title: "Brain 配置",
                save: "保存",
                reset: "重置",
                saved: "配置已保存",
                failedSave: "保存配置失败",
                brainLabel: "Brain",
                loading: "加载中…",
                failedLoad: "加载 Brain 配置失败。",
                discardSwitchConfirm: "放弃未保存的更改并切换 Brain 版本？",
                discard: "放弃",
                pieceScores: "棋子分值",
                specialEvaluations: "特殊评估",
                gamePhase: "对局阶段",
                pawnFilesOpeningMid: "兵路（开局 / 中局）",
                pawnFilesEndGame: "兵路（残局）"
            },
            customTheme: {
                title: "自定义主题",
                name: "主题名称",
                save: "保存",
                delete: "删除",
                saved: "已保存",
                searchProperties: "搜索属性",
                filterPlaceholder: "按属性名筛选…",
                namePlaceholder: "我的主题",
                resetPreset: "重置为当前预设",
                couldNotSave: "无法保存主题。请重试。",
                untitled: "未命名",
                defaultName: "自定义主题"
            },
            positionSetup: {
                clearBoard: "清空棋盘",
                startingPosition: "初始局面",
                flipBoard: "翻转棋盘",
                eraser: "橡皮擦",
                selectAndMove: "选择并移动",
                defaultStartingPosition: "标准初始局面",
                savePosition: "保存局面",
                saveAsNewPosition: "另存为新局面",
                validatePosition: "验证局面",
                positionFlags: "局面标志",
                turn: "行棋方",
                flagCheck: "将军",
                flagCheckmate: "将死",
                flagDraw: "和棋",
                flagWhiteKingMoved: "白王已动",
                flagBlackKingMoved: "黑王已动",
                flagWhiteKingsideRookMoved: "白王侧车已动",
                flagWhiteQueensideRookMoved: "白后侧车已动",
                flagBlackKingsideRookMoved: "黑王侧车已动",
                flagBlackQueensideRookMoved: "黑后侧车已动"
            }
        },
        errorPage: {
            code: "错误 {{code}}",
            notFoundTitle: "页面未找到",
            notFoundMessage: "您要查找的页面不存在。",
            genericTitle: "出了点问题",
            genericMessage: "发生了意外错误。请重试。",
            backHome: "返回首页"
        },
        mobile: {
            drawOfferTitle: "和棋提议",
            drawOfferMessage: "对手提议和棋。是否接受？",
            rematchTitle: "重赛",
            rematchMessage: "对手提议重赛。是否接受？",
            gameId: "对局 ID：{{id}}",
            drawOfferAgree: "对手提议和棋，是否同意？",
            rematchOfferAgree: "对手提议重赛，是否同意？",
            newGameWatchFromHome: "新对局已开始 — 请前往首页观战。"
        }
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = zhExtra;
    } else {
        global.ShmerlingStringsZhExtra = zhExtra;
    }
})(typeof window !== "undefined" ? window : globalThis);
