/**
 * Simplified Chinese string catalog — mirrors src/strings/en.js structure.
 */
(function (global) {
    "use strict";

    const zh = {
        common: {
            white: "白",
            black: "黑",
            draw: "和棋",
            winner: "胜者",
            engine: "引擎",
            ok: "确定",
            cancel: "取消",
            confirm: "确认",
            yes: "是",
            no: "否",
            notice: "提示",
            input: "输入",
            start: "开始",
            collapse: "收起",
            expand: "展开",
            delete: "删除",
            rename: "重命名",
            save: "保存",
            aPlayer: "某玩家",
            pleaseEnterValue: "请输入一个值。",
        },
        play: {
            appTitle: "Shmerling 国际象棋",
            shell: {
                gameActions: "对局操作",
                playersAndClocks: "棋手与时钟",
                whitePlayerClock: "白方时钟",
                blackPlayerClock: "黑方时钟",
                startFromLoadedPosition: "从已加载局面开始对局",
                moves: "棋谱",
                expandMovesPanel: "展开棋谱面板",
                expandMoves: "展开棋谱",
                collapseMovesPanel: "收起棋谱面板",
                reviewNavigation: "复盘导航",
                positionSetup: "局面设置",
                pieces: "棋子",
                collapsePiecesPanel: "收起棋子面板",
                brainConfiguration: "Brain 配置",
                configuration: "配置",
                collapseConfigurationPanel: "收起配置面板",
                games: "对局",
                expandGamesPanel: "展开对局面板",
                expandGames: "展开对局",
                collapseGamesPanel: "收起对局面板",
                chat: "聊天",
                expandChatPanel: "展开聊天面板",
                collapseChatPanel: "收起聊天面板",
                chatPlaceholder: "输入消息…",
                chatWatcherReadonly: "观众只能阅读聊天",
                sendChat: "发送",
                savedListFilter: "已保存列表筛选",
                positions: "局面",
                gameStatus: "对局状态",
                capturedPieces: "被吃棋子",
            },
            sessionMode: {
                play: "对局模式",
                positionSetup: "局面设置",
                configuration: "配置模式",
                playback: "回放模式",
                review: "复盘模式",
                watch: "观战模式",
                practice: "练习模式",
            },
            status: {
                chooseNewGameOrSetup:
                    "请从侧边栏选择「新对局」或「局面设置」",
                chooseNewGame: "请从侧边栏选择「新对局」",
                setMoveColorEngineThinkTime:
                    "在顶部设置走法、颜色、引擎和思考时间，然后按「开始对局」",
                gameOver: "对局结束",
                gameInProgress: "对局进行中",
                boardLoading: "棋盘仍在加载…",
                boardNotReady: "棋盘尚未就绪。请稍候再试。",
                leaveOnlineBeforeConfiguration:
                    "请先离开在线对局，再打开配置",
                configurationNotInPractice:
                    "练习模式下不可用配置",
                configurationModeEdit:
                    "配置模式 — 编辑数值并保存",
                selectSavedOrSetup:
                    "请先选择已保存的对局，或在棋盘上设置局面",
                gameAlreadyInProgress: "已有对局正在进行",
                yourMove: "轮到您走棋",
                engineToMove: "引擎思考中…",
                leaveOnlineBeforePositionSetup:
                    "请先离开在线对局，再打开局面设置",
                positionSetupNotInPractice:
                    "练习模式下不可用局面设置",
                positionSetupPlacePieces:
                    "局面设置 — 在棋盘上放置棋子",
                drawWithReason: "和棋 — {{reason}}",
                checkmateWins: "将死 — {{winner}} 胜",
                check: "将军",
                waitBeforeEvaluate:
                    "请等待当前走法完成后再评估",
                evaluationUnavailable:
                    "评估不可用。请重启 Shmerling Chess 应用。",
                evaluatingPosition: "正在评估局面…",
                evaluationFailed: "评估失败",
                evaluationLine: "评估（{{side}} 行棋）：{{score}}",
                checkmate: "将死",
                drawZero: "和棋 (0)",
                totalLabel: "合计：{{value}}",
                openFolderDesktopOnly:
                    "打开文件夹仅在桌面应用中可用",
                couldNotOpenGamesLogFolder: "无法打开对局日志文件夹",
                positionValid: "局面有效",
                playingFromCustomPosition: "从自定义局面开始对局",
                nothingToSave: "没有可保存的内容",
                positionSaved: "局面已保存",
                couldNotSavePosition: "无法保存局面",
                savedPositionNotFound: "未找到已保存的局面",
                positionUpdated: "局面已更新",
                couldNotUpdatePosition: "无法更新局面",
                nameCannotBeEmpty: "名称不能为空",
                gameRenamed: "对局已重命名",
                couldNotRenameGame: "无法重命名对局",
                deletedCount: "已删除 {{count}} 项",
                couldNotDeleteSelected: "无法删除所选项目",
                couldNotLoadSavedGame: "无法加载已保存的对局",
                editingPositionSaveBookmark:
                    "正在编辑局面 — 保存以更新此书签",
                couldNotOpenPositionForEditing:
                    "无法打开局面进行编辑",
                gameSaved: "对局已保存",
                couldNotSaveGame: "无法保存对局",
                engineMoveNotApplied: "无法应用引擎走法",
                engineCouldNotFindMove: "引擎找不到可走之步",
                engineError: "引擎错误",
                engineThinking: "引擎思考中…",
                sessionError: "会话错误",
                timesUpLost: "时间到！{{loser}} 负",
                drawOfferTitle: "和棋提议",
                drawOfferMessage: "对手提议和棋。是否接受？",
                rematchTitle: "重赛",
                playerDisconnectedWaiting:
                    "{{who}} 已断开 — 等待重新加入（{{countdown}}）",
                opponentDisconnectedCountdown:
                    "对手已断开 — {{countdown}}",
                gameCancelledReconnectTimeout:
                    "对局已取消 — 重连超时且未走任何棋。",
                playerFailedToReconnectWins:
                    "{{loser}} 未能重连 — {{winner}} 胜",
                gameOverOpponentFailedReconnect:
                    "对局结束 — 对手未能重连。",
                couldNotStartRematch: "无法开始重赛",
                rematchStarted: "重赛已开始",
                gameCancelled: "对局已取消",
                gameCancelledWithDetail: "对局已取消 — {{detail}}",
                resignFailed: "认输失败",
                gameResumedYourMove: "对局已恢复 — 轮到您走棋",
                practiceNotAvailable: "练习模式不可用",
                couldNotJoinOnPlay: "无法在 /play 加入此对局",
                practiceDebugNotAvailable:
                    "此账户不可用练习 / 调试",
                reviewRequiresWebApi: "复盘需要 Web API",
                couldNotLoadReviewGame: "无法加载复盘对局",
                notReviewGameLink: "此链接不是复盘对局",
                onlineRequiresWebApi: "在线对局需要 Web API",
                couldNotLoadOnlineGame: "无法加载在线对局",
                notOnlineGameOnPlay: "此链接不是 /play 上的在线对局",
                watchingLiveGame: "正在观战",
                waitingForOpponentToJoin: "等待对手加入…",
                waitingForOpponent: "等待对手…",
                onlineGameConnected: "在线对局 — 已连接",
                gameDeleted: "对局已删除",
                itemsDeleted: "已删除 {{count}} 项",
                choosePromotionPiece: "选择升变棋子",
                invalidPromotionPiece: "无效的升变棋子",
                drawOfferNotAvailable: "当前无法提议和棋",
            },
            drawReasons: {
                stalemate: "逼和",
                fiftyMoves: "50 步规则",
                insufficientMaterial: "子力不足",
                threefoldRepetition: "三次重复",
                drawOfferAccepted: "已接受 {{by}} 方的和棋提议",
            },
            actions: {
                newGame: "新对局",
                resign: "认输",
                draw: "和棋",
                undo: "悔棋",
                redo: "重做",
                lastMove: "上一步",
                positionSetup: "局面设置",
                config: "配置",
                flip: "翻转",
                save: "保存",
                exit: "退出",
                loadToStart: "加载并开始",
                editPosition: "编辑局面",
            },
            savedGames: {
                defaultName: "已保存对局",
                nameAriaLabel: "已保存对局名称",
                showDetails: "显示详情",
                detailsAriaLabel: "已保存对局详情",
                editPosition: "编辑局面",
                deleteSavedGame: "删除已保存对局",
                renameSavedGame: "重命名已保存对局",
                noSavedPositions: "尚无已保存局面。",
                noSavedGames: "尚无已保存对局。",
                nextMoveDash: "下一步：—",
                nextMove: "下一步：{{side}}",
                player: "棋手",
                savedAt: "保存于：{{when}}",
                gameId: "对局 ID：{{id}}",
                playersVs: "{{white}} 对 {{black}}",
            },
            reviewNav: {
                start: "开始",
                back: "后退",
                play: "播放",
                pause: "暂停",
                forward: "前进",
                end: "结束",
            },
            newGameDialog: {
                title: "新对局（对 AI）",
                yourColor: "您的颜色",
                engine: "引擎",
                brain43: "Brain 4.3",
                brain42: "Brain 4.2",
                brain41: "Brain 4.1",
                brain4: "Brain 4.0",
                timePerSideMinutes: "每方时间（分钟）",
                allowUndo: "允许悔棋",
                private: "私人",
                privateHint:
                    "私人对局不会显示在其他会员的进行中对局列表中。",
            },
            prompts: {
                positionName: "局面名称",
                savePositionAs: "将局面另存为",
            },
            dialogs: {
                resignTitle: "认输并结束此对局？",
                resignBody: "您将输掉此对局。",
                leaveTitle: "离开对局？",
                leaveBody: "您的对局将被判负（认输）。",
                areYouSure: "确定吗？",
                discardUnsavedBrainConfig:
                    "放弃未保存的 Brain 配置更改？",
                accept: "接受",
                decline: "拒绝",
                saveAs: "另存为",
                savePosition: "保存局面",
                invalidPosition: "无效局面",
                rematchChooseColor: "请选择重赛时使用的颜色：",
                rematchOfferAgree: "对手提议重赛。是否同意？",
                rematchColorPreference:
                    "对手想执 {{offerer}}。您将执 {{you}}。是否同意？",
            },
        },
        session: {
            engineThinking: "引擎思考中…",
            engineCouldNotFindMove: "引擎找不到可走之步",
            engineError: "引擎错误",
            positionSetupPlacePieces: "局面设置 — 在棋盘上放置棋子",
            configurationModeEdit: "配置模式 — 编辑数值并保存",
            practiceBothSides: "练习 — 双方",
            opponentDisconnected: "对手已断开",
            opponentRejoined: "对手已重新加入",
            playerRejoined: "{{name}} 已重新加入",
            drawOfferSent: "已发送和棋提议",
            drawOfferDeclined: "和棋提议被拒绝",
            rematchOfferSent: "已发送重赛提议",
            rematchOfferDeclined: "重赛提议被拒绝",
            drawAgreed: "双方同意和棋",
            rematchAcceptedNoGameId: "已接受重赛，但没有新的对局 ID",
            rematchOfferAccepted: "已接受重赛提议",
            gameOver: "对局结束",
            somethingWentWrong: "出现问题",
            opponentResigned: "对手认输",
            opponentLeftGame: "对手离开了对局",
            opponentFailedToReconnect: "对手未能重连",
            gameCancelled: "对局已取消",
            gameCancelledWithDetail: "对局已取消 — {{detail}}",
            waitingForOpponent: "等待对手…",
            couldNotResolveWebSocketUrl: "无法解析 WebSocket URL",
            opponentJoined: "{{name}} 已加入",
            opponentDefault: "对手",
            connectionError: "连接错误",
            playerDisconnectedWaitingRejoin:
                "{{name}} 已断开 — 等待重新加入",
            playerFailedToReconnectWins:
                "{{loser}} 未能重连 — {{winner}} 胜",
            watcherWaitingForReconnect: "等待棋手重新连接…",
        },
        site: {
            confirm: "确认",
            cancel: "取消",
            notice: "提示",
            ok: "确定",
            home: "首页",
            search: "搜索",
            friends: "好友",
            groups: "群组",
            debug: "调试",
            account: "账户",
            preferences: "偏好设置",
            administrate: "管理",
            logOut: "退出登录",
            logIn: "登录",
            admin: "管理员",
            homeAria: "首页",
        },
        validation: {
            validEmail: "请填写有效的电子邮箱",
            passwordsMustMatch: "请确保两次输入的密码一致。",
            chooseUsername: "请选择用户名",
            usernameNotAvailable: "此用户名不可用",
            passwordNoWhitespace: "密码不能包含空格。",
            passwordUppercase: "密码至少包含一个大写字母。",
        },
    };

    if (typeof module === "object" && module && module.exports) {
        module.exports = zh;
    } else {
        global.ShmerlingStringsZh = zh;
    }
})(typeof window !== "undefined" ? window : globalThis);
