const express = require("express");
const { requireLogin } = require("./../../utils.js");
const gameController = require("./controller");
const router = express.Router();
router.get("/review", requireLogin, gameController.review);
router.get("/mobile-review", requireLogin, gameController.reviewMobile);
router.get("/watch", requireLogin, gameController.watchGame);
router.get("/mobile-game", requireLogin, gameController.startGameMobile);
router.get("/game", requireLogin, gameController.startGame);
router.get("/research", requireLogin, gameController.showResearch);
router.get("/gameInfo", requireLogin, gameController.getGameInfo);
router.get("/gameMoves", requireLogin, gameController.getGameMoves);
router.post("/rematch", requireLogin, gameController.rematch);
router.post("/cancel-before-move", requireLogin, gameController.cancelBeforeMove);
module.exports = router;